#!/usr/bin/env bash
# AUTO-GENERATED by spice2rnm (Veylon Systems).
#
# One simulator, one command. The analog half is models, so
# there is no bridge to build and no shared libngspice to find.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT" || exit 1
XEZIM="${XEZIM:-$HOME/xezim/target/release/xezim}"

# The sources by NAME, found on a search path, so this runs
# from the tree it was generated in and from a copy of it.
SEARCH=${SEARCH:-"../analog ../../cpump ../../lpfilt ../../ro_vco ../../../demo4b_pll_deck . .. ../.. ../../.. ../../../.. ../../analog ../../../analog"}
SRC=""
for f in ams_node_pkg.sv cpump_cp_rnm.sv lpfilt_rc_rnm.sv ro_vco_rnm.sv cpump_iface.sv lpfilt_iface.sv ro_vco_iface.sv netlist_top.sv pfd.sv divn.sv pll_rtl_loop.sv; do
  found=""
  for d in $SEARCH; do [ -f "$d/$f" ] && { found="$d/$f"; break; }; done
  [ -n "$found" ] || { echo "ERROR: $f not found on: $SEARCH" >&2
                       echo "  set SEARCH to the directories holding them" >&2
                       exit 1; }
  SRC="$SRC $found"
done

exec "$XEZIM" $SRC
