`timescale 1fs/1fs
//======================================================================
// cpump -- switched current driver block, with the subcircuit's own interface.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// .subckt cpump pupb pdn dra dd
//
// so the netlist's own card instantiates it unchanged. The characterized
// core cpump_cp_rnm is instantiated untouched inside: it is
// what the equivalence check ran against, and it keeps its measured
// behaviour and its `real` ports. Only the boundary changes.
//
// The control bits are the GATE LEVELS the characterization drove,
// so the port values go through as they are. Applying an active-low
// sense here would apply it a SECOND time -- the boundary already
// did, where the co-simulation states it.
//
// This driver and the passive network form an ALGEBRAIC loop: the
// current depends on the node voltage and the node voltage depends
// on the current, with no memory between them. It is NOT left to
// the simulator to settle by iteration. On this characteristic the
// slope times the injection resistance exceeds one in the strongest
// state, so an iteration on the current alone does not converge --
// it rings at the step rate and lands on the wrong operating point.
//
// So the conductance port carries the slope of this table out
// alongside the current, and the network solves both in one step.
// See the receiving block's header for the algebra.
//
// EXPECTED: the domain assertion may still report a node voltage
// above the supply on the cycle a control switches, where the table
// is evaluated at the previous voltage and the newly enabled device
// reads far more current than it will carry once settled. The table
// clamps at its measured endpoints, so what comes back there is the
// endpoint rather than an extrapolation. Left reported rather than
// silenced: the message is true, and a clamp added here would also
// hide a node that really does leave the characterized range.
//======================================================================
module cpump(
  input  logic  pupb,
  input  logic  pdn,
  input  real   dra_v,
  output real   dra_i,
  output real   dra_g,
  input  real   dd_v
);
  real i_out, g_out;

  cpump_cp_rnm u_core (
    .ctl  ({pupb, pdn}),
    .vout (dra_v),
    .iout (i_out),
    .gout (g_out)
  );

  assign dra_i = i_out;
  assign dra_g = g_out;
endmodule : cpump
