`timescale 1fs/1fs
//======================================================================
// cpump_cp_rnm -- real-number model of a digitally-switched current driver.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// The block has no analog input. Its forcing term is a digital state, and
// for each state it presents a measured output characteristic:
//
//     iout = f(ctl, vout)
//
// and, alongside it, that characteristic's slope as an output conductance,
// so a resistive node it drives can solve the algebraic loop between them
// in closed form rather than by an iteration that need not converge.
//
// SIGN: iout is the current flowing INTO the node this block drives.
// Sourcing (pulling the node up) is POSITIVE, sinking is NEGATIVE.
//
// This is a table per state rather than a current and an output
// conductance because the measurement says it is not a current source: the
// characteristic runs -5.08 to 9.18 mA across 0.00..3.30 V,
// which is a transistor going from triode to saturation. A single
// linearization would be wrong over most of the range the node is used
// over.
//
// The tables are CLAMPED. The driven node leaves its characterized range
// during acquisition, and holding the last measured current is honest
// there where extrapolating is not.
//
// NOT modelled: the dynamics of the node itself, which belong to whatever
// this drives and would be double-counted here; and switching transients
// (charge injection, clock feedthrough), which a per-state DC
// characteristic does not describe.
//======================================================================
module cpump_cp_rnm (
  input  logic [1:0] ctl,   // bit0=vcpc0, bit1=vcpc1
  input  wreal                  vout,  // voltage on the driven node
  output wreal                  iout,  // amps INTO that node
  output wreal                  gout   // -diout/dvout there, siemens
);
  // always_comb assigns a variable and these ports are nets, so
  // the value is computed into one and the port driven from it.
  real iout__d, gout__d;
  assign iout = iout__d;
  assign gout = gout__d;

  localparam int NST = 4;   // 2**2 states
  localparam int NPT = 12;   // points per characteristic

  real VT [0:NST-1][0:NPT-1];
  real IT [0:NST-1][0:NPT-1];

  initial begin
    VT[0][0] = 0.000000; IT[0][0] = 9.175150460e-03;
    VT[0][1] = 0.300000; IT[0][1] = 8.973917270e-03;
    VT[0][2] = 0.600000; IT[0][2] = 8.754516570e-03;
    VT[0][3] = 0.900000; IT[0][3] = 8.506020660e-03;
    VT[0][4] = 1.200000; IT[0][4] = 8.207351700e-03;
    VT[0][5] = 1.500000; IT[0][5] = 7.813231610e-03;
    VT[0][6] = 1.800000; IT[0][6] = 7.239005140e-03;
    VT[0][7] = 2.100000; IT[0][7] = 6.416818320e-03;
    VT[0][8] = 2.400000; IT[0][8] = 5.313512030e-03;
    VT[0][9] = 2.700000; IT[0][9] = 3.899200870e-03;
    VT[0][10] = 3.000000; IT[0][10] = 2.140666770e-03;
    VT[0][11] = 3.300000; IT[0][11] = -3.960506540e-09;
    VT[2][0] = 0.000000; IT[2][0] = 4.988388300e-10;
    VT[2][1] = 0.300000; IT[2][1] = -5.399134220e-10;
    VT[2][2] = 0.600000; IT[2][2] = -8.414842110e-10;
    VT[2][3] = 0.900000; IT[2][3] = -1.103290280e-09;
    VT[2][4] = 1.200000; IT[2][4] = -1.357485920e-09;
    VT[2][5] = 1.500000; IT[2][5] = -1.622011790e-09;
    VT[2][6] = 1.800000; IT[2][6] = -1.908813070e-09;
    VT[2][7] = 2.100000; IT[2][7] = -2.226887500e-09;
    VT[2][8] = 2.400000; IT[2][8] = -2.583836880e-09;
    VT[2][9] = 2.700000; IT[2][9] = -2.986751720e-09;
    VT[2][10] = 3.000000; IT[2][10] = -3.442751470e-09;
    VT[2][11] = 3.300000; IT[2][11] = -3.960506550e-09;
    VT[1][0] = 0.000000; IT[1][0] = 9.175150460e-03;
    VT[1][1] = 0.300000; IT[1][1] = 7.605315370e-03;
    VT[1][2] = 0.600000; IT[1][2] = 6.318363300e-03;
    VT[1][3] = 0.900000; IT[1][3] = 5.264586100e-03;
    VT[1][4] = 1.200000; IT[1][4] = 4.390300160e-03;
    VT[1][5] = 1.500000; IT[1][5] = 3.618055730e-03;
    VT[1][6] = 1.800000; IT[1][6] = 2.797868410e-03;
    VT[1][7] = 2.100000; IT[1][7] = 1.798437190e-03;
    VT[1][8] = 2.400000; IT[1][8] = 5.551522710e-04;
    VT[1][9] = 2.700000; IT[1][9] = -9.775200550e-04;
    VT[1][10] = 3.000000; IT[1][10] = -2.840950460e-03;
    VT[1][11] = 3.300000; IT[1][11] = -5.077638980e-03;
    VT[3][0] = 0.000000; IT[3][0] = 4.988388300e-10;
    VT[3][1] = 0.300000; IT[3][1] = -1.368602440e-03;
    VT[3][2] = 0.600000; IT[3][2] = -2.436154110e-03;
    VT[3][3] = 0.900000; IT[3][3] = -3.241435660e-03;
    VT[3][4] = 1.200000; IT[3][4] = -3.817052900e-03;
    VT[3][5] = 1.500000; IT[3][5] = -4.195177500e-03;
    VT[3][6] = 1.800000; IT[3][6] = -4.441138640e-03;
    VT[3][7] = 2.100000; IT[3][7] = -4.618383360e-03;
    VT[3][8] = 2.400000; IT[3][8] = -4.758362340e-03;
    VT[3][9] = 2.700000; IT[3][9] = -4.876723910e-03;
    VT[3][10] = 3.000000; IT[3][10] = -4.981620670e-03;
    VT[3][11] = 3.300000; IT[3][11] = -5.077638980e-03;
  end

  function automatic real iv_of(input int s, input real v);
    int  k;
    real t;
    if (s < 0 || s >= NST) return 0.0;
    if (v <= VT[s][0])     return IT[s][0];
    if (v >= VT[s][NPT-1]) return IT[s][NPT-1];
    for (k = 0; k < NPT-1; k++) begin
      if (v >= VT[s][k] && v <= VT[s][k+1]) begin
        if (VT[s][k+1] == VT[s][k]) return IT[s][k];
        t = (v - VT[s][k]) / (VT[s][k+1] - VT[s][k]);
        return IT[s][k] + t * (IT[s][k+1] - IT[s][k]);
      end
    end
    return IT[s][NPT-1];
  endfunction

  // The SLOPE of the same characteristic, as a positive conductance.
  //
  // Whatever this drives needs it, not the current alone. A node with no
  // capacitance takes its voltage from the current pushed into it, and
  // that current comes from the table above at that voltage: an algebraic
  // loop. Passing only the current leaves the loop to be closed by
  // iteration, and on this table the steepest state has a loop gain above
  // one, so the iteration does not converge -- it oscillates at the step
  // rate and settles on the wrong operating point. Passing the slope lets
  // the receiving block close the loop in one Newton step instead, which
  // is exact for a piecewise-linear table and stable at any gain.
  //
  // SIGN: iout is INTO the node, so a device that sinks harder as the node
  // rises has diout/dvout < 0 and therefore a POSITIVE conductance, the
  // same sign a resistor to ground has.
  //
  // Zero outside the characterized range and on a flat segment, because
  // the table is clamped there and a clamped current really has no slope.
  function automatic real gv_of(input int s, input real v);
    int k;
    if (s < 0 || s >= NST)   return 0.0;
    if (v <= VT[s][0])       return 0.0;
    if (v >= VT[s][NPT-1])   return 0.0;
    for (k = 0; k < NPT-1; k++) begin
      if (v >= VT[s][k] && v <= VT[s][k+1]) begin
        if (VT[s][k+1] == VT[s][k]) return 0.0;
        return -(IT[s][k+1] - IT[s][k]) / (VT[s][k+1] - VT[s][k]);
      end
    end
    return 0.0;
  endfunction

  always_comb iout__d = iv_of(int'(ctl), vout);
  always_comb gout__d = gv_of(int'(ctl), vout);


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.3;
  localparam real DOMAIN_EPS = 0.0; // exact -- no stimulus here overshoots, so no margin is earned
  bit domain_reported = 1'b0;

  always @(vout) begin : domain_check
    a_input_domain: assert (vout >= DOMAIN_LO - DOMAIN_EPS && vout <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. the table clamps at its measured end points, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               vout, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(iout) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (iout == iout)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output current is NaN -- the voltage on the driven node is not a number, so whatever integrates that node has diverged. Reported once.");
    end
  end
`endif

endmodule : cpump_cp_rnm
