`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.714e+11 .. 3.835e+11 rad/s
// rise/fall asymmetry 1.8546 (rise x1.3618, fall x0.7343), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.457e-11 s, as a 0/76 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv1_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 191.463; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 1.914633313e-13;
  localparam real DC_BIAS = 1.773220773;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.713531634e+11;
    WX[1] = 0.11082625; WP[1] = 1.713833232e+11;
    WX[2] = 0.2216525; WP[2] = 1.714293725e+11;
    WX[3] = 0.33247875; WP[3] = 1.714888102e+11;
    WX[4] = 0.443305; WP[4] = 1.715297181e+11;
    WX[5] = 0.55413125; WP[5] = 1.717645721e+11;
    WX[6] = 0.6649575; WP[6] = 1.731728213e+11;
    WX[7] = 0.77578375; WP[7] = 1.761381529e+11;
    WX[8] = 0.88661; WP[8] = 1.798456343e+11;
    WX[9] = 0.99743625; WP[9] = 1.840359651e+11;
    WX[10] = 1.1082625; WP[10] = 1.887749753e+11;
    WX[11] = 1.21908875; WP[11] = 1.942355146e+11;
    WX[12] = 1.329915; WP[12] = 2.007070657e+11;
    WX[13] = 1.44074125; WP[13] = 2.086615094e+11;
    WX[14] = 1.5515675; WP[14] = 2.190721479e+11;
    WX[15] = 1.66239375; WP[15] = 2.383282956e+11;
    WX[16] = 1.77322; WP[16] = 2.721483867e+11;
    WX[17] = 1.88404625; WP[17] = 3.835204665e+11;
    WX[18] = 1.9948725; WP[18] = 3.679482742e+11;
    WX[19] = 2.10569875; WP[19] = 3.56476535e+11;
    WX[20] = 2.216525; WP[20] = 3.470927062e+11;
    WX[21] = 2.32735125; WP[21] = 3.391957492e+11;
    WX[22] = 2.4381775; WP[22] = 3.323845544e+11;
    WX[23] = 2.54900375; WP[23] = 3.264454304e+11;
    WX[24] = 2.65983; WP[24] = 3.217010421e+11;
    WX[25] = 2.77065625; WP[25] = 3.193811473e+11;
    WX[26] = 2.8814825; WP[26] = 3.187488789e+11;
    WX[27] = 2.99230875; WP[27] = 3.184237506e+11;
    WX[28] = 3.103135; WP[28] = 3.182040182e+11;
    WX[29] = 3.21396125; WP[29] = 3.180182565e+11;
    WX[30] = 3.3247875; WP[30] = 3.179058162e+11;
    WX[31] = 3.43561375; WP[31] = 3.178394941e+11;
    WX[32] = 3.54644; WP[32] = 3.177926253e+11;
  end

  real LUT_X[0:400];
  real LUT_Y[0:400];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999946;
    LUT_X[1] = 0.0088661; LUT_Y[1] = 3.29999933;
    LUT_X[2] = 0.0177322; LUT_Y[2] = 3.29999916;
    LUT_X[3] = 0.0265983; LUT_Y[3] = 3.29999895;
    LUT_X[4] = 0.0354644; LUT_Y[4] = 3.2999987;
    LUT_X[5] = 0.0443305; LUT_Y[5] = 3.29999838;
    LUT_X[6] = 0.0531966; LUT_Y[6] = 3.29999798;
    LUT_X[7] = 0.0620627; LUT_Y[7] = 3.29999749;
    LUT_X[8] = 0.0709288; LUT_Y[8] = 3.29999687;
    LUT_X[9] = 0.0797949; LUT_Y[9] = 3.29999611;
    LUT_X[10] = 0.088661; LUT_Y[10] = 3.29999516;
    LUT_X[11] = 0.0975271; LUT_Y[11] = 3.29999399;
    LUT_X[12] = 0.1063932; LUT_Y[12] = 3.29999254;
    LUT_X[13] = 0.1152593; LUT_Y[13] = 3.29999075;
    LUT_X[14] = 0.1241254; LUT_Y[14] = 3.29998853;
    LUT_X[15] = 0.1329915; LUT_Y[15] = 3.29998579;
    LUT_X[16] = 0.1418576; LUT_Y[16] = 3.29998241;
    LUT_X[17] = 0.1507237; LUT_Y[17] = 3.29997826;
    LUT_X[18] = 0.1595898; LUT_Y[18] = 3.29997314;
    LUT_X[19] = 0.1684559; LUT_Y[19] = 3.29996687;
    LUT_X[20] = 0.177322; LUT_Y[20] = 3.29995918;
    LUT_X[21] = 0.1861881; LUT_Y[21] = 3.29994976;
    LUT_X[22] = 0.1950542; LUT_Y[22] = 3.29993826;
    LUT_X[23] = 0.2039203; LUT_Y[23] = 3.29992423;
    LUT_X[24] = 0.2127864; LUT_Y[24] = 3.29990715;
    LUT_X[25] = 0.2216525; LUT_Y[25] = 3.2998864;
    LUT_X[26] = 0.2305186; LUT_Y[26] = 3.29986124;
    LUT_X[27] = 0.2393847; LUT_Y[27] = 3.2998308;
    LUT_X[28] = 0.2482508; LUT_Y[28] = 3.29979403;
    LUT_X[29] = 0.2571169; LUT_Y[29] = 3.29974973;
    LUT_X[30] = 0.265983; LUT_Y[30] = 3.29969647;
    LUT_X[31] = 0.2748491; LUT_Y[31] = 3.29963258;
    LUT_X[32] = 0.2837152; LUT_Y[32] = 3.29955616;
    LUT_X[33] = 0.2925813; LUT_Y[33] = 3.29946497;
    LUT_X[34] = 0.3014474; LUT_Y[34] = 3.29935649;
    LUT_X[35] = 0.3103135; LUT_Y[35] = 3.29922787;
    LUT_X[36] = 0.3191796; LUT_Y[36] = 3.29907591;
    LUT_X[37] = 0.3280457; LUT_Y[37] = 3.29889709;
    LUT_X[38] = 0.3369118; LUT_Y[38] = 3.29868758;
    LUT_X[39] = 0.3457779; LUT_Y[39] = 3.29844328;
    LUT_X[40] = 0.354644; LUT_Y[40] = 3.29815991;
    LUT_X[41] = 0.3635101; LUT_Y[41] = 3.29783304;
    LUT_X[42] = 0.3723762; LUT_Y[42] = 3.29745824;
    LUT_X[43] = 0.3812423; LUT_Y[43] = 3.29703116;
    LUT_X[44] = 0.3901084; LUT_Y[44] = 3.29654768;
    LUT_X[45] = 0.3989745; LUT_Y[45] = 3.29600399;
    LUT_X[46] = 0.4078406; LUT_Y[46] = 3.29539671;
    LUT_X[47] = 0.4167067; LUT_Y[47] = 3.29472303;
    LUT_X[48] = 0.4255728; LUT_Y[48] = 3.29398072;
    LUT_X[49] = 0.4344389; LUT_Y[49] = 3.29316819;
    LUT_X[50] = 0.443305; LUT_Y[50] = 3.29228454;
    LUT_X[51] = 0.4521711; LUT_Y[51] = 3.29132953;
    LUT_X[52] = 0.4610372; LUT_Y[52] = 3.2903035;
    LUT_X[53] = 0.4699033; LUT_Y[53] = 3.28920741;
    LUT_X[54] = 0.4787694; LUT_Y[54] = 3.28804266;
    LUT_X[55] = 0.4876355; LUT_Y[55] = 3.28681111;
    LUT_X[56] = 0.4965016; LUT_Y[56] = 3.28551489;
    LUT_X[57] = 0.5053677; LUT_Y[57] = 3.2841564;
    LUT_X[58] = 0.5142338; LUT_Y[58] = 3.28273819;
    LUT_X[59] = 0.5230999; LUT_Y[59] = 3.28126287;
    LUT_X[60] = 0.531966; LUT_Y[60] = 3.27973308;
    LUT_X[61] = 0.5408321; LUT_Y[61] = 3.27815141;
    LUT_X[62] = 0.5496982; LUT_Y[62] = 3.27652035;
    LUT_X[63] = 0.5585643; LUT_Y[63] = 3.27484228;
    LUT_X[64] = 0.5674304; LUT_Y[64] = 3.27311942;
    LUT_X[65] = 0.5762965; LUT_Y[65] = 3.27135383;
    LUT_X[66] = 0.5851626; LUT_Y[66] = 3.26954739;
    LUT_X[67] = 0.5940287; LUT_Y[67] = 3.2677018;
    LUT_X[68] = 0.6028948; LUT_Y[68] = 3.26581856;
    LUT_X[69] = 0.6117609; LUT_Y[69] = 3.26389903;
    LUT_X[70] = 0.620627; LUT_Y[70] = 3.26194437;
    LUT_X[71] = 0.6294931; LUT_Y[71] = 3.25995559;
    LUT_X[72] = 0.6383592; LUT_Y[72] = 3.25793355;
    LUT_X[73] = 0.6472253; LUT_Y[73] = 3.25587897;
    LUT_X[74] = 0.6560914; LUT_Y[74] = 3.25379245;
    LUT_X[75] = 0.6649575; LUT_Y[75] = 3.25167444;
    LUT_X[76] = 0.6738236; LUT_Y[76] = 3.24952534;
    LUT_X[77] = 0.6826897; LUT_Y[77] = 3.2473454;
    LUT_X[78] = 0.6915558; LUT_Y[78] = 3.24513482;
    LUT_X[79] = 0.7004219; LUT_Y[79] = 3.24289369;
    LUT_X[80] = 0.709288; LUT_Y[80] = 3.24062207;
    LUT_X[81] = 0.7181541; LUT_Y[81] = 3.23831993;
    LUT_X[82] = 0.7270202; LUT_Y[82] = 3.23598719;
    LUT_X[83] = 0.7358863; LUT_Y[83] = 3.23362371;
    LUT_X[84] = 0.7447524; LUT_Y[84] = 3.23122934;
    LUT_X[85] = 0.7536185; LUT_Y[85] = 3.22880384;
    LUT_X[86] = 0.7624846; LUT_Y[86] = 3.22634697;
    LUT_X[87] = 0.7713507; LUT_Y[87] = 3.22385844;
    LUT_X[88] = 0.7802168; LUT_Y[88] = 3.22133793;
    LUT_X[89] = 0.7890829; LUT_Y[89] = 3.21878511;
    LUT_X[90] = 0.797949; LUT_Y[90] = 3.21619959;
    LUT_X[91] = 0.8068151; LUT_Y[91] = 3.21358099;
    LUT_X[92] = 0.8156812; LUT_Y[92] = 3.21092888;
    LUT_X[93] = 0.8245473; LUT_Y[93] = 3.20824281;
    LUT_X[94] = 0.8334134; LUT_Y[94] = 3.20552233;
    LUT_X[95] = 0.8422795; LUT_Y[95] = 3.20276693;
    LUT_X[96] = 0.8511456; LUT_Y[96] = 3.19997612;
    LUT_X[97] = 0.8600117; LUT_Y[97] = 3.19714936;
    LUT_X[98] = 0.8688778; LUT_Y[98] = 3.19428609;
    LUT_X[99] = 0.8777439; LUT_Y[99] = 3.19138575;
    LUT_X[100] = 0.88661; LUT_Y[100] = 3.18844772;
    LUT_X[101] = 0.8954761; LUT_Y[101] = 3.18547139;
    LUT_X[102] = 0.9043422; LUT_Y[102] = 3.18245612;
    LUT_X[103] = 0.9132083; LUT_Y[103] = 3.17940123;
    LUT_X[104] = 0.9220744; LUT_Y[104] = 3.17630602;
    LUT_X[105] = 0.9309405; LUT_Y[105] = 3.17316977;
    LUT_X[106] = 0.9398066; LUT_Y[106] = 3.16999173;
    LUT_X[107] = 0.9486727; LUT_Y[107] = 3.16677112;
    LUT_X[108] = 0.9575388; LUT_Y[108] = 3.16350713;
    LUT_X[109] = 0.9664049; LUT_Y[109] = 3.16019891;
    LUT_X[110] = 0.975271; LUT_Y[110] = 3.1568456;
    LUT_X[111] = 0.9841371; LUT_Y[111] = 3.15344627;
    LUT_X[112] = 0.9930032; LUT_Y[112] = 3.14999999;
    LUT_X[113] = 1.0018693; LUT_Y[113] = 3.14650576;
    LUT_X[114] = 1.0107354; LUT_Y[114] = 3.14296257;
    LUT_X[115] = 1.0196015; LUT_Y[115] = 3.13936934;
    LUT_X[116] = 1.0284676; LUT_Y[116] = 3.13572497;
    LUT_X[117] = 1.0373337; LUT_Y[117] = 3.13202829;
    LUT_X[118] = 1.0461998; LUT_Y[118] = 3.12827811;
    LUT_X[119] = 1.0550659; LUT_Y[119] = 3.12447315;
    LUT_X[120] = 1.063932; LUT_Y[120] = 3.12061212;
    LUT_X[121] = 1.0727981; LUT_Y[121] = 3.11669363;
    LUT_X[122] = 1.0816642; LUT_Y[122] = 3.11271626;
    LUT_X[123] = 1.0905303; LUT_Y[123] = 3.10867852;
    LUT_X[124] = 1.0993964; LUT_Y[124] = 3.10457884;
    LUT_X[125] = 1.1082625; LUT_Y[125] = 3.10041559;
    LUT_X[126] = 1.1171286; LUT_Y[126] = 3.09618706;
    LUT_X[127] = 1.1259947; LUT_Y[127] = 3.09189148;
    LUT_X[128] = 1.1348608; LUT_Y[128] = 3.08752695;
    LUT_X[129] = 1.1437269; LUT_Y[129] = 3.08309154;
    LUT_X[130] = 1.152593; LUT_Y[130] = 3.07858317;
    LUT_X[131] = 1.1614591; LUT_Y[131] = 3.07399969;
    LUT_X[132] = 1.1703252; LUT_Y[132] = 3.06933883;
    LUT_X[133] = 1.1791913; LUT_Y[133] = 3.06459822;
    LUT_X[134] = 1.1880574; LUT_Y[134] = 3.05977536;
    LUT_X[135] = 1.1969235; LUT_Y[135] = 3.05486761;
    LUT_X[136] = 1.2057896; LUT_Y[136] = 3.04987219;
    LUT_X[137] = 1.2146557; LUT_Y[137] = 3.0447862;
    LUT_X[138] = 1.2235218; LUT_Y[138] = 3.03960655;
    LUT_X[139] = 1.2323879; LUT_Y[139] = 3.03432998;
    LUT_X[140] = 1.241254; LUT_Y[140] = 3.02895305;
    LUT_X[141] = 1.2501201; LUT_Y[141] = 3.02347215;
    LUT_X[142] = 1.2589862; LUT_Y[142] = 3.0178834;
    LUT_X[143] = 1.2678523; LUT_Y[143] = 3.01218273;
    LUT_X[144] = 1.2767184; LUT_Y[144] = 3.00636582;
    LUT_X[145] = 1.2855845; LUT_Y[145] = 3.00042805;
    LUT_X[146] = 1.2944506; LUT_Y[146] = 2.99436453;
    LUT_X[147] = 1.3033167; LUT_Y[147] = 2.98817004;
    LUT_X[148] = 1.3121828; LUT_Y[148] = 2.98183903;
    LUT_X[149] = 1.3210489; LUT_Y[149] = 2.97536554;
    LUT_X[150] = 1.329915; LUT_Y[150] = 2.9687432;
    LUT_X[151] = 1.3387811; LUT_Y[151] = 2.96196521;
    LUT_X[152] = 1.3476472; LUT_Y[152] = 2.95502423;
    LUT_X[153] = 1.3565133; LUT_Y[153] = 2.94791239;
    LUT_X[154] = 1.3653794; LUT_Y[154] = 2.9406212;
    LUT_X[155] = 1.3742455; LUT_Y[155] = 2.93314148;
    LUT_X[156] = 1.3831116; LUT_Y[156] = 2.92546331;
    LUT_X[157] = 1.3919777; LUT_Y[157] = 2.91757592;
    LUT_X[158] = 1.4008438; LUT_Y[158] = 2.90946759;
    LUT_X[159] = 1.4097099; LUT_Y[159] = 2.90112554;
    LUT_X[160] = 1.418576; LUT_Y[160] = 2.8925358;
    LUT_X[161] = 1.4274421; LUT_Y[161] = 2.88368302;
    LUT_X[162] = 1.4363082; LUT_Y[162] = 2.87455034;
    LUT_X[163] = 1.4451743; LUT_Y[163] = 2.86511909;
    LUT_X[164] = 1.4540404; LUT_Y[164] = 2.85536862;
    LUT_X[165] = 1.4629065; LUT_Y[165] = 2.84527588;
    LUT_X[166] = 1.4717726; LUT_Y[166] = 2.83481514;
    LUT_X[167] = 1.4806387; LUT_Y[167] = 2.82395743;
    LUT_X[168] = 1.4895048; LUT_Y[168] = 2.81267006;
    LUT_X[169] = 1.4983709; LUT_Y[169] = 2.80091584;
    LUT_X[170] = 1.507237; LUT_Y[170] = 2.78865223;
    LUT_X[171] = 1.5161031; LUT_Y[171] = 2.77583023;
    LUT_X[172] = 1.5249692; LUT_Y[172] = 2.76239294;
    LUT_X[173] = 1.5338353; LUT_Y[173] = 2.74827367;
    LUT_X[174] = 1.5427014; LUT_Y[174] = 2.73339358;
    LUT_X[175] = 1.5515675; LUT_Y[175] = 2.71765835;
    LUT_X[176] = 1.5604336; LUT_Y[176] = 2.70095382;
    LUT_X[177] = 1.5692997; LUT_Y[177] = 2.68313986;
    LUT_X[178] = 1.5781658; LUT_Y[178] = 2.66404191;
    LUT_X[179] = 1.5870319; LUT_Y[179] = 2.64343877;
    LUT_X[180] = 1.595898; LUT_Y[180] = 2.62104524;
    LUT_X[181] = 1.6047641; LUT_Y[181] = 2.59648737;
    LUT_X[182] = 1.6136302; LUT_Y[182] = 2.56926881;
    LUT_X[183] = 1.6224963; LUT_Y[183] = 2.53873269;
    LUT_X[184] = 1.6313624; LUT_Y[184] = 2.50404529;
    LUT_X[185] = 1.6402285; LUT_Y[185] = 2.464285;
    LUT_X[186] = 1.6490946; LUT_Y[186] = 2.41876133;
    LUT_X[187] = 1.6579607; LUT_Y[187] = 2.3674463;
    LUT_X[188] = 1.6668268; LUT_Y[188] = 2.31097571;
    LUT_X[189] = 1.6756929; LUT_Y[189] = 2.25018244;
    LUT_X[190] = 1.684559; LUT_Y[190] = 2.18579142;
    LUT_X[191] = 1.6934251; LUT_Y[191] = 2.11840241;
    LUT_X[192] = 1.7022912; LUT_Y[192] = 2.04854586;
    LUT_X[193] = 1.7111573; LUT_Y[193] = 1.9767203;
    LUT_X[194] = 1.7200234; LUT_Y[194] = 1.90340867;
    LUT_X[195] = 1.7288895; LUT_Y[195] = 1.82908418;
    LUT_X[196] = 1.7377556; LUT_Y[196] = 1.75421235;
    LUT_X[197] = 1.7466217; LUT_Y[197] = 1.679252;
    LUT_X[198] = 1.7554878; LUT_Y[198] = 1.60465606;
    LUT_X[199] = 1.7643539; LUT_Y[199] = 1.53087182;
    LUT_X[200] = 1.77322; LUT_Y[200] = 1.45834011;
    LUT_X[201] = 1.7820861; LUT_Y[201] = 1.38749261;
    LUT_X[202] = 1.7909522; LUT_Y[202] = 1.31874658;
    LUT_X[203] = 1.7998183; LUT_Y[203] = 1.25249673;
    LUT_X[204] = 1.8086844; LUT_Y[204] = 1.18910407;
    LUT_X[205] = 1.8175505; LUT_Y[205] = 1.12888284;
    LUT_X[206] = 1.8264166; LUT_Y[206] = 1.07208679;
    LUT_X[207] = 1.8352827; LUT_Y[207] = 1.01889745;
    LUT_X[208] = 1.8441488; LUT_Y[208] = 0.969417045;
    LUT_X[209] = 1.8530149; LUT_Y[209] = 0.923668344;
    LUT_X[210] = 1.861881; LUT_Y[210] = 0.881600468;
    LUT_X[211] = 1.8707471; LUT_Y[211] = 0.843093761;
    LUT_X[212] = 1.8796132; LUT_Y[212] = 0.807954246;
    LUT_X[213] = 1.8884793; LUT_Y[213] = 0.775904956;
    LUT_X[214] = 1.8973454; LUT_Y[214] = 0.746601629;
    LUT_X[215] = 1.9062115; LUT_Y[215] = 0.719678583;
    LUT_X[216] = 1.9150776; LUT_Y[216] = 0.694794645;
    LUT_X[217] = 1.9239437; LUT_Y[217] = 0.671656333;
    LUT_X[218] = 1.9328098; LUT_Y[218] = 0.650020938;
    LUT_X[219] = 1.9416759; LUT_Y[219] = 0.629690354;
    LUT_X[220] = 1.950542; LUT_Y[220] = 0.610502794;
    LUT_X[221] = 1.9594081; LUT_Y[221] = 0.592325235;
    LUT_X[222] = 1.9682742; LUT_Y[222] = 0.575047306;
    LUT_X[223] = 1.9771403; LUT_Y[223] = 0.558576531;
    LUT_X[224] = 1.9860064; LUT_Y[224] = 0.542834691;
    LUT_X[225] = 1.9948725; LUT_Y[225] = 0.527755036;
    LUT_X[226] = 2.0037386; LUT_Y[226] = 0.513280125;
    LUT_X[227] = 2.0126047; LUT_Y[227] = 0.499360159;
    LUT_X[228] = 2.0214708; LUT_Y[228] = 0.485951657;
    LUT_X[229] = 2.0303369; LUT_Y[229] = 0.473016418;
    LUT_X[230] = 2.039203; LUT_Y[230] = 0.460520684;
    LUT_X[231] = 2.0480691; LUT_Y[231] = 0.448434464;
    LUT_X[232] = 2.0569352; LUT_Y[232] = 0.436730982;
    LUT_X[233] = 2.0658013; LUT_Y[233] = 0.425386229;
    LUT_X[234] = 2.0746674; LUT_Y[234] = 0.414378587;
    LUT_X[235] = 2.0835335; LUT_Y[235] = 0.403688514;
    LUT_X[236] = 2.0923996; LUT_Y[236] = 0.393298286;
    LUT_X[237] = 2.1012657; LUT_Y[237] = 0.383191771;
    LUT_X[238] = 2.1101318; LUT_Y[238] = 0.373354247;
    LUT_X[239] = 2.1189979; LUT_Y[239] = 0.363772236;
    LUT_X[240] = 2.127864; LUT_Y[240] = 0.354433369;
    LUT_X[241] = 2.1367301; LUT_Y[241] = 0.345326266;
    LUT_X[242] = 2.1455962; LUT_Y[242] = 0.336440432;
    LUT_X[243] = 2.1544623; LUT_Y[243] = 0.32776617;
    LUT_X[244] = 2.1633284; LUT_Y[244] = 0.3192945;
    LUT_X[245] = 2.1721945; LUT_Y[245] = 0.311017089;
    LUT_X[246] = 2.1810606; LUT_Y[246] = 0.302926195;
    LUT_X[247] = 2.1899267; LUT_Y[247] = 0.295014609;
    LUT_X[248] = 2.1987928; LUT_Y[248] = 0.287275611;
    LUT_X[249] = 2.2076589; LUT_Y[249] = 0.279702925;
    LUT_X[250] = 2.216525; LUT_Y[250] = 0.272290682;
    LUT_X[251] = 2.2253911; LUT_Y[251] = 0.265033389;
    LUT_X[252] = 2.2342572; LUT_Y[252] = 0.257925895;
    LUT_X[253] = 2.2431233; LUT_Y[253] = 0.250963369;
    LUT_X[254] = 2.2519894; LUT_Y[254] = 0.24414127;
    LUT_X[255] = 2.2608555; LUT_Y[255] = 0.23745533;
    LUT_X[256] = 2.2697216; LUT_Y[256] = 0.230901533;
    LUT_X[257] = 2.2785877; LUT_Y[257] = 0.224476098;
    LUT_X[258] = 2.2874538; LUT_Y[258] = 0.218175463;
    LUT_X[259] = 2.2963199; LUT_Y[259] = 0.211996274;
    LUT_X[260] = 2.305186; LUT_Y[260] = 0.20593537;
    LUT_X[261] = 2.3140521; LUT_Y[261] = 0.199989783;
    LUT_X[262] = 2.3229182; LUT_Y[262] = 0.194156729;
    LUT_X[263] = 2.3317843; LUT_Y[263] = 0.188433612;
    LUT_X[264] = 2.3406504; LUT_Y[264] = 0.182818047;
    LUT_X[265] = 2.3495165; LUT_Y[265] = 0.177307894;
    LUT_X[266] = 2.3583826; LUT_Y[266] = 0.171901353;
    LUT_X[267] = 2.3672487; LUT_Y[267] = 0.166597116;
    LUT_X[268] = 2.3761148; LUT_Y[268] = 0.161394581;
    LUT_X[269] = 2.3849809; LUT_Y[269] = 0.15629371;
    LUT_X[270] = 2.393847; LUT_Y[270] = 0.151293749;
    LUT_X[271] = 2.4027131; LUT_Y[271] = 0.146391801;
    LUT_X[272] = 2.4115792; LUT_Y[272] = 0.141583775;
    LUT_X[273] = 2.4204453; LUT_Y[273] = 0.136866086;
    LUT_X[274] = 2.4293114; LUT_Y[274] = 0.132236042;
    LUT_X[275] = 2.4381775; LUT_Y[275] = 0.127691579;
    LUT_X[276] = 2.4470436; LUT_Y[276] = 0.123231014;
    LUT_X[277] = 2.4559097; LUT_Y[277] = 0.1188529;
    LUT_X[278] = 2.4647758; LUT_Y[278] = 0.114555953;
    LUT_X[279] = 2.4736419; LUT_Y[279] = 0.11033901;
    LUT_X[280] = 2.482508; LUT_Y[280] = 0.106201014;
    LUT_X[281] = 2.4913741; LUT_Y[281] = 0.102140998;
    LUT_X[282] = 2.5002402; LUT_Y[282] = 0.0981580787;
    LUT_X[283] = 2.5091063; LUT_Y[283] = 0.0942514592;
    LUT_X[284] = 2.5179724; LUT_Y[284] = 0.0904204231;
    LUT_X[285] = 2.5268385; LUT_Y[285] = 0.0866643373;
    LUT_X[286] = 2.5357046; LUT_Y[286] = 0.0829826535;
    LUT_X[287] = 2.5445707; LUT_Y[287] = 0.0793749115;
    LUT_X[288] = 2.5534368; LUT_Y[288] = 0.075840742;
    LUT_X[289] = 2.5623029; LUT_Y[289] = 0.0723798719;
    LUT_X[290] = 2.571169; LUT_Y[290] = 0.0689921285;
    LUT_X[291] = 2.5800351; LUT_Y[291] = 0.0656774455;
    LUT_X[292] = 2.5889012; LUT_Y[292] = 0.0624358689;
    LUT_X[293] = 2.5977673; LUT_Y[293] = 0.0592675636;
    LUT_X[294] = 2.6066334; LUT_Y[294] = 0.0561728198;
    LUT_X[295] = 2.6154995; LUT_Y[295] = 0.0531520594;
    LUT_X[296] = 2.6243656; LUT_Y[296] = 0.0502058427;
    LUT_X[297] = 2.6332317; LUT_Y[297] = 0.0473348737;
    LUT_X[298] = 2.6420978; LUT_Y[298] = 0.044540005;
    LUT_X[299] = 2.6509639; LUT_Y[299] = 0.0418222406;
    LUT_X[300] = 2.65983; LUT_Y[300] = 0.0391827373;
    LUT_X[301] = 2.6686961; LUT_Y[301] = 0.0366228025;
    LUT_X[302] = 2.6775622; LUT_Y[302] = 0.0341438893;
    LUT_X[303] = 2.6864283; LUT_Y[303] = 0.0317475861;
    LUT_X[304] = 2.6952944; LUT_Y[304] = 0.0294356024;
    LUT_X[305] = 2.7041605; LUT_Y[305] = 0.0272097466;
    LUT_X[306] = 2.7130266; LUT_Y[306] = 0.025071898;
    LUT_X[307] = 2.7218927; LUT_Y[307] = 0.0230239703;
    LUT_X[308] = 2.7307588; LUT_Y[308] = 0.0210678662;
    LUT_X[309] = 2.7396249; LUT_Y[309] = 0.0192054242;
    LUT_X[310] = 2.748491; LUT_Y[310] = 0.0174383556;
    LUT_X[311] = 2.7573571; LUT_Y[311] = 0.0157681743;
    LUT_X[312] = 2.7662232; LUT_Y[312] = 0.0141961195;
    LUT_X[313] = 2.7750893; LUT_Y[313] = 0.0127230751;
    LUT_X[314] = 2.7839554; LUT_Y[314] = 0.0113494867;
    LUT_X[315] = 2.7928215; LUT_Y[315] = 0.0100752827;
    LUT_X[316] = 2.8016876; LUT_Y[316] = 0.00889980175;
    LUT_X[317] = 2.8105537; LUT_Y[317] = 0.00782173378;
    LUT_X[318] = 2.8194198; LUT_Y[318] = 0.00683907826;
    LUT_X[319] = 2.8282859; LUT_Y[319] = 0.00594912541;
    LUT_X[320] = 2.837152; LUT_Y[320] = 0.00514846371;
    LUT_X[321] = 2.8460181; LUT_Y[321] = 0.00443301637;
    LUT_X[322] = 2.8548842; LUT_Y[322] = 0.00379810671;
    LUT_X[323] = 2.8637503; LUT_Y[323] = 0.00323855063;
    LUT_X[324] = 2.8726164; LUT_Y[324] = 0.00274877164;
    LUT_X[325] = 2.8814825; LUT_Y[325] = 0.00232293186;
    LUT_X[326] = 2.8903486; LUT_Y[326] = 0.001955071;
    LUT_X[327] = 2.8992147; LUT_Y[327] = 0.00163924443;
    LUT_X[328] = 2.9080808; LUT_Y[328] = 0.00136965175;
    LUT_X[329] = 2.9169469; LUT_Y[329] = 0.00114074861;
    LUT_X[330] = 2.925813; LUT_Y[330] = 0.00094733626;
    LUT_X[331] = 2.9346791; LUT_Y[331] = 0.000784626033;
    LUT_X[332] = 2.9435452; LUT_Y[332] = 0.000648278291;
    LUT_X[333] = 2.9524113; LUT_Y[333] = 0.000534417669;
    LUT_X[334] = 2.9612774; LUT_Y[334] = 0.000439628179;
    LUT_X[335] = 2.9701435; LUT_Y[335] = 0.000360932638;
    LUT_X[336] = 2.9790096; LUT_Y[336] = 0.000295761175;
    LUT_X[337] = 2.9878757; LUT_Y[337] = 0.00024191325;
    LUT_X[338] = 2.9967418; LUT_Y[338] = 0.000197516932;
    LUT_X[339] = 3.0056079; LUT_Y[339] = 0.00016098826;
    LUT_X[340] = 3.014474; LUT_Y[340] = 0.000130992667;
    LUT_X[341] = 3.0233401; LUT_Y[341] = 0.000106409612;
    LUT_X[342] = 3.0322062; LUT_Y[342] = 8.63009905e-05;
    LUT_X[343] = 3.0410723; LUT_Y[343] = 6.98834258e-05;
    LUT_X[344] = 3.0499384; LUT_Y[344] = 5.65042703e-05;
    LUT_X[345] = 3.0588045; LUT_Y[345] = 4.56210121e-05;
    LUT_X[346] = 3.0676706; LUT_Y[346] = 3.67836971e-05;
    LUT_X[347] = 3.0765367; LUT_Y[347] = 2.96199842e-05;
    LUT_X[348] = 3.0854028; LUT_Y[348] = 2.38224705e-05;
    LUT_X[349] = 3.0942689; LUT_Y[349] = 1.91379623e-05;
    LUT_X[350] = 3.103135; LUT_Y[350] = 1.53584098e-05;
    LUT_X[351] = 3.1120011; LUT_Y[351] = 1.23132622e-05;
    LUT_X[352] = 3.1208672; LUT_Y[352] = 9.8630345e-06;
    LUT_X[353] = 3.1297333; LUT_Y[353] = 7.89390837e-06;
    LUT_X[354] = 3.1385994; LUT_Y[354] = 6.31321304e-06;
    LUT_X[355] = 3.1474655; LUT_Y[355] = 5.04565432e-06;
    LUT_X[356] = 3.1563316; LUT_Y[356] = 4.03017813e-06;
    LUT_X[357] = 3.1651977; LUT_Y[357] = 3.21737e-06;
    LUT_X[358] = 3.1740638; LUT_Y[358] = 2.56730609e-06;
    LUT_X[359] = 3.1829299; LUT_Y[359] = 2.0477829e-06;
    LUT_X[360] = 3.191796; LUT_Y[360] = 1.63286345e-06;
    LUT_X[361] = 3.2006621; LUT_Y[361] = 1.3016868e-06;
    LUT_X[362] = 3.2095282; LUT_Y[362] = 1.03749599e-06;
    LUT_X[363] = 3.2183943; LUT_Y[363] = 8.26846265e-07;
    LUT_X[364] = 3.2272604; LUT_Y[364] = 6.58961837e-07;
    LUT_X[365] = 3.2361265; LUT_Y[365] = 5.2521434e-07;
    LUT_X[366] = 3.2449926; LUT_Y[366] = 4.18700918e-07;
    LUT_X[367] = 3.2538587; LUT_Y[367] = 3.33903518e-07;
    LUT_X[368] = 3.2627248; LUT_Y[368] = 2.66414219e-07;
    LUT_X[369] = 3.2715909; LUT_Y[369] = 2.12714158e-07;
    LUT_X[370] = 3.280457; LUT_Y[370] = 1.69995833e-07;
    LUT_X[371] = 3.2893231; LUT_Y[371] = 1.36020463e-07;
    LUT_X[372] = 3.2981892; LUT_Y[372] = 1.09003613e-07;
    LUT_X[373] = 3.3070553; LUT_Y[373] = 8.75235872e-08;
    LUT_X[374] = 3.3159214; LUT_Y[374] = 7.04481107e-08;
    LUT_X[375] = 3.3247875; LUT_Y[375] = 5.68757182e-08;
    LUT_X[376] = 3.3336536; LUT_Y[376] = 4.60889186e-08;
    LUT_X[377] = 3.3425197; LUT_Y[377] = 3.75168023e-08;
    LUT_X[378] = 3.3513858; LUT_Y[378] = 3.07052043e-08;
    LUT_X[379] = 3.3602519; LUT_Y[379] = 2.5292909e-08;
    LUT_X[380] = 3.369118; LUT_Y[380] = 2.09926814e-08;
    LUT_X[381] = 3.3779841; LUT_Y[381] = 1.75761539e-08;
    LUT_X[382] = 3.3868502; LUT_Y[382] = 1.48617903e-08;
    LUT_X[383] = 3.3957163; LUT_Y[383] = 1.27053008e-08;
    LUT_X[384] = 3.4045824; LUT_Y[384] = 1.09920141e-08;
    LUT_X[385] = 3.4134485; LUT_Y[385] = 9.63080692e-09;
    LUT_X[386] = 3.4223146; LUT_Y[386] = 8.54927556e-09;
    LUT_X[387] = 3.4311807; LUT_Y[387] = 7.68989521e-09;
    LUT_X[388] = 3.4400468; LUT_Y[388] = 7.006966e-09;
    LUT_X[389] = 3.4489129; LUT_Y[389] = 6.46418372e-09;
    LUT_X[390] = 3.457779; LUT_Y[390] = 6.03271088e-09;
    LUT_X[391] = 3.4666451; LUT_Y[391] = 5.6896413e-09;
    LUT_X[392] = 3.4755112; LUT_Y[392] = 5.41678175e-09;
    LUT_X[393] = 3.4843773; LUT_Y[393] = 5.19968238e-09;
    LUT_X[394] = 3.4932434; LUT_Y[394] = 5.02686708e-09;
    LUT_X[395] = 3.5021095; LUT_Y[395] = 4.88922174e-09;
    LUT_X[396] = 3.5109756; LUT_Y[396] = 4.7795078e-09;
    LUT_X[397] = 3.5198417; LUT_Y[397] = 4.69197764e-09;
    LUT_X[398] = 3.5287078; LUT_Y[398] = 4.62206646e-09;
    LUT_X[399] = 3.5375739; LUT_Y[399] = 4.56614942e-09;
    LUT_X[400] = 3.54644; LUT_Y[400] = 4.52134765e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[400]) ? LUT_X[400] : xin);
      lo = 0;
      hi = 400;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 76;
  localparam int NDEPTH  = 78;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.361839241;
  localparam real K_FALL = 0.7343010612;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.54644;
  localparam real DOMAIN_EPS = 0.0709288; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
