`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.714e+11 .. 3.835e+11 rad/s
// rise/fall asymmetry 1.8546 (rise x1.3618, fall x0.7343), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.457e-11 s, as a 0/76 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv1_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 191.469; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 1.914685297e-13;
  localparam real DC_BIAS = 1.773253157;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.713564001e+11;
    WX[1] = 0.110828375; WP[1] = 1.713865548e+11;
    WX[2] = 0.22165675; WP[2] = 1.714325963e+11;
    WX[3] = 0.332485125; WP[3] = 1.714920149e+11;
    WX[4] = 0.4433135; WP[4] = 1.715328627e+11;
    WX[5] = 0.554141875; WP[5] = 1.717675775e+11;
    WX[6] = 0.66497025; WP[6] = 1.731755933e+11;
    WX[7] = 0.775798625; WP[7] = 1.761409595e+11;
    WX[8] = 0.886627; WP[8] = 1.798485841e+11;
    WX[9] = 0.997455375; WP[9] = 1.840391037e+11;
    WX[10] = 1.10828375; WP[10] = 1.887783608e+11;
    WX[11] = 1.219112125; WP[11] = 1.942390932e+11;
    WX[12] = 1.3299405; WP[12] = 2.007111206e+11;
    WX[13] = 1.440768875; WP[13] = 2.086660972e+11;
    WX[14] = 1.55159725; WP[14] = 2.190777845e+11;
    WX[15] = 1.662425625; WP[15] = 2.38339379e+11;
    WX[16] = 1.773254; WP[16] = 2.721565513e+11;
    WX[17] = 1.884082375; WP[17] = 3.835138018e+11;
    WX[18] = 1.99491075; WP[18] = 3.679436311e+11;
    WX[19] = 2.105739125; WP[19] = 3.564726964e+11;
    WX[20] = 2.2165675; WP[20] = 3.470893057e+11;
    WX[21] = 2.327395875; WP[21] = 3.391926802e+11;
    WX[22] = 2.43822425; WP[22] = 3.323817549e+11;
    WX[23] = 2.549052625; WP[23] = 3.264429087e+11;
    WX[24] = 2.659881; WP[24] = 3.216991679e+11;
    WX[25] = 2.770709375; WP[25] = 3.193803782e+11;
    WX[26] = 2.88153775; WP[26] = 3.187485603e+11;
    WX[27] = 2.992366125; WP[27] = 3.184235784e+11;
    WX[28] = 3.1031945; WP[28] = 3.182037136e+11;
    WX[29] = 3.214022875; WP[29] = 3.18017995e+11;
    WX[30] = 3.32485125; WP[30] = 3.179055408e+11;
    WX[31] = 3.435679625; WP[31] = 3.178392583e+11;
    WX[32] = 3.546508; WP[32] = 3.177924163e+11;
  end

  real LUT_X[0:400];
  real LUT_Y[0:400];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999946;
    LUT_X[1] = 0.00886627; LUT_Y[1] = 3.29999933;
    LUT_X[2] = 0.01773254; LUT_Y[2] = 3.29999916;
    LUT_X[3] = 0.02659881; LUT_Y[3] = 3.29999895;
    LUT_X[4] = 0.03546508; LUT_Y[4] = 3.2999987;
    LUT_X[5] = 0.04433135; LUT_Y[5] = 3.29999838;
    LUT_X[6] = 0.05319762; LUT_Y[6] = 3.29999798;
    LUT_X[7] = 0.06206389; LUT_Y[7] = 3.29999749;
    LUT_X[8] = 0.07093016; LUT_Y[8] = 3.29999687;
    LUT_X[9] = 0.07979643; LUT_Y[9] = 3.29999611;
    LUT_X[10] = 0.0886627; LUT_Y[10] = 3.29999516;
    LUT_X[11] = 0.09752897; LUT_Y[11] = 3.29999399;
    LUT_X[12] = 0.10639524; LUT_Y[12] = 3.29999254;
    LUT_X[13] = 0.11526151; LUT_Y[13] = 3.29999075;
    LUT_X[14] = 0.12412778; LUT_Y[14] = 3.29998853;
    LUT_X[15] = 0.13299405; LUT_Y[15] = 3.29998579;
    LUT_X[16] = 0.14186032; LUT_Y[16] = 3.29998241;
    LUT_X[17] = 0.15072659; LUT_Y[17] = 3.29997825;
    LUT_X[18] = 0.15959286; LUT_Y[18] = 3.29997314;
    LUT_X[19] = 0.16845913; LUT_Y[19] = 3.29996687;
    LUT_X[20] = 0.1773254; LUT_Y[20] = 3.29995917;
    LUT_X[21] = 0.18619167; LUT_Y[21] = 3.29994976;
    LUT_X[22] = 0.19505794; LUT_Y[22] = 3.29993825;
    LUT_X[23] = 0.20392421; LUT_Y[23] = 3.29992422;
    LUT_X[24] = 0.21279048; LUT_Y[24] = 3.29990714;
    LUT_X[25] = 0.22165675; LUT_Y[25] = 3.29988639;
    LUT_X[26] = 0.23052302; LUT_Y[26] = 3.29986123;
    LUT_X[27] = 0.23938929; LUT_Y[27] = 3.29983078;
    LUT_X[28] = 0.24825556; LUT_Y[28] = 3.29979401;
    LUT_X[29] = 0.25712183; LUT_Y[29] = 3.2997497;
    LUT_X[30] = 0.2659881; LUT_Y[30] = 3.29969643;
    LUT_X[31] = 0.27485437; LUT_Y[31] = 3.29963254;
    LUT_X[32] = 0.28372064; LUT_Y[32] = 3.2995561;
    LUT_X[33] = 0.29258691; LUT_Y[33] = 3.2994649;
    LUT_X[34] = 0.30145318; LUT_Y[34] = 3.29935642;
    LUT_X[35] = 0.31031945; LUT_Y[35] = 3.29922778;
    LUT_X[36] = 0.31918572; LUT_Y[36] = 3.2990758;
    LUT_X[37] = 0.32805199; LUT_Y[37] = 3.29889695;
    LUT_X[38] = 0.33691826; LUT_Y[38] = 3.29868741;
    LUT_X[39] = 0.34578453; LUT_Y[39] = 3.29844309;
    LUT_X[40] = 0.3546508; LUT_Y[40] = 3.29815967;
    LUT_X[41] = 0.36351707; LUT_Y[41] = 3.29783276;
    LUT_X[42] = 0.37238334; LUT_Y[42] = 3.29745792;
    LUT_X[43] = 0.38124961; LUT_Y[43] = 3.29703079;
    LUT_X[44] = 0.39011588; LUT_Y[44] = 3.29654725;
    LUT_X[45] = 0.39898215; LUT_Y[45] = 3.29600349;
    LUT_X[46] = 0.40784842; LUT_Y[46] = 3.29539615;
    LUT_X[47] = 0.41671469; LUT_Y[47] = 3.2947224;
    LUT_X[48] = 0.42558096; LUT_Y[48] = 3.29398;
    LUT_X[49] = 0.43444723; LUT_Y[49] = 3.2931674;
    LUT_X[50] = 0.4433135; LUT_Y[50] = 3.29228366;
    LUT_X[51] = 0.45217977; LUT_Y[51] = 3.29132856;
    LUT_X[52] = 0.46104604; LUT_Y[52] = 3.29030244;
    LUT_X[53] = 0.46991231; LUT_Y[53] = 3.28920626;
    LUT_X[54] = 0.47877858; LUT_Y[54] = 3.28804142;
    LUT_X[55] = 0.48764485; LUT_Y[55] = 3.28680977;
    LUT_X[56] = 0.49651112; LUT_Y[56] = 3.28551346;
    LUT_X[57] = 0.50537739; LUT_Y[57] = 3.28415488;
    LUT_X[58] = 0.51424366; LUT_Y[58] = 3.28273658;
    LUT_X[59] = 0.52310993; LUT_Y[59] = 3.28126117;
    LUT_X[60] = 0.5319762; LUT_Y[60] = 3.27973129;
    LUT_X[61] = 0.54084247; LUT_Y[61] = 3.27814953;
    LUT_X[62] = 0.54970874; LUT_Y[62] = 3.27651838;
    LUT_X[63] = 0.55857501; LUT_Y[63] = 3.27484022;
    LUT_X[64] = 0.56744128; LUT_Y[64] = 3.27311728;
    LUT_X[65] = 0.57630755; LUT_Y[65] = 3.2713516;
    LUT_X[66] = 0.58517382; LUT_Y[66] = 3.26954508;
    LUT_X[67] = 0.59404009; LUT_Y[67] = 3.2676994;
    LUT_X[68] = 0.60290636; LUT_Y[68] = 3.26581608;
    LUT_X[69] = 0.61177263; LUT_Y[69] = 3.26389647;
    LUT_X[70] = 0.6206389; LUT_Y[70] = 3.26194172;
    LUT_X[71] = 0.62950517; LUT_Y[71] = 3.25995286;
    LUT_X[72] = 0.63837144; LUT_Y[72] = 3.25793074;
    LUT_X[73] = 0.64723771; LUT_Y[73] = 3.25587608;
    LUT_X[74] = 0.65610398; LUT_Y[74] = 3.25378946;
    LUT_X[75] = 0.66497025; LUT_Y[75] = 3.25167138;
    LUT_X[76] = 0.67383652; LUT_Y[76] = 3.24952218;
    LUT_X[77] = 0.68270279; LUT_Y[77] = 3.24734216;
    LUT_X[78] = 0.69156906; LUT_Y[78] = 3.24513149;
    LUT_X[79] = 0.70043533; LUT_Y[79] = 3.24289028;
    LUT_X[80] = 0.7093016; LUT_Y[80] = 3.24061857;
    LUT_X[81] = 0.71816787; LUT_Y[81] = 3.23831633;
    LUT_X[82] = 0.72703414; LUT_Y[82] = 3.2359835;
    LUT_X[83] = 0.73590041; LUT_Y[83] = 3.23361993;
    LUT_X[84] = 0.74476668; LUT_Y[84] = 3.23122545;
    LUT_X[85] = 0.75363295; LUT_Y[85] = 3.22879986;
    LUT_X[86] = 0.76249922; LUT_Y[86] = 3.22634289;
    LUT_X[87] = 0.77136549; LUT_Y[87] = 3.22385426;
    LUT_X[88] = 0.78023176; LUT_Y[88] = 3.22133365;
    LUT_X[89] = 0.78909803; LUT_Y[89] = 3.21878073;
    LUT_X[90] = 0.7979643; LUT_Y[90] = 3.2161951;
    LUT_X[91] = 0.80683057; LUT_Y[91] = 3.21357639;
    LUT_X[92] = 0.81569684; LUT_Y[92] = 3.21092417;
    LUT_X[93] = 0.82456311; LUT_Y[93] = 3.20823799;
    LUT_X[94] = 0.83342938; LUT_Y[94] = 3.20551739;
    LUT_X[95] = 0.84229565; LUT_Y[95] = 3.20276188;
    LUT_X[96] = 0.85116192; LUT_Y[96] = 3.19997095;
    LUT_X[97] = 0.86002819; LUT_Y[97] = 3.19714407;
    LUT_X[98] = 0.86889446; LUT_Y[98] = 3.19428068;
    LUT_X[99] = 0.87776073; LUT_Y[99] = 3.19138021;
    LUT_X[100] = 0.886627; LUT_Y[100] = 3.18844205;
    LUT_X[101] = 0.89549327; LUT_Y[101] = 3.18546559;
    LUT_X[102] = 0.90435954; LUT_Y[102] = 3.18245018;
    LUT_X[103] = 0.91322581; LUT_Y[103] = 3.17939515;
    LUT_X[104] = 0.92209208; LUT_Y[104] = 3.1762998;
    LUT_X[105] = 0.93095835; LUT_Y[105] = 3.17316341;
    LUT_X[106] = 0.93982462; LUT_Y[106] = 3.16998523;
    LUT_X[107] = 0.94869089; LUT_Y[107] = 3.16676447;
    LUT_X[108] = 0.95755716; LUT_Y[108] = 3.16350032;
    LUT_X[109] = 0.96642343; LUT_Y[109] = 3.16019195;
    LUT_X[110] = 0.9752897; LUT_Y[110] = 3.15683847;
    LUT_X[111] = 0.98415597; LUT_Y[111] = 3.15343898;
    LUT_X[112] = 0.99302224; LUT_Y[112] = 3.14999253;
    LUT_X[113] = 1.00188851; LUT_Y[113] = 3.14649814;
    LUT_X[114] = 1.01075478; LUT_Y[114] = 3.14295477;
    LUT_X[115] = 1.01962105; LUT_Y[115] = 3.13936136;
    LUT_X[116] = 1.02848732; LUT_Y[116] = 3.13571681;
    LUT_X[117] = 1.03735359; LUT_Y[117] = 3.13201994;
    LUT_X[118] = 1.04621986; LUT_Y[118] = 3.12826956;
    LUT_X[119] = 1.05508613; LUT_Y[119] = 3.12446441;
    LUT_X[120] = 1.0639524; LUT_Y[120] = 3.12060317;
    LUT_X[121] = 1.07281867; LUT_Y[121] = 3.11668447;
    LUT_X[122] = 1.08168494; LUT_Y[122] = 3.11270689;
    LUT_X[123] = 1.09055121; LUT_Y[123] = 3.10866892;
    LUT_X[124] = 1.09941748; LUT_Y[124] = 3.10456902;
    LUT_X[125] = 1.10828375; LUT_Y[125] = 3.10040553;
    LUT_X[126] = 1.11715002; LUT_Y[126] = 3.09617677;
    LUT_X[127] = 1.12601629; LUT_Y[127] = 3.09188093;
    LUT_X[128] = 1.13488256; LUT_Y[128] = 3.08751616;
    LUT_X[129] = 1.14374883; LUT_Y[129] = 3.08308048;
    LUT_X[130] = 1.1526151; LUT_Y[130] = 3.07857184;
    LUT_X[131] = 1.16148137; LUT_Y[131] = 3.07398808;
    LUT_X[132] = 1.17034764; LUT_Y[132] = 3.06932693;
    LUT_X[133] = 1.17921391; LUT_Y[133] = 3.06458603;
    LUT_X[134] = 1.18808018; LUT_Y[134] = 3.05976286;
    LUT_X[135] = 1.19694645; LUT_Y[135] = 3.05485479;
    LUT_X[136] = 1.20581272; LUT_Y[136] = 3.04985905;
    LUT_X[137] = 1.21467899; LUT_Y[137] = 3.04477272;
    LUT_X[138] = 1.22354526; LUT_Y[138] = 3.03959271;
    LUT_X[139] = 1.23241153; LUT_Y[139] = 3.03431578;
    LUT_X[140] = 1.2412778; LUT_Y[140] = 3.02893848;
    LUT_X[141] = 1.25014407; LUT_Y[141] = 3.02345718;
    LUT_X[142] = 1.25901034; LUT_Y[142] = 3.01786803;
    LUT_X[143] = 1.26787661; LUT_Y[143] = 3.01216694;
    LUT_X[144] = 1.27674288; LUT_Y[144] = 3.00634959;
    LUT_X[145] = 1.28560915; LUT_Y[145] = 3.00041137;
    LUT_X[146] = 1.29447542; LUT_Y[146] = 2.99434737;
    LUT_X[147] = 1.30334169; LUT_Y[147] = 2.98815239;
    LUT_X[148] = 1.31220796; LUT_Y[148] = 2.98182086;
    LUT_X[149] = 1.32107423; LUT_Y[149] = 2.97534683;
    LUT_X[150] = 1.3299405; LUT_Y[150] = 2.96872393;
    LUT_X[151] = 1.33880677; LUT_Y[151] = 2.96194535;
    LUT_X[152] = 1.34767304; LUT_Y[152] = 2.95500375;
    LUT_X[153] = 1.35653931; LUT_Y[153] = 2.94789127;
    LUT_X[154] = 1.36540558; LUT_Y[154] = 2.94059939;
    LUT_X[155] = 1.37427185; LUT_Y[155] = 2.93311896;
    LUT_X[156] = 1.38313812; LUT_Y[156] = 2.92544004;
    LUT_X[157] = 1.39200439; LUT_Y[157] = 2.91755185;
    LUT_X[158] = 1.40087066; LUT_Y[158] = 2.90944268;
    LUT_X[159] = 1.40973693; LUT_Y[159] = 2.90109974;
    LUT_X[160] = 1.4186032; LUT_Y[160] = 2.89250905;
    LUT_X[161] = 1.42746947; LUT_Y[161] = 2.88365527;
    LUT_X[162] = 1.43633574; LUT_Y[162] = 2.87452151;
    LUT_X[163] = 1.44520201; LUT_Y[163] = 2.86508913;
    LUT_X[164] = 1.45406828; LUT_Y[164] = 2.85533743;
    LUT_X[165] = 1.46293455; LUT_Y[165] = 2.84524338;
    LUT_X[166] = 1.47180082; LUT_Y[166] = 2.83478122;
    LUT_X[167] = 1.48066709; LUT_Y[167] = 2.82392199;
    LUT_X[168] = 1.48953336; LUT_Y[168] = 2.81263297;
    LUT_X[169] = 1.49839963; LUT_Y[169] = 2.80087695;
    LUT_X[170] = 1.5072659; LUT_Y[170] = 2.78861137;
    LUT_X[171] = 1.51613217; LUT_Y[171] = 2.77578722;
    LUT_X[172] = 1.52499844; LUT_Y[172] = 2.76234753;
    LUT_X[173] = 1.53386471; LUT_Y[173] = 2.74822562;
    LUT_X[174] = 1.54273098; LUT_Y[174] = 2.73334256;
    LUT_X[175] = 1.55159725; LUT_Y[175] = 2.71760399;
    LUT_X[176] = 1.56046352; LUT_Y[176] = 2.70089565;
    LUT_X[177] = 1.56932979; LUT_Y[177] = 2.68307733;
    LUT_X[178] = 1.57819606; LUT_Y[178] = 2.66397429;
    LUT_X[179] = 1.58706233; LUT_Y[179] = 2.64336516;
    LUT_X[180] = 1.5959286; LUT_Y[180] = 2.62096445;
    LUT_X[181] = 1.60479487; LUT_Y[181] = 2.59639784;
    LUT_X[182] = 1.61366114; LUT_Y[182] = 2.56916845;
    LUT_X[183] = 1.62252741; LUT_Y[183] = 2.53861877;
    LUT_X[184] = 1.63139368; LUT_Y[184] = 2.50391446;
    LUT_X[185] = 1.64025995; LUT_Y[185] = 2.46413396;
    LUT_X[186] = 1.64912622; LUT_Y[186] = 2.41858838;
    LUT_X[187] = 1.65799249; LUT_Y[187] = 2.36725254;
    LUT_X[188] = 1.66685876; LUT_Y[188] = 2.31076385;
    LUT_X[189] = 1.67572503; LUT_Y[189] = 2.24995519;
    LUT_X[190] = 1.6845913; LUT_Y[190] = 2.18555102;
    LUT_X[191] = 1.69345757; LUT_Y[191] = 2.11815077;
    LUT_X[192] = 1.70232384; LUT_Y[192] = 2.04828475;
    LUT_X[193] = 1.71119011; LUT_Y[193] = 1.97645145;
    LUT_X[194] = 1.72005638; LUT_Y[194] = 1.90313378;
    LUT_X[195] = 1.72892265; LUT_Y[195] = 1.82880497;
    LUT_X[196] = 1.73778892; LUT_Y[196] = 1.75393052;
    LUT_X[197] = 1.74665519; LUT_Y[197] = 1.67896926;
    LUT_X[198] = 1.75552146; LUT_Y[198] = 1.60437412;
    LUT_X[199] = 1.76438773; LUT_Y[199] = 1.5305924;
    LUT_X[200] = 1.773254; LUT_Y[200] = 1.45806493;
    LUT_X[201] = 1.78212027; LUT_Y[201] = 1.38722336;
    LUT_X[202] = 1.79098654; LUT_Y[202] = 1.31848493;
    LUT_X[203] = 1.79985281; LUT_Y[203] = 1.25224422;
    LUT_X[204] = 1.80871908; LUT_Y[204] = 1.18886215;
    LUT_X[205] = 1.81758535; LUT_Y[205] = 1.12865274;
    LUT_X[206] = 1.82645162; LUT_Y[206] = 1.07186951;
    LUT_X[207] = 1.83531789; LUT_Y[207] = 1.01869368;
    LUT_X[208] = 1.84418416; LUT_Y[208] = 0.969227187;
    LUT_X[209] = 1.85305043; LUT_Y[209] = 0.923492472;
    LUT_X[210] = 1.8619167; LUT_Y[210] = 0.88143838;
    LUT_X[211] = 1.87078297; LUT_Y[211] = 0.842944969;
    LUT_X[212] = 1.87964924; LUT_Y[212] = 0.807817927;
    LUT_X[213] = 1.88851551; LUT_Y[213] = 0.775779942;
    LUT_X[214] = 1.89738178; LUT_Y[214] = 0.746486539;
    LUT_X[215] = 1.90624805; LUT_Y[215] = 0.719572034;
    LUT_X[216] = 1.91511432; LUT_Y[216] = 0.694695399;
    LUT_X[217] = 1.92398059; LUT_Y[217] = 0.67156335;
    LUT_X[218] = 1.93284686; LUT_Y[218] = 0.649933365;
    LUT_X[219] = 1.94171313; LUT_Y[219] = 0.629607495;
    LUT_X[220] = 1.9505794; LUT_Y[220] = 0.610424078;
    LUT_X[221] = 1.95944567; LUT_Y[221] = 0.592250193;
    LUT_X[222] = 1.96831194; LUT_Y[222] = 0.574975545;
    LUT_X[223] = 1.97717821; LUT_Y[223] = 0.55850772;
    LUT_X[224] = 1.98604448; LUT_Y[224] = 0.542768552;
    LUT_X[225] = 1.99491075; LUT_Y[225] = 0.527691328;
    LUT_X[226] = 2.00377702; LUT_Y[226] = 0.513218641;
    LUT_X[227] = 2.01264329; LUT_Y[227] = 0.499300719;
    LUT_X[228] = 2.02150956; LUT_Y[228] = 0.485894104;
    LUT_X[229] = 2.03037583; LUT_Y[229] = 0.472960614;
    LUT_X[230] = 2.0392421; LUT_Y[230] = 0.460466505;
    LUT_X[231] = 2.04810837; LUT_Y[231] = 0.448381801;
    LUT_X[232] = 2.05697464; LUT_Y[232] = 0.436679738;
    LUT_X[233] = 2.06584091; LUT_Y[233] = 0.425336317;
    LUT_X[234] = 2.07470718; LUT_Y[234] = 0.414329928;
    LUT_X[235] = 2.08357345; LUT_Y[235] = 0.403641037;
    LUT_X[236] = 2.09243972; LUT_Y[236] = 0.393251925;
    LUT_X[237] = 2.10130599; LUT_Y[237] = 0.383146469;
    LUT_X[238] = 2.11017226; LUT_Y[238] = 0.373309949;
    LUT_X[239] = 2.11903853; LUT_Y[239] = 0.363728894;
    LUT_X[240] = 2.1279048; LUT_Y[240] = 0.354390938;
    LUT_X[241] = 2.13677107; LUT_Y[241] = 0.345284704;
    LUT_X[242] = 2.14563734; LUT_Y[242] = 0.336399701;
    LUT_X[243] = 2.15450361; LUT_Y[243] = 0.327726235;
    LUT_X[244] = 2.16336988; LUT_Y[244] = 0.319255328;
    LUT_X[245] = 2.17223615; LUT_Y[245] = 0.31097865;
    LUT_X[246] = 2.18110242; LUT_Y[246] = 0.302888462;
    LUT_X[247] = 2.18996869; LUT_Y[247] = 0.294977555;
    LUT_X[248] = 2.19883496; LUT_Y[248] = 0.287239213;
    LUT_X[249] = 2.20770123; LUT_Y[249] = 0.279667159;
    LUT_X[250] = 2.2165675; LUT_Y[250] = 0.272255528;
    LUT_X[251] = 2.22543377; LUT_Y[251] = 0.264998828;
    LUT_X[252] = 2.23430004; LUT_Y[252] = 0.257891908;
    LUT_X[253] = 2.24316631; LUT_Y[253] = 0.250929939;
    LUT_X[254] = 2.25203258; LUT_Y[254] = 0.244108381;
    LUT_X[255] = 2.26089885; LUT_Y[255] = 0.237422968;
    LUT_X[256] = 2.26976512; LUT_Y[256] = 0.230869683;
    LUT_X[257] = 2.27863139; LUT_Y[257] = 0.224444747;
    LUT_X[258] = 2.28749766; LUT_Y[258] = 0.218144599;
    LUT_X[259] = 2.29636393; LUT_Y[259] = 0.211965885;
    LUT_X[260] = 2.3052302; LUT_Y[260] = 0.205905446;
    LUT_X[261] = 2.31409647; LUT_Y[261] = 0.199960314;
    LUT_X[262] = 2.32296274; LUT_Y[262] = 0.194127705;
    LUT_X[263] = 2.33182901; LUT_Y[263] = 0.188405026;
    LUT_X[264] = 2.34069528; LUT_Y[264] = 0.182789891;
    LUT_X[265] = 2.34956155; LUT_Y[265] = 0.177280162;
    LUT_X[266] = 2.35842782; LUT_Y[266] = 0.171874041;
    LUT_X[267] = 2.36729409; LUT_Y[267] = 0.166570223;
    LUT_X[268] = 2.37616036; LUT_Y[268] = 0.16136811;
    LUT_X[269] = 2.38502663; LUT_Y[269] = 0.156267663;
    LUT_X[270] = 2.3938929; LUT_Y[270] = 0.151268123;
    LUT_X[271] = 2.40275917; LUT_Y[271] = 0.146366579;
    LUT_X[272] = 2.41162544; LUT_Y[272] = 0.141558939;
    LUT_X[273] = 2.42049171; LUT_Y[273] = 0.136841624;
    LUT_X[274] = 2.42935798; LUT_Y[274] = 0.132211945;
    LUT_X[275] = 2.43822425; LUT_Y[275] = 0.12766784;
    LUT_X[276] = 2.44709052; LUT_Y[276] = 0.123207629;
    LUT_X[277] = 2.45595679; LUT_Y[277] = 0.118829865;
    LUT_X[278] = 2.46482306; LUT_Y[278] = 0.114533264;
    LUT_X[279] = 2.47368933; LUT_Y[279] = 0.110316665;
    LUT_X[280] = 2.4825556; LUT_Y[280] = 0.10617901;
    LUT_X[281] = 2.49142187; LUT_Y[281] = 0.102119332;
    LUT_X[282] = 2.50028814; LUT_Y[282] = 0.0981367507;
    LUT_X[283] = 2.50915441; LUT_Y[283] = 0.0942304676;
    LUT_X[284] = 2.51802068; LUT_Y[284] = 0.0903997671;
    LUT_X[285] = 2.52688695; LUT_Y[285] = 0.0866440165;
    LUT_X[286] = 2.53575322; LUT_Y[286] = 0.0829626681;
    LUT_X[287] = 2.54461949; LUT_Y[287] = 0.079355262;
    LUT_X[288] = 2.55348576; LUT_Y[288] = 0.0758214295;
    LUT_X[289] = 2.56235203; LUT_Y[289] = 0.0723608979;
    LUT_X[290] = 2.5712183; LUT_Y[290] = 0.0689734952;
    LUT_X[291] = 2.58008457; LUT_Y[291] = 0.0656591556;
    LUT_X[292] = 2.58895084; LUT_Y[292] = 0.0624179259;
    LUT_X[293] = 2.59781711; LUT_Y[293] = 0.0592499715;
    LUT_X[294] = 2.60668338; LUT_Y[294] = 0.0561555833;
    LUT_X[295] = 2.61554965; LUT_Y[295] = 0.0531351843;
    LUT_X[296] = 2.62441592; LUT_Y[296] = 0.0501893353;
    LUT_X[297] = 2.63328219; LUT_Y[297] = 0.0473187414;
    LUT_X[298] = 2.64214846; LUT_Y[298] = 0.0445242559;
    LUT_X[299] = 2.65101473; LUT_Y[299] = 0.0418068839;
    LUT_X[300] = 2.659881; LUT_Y[300] = 0.0391677831;
    LUT_X[301] = 2.66874727; LUT_Y[301] = 0.0366082618;
    LUT_X[302] = 2.67761354; LUT_Y[302] = 0.0341297739;
    LUT_X[303] = 2.68647981; LUT_Y[303] = 0.0317339088;
    LUT_X[304] = 2.69534608; LUT_Y[304] = 0.0294223767;
    LUT_X[305] = 2.70421235; LUT_Y[305] = 0.0271969865;
    LUT_X[306] = 2.71307862; LUT_Y[306] = 0.0250596181;
    LUT_X[307] = 2.72194489; LUT_Y[307] = 0.0230121852;
    LUT_X[308] = 2.73081116; LUT_Y[308] = 0.0210565906;
    LUT_X[309] = 2.73967743; LUT_Y[309] = 0.0191946722;
    LUT_X[310] = 2.7485437; LUT_Y[310] = 0.0174281405;
    LUT_X[311] = 2.75740997; LUT_Y[311] = 0.0157585079;
    LUT_X[312] = 2.76627624; LUT_Y[312] = 0.0141870122;
    LUT_X[313] = 2.77514251; LUT_Y[313] = 0.0127145346;
    LUT_X[314] = 2.78400878; LUT_Y[314] = 0.0113415181;
    LUT_X[315] = 2.79287505; LUT_Y[315] = 0.0100678876;
    LUT_X[316] = 2.80174132; LUT_Y[316] = 0.00889297804;
    LUT_X[317] = 2.81060759; LUT_Y[317] = 0.00781547517;
    LUT_X[318] = 2.81947386; LUT_Y[318] = 0.0068333741;
    LUT_X[319] = 2.82834013; LUT_Y[319] = 0.00594396053;
    LUT_X[320] = 2.8372064; LUT_Y[320] = 0.00514381859;
    LUT_X[321] = 2.84607267; LUT_Y[321] = 0.00442886731;
    LUT_X[322] = 2.85493894; LUT_Y[322] = 0.00379442634;
    LUT_X[323] = 2.86380521; LUT_Y[323] = 0.00323530849;
    LUT_X[324] = 2.87267148; LUT_Y[324] = 0.0027459349;
    LUT_X[325] = 2.88153775; LUT_Y[325] = 0.00232046618;
    LUT_X[326] = 2.89040402; LUT_Y[326] = 0.00195294137;
    LUT_X[327] = 2.89927029; LUT_Y[327] = 0.00163741601;
    LUT_X[328] = 2.90813656; LUT_Y[328] = 0.00136809065;
    LUT_X[329] = 2.91700283; LUT_Y[329] = 0.00113942253;
    LUT_X[330] = 2.9258691; LUT_Y[330] = 0.000946215015;
    LUT_X[331] = 2.93473537; LUT_Y[331] = 0.000783681902;
    LUT_X[332] = 2.94360164; LUT_Y[332] = 0.00064748622;
    LUT_X[333] = 2.95246791; LUT_Y[333] = 0.000533755338;
    LUT_X[334] = 2.96133418; LUT_Y[334] = 0.000439075947;
    LUT_X[335] = 2.97020045; LUT_Y[335] = 0.000360473408;
    LUT_X[336] = 2.97906672; LUT_Y[336] = 0.000295380194;
    LUT_X[337] = 2.98793299; LUT_Y[337] = 0.000241597887;
    LUT_X[338] = 2.99679926; LUT_Y[338] = 0.000197256433;
    LUT_X[339] = 3.00566553; LUT_Y[339] = 0.000160773515;
    LUT_X[340] = 3.0145318; LUT_Y[340] = 0.000130815989;
    LUT_X[341] = 3.02339807; LUT_Y[341] = 0.000106264534;
    LUT_X[342] = 3.03226434; LUT_Y[342] = 8.61820881e-05;
    LUT_X[343] = 3.04113061; LUT_Y[343] = 6.97861595e-05;
    LUT_X[344] = 3.04999688; LUT_Y[344] = 5.642485e-05;
    LUT_X[345] = 3.05886315; LUT_Y[345] = 4.55562804e-05;
    LUT_X[346] = 3.06772942; LUT_Y[346] = 3.67310296e-05;
    LUT_X[347] = 3.07659569; LUT_Y[347] = 2.95772047e-05;
    LUT_X[348] = 3.08546196; LUT_Y[348] = 2.37877786e-05;
    LUT_X[349] = 3.09432823; LUT_Y[349] = 1.91098722e-05;
    LUT_X[350] = 3.1031945; LUT_Y[350] = 1.53356983e-05;
    LUT_X[351] = 3.11206077; LUT_Y[351] = 1.22949243e-05;
    LUT_X[352] = 3.12092704; LUT_Y[352] = 9.84824684e-06;
    LUT_X[353] = 3.12979331; LUT_Y[353] = 7.88199775e-06;
    LUT_X[354] = 3.13865958; LUT_Y[354] = 6.30363022e-06;
    LUT_X[355] = 3.14752585; LUT_Y[355] = 5.03795215e-06;
    LUT_X[356] = 3.15639212; LUT_Y[356] = 4.02399327e-06;
    LUT_X[357] = 3.16525839; LUT_Y[357] = 3.21240777e-06;
    LUT_X[358] = 3.17412466; LUT_Y[358] = 2.56332788e-06;
    LUT_X[359] = 3.18299093; LUT_Y[359] = 2.04459584e-06;
    LUT_X[360] = 3.1918572; LUT_Y[360] = 1.63031184e-06;
    LUT_X[361] = 3.20072347; LUT_Y[361] = 1.29964513e-06;
    LUT_X[362] = 3.20958974; LUT_Y[362] = 1.0358632e-06;
    LUT_X[363] = 3.21845601; LUT_Y[363] = 8.25541102e-07;
    LUT_X[364] = 3.22732228; LUT_Y[364] = 6.57919007e-07;
    LUT_X[365] = 3.23618855; LUT_Y[365] = 5.24381435e-07;
    LUT_X[366] = 3.24505482; LUT_Y[366] = 4.18035912e-07;
    LUT_X[367] = 3.25392109; LUT_Y[367] = 3.33372732e-07;
    LUT_X[368] = 3.26278736; LUT_Y[368] = 2.65990682e-07;
    LUT_X[369] = 3.27165363; LUT_Y[369] = 2.12376284e-07;
    LUT_X[370] = 3.2805199; LUT_Y[370] = 1.69726357e-07;
    LUT_X[371] = 3.28938617; LUT_Y[371] = 1.35805582e-07;
    LUT_X[372] = 3.29825244; LUT_Y[372] = 1.08832297e-07;
    LUT_X[373] = 3.30711871; LUT_Y[373] = 8.73870253e-08;
    LUT_X[374] = 3.31598498; LUT_Y[374] = 7.03392677e-08;
    LUT_X[375] = 3.32485125; LUT_Y[375] = 5.67889789e-08;
    LUT_X[376] = 3.33371752; LUT_Y[376] = 4.60198015e-08;
    LUT_X[377] = 3.34258379; LUT_Y[377] = 3.74617322e-08;
    LUT_X[378] = 3.35145006; LUT_Y[378] = 3.06613302e-08;
    LUT_X[379] = 3.36031633; LUT_Y[379] = 2.52579569e-08;
    LUT_X[380] = 3.3691826; LUT_Y[380] = 2.09648382e-08;
    LUT_X[381] = 3.37804887; LUT_Y[381] = 1.75539747e-08;
    LUT_X[382] = 3.38691514; LUT_Y[382] = 1.48441234e-08;
    LUT_X[383] = 3.39578141; LUT_Y[383] = 1.26912282e-08;
    LUT_X[384] = 3.40464768; LUT_Y[384] = 1.09808043e-08;
    LUT_X[385] = 3.41351395; LUT_Y[385] = 9.6218774e-09;
    LUT_X[386] = 3.42238022; LUT_Y[386] = 8.54216218e-09;
    LUT_X[387] = 3.43124649; LUT_Y[387] = 7.68422787e-09;
    LUT_X[388] = 3.44011276; LUT_Y[388] = 7.00245049e-09;
    LUT_X[389] = 3.44897903; LUT_Y[389] = 6.46058536e-09;
    LUT_X[390] = 3.4578453; LUT_Y[390] = 6.02984269e-09;
    LUT_X[391] = 3.46671157; LUT_Y[391] = 5.68735453e-09;
    LUT_X[392] = 3.47557784; LUT_Y[392] = 5.414958e-09;
    LUT_X[393] = 3.48444411; LUT_Y[393] = 5.19822723e-09;
    LUT_X[394] = 3.49331038; LUT_Y[394] = 5.02570565e-09;
    LUT_X[395] = 3.50217665; LUT_Y[395] = 4.88829368e-09;
    LUT_X[396] = 3.51104292; LUT_Y[396] = 4.77876602e-09;
    LUT_X[397] = 3.51990919; LUT_Y[397] = 4.69138422e-09;
    LUT_X[398] = 3.52877546; LUT_Y[398] = 4.62159093e-09;
    LUT_X[399] = 3.53764173; LUT_Y[399] = 4.5657677e-09;
    LUT_X[400] = 3.546508; LUT_Y[400] = 4.52104094e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[400]) ? LUT_X[400] : xin);
      lo = 0;
      hi = 400;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 76;
  localparam int NDEPTH  = 78;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.361825932;
  localparam real K_FALL = 0.7343082377;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.546508;
  localparam real DOMAIN_EPS = 0.07093016; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
