`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.712e+11 .. 3.838e+11 rad/s
// rise/fall asymmetry 1.8563 (rise x1.3625, fall x0.7340), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.46e-11 s, as a 0/76 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv1_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 191.219; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 1.912186795e-13;
  localparam real DC_BIAS = 1.771624793;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.712013996e+11;
    WX[1] = 0.1107265; WP[1] = 1.712317995e+11;
    WX[2] = 0.221453; WP[2] = 1.712782132e+11;
    WX[3] = 0.3321795; WP[3] = 1.713385426e+11;
    WX[4] = 0.442906; WP[4] = 1.713822606e+11;
    WX[5] = 0.5536325; WP[5] = 1.716232918e+11;
    WX[6] = 0.664359; WP[6] = 1.730429316e+11;
    WX[7] = 0.7750855; WP[7] = 1.760066944e+11;
    WX[8] = 0.885812; WP[8] = 1.797074609e+11;
    WX[9] = 0.9965385; WP[9] = 1.838888915e+11;
    WX[10] = 1.107265; WP[10] = 1.886162773e+11;
    WX[11] = 1.2179915; WP[11] = 1.940679847e+11;
    WX[12] = 1.328718; WP[12] = 2.005170405e+11;
    WX[13] = 1.4394445; WP[13] = 2.084466772e+11;
    WX[14] = 1.550171; WP[14] = 2.188083374e+11;
    WX[15] = 1.6608975; WP[15] = 2.377974488e+11;
    WX[16] = 1.771624; WP[16] = 2.717598542e+11;
    WX[17] = 1.8823505; WP[17] = 3.838347411e+11;
    WX[18] = 1.993077; WP[18] = 3.681666055e+11;
    WX[19] = 2.1038035; WP[19] = 3.566580032e+11;
    WX[20] = 2.21453; WP[20] = 3.472530969e+11;
    WX[21] = 2.3252565; WP[21] = 3.393400852e+11;
    WX[22] = 2.435983; WP[22] = 3.325168882e+11;
    WX[23] = 2.5467095; WP[23] = 3.265641826e+11;
    WX[24] = 2.657436; WP[24] = 3.217855838e+11;
    WX[25] = 2.7681625; WP[25] = 3.194186844e+11;
    WX[26] = 2.878889; WP[26] = 3.187639249e+11;
    WX[27] = 2.9896155; WP[27] = 3.1843189e+11;
    WX[28] = 3.100342; WP[28] = 3.182184093e+11;
    WX[29] = 3.2110685; WP[29] = 3.180302235e+11;
    WX[30] = 3.321795; WP[30] = 3.179173598e+11;
    WX[31] = 3.4325215; WP[31] = 3.178506308e+11;
    WX[32] = 3.543248; WP[32] = 3.178030938e+11;
  end

  real LUT_X[0:400];
  real LUT_Y[0:400];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999946;
    LUT_X[1] = 0.00885812; LUT_Y[1] = 3.29999933;
    LUT_X[2] = 0.01771624; LUT_Y[2] = 3.29999916;
    LUT_X[3] = 0.02657436; LUT_Y[3] = 3.29999895;
    LUT_X[4] = 0.03543248; LUT_Y[4] = 3.2999987;
    LUT_X[5] = 0.0442906; LUT_Y[5] = 3.29999838;
    LUT_X[6] = 0.05314872; LUT_Y[6] = 3.29999798;
    LUT_X[7] = 0.06200684; LUT_Y[7] = 3.29999749;
    LUT_X[8] = 0.07086496; LUT_Y[8] = 3.29999688;
    LUT_X[9] = 0.07972308; LUT_Y[9] = 3.29999612;
    LUT_X[10] = 0.0885812; LUT_Y[10] = 3.29999517;
    LUT_X[11] = 0.09743932; LUT_Y[11] = 3.299994;
    LUT_X[12] = 0.10629744; LUT_Y[12] = 3.29999256;
    LUT_X[13] = 0.11515556; LUT_Y[13] = 3.29999077;
    LUT_X[14] = 0.12401368; LUT_Y[14] = 3.29998856;
    LUT_X[15] = 0.1328718; LUT_Y[15] = 3.29998583;
    LUT_X[16] = 0.14172992; LUT_Y[16] = 3.29998247;
    LUT_X[17] = 0.15058804; LUT_Y[17] = 3.29997833;
    LUT_X[18] = 0.15944616; LUT_Y[18] = 3.29997324;
    LUT_X[19] = 0.16830428; LUT_Y[19] = 3.29996699;
    LUT_X[20] = 0.1771624; LUT_Y[20] = 3.29995933;
    LUT_X[21] = 0.18602052; LUT_Y[21] = 3.29994996;
    LUT_X[22] = 0.19487864; LUT_Y[22] = 3.29993851;
    LUT_X[23] = 0.20373676; LUT_Y[23] = 3.29992455;
    LUT_X[24] = 0.21259488; LUT_Y[24] = 3.29990755;
    LUT_X[25] = 0.221453; LUT_Y[25] = 3.29988691;
    LUT_X[26] = 0.23031112; LUT_Y[26] = 3.29986189;
    LUT_X[27] = 0.23916924; LUT_Y[27] = 3.29983161;
    LUT_X[28] = 0.24802736; LUT_Y[28] = 3.29979504;
    LUT_X[29] = 0.25688548; LUT_Y[29] = 3.29975099;
    LUT_X[30] = 0.2657436; LUT_Y[30] = 3.29969804;
    LUT_X[31] = 0.27460172; LUT_Y[31] = 3.29963453;
    LUT_X[32] = 0.28345984; LUT_Y[32] = 3.29955855;
    LUT_X[33] = 0.29231796; LUT_Y[33] = 3.29946791;
    LUT_X[34] = 0.30117608; LUT_Y[34] = 3.2993601;
    LUT_X[35] = 0.3100342; LUT_Y[35] = 3.29923226;
    LUT_X[36] = 0.31889232; LUT_Y[36] = 3.29908124;
    LUT_X[37] = 0.32775044; LUT_Y[37] = 3.29890352;
    LUT_X[38] = 0.33660856; LUT_Y[38] = 3.29869529;
    LUT_X[39] = 0.34546668; LUT_Y[39] = 3.29845249;
    LUT_X[40] = 0.3543248; LUT_Y[40] = 3.29817084;
    LUT_X[41] = 0.36318292; LUT_Y[41] = 3.29784593;
    LUT_X[42] = 0.37204104; LUT_Y[42] = 3.29747333;
    LUT_X[43] = 0.38089916; LUT_Y[43] = 3.29704872;
    LUT_X[44] = 0.38975728; LUT_Y[44] = 3.29656795;
    LUT_X[45] = 0.3986154; LUT_Y[45] = 3.29602722;
    LUT_X[46] = 0.40747352; LUT_Y[46] = 3.29542316;
    LUT_X[47] = 0.41633164; LUT_Y[47] = 3.29475291;
    LUT_X[48] = 0.42518976; LUT_Y[48] = 3.29401423;
    LUT_X[49] = 0.43404788; LUT_Y[49] = 3.29320552;
    LUT_X[50] = 0.442906; LUT_Y[50] = 3.29232585;
    LUT_X[51] = 0.45176412; LUT_Y[51] = 3.29137492;
    LUT_X[52] = 0.46062224; LUT_Y[52] = 3.29035309;
    LUT_X[53] = 0.46948036; LUT_Y[53] = 3.28926126;
    LUT_X[54] = 0.47833848; LUT_Y[54] = 3.28810083;
    LUT_X[55] = 0.4871966; LUT_Y[55] = 3.28687361;
    LUT_X[56] = 0.49605472; LUT_Y[56] = 3.28558173;
    LUT_X[57] = 0.50491284; LUT_Y[57] = 3.28422757;
    LUT_X[58] = 0.51377096; LUT_Y[58] = 3.28281366;
    LUT_X[59] = 0.52262908; LUT_Y[59] = 3.28134261;
    LUT_X[60] = 0.5314872; LUT_Y[60] = 3.27981705;
    LUT_X[61] = 0.54034532; LUT_Y[61] = 3.27823955;
    LUT_X[62] = 0.54920344; LUT_Y[62] = 3.27661263;
    LUT_X[63] = 0.55806156; LUT_Y[63] = 3.27493865;
    LUT_X[64] = 0.56691968; LUT_Y[64] = 3.27321984;
    LUT_X[65] = 0.5757778; LUT_Y[65] = 3.27145827;
    LUT_X[66] = 0.58463592; LUT_Y[66] = 3.26965581;
    LUT_X[67] = 0.59349404; LUT_Y[67] = 3.26781417;
    LUT_X[68] = 0.60235216; LUT_Y[68] = 3.26593488;
    LUT_X[69] = 0.61121028; LUT_Y[69] = 3.26401928;
    LUT_X[70] = 0.6200684; LUT_Y[70] = 3.26206854;
    LUT_X[71] = 0.62892652; LUT_Y[71] = 3.26008369;
    LUT_X[72] = 0.63778464; LUT_Y[72] = 3.25806558;
    LUT_X[73] = 0.64664276; LUT_Y[73] = 3.25601496;
    LUT_X[74] = 0.65550088; LUT_Y[74] = 3.2539324;
    LUT_X[75] = 0.664359; LUT_Y[75] = 3.2518184;
    LUT_X[76] = 0.67321712; LUT_Y[76] = 3.24967333;
    LUT_X[77] = 0.68207524; LUT_Y[77] = 3.24749747;
    LUT_X[78] = 0.69093336; LUT_Y[78] = 3.24529101;
    LUT_X[79] = 0.69979148; LUT_Y[79] = 3.24305405;
    LUT_X[80] = 0.7086496; LUT_Y[80] = 3.24078666;
    LUT_X[81] = 0.71750772; LUT_Y[81] = 3.2384888;
    LUT_X[82] = 0.72636584; LUT_Y[82] = 3.2361604;
    LUT_X[83] = 0.73522396; LUT_Y[83] = 3.23380134;
    LUT_X[84] = 0.74408208; LUT_Y[84] = 3.23141145;
    LUT_X[85] = 0.7529402; LUT_Y[85] = 3.2289905;
    LUT_X[86] = 0.76179832; LUT_Y[86] = 3.22653827;
    LUT_X[87] = 0.77065644; LUT_Y[87] = 3.22405445;
    LUT_X[88] = 0.77951456; LUT_Y[88] = 3.22153874;
    LUT_X[89] = 0.78837268; LUT_Y[89] = 3.2189908;
    LUT_X[90] = 0.7972308; LUT_Y[90] = 3.21641026;
    LUT_X[91] = 0.80608892; LUT_Y[91] = 3.21379672;
    LUT_X[92] = 0.81494704; LUT_Y[92] = 3.21114977;
    LUT_X[93] = 0.82380516; LUT_Y[93] = 3.20846896;
    LUT_X[94] = 0.83266328; LUT_Y[94] = 3.20575384;
    LUT_X[95] = 0.8415214; LUT_Y[95] = 3.20300391;
    LUT_X[96] = 0.85037952; LUT_Y[96] = 3.20021867;
    LUT_X[97] = 0.85923764; LUT_Y[97] = 3.1973976;
    LUT_X[98] = 0.86809576; LUT_Y[98] = 3.19454013;
    LUT_X[99] = 0.87695388; LUT_Y[99] = 3.1916457;
    LUT_X[100] = 0.885812; LUT_Y[100] = 3.18871372;
    LUT_X[101] = 0.89467012; LUT_Y[101] = 3.18574356;
    LUT_X[102] = 0.90352824; LUT_Y[102] = 3.18273458;
    LUT_X[103] = 0.91238636; LUT_Y[103] = 3.17968612;
    LUT_X[104] = 0.92124448; LUT_Y[104] = 3.17659748;
    LUT_X[105] = 0.9301026; LUT_Y[105] = 3.17346794;
    LUT_X[106] = 0.93896072; LUT_Y[106] = 3.17029676;
    LUT_X[107] = 0.94781884; LUT_Y[107] = 3.16708316;
    LUT_X[108] = 0.95667696; LUT_Y[108] = 3.16382634;
    LUT_X[109] = 0.96553508; LUT_Y[109] = 3.16052545;
    LUT_X[110] = 0.9743932; LUT_Y[110] = 3.15717963;
    LUT_X[111] = 0.98325132; LUT_Y[111] = 3.15378798;
    LUT_X[112] = 0.99210944; LUT_Y[112] = 3.15034955;
    LUT_X[113] = 1.00096756; LUT_Y[113] = 3.14686336;
    LUT_X[114] = 1.00982568; LUT_Y[114] = 3.14332841;
    LUT_X[115] = 1.0186838; LUT_Y[115] = 3.13974362;
    LUT_X[116] = 1.02754192; LUT_Y[116] = 3.13610789;
    LUT_X[117] = 1.03640004; LUT_Y[117] = 3.13242008;
    LUT_X[118] = 1.04525816; LUT_Y[118] = 3.12867898;
    LUT_X[119] = 1.05411628; LUT_Y[119] = 3.12488335;
    LUT_X[120] = 1.0629744; LUT_Y[120] = 3.12103188;
    LUT_X[121] = 1.07183252; LUT_Y[121] = 3.11712321;
    LUT_X[122] = 1.08069064; LUT_Y[122] = 3.11315593;
    LUT_X[123] = 1.08954876; LUT_Y[123] = 3.10912854;
    LUT_X[124] = 1.09840688; LUT_Y[124] = 3.10503951;
    LUT_X[125] = 1.107265; LUT_Y[125] = 3.10088721;
    LUT_X[126] = 1.11612312; LUT_Y[126] = 3.09666995;
    LUT_X[127] = 1.12498124; LUT_Y[127] = 3.09238595;
    LUT_X[128] = 1.13383936; LUT_Y[128] = 3.08803336;
    LUT_X[129] = 1.14269748; LUT_Y[129] = 3.08361022;
    LUT_X[130] = 1.1515556; LUT_Y[130] = 3.07911452;
    LUT_X[131] = 1.16041372; LUT_Y[131] = 3.07454409;
    LUT_X[132] = 1.16927184; LUT_Y[132] = 3.0698967;
    LUT_X[133] = 1.17812996; LUT_Y[133] = 3.06516999;
    LUT_X[134] = 1.18698808; LUT_Y[134] = 3.06036148;
    LUT_X[135] = 1.1958462; LUT_Y[135] = 3.05546856;
    LUT_X[136] = 1.20470432; LUT_Y[136] = 3.05048848;
    LUT_X[137] = 1.21356244; LUT_Y[137] = 3.04541834;
    LUT_X[138] = 1.22242056; LUT_Y[138] = 3.0402551;
    LUT_X[139] = 1.23127868; LUT_Y[139] = 3.03499554;
    LUT_X[140] = 1.2401368; LUT_Y[140] = 3.02963624;
    LUT_X[141] = 1.24899492; LUT_Y[141] = 3.02417361;
    LUT_X[142] = 1.25785304; LUT_Y[142] = 3.01860384;
    LUT_X[143] = 1.26671116; LUT_Y[143] = 3.01292288;
    LUT_X[144] = 1.27556928; LUT_Y[144] = 3.00712645;
    LUT_X[145] = 1.2844274; LUT_Y[145] = 3.00121;
    LUT_X[146] = 1.29328552; LUT_Y[146] = 2.99516868;
    LUT_X[147] = 1.30214364; LUT_Y[147] = 2.98899734;
    LUT_X[148] = 1.31100176; LUT_Y[148] = 2.98269047;
    LUT_X[149] = 1.31985988; LUT_Y[149] = 2.97624218;
    LUT_X[150] = 1.328718; LUT_Y[150] = 2.96964621;
    LUT_X[151] = 1.33757612; LUT_Y[151] = 2.9628958;
    LUT_X[152] = 1.34643424; LUT_Y[152] = 2.95598372;
    LUT_X[153] = 1.35529236; LUT_Y[153] = 2.9489022;
    LUT_X[154] = 1.36415048; LUT_Y[154] = 2.94164286;
    LUT_X[155] = 1.3730086; LUT_Y[155] = 2.93419665;
    LUT_X[156] = 1.38186672; LUT_Y[156] = 2.92655377;
    LUT_X[157] = 1.39072484; LUT_Y[157] = 2.9187036;
    LUT_X[158] = 1.39958296; LUT_Y[158] = 2.91063462;
    LUT_X[159] = 1.40844108; LUT_Y[159] = 2.90233421;
    LUT_X[160] = 1.4172992; LUT_Y[160] = 2.89378863;
    LUT_X[161] = 1.42615732; LUT_Y[161] = 2.88498279;
    LUT_X[162] = 1.43501544; LUT_Y[162] = 2.87590009;
    LUT_X[163] = 1.44387356; LUT_Y[163] = 2.86652221;
    LUT_X[164] = 1.45273168; LUT_Y[164] = 2.85682883;
    LUT_X[165] = 1.4615898; LUT_Y[165] = 2.84679736;
    LUT_X[166] = 1.47044792; LUT_Y[166] = 2.83640255;
    LUT_X[167] = 1.47930604; LUT_Y[167] = 2.82561604;
    LUT_X[168] = 1.48816416; LUT_Y[168] = 2.81440581;
    LUT_X[169] = 1.49702228; LUT_Y[169] = 2.8027355;
    LUT_X[170] = 1.5058804; LUT_Y[170] = 2.79056356;
    LUT_X[171] = 1.51473852; LUT_Y[171] = 2.7778422;
    LUT_X[172] = 1.52359664; LUT_Y[172] = 2.76451597;
    LUT_X[173] = 1.53245476; LUT_Y[173] = 2.75052003;
    LUT_X[174] = 1.54131288; LUT_Y[174] = 2.73577782;
    LUT_X[175] = 1.550171; LUT_Y[175] = 2.72019793;
    LUT_X[176] = 1.55902912; LUT_Y[176] = 2.70366997;
    LUT_X[177] = 1.56788724; LUT_Y[177] = 2.68605879;
    LUT_X[178] = 1.57674536; LUT_Y[178] = 2.66719643;
    LUT_X[179] = 1.58560348; LUT_Y[179] = 2.64687075;
    LUT_X[180] = 1.5944616; LUT_Y[180] = 2.62480902;
    LUT_X[181] = 1.60331972; LUT_Y[181] = 2.60065463;
    LUT_X[182] = 1.61217784; LUT_Y[182] = 2.57393503;
    LUT_X[183] = 1.62103596; LUT_Y[183] = 2.54402357;
    LUT_X[184] = 1.62989408; LUT_Y[184] = 2.51011602;
    LUT_X[185] = 1.6387522; LUT_Y[185] = 2.47129296;
    LUT_X[186] = 1.64761032; LUT_Y[186] = 2.42679529;
    LUT_X[187] = 1.65646844; LUT_Y[187] = 2.37646648;
    LUT_X[188] = 1.66532656; LUT_Y[188] = 2.32085705;
    LUT_X[189] = 1.67418468; LUT_Y[189] = 2.26079604;
    LUT_X[190] = 1.6830428; LUT_Y[190] = 2.19703091;
    LUT_X[191] = 1.69190092; LUT_Y[191] = 2.13017716;
    LUT_X[192] = 1.70075904; LUT_Y[192] = 2.06077226;
    LUT_X[193] = 1.70961716; LUT_Y[193] = 1.98931727;
    LUT_X[194] = 1.71847528; LUT_Y[194] = 1.91629593;
    LUT_X[195] = 1.7273334; LUT_Y[195] = 1.84218167;
    LUT_X[196] = 1.73619152; LUT_Y[196] = 1.76744001;
    LUT_X[197] = 1.74504964; LUT_Y[197] = 1.69252963;
    LUT_X[198] = 1.75390776; LUT_Y[198] = 1.61790325;
    LUT_X[199] = 1.76276588; LUT_Y[199] = 1.54400798;
    LUT_X[200] = 1.771624; LUT_Y[200] = 1.47128473;
    LUT_X[201] = 1.78048212; LUT_Y[201] = 1.40016597;
    LUT_X[202] = 1.78934024; LUT_Y[202] = 1.33107094;
    LUT_X[203] = 1.79819836; LUT_Y[203] = 1.26439811;
    LUT_X[204] = 1.80705648; LUT_Y[204] = 1.20051457;
    LUT_X[205] = 1.8159146; LUT_Y[205] = 1.13974331;
    LUT_X[206] = 1.82477272; LUT_Y[206] = 1.08234947;
    LUT_X[207] = 1.83363084; LUT_Y[207] = 1.02852811;
    LUT_X[208] = 1.84248896; LUT_Y[208] = 0.978396121;
    LUT_X[209] = 1.85134708; LUT_Y[209] = 0.931990694;
    LUT_X[210] = 1.8602052; LUT_Y[210] = 0.889274321;
    LUT_X[211] = 1.86906332; LUT_Y[211] = 0.850140641;
    LUT_X[212] = 1.87792144; LUT_Y[212] = 0.814411145;
    LUT_X[213] = 1.88677956; LUT_Y[213] = 0.781825261;
    LUT_X[214] = 1.89563768; LUT_Y[214] = 0.752049574;
    LUT_X[215] = 1.9044958; LUT_Y[215] = 0.724719441;
    LUT_X[216] = 1.91335392; LUT_Y[216] = 0.699487299;
    LUT_X[217] = 1.92221204; LUT_Y[217] = 0.676050525;
    LUT_X[218] = 1.93107016; LUT_Y[218] = 0.654157527;
    LUT_X[219] = 1.93992828; LUT_Y[219] = 0.633602672;
    LUT_X[220] = 1.9487864; LUT_Y[220] = 0.614218122;
    LUT_X[221] = 1.95764452; LUT_Y[221] = 0.595866079;
    LUT_X[222] = 1.96650264; LUT_Y[222] = 0.578432402;
    LUT_X[223] = 1.97536076; LUT_Y[223] = 0.561821628;
    LUT_X[224] = 1.98421888; LUT_Y[224] = 0.545953151;
    LUT_X[225] = 1.993077; LUT_Y[225] = 0.53075829;
    LUT_X[226] = 2.00193512; LUT_Y[226] = 0.516178032;
    LUT_X[227] = 2.01079324; LUT_Y[227] = 0.502161281;
    LUT_X[228] = 2.01965136; LUT_Y[228] = 0.488663482;
    LUT_X[229] = 2.02850948; LUT_Y[229] = 0.475645533;
    LUT_X[230] = 2.0373676; LUT_Y[230] = 0.463072915;
    LUT_X[231] = 2.04622572; LUT_Y[231] = 0.45091499;
    LUT_X[232] = 2.05508384; LUT_Y[232] = 0.439144431;
    LUT_X[233] = 2.06394196; LUT_Y[233] = 0.427736752;
    LUT_X[234] = 2.07280008; LUT_Y[234] = 0.41666992;
    LUT_X[235] = 2.0816582; LUT_Y[235] = 0.405924035;
    LUT_X[236] = 2.09051632; LUT_Y[236] = 0.395481057;
    LUT_X[237] = 2.09937444; LUT_Y[237] = 0.385324579;
    LUT_X[238] = 2.10823256; LUT_Y[238] = 0.375439633;
    LUT_X[239] = 2.11709068; LUT_Y[239] = 0.365812525;
    LUT_X[240] = 2.1259488; LUT_Y[240] = 0.356430692;
    LUT_X[241] = 2.13480692; LUT_Y[241] = 0.347282582;
    LUT_X[242] = 2.14366504; LUT_Y[242] = 0.338357544;
    LUT_X[243] = 2.15252316; LUT_Y[243] = 0.329645742;
    LUT_X[244] = 2.16138128; LUT_Y[244] = 0.32113807;
    LUT_X[245] = 2.1702394; LUT_Y[245] = 0.312826083;
    LUT_X[246] = 2.17909752; LUT_Y[246] = 0.304701933;
    LUT_X[247] = 2.18795564; LUT_Y[247] = 0.296758318;
    LUT_X[248] = 2.19681376; LUT_Y[248] = 0.288988432;
    LUT_X[249] = 2.20567188; LUT_Y[249] = 0.281385921;
    LUT_X[250] = 2.21453; LUT_Y[250] = 0.273944843;
    LUT_X[251] = 2.22338812; LUT_Y[251] = 0.266659639;
    LUT_X[252] = 2.23224624; LUT_Y[252] = 0.259525098;
    LUT_X[253] = 2.24110436; LUT_Y[253] = 0.252536331;
    LUT_X[254] = 2.24996248; LUT_Y[254] = 0.245688746;
    LUT_X[255] = 2.2588206; LUT_Y[255] = 0.238978026;
    LUT_X[256] = 2.26767872; LUT_Y[256] = 0.23240011;
    LUT_X[257] = 2.27653684; LUT_Y[257] = 0.225951175;
    LUT_X[258] = 2.28539496; LUT_Y[258] = 0.219627618;
    LUT_X[259] = 2.29425308; LUT_Y[259] = 0.213426049;
    LUT_X[260] = 2.3031112; LUT_Y[260] = 0.207343271;
    LUT_X[261] = 2.31196932; LUT_Y[261] = 0.201376278;
    LUT_X[262] = 2.32082744; LUT_Y[262] = 0.195522252;
    LUT_X[263] = 2.32968556; LUT_Y[263] = 0.189778559;
    LUT_X[264] = 2.33854368; LUT_Y[264] = 0.184142767;
    LUT_X[265] = 2.3474018; LUT_Y[265] = 0.17861268;
    LUT_X[266] = 2.35625992; LUT_Y[266] = 0.173186408;
    LUT_X[267] = 2.36511804; LUT_Y[267] = 0.167862512;
    LUT_X[268] = 2.37397616; LUT_Y[268] = 0.16264021;
    LUT_X[269] = 2.38283428; LUT_Y[269] = 0.157519392;
    LUT_X[270] = 2.3916924; LUT_Y[270] = 0.152499655;
    LUT_X[271] = 2.40055052; LUT_Y[271] = 0.147578646;
    LUT_X[272] = 2.40940864; LUT_Y[272] = 0.142752383;
    LUT_X[273] = 2.41826676; LUT_Y[273] = 0.138017084;
    LUT_X[274] = 2.42712488; LUT_Y[274] = 0.133369862;
    LUT_X[275] = 2.435983; LUT_Y[275] = 0.128808532;
    LUT_X[276] = 2.44484112; LUT_Y[276] = 0.124331339;
    LUT_X[277] = 2.45369924; LUT_Y[277] = 0.11993679;
    LUT_X[278] = 2.46255736; LUT_Y[278] = 0.115623569;
    LUT_X[279] = 2.47141548; LUT_Y[279] = 0.111390489;
    LUT_X[280] = 2.4802736; LUT_Y[280] = 0.10723647;
    LUT_X[281] = 2.48913172; LUT_Y[281] = 0.103160524;
    LUT_X[282] = 2.49798984; LUT_Y[282] = 0.0991617526;
    LUT_X[283] = 2.50684796; LUT_Y[283] = 0.0952393376;
    LUT_X[284] = 2.51570608; LUT_Y[284] = 0.0913925441;
    LUT_X[285] = 2.5245642; LUT_Y[285] = 0.0876207197;
    LUT_X[286] = 2.53342232; LUT_Y[286] = 0.0839232955;
    LUT_X[287] = 2.54228044; LUT_Y[287] = 0.0802997898;
    LUT_X[288] = 2.55113856; LUT_Y[288] = 0.0767498104;
    LUT_X[289] = 2.55999668; LUT_Y[289] = 0.0732730598;
    LUT_X[290] = 2.5688548; LUT_Y[290] = 0.0698693391;
    LUT_X[291] = 2.57771292; LUT_Y[291] = 0.066538554;
    LUT_X[292] = 2.58657104; LUT_Y[292] = 0.0632807206;
    LUT_X[293] = 2.59542916; LUT_Y[293] = 0.0600959716;
    LUT_X[294] = 2.60428728; LUT_Y[294] = 0.0569845627;
    LUT_X[295] = 2.6131454; LUT_Y[295] = 0.0539468795;
    LUT_X[296] = 2.62200352; LUT_Y[296] = 0.0509834435;
    LUT_X[297] = 2.63086164; LUT_Y[297] = 0.0480949183;
    LUT_X[298] = 2.63971976; LUT_Y[298] = 0.0452821142;
    LUT_X[299] = 2.64857788; LUT_Y[299] = 0.0425459919;
    LUT_X[300] = 2.657436; LUT_Y[300] = 0.0398876642;
    LUT_X[301] = 2.66629412; LUT_Y[301] = 0.0373083948;
    LUT_X[302] = 2.67515224; LUT_Y[302] = 0.0348095943;
    LUT_X[303] = 2.68401036; LUT_Y[303] = 0.0323928116;
    LUT_X[304] = 2.69286848; LUT_Y[304] = 0.0300597204;
    LUT_X[305] = 2.7017266; LUT_Y[305] = 0.0278120999;
    LUT_X[306] = 2.71058472; LUT_Y[306] = 0.0256518081;
    LUT_X[307] = 2.71944284; LUT_Y[307] = 0.0235807483;
    LUT_X[308] = 2.72830096; LUT_Y[308] = 0.0216008261;
    LUT_X[309] = 2.73715908; LUT_Y[309] = 0.0197138986;
    LUT_X[310] = 2.7460172; LUT_Y[310] = 0.0179217145;
    LUT_X[311] = 2.75487532; LUT_Y[311] = 0.0162258459;
    LUT_X[312] = 2.76373344; LUT_Y[312] = 0.0146276134;
    LUT_X[313] = 2.77259156; LUT_Y[313] = 0.0131280059;
    LUT_X[314] = 2.78144968; LUT_Y[314] = 0.0117275993;
    LUT_X[315] = 2.7903078; LUT_Y[315] = 0.0104264752;
    LUT_X[316] = 2.79916592; LUT_Y[316] = 0.00922414725;
    LUT_X[317] = 2.80802404; LUT_Y[317] = 0.00811949778;
    LUT_X[318] = 2.81688216; LUT_Y[318] = 0.00711073079;
    LUT_X[319] = 2.82574028; LUT_Y[319] = 0.00619534637;
    LUT_X[320] = 2.8345984; LUT_Y[320] = 0.0053701404;
    LUT_X[321] = 2.84345652; LUT_Y[321] = 0.00463123244;
    LUT_X[322] = 2.85231464; LUT_Y[322] = 0.00397412265;
    LUT_X[323] = 2.86117276; LUT_Y[323] = 0.00339377642;
    LUT_X[324] = 2.87003088; LUT_Y[324] = 0.00288473298;
    LUT_X[325] = 2.878889; LUT_Y[325] = 0.00244123194;
    LUT_X[326] = 2.88774712; LUT_Y[326] = 0.00205735029;
    LUT_X[327] = 2.89660524; LUT_Y[327] = 0.00172714096;
    LUT_X[328] = 2.90546336; LUT_Y[328] = 0.00144476448;
    LUT_X[329] = 2.91432148; LUT_Y[329] = 0.00120460577;
    LUT_X[330] = 2.9231796; LUT_Y[330] = 0.00100137036;
    LUT_X[331] = 2.93203772; LUT_Y[331] = 0.000830156017;
    LUT_X[332] = 2.94089584; LUT_Y[332] = 0.000686498986;
    LUT_X[333] = 2.94975396; LUT_Y[333] = 0.000566395888;
    LUT_X[334] = 2.95861208; LUT_Y[334] = 0.000466304382;
    LUT_X[335] = 2.9674702; LUT_Y[335] = 0.000383126857;
    LUT_X[336] = 2.97632832; LUT_Y[336] = 0.000314181852;
    LUT_X[337] = 2.98518644; LUT_Y[337] = 0.000257167768;
    LUT_X[338] = 2.99404456; LUT_Y[338] = 0.000210122804;
    LUT_X[339] = 3.00290268; LUT_Y[339] = 0.000171384231;
    LUT_X[340] = 3.0117608; LUT_Y[340] = 0.000139549213;
    LUT_X[341] = 3.02061892; LUT_Y[341] = 0.000113438536;
    LUT_X[342] = 3.02947704; LUT_Y[342] = 9.20639889e-05;
    LUT_X[343] = 3.03833516; LUT_Y[343] = 7.45995971e-05;
    LUT_X[344] = 3.04719328; LUT_Y[344] = 6.03566278e-05;
    LUT_X[345] = 3.0560514; LUT_Y[345] = 4.87620825e-05;
    LUT_X[346] = 3.06490952; LUT_Y[346] = 3.93403121e-05;
    LUT_X[347] = 3.07376764; LUT_Y[347] = 3.16973661e-05;
    LUT_X[348] = 3.08262576; LUT_Y[348] = 2.55077092e-05;
    LUT_X[349] = 3.09148388; LUT_Y[349] = 2.0502968e-05;
    LUT_X[350] = 3.100342; LUT_Y[350] = 1.64624169e-05;
    LUT_X[351] = 3.10920012; LUT_Y[351] = 1.32049472e-05;
    LUT_X[352] = 3.11805824; LUT_Y[352] = 1.05823047e-05;
    LUT_X[353] = 3.12691636; LUT_Y[353] = 8.47340707e-06;
    LUT_X[354] = 3.13577448; LUT_Y[354] = 6.77958345e-06;
    LUT_X[355] = 3.1446326; LUT_Y[355] = 5.42059705e-06;
    LUT_X[356] = 3.15349072; LUT_Y[356] = 4.33133324e-06;
    LUT_X[357] = 3.16234884; LUT_Y[357] = 3.45905025e-06;
    LUT_X[358] = 3.17120696; LUT_Y[358] = 2.76110444e-06;
    LUT_X[359] = 3.18006508; LUT_Y[359] = 2.2030743e-06;
    LUT_X[360] = 3.1889232; LUT_Y[360] = 1.75721795e-06;
    LUT_X[361] = 3.19778132; LUT_Y[361] = 1.40120872e-06;
    LUT_X[362] = 3.20663944; LUT_Y[362] = 1.11710154e-06;
    LUT_X[363] = 3.21549756; LUT_Y[363] = 8.90490323e-07;
    LUT_X[364] = 3.22435568; LUT_Y[364] = 7.09822578e-07;
    LUT_X[365] = 3.2332138; LUT_Y[365] = 5.65843383e-07;
    LUT_X[366] = 3.24207192; LUT_Y[366] = 4.51145091e-07;
    LUT_X[367] = 3.25093004; LUT_Y[367] = 3.5980345e-07;
    LUT_X[368] = 3.25978816; LUT_Y[368] = 2.87084029e-07;
    LUT_X[369] = 3.26864628; LUT_Y[369] = 2.29205771e-07;
    LUT_X[370] = 3.2775044; LUT_Y[370] = 1.83150815e-07;
    LUT_X[371] = 3.28636252; LUT_Y[371] = 1.46511743e-07;
    LUT_X[372] = 3.29522064; LUT_Y[372] = 1.17369028e-07;
    LUT_X[373] = 3.30407876; LUT_Y[373] = 9.41928213e-08;
    LUT_X[374] = 3.31293688; LUT_Y[374] = 7.57643203e-08;
    LUT_X[375] = 3.321795; LUT_Y[375] = 6.11128626e-08;
    LUT_X[376] = 3.33065312; LUT_Y[376] = 4.94656488e-08;
    LUT_X[377] = 3.33951124; LUT_Y[377] = 4.02075805e-08;
    LUT_X[378] = 3.34836936; LUT_Y[378] = 3.28492009e-08;
    LUT_X[379] = 3.35722748; LUT_Y[379] = 2.70011175e-08;
    LUT_X[380] = 3.3660856; LUT_Y[380] = 2.23536058e-08;
    LUT_X[381] = 3.37494372; LUT_Y[381] = 1.86603552e-08;
    LUT_X[382] = 3.38380184; LUT_Y[382] = 1.57255137e-08;
    LUT_X[383] = 3.39265996; LUT_Y[383] = 1.33933746e-08;
    LUT_X[384] = 3.40151808; LUT_Y[384] = 1.15401628e-08;
    LUT_X[385] = 3.4103762; LUT_Y[385] = 1.00674969e-08;
    LUT_X[386] = 3.41923432; LUT_Y[386] = 8.89718737e-09;
    LUT_X[387] = 3.42809244; LUT_Y[387] = 7.96709815e-09;
    LUT_X[388] = 3.43695056; LUT_Y[388] = 7.2278541e-09;
    LUT_X[389] = 3.44580868; LUT_Y[389] = 6.64022279e-09;
    LUT_X[390] = 3.4546668; LUT_Y[390] = 6.17303364e-09;
    LUT_X[391] = 3.46352492; LUT_Y[391] = 5.80152172e-09;
    LUT_X[392] = 3.47238304; LUT_Y[392] = 5.5060127e-09;
    LUT_X[393] = 3.48124116; LUT_Y[393] = 5.27087736e-09;
    LUT_X[394] = 3.49009928; LUT_Y[394] = 5.0837e-09;
    LUT_X[395] = 3.4989574; LUT_Y[395] = 4.93461829e-09;
    LUT_X[396] = 3.50781552; LUT_Y[396] = 4.81579789e-09;
    LUT_X[397] = 3.51667364; LUT_Y[397] = 4.72101642e-09;
    LUT_X[398] = 3.52553176; LUT_Y[398] = 4.64533082e-09;
    LUT_X[399] = 3.53438988; LUT_Y[399] = 4.58481538e-09;
    LUT_X[400] = 3.543248; LUT_Y[400] = 4.53635193e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[400]) ? LUT_X[400] : xin);
      lo = 0;
      hi = 400;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 76;
  localparam int NDEPTH  = 78;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.362465158;
  localparam real K_FALL = 0.7339637232;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.543248;
  localparam real DOMAIN_EPS = 0.07086496; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
