`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.456e+11 .. 3.289e+11 rad/s
// rise/fall asymmetry 1.7851 (rise x1.3361, fall x0.7485), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.642e-11 s, as a 0/72 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv2_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 227.552; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 2.275518977e-13;
  localparam real DC_BIAS = 1.740106397;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.455886479e+11;
    WX[1] = 0.1084847334; WP[1] = 1.461306334e+11;
    WX[2] = 0.2169694669; WP[2] = 1.468904816e+11;
    WX[3] = 0.3254542003; WP[3] = 1.479498711e+11;
    WX[4] = 0.4339389337; WP[4] = 1.494783119e+11;
    WX[5] = 0.5424236672; WP[5] = 1.51562364e+11;
    WX[6] = 0.6509084006; WP[6] = 1.540745364e+11;
    WX[7] = 0.7593931341; WP[7] = 1.568926497e+11;
    WX[8] = 0.8678778675; WP[8] = 1.600197189e+11;
    WX[9] = 0.9763626009; WP[9] = 1.635154272e+11;
    WX[10] = 1.084847334; WP[10] = 1.674771845e+11;
    WX[11] = 1.193332068; WP[11] = 1.720589243e+11;
    WX[12] = 1.301816801; WP[12] = 1.775068361e+11;
    WX[13] = 1.410301535; WP[13] = 1.842308369e+11;
    WX[14] = 1.518786268; WP[14] = 1.931204015e+11;
    WX[15] = 1.627271002; WP[15] = 2.089996154e+11;
    WX[16] = 1.735755735; WP[16] = 2.422173848e+11;
    WX[17] = 1.844240468; WP[17] = 3.289192036e+11;
    WX[18] = 1.952725202; WP[18] = 3.143370439e+11;
    WX[19] = 2.061209935; WP[19] = 3.043493259e+11;
    WX[20] = 2.169694669; WP[20] = 2.964694646e+11;
    WX[21] = 2.278179402; WP[21] = 2.899103173e+11;
    WX[22] = 2.386664136; WP[22] = 2.841614511e+11;
    WX[23] = 2.495148869; WP[23] = 2.792448359e+11;
    WX[24] = 2.603633602; WP[24] = 2.748155213e+11;
    WX[25] = 2.712118336; WP[25] = 2.710373234e+11;
    WX[26] = 2.820603069; WP[26] = 2.678770694e+11;
    WX[27] = 2.929087803; WP[27] = 2.654780918e+11;
    WX[28] = 3.037572536; WP[28] = 2.6369705e+11;
    WX[29] = 3.14605727; WP[29] = 2.622407585e+11;
    WX[30] = 3.254542003; WP[30] = 2.61119943e+11;
    WX[31] = 3.363026737; WP[31] = 2.60462883e+11;
    WX[32] = 3.47151147; WP[32] = 2.598891384e+11;
  end

  real LUT_X[0:399];
  real LUT_Y[0:399];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999948;
    LUT_X[1] = 0.00870053; LUT_Y[1] = 3.29999936;
    LUT_X[2] = 0.01740106; LUT_Y[2] = 3.2999992;
    LUT_X[3] = 0.02610159; LUT_Y[3] = 3.29999901;
    LUT_X[4] = 0.03480212; LUT_Y[4] = 3.29999877;
    LUT_X[5] = 0.04350265; LUT_Y[5] = 3.29999847;
    LUT_X[6] = 0.05220318; LUT_Y[6] = 3.29999811;
    LUT_X[7] = 0.06090371; LUT_Y[7] = 3.29999765;
    LUT_X[8] = 0.06960424; LUT_Y[8] = 3.29999709;
    LUT_X[9] = 0.07830477; LUT_Y[9] = 3.29999639;
    LUT_X[10] = 0.0870053; LUT_Y[10] = 3.29999553;
    LUT_X[11] = 0.09570583; LUT_Y[11] = 3.29999447;
    LUT_X[12] = 0.10440636; LUT_Y[12] = 3.29999316;
    LUT_X[13] = 0.11310689; LUT_Y[13] = 3.29999155;
    LUT_X[14] = 0.12180742; LUT_Y[14] = 3.29998956;
    LUT_X[15] = 0.13050795; LUT_Y[15] = 3.29998711;
    LUT_X[16] = 0.13920848; LUT_Y[16] = 3.2999841;
    LUT_X[17] = 0.14790901; LUT_Y[17] = 3.2999804;
    LUT_X[18] = 0.15660954; LUT_Y[18] = 3.29997587;
    LUT_X[19] = 0.16531007; LUT_Y[19] = 3.29997031;
    LUT_X[20] = 0.1740106; LUT_Y[20] = 3.29996353;
    LUT_X[21] = 0.18271113; LUT_Y[21] = 3.29995524;
    LUT_X[22] = 0.19141166; LUT_Y[22] = 3.29994514;
    LUT_X[23] = 0.20011219; LUT_Y[23] = 3.29993285;
    LUT_X[24] = 0.20881272; LUT_Y[24] = 3.29991791;
    LUT_X[25] = 0.21751325; LUT_Y[25] = 3.2998998;
    LUT_X[26] = 0.22621378; LUT_Y[26] = 3.29987788;
    LUT_X[27] = 0.23491431; LUT_Y[27] = 3.2998514;
    LUT_X[28] = 0.24361484; LUT_Y[28] = 3.29981947;
    LUT_X[29] = 0.25231537; LUT_Y[29] = 3.29978105;
    LUT_X[30] = 0.2610159; LUT_Y[30] = 3.29973491;
    LUT_X[31] = 0.26971643; LUT_Y[31] = 3.29967962;
    LUT_X[32] = 0.27841696; LUT_Y[32] = 3.29961353;
    LUT_X[33] = 0.28711749; LUT_Y[33] = 3.2995347;
    LUT_X[34] = 0.29581802; LUT_Y[34] = 3.29944094;
    LUT_X[35] = 0.30451855; LUT_Y[35] = 3.29932973;
    LUT_X[36] = 0.31321908; LUT_Y[36] = 3.29919822;
    LUT_X[37] = 0.32191961; LUT_Y[37] = 3.29904324;
    LUT_X[38] = 0.33062014; LUT_Y[38] = 3.29886131;
    LUT_X[39] = 0.33932067; LUT_Y[39] = 3.29864859;
    LUT_X[40] = 0.3480212; LUT_Y[40] = 3.29840103;
    LUT_X[41] = 0.35672173; LUT_Y[41] = 3.29811433;
    LUT_X[42] = 0.36542226; LUT_Y[42] = 3.29778405;
    LUT_X[43] = 0.37412279; LUT_Y[43] = 3.29740572;
    LUT_X[44] = 0.38282332; LUT_Y[44] = 3.29697492;
    LUT_X[45] = 0.39152385; LUT_Y[45] = 3.29648742;
    LUT_X[46] = 0.40022438; LUT_Y[46] = 3.29593927;
    LUT_X[47] = 0.40892491; LUT_Y[47] = 3.29532691;
    LUT_X[48] = 0.41762544; LUT_Y[48] = 3.2946473;
    LUT_X[49] = 0.42632597; LUT_Y[49] = 3.29389797;
    LUT_X[50] = 0.4350265; LUT_Y[50] = 3.29307706;
    LUT_X[51] = 0.44372703; LUT_Y[51] = 3.29218338;
    LUT_X[52] = 0.45242756; LUT_Y[52] = 3.2912164;
    LUT_X[53] = 0.46112809; LUT_Y[53] = 3.29017622;
    LUT_X[54] = 0.46982862; LUT_Y[54] = 3.2890635;
    LUT_X[55] = 0.47852915; LUT_Y[55] = 3.28787946;
    LUT_X[56] = 0.48722968; LUT_Y[56] = 3.28662572;
    LUT_X[57] = 0.49593021; LUT_Y[57] = 3.28530429;
    LUT_X[58] = 0.50463074; LUT_Y[58] = 3.28391745;
    LUT_X[59] = 0.51333127; LUT_Y[59] = 3.28246767;
    LUT_X[60] = 0.5220318; LUT_Y[60] = 3.28095755;
    LUT_X[61] = 0.53073233; LUT_Y[61] = 3.27938971;
    LUT_X[62] = 0.53943286; LUT_Y[62] = 3.27776678;
    LUT_X[63] = 0.54813339; LUT_Y[63] = 3.27609133;
    LUT_X[64] = 0.55683392; LUT_Y[64] = 3.27436581;
    LUT_X[65] = 0.56553445; LUT_Y[65] = 3.27259256;
    LUT_X[66] = 0.57423498; LUT_Y[66] = 3.27077374;
    LUT_X[67] = 0.58293551; LUT_Y[67] = 3.26891137;
    LUT_X[68] = 0.59163604; LUT_Y[68] = 3.26700726;
    LUT_X[69] = 0.60033657; LUT_Y[69] = 3.26506307;
    LUT_X[70] = 0.6090371; LUT_Y[70] = 3.26308026;
    LUT_X[71] = 0.61773763; LUT_Y[71] = 3.26106014;
    LUT_X[72] = 0.62643816; LUT_Y[72] = 3.25900383;
    LUT_X[73] = 0.63513869; LUT_Y[73] = 3.2569123;
    LUT_X[74] = 0.64383922; LUT_Y[74] = 3.25478638;
    LUT_X[75] = 0.65253975; LUT_Y[75] = 3.25262677;
    LUT_X[76] = 0.66124028; LUT_Y[76] = 3.25043403;
    LUT_X[77] = 0.66994081; LUT_Y[77] = 3.2482086;
    LUT_X[78] = 0.67864134; LUT_Y[78] = 3.24595084;
    LUT_X[79] = 0.68734187; LUT_Y[79] = 3.243661;
    LUT_X[80] = 0.6960424; LUT_Y[80] = 3.24133924;
    LUT_X[81] = 0.70474293; LUT_Y[81] = 3.23898566;
    LUT_X[82] = 0.71344346; LUT_Y[82] = 3.23660028;
    LUT_X[83] = 0.72214399; LUT_Y[83] = 3.23418305;
    LUT_X[84] = 0.73084452; LUT_Y[84] = 3.23173388;
    LUT_X[85] = 0.73954505; LUT_Y[85] = 3.22925262;
    LUT_X[86] = 0.74824558; LUT_Y[86] = 3.22673908;
    LUT_X[87] = 0.75694611; LUT_Y[87] = 3.22419302;
    LUT_X[88] = 0.76564664; LUT_Y[88] = 3.22161416;
    LUT_X[89] = 0.77434717; LUT_Y[89] = 3.21900222;
    LUT_X[90] = 0.7830477; LUT_Y[90] = 3.21635683;
    LUT_X[91] = 0.79174823; LUT_Y[91] = 3.21367765;
    LUT_X[92] = 0.80044876; LUT_Y[92] = 3.21096426;
    LUT_X[93] = 0.80914929; LUT_Y[93] = 3.20821626;
    LUT_X[94] = 0.81784982; LUT_Y[94] = 3.20543318;
    LUT_X[95] = 0.82655035; LUT_Y[95] = 3.20261457;
    LUT_X[96] = 0.83525088; LUT_Y[96] = 3.19975993;
    LUT_X[97] = 0.84395141; LUT_Y[97] = 3.19686873;
    LUT_X[98] = 0.85265194; LUT_Y[98] = 3.19394044;
    LUT_X[99] = 0.86135247; LUT_Y[99] = 3.1909745;
    LUT_X[100] = 0.870053; LUT_Y[100] = 3.18797031;
    LUT_X[101] = 0.87875353; LUT_Y[101] = 3.18492726;
    LUT_X[102] = 0.88745406; LUT_Y[102] = 3.18184473;
    LUT_X[103] = 0.89615459; LUT_Y[103] = 3.17872204;
    LUT_X[104] = 0.90485512; LUT_Y[104] = 3.17555852;
    LUT_X[105] = 0.91355565; LUT_Y[105] = 3.17235345;
    LUT_X[106] = 0.92225618; LUT_Y[106] = 3.16910609;
    LUT_X[107] = 0.93095671; LUT_Y[107] = 3.16581568;
    LUT_X[108] = 0.93965724; LUT_Y[108] = 3.16248142;
    LUT_X[109] = 0.94835777; LUT_Y[109] = 3.15910247;
    LUT_X[110] = 0.9570583; LUT_Y[110] = 3.15567798;
    LUT_X[111] = 0.96575883; LUT_Y[111] = 3.15220706;
    LUT_X[112] = 0.97445936; LUT_Y[112] = 3.14868878;
    LUT_X[113] = 0.98315989; LUT_Y[113] = 3.14512217;
    LUT_X[114] = 0.99186042; LUT_Y[114] = 3.14150622;
    LUT_X[115] = 1.00056095; LUT_Y[115] = 3.13783989;
    LUT_X[116] = 1.00926148; LUT_Y[116] = 3.13412209;
    LUT_X[117] = 1.01796201; LUT_Y[117] = 3.13035169;
    LUT_X[118] = 1.02666254; LUT_Y[118] = 3.1265275;
    LUT_X[119] = 1.03536307; LUT_Y[119] = 3.1226483;
    LUT_X[120] = 1.0440636; LUT_Y[120] = 3.1187128;
    LUT_X[121] = 1.05276413; LUT_Y[121] = 3.11471967;
    LUT_X[122] = 1.06146466; LUT_Y[122] = 3.11066751;
    LUT_X[123] = 1.07016519; LUT_Y[123] = 3.10655487;
    LUT_X[124] = 1.07886572; LUT_Y[124] = 3.10238021;
    LUT_X[125] = 1.08756625; LUT_Y[125] = 3.09814196;
    LUT_X[126] = 1.09626678; LUT_Y[126] = 3.09383845;
    LUT_X[127] = 1.10496731; LUT_Y[127] = 3.08946794;
    LUT_X[128] = 1.11366784; LUT_Y[128] = 3.08502861;
    LUT_X[129] = 1.12236837; LUT_Y[129] = 3.08051856;
    LUT_X[130] = 1.1310689; LUT_Y[130] = 3.07593579;
    LUT_X[131] = 1.13976943; LUT_Y[131] = 3.07127821;
    LUT_X[132] = 1.14846996; LUT_Y[132] = 3.06654362;
    LUT_X[133] = 1.15717049; LUT_Y[133] = 3.06172972;
    LUT_X[134] = 1.16587102; LUT_Y[134] = 3.05683408;
    LUT_X[135] = 1.17457155; LUT_Y[135] = 3.05185417;
    LUT_X[136] = 1.18327208; LUT_Y[136] = 3.0467873;
    LUT_X[137] = 1.19197261; LUT_Y[137] = 3.04163065;
    LUT_X[138] = 1.20067314; LUT_Y[138] = 3.03638126;
    LUT_X[139] = 1.20937367; LUT_Y[139] = 3.03103599;
    LUT_X[140] = 1.2180742; LUT_Y[140] = 3.02559152;
    LUT_X[141] = 1.22677473; LUT_Y[141] = 3.02004438;
    LUT_X[142] = 1.23547526; LUT_Y[142] = 3.01439085;
    LUT_X[143] = 1.24417579; LUT_Y[143] = 3.00862703;
    LUT_X[144] = 1.25287632; LUT_Y[144] = 3.00274877;
    LUT_X[145] = 1.26157685; LUT_Y[145] = 2.99675165;
    LUT_X[146] = 1.27027738; LUT_Y[146] = 2.99063101;
    LUT_X[147] = 1.27897791; LUT_Y[147] = 2.98438186;
    LUT_X[148] = 1.28767844; LUT_Y[148] = 2.9779989;
    LUT_X[149] = 1.29637897; LUT_Y[149] = 2.97147647;
    LUT_X[150] = 1.3050795; LUT_Y[150] = 2.96480854;
    LUT_X[151] = 1.31378003; LUT_Y[151] = 2.95798862;
    LUT_X[152] = 1.32248056; LUT_Y[152] = 2.9510098;
    LUT_X[153] = 1.33118109; LUT_Y[153] = 2.94386463;
    LUT_X[154] = 1.33988162; LUT_Y[154] = 2.9365451;
    LUT_X[155] = 1.34858215; LUT_Y[155] = 2.92904258;
    LUT_X[156] = 1.35728268; LUT_Y[156] = 2.92134775;
    LUT_X[157] = 1.36598321; LUT_Y[157] = 2.91345053;
    LUT_X[158] = 1.37468374; LUT_Y[158] = 2.90533997;
    LUT_X[159] = 1.38338427; LUT_Y[159] = 2.89700416;
    LUT_X[160] = 1.3920848; LUT_Y[160] = 2.88843012;
    LUT_X[161] = 1.40078533; LUT_Y[161] = 2.87960364;
    LUT_X[162] = 1.40948586; LUT_Y[162] = 2.87050914;
    LUT_X[163] = 1.41818639; LUT_Y[163] = 2.86112948;
    LUT_X[164] = 1.42688692; LUT_Y[164] = 2.85144569;
    LUT_X[165] = 1.43558745; LUT_Y[165] = 2.84143677;
    LUT_X[166] = 1.44428798; LUT_Y[166] = 2.83107933;
    LUT_X[167] = 1.45298851; LUT_Y[167] = 2.82034719;
    LUT_X[168] = 1.46168904; LUT_Y[168] = 2.80921094;
    LUT_X[169] = 1.47038957; LUT_Y[169] = 2.79763732;
    LUT_X[170] = 1.4790901; LUT_Y[170] = 2.78558857;
    LUT_X[171] = 1.48779063; LUT_Y[171] = 2.77302143;
    LUT_X[172] = 1.49649116; LUT_Y[172] = 2.7598861;
    LUT_X[173] = 1.50519169; LUT_Y[173] = 2.74612475;
    LUT_X[174] = 1.51389222; LUT_Y[174] = 2.7316696;
    LUT_X[175] = 1.52259275; LUT_Y[175] = 2.71644051;
    LUT_X[176] = 1.53129328; LUT_Y[176] = 2.70034164;
    LUT_X[177] = 1.53999381; LUT_Y[177] = 2.68325698;
    LUT_X[178] = 1.54869434; LUT_Y[178] = 2.66504426;
    LUT_X[179] = 1.55739487; LUT_Y[179] = 2.6455263;
    LUT_X[180] = 1.5660954; LUT_Y[180] = 2.62447895;
    LUT_X[181] = 1.57479593; LUT_Y[181] = 2.6016139;
    LUT_X[182] = 1.58349646; LUT_Y[182] = 2.57655465;
    LUT_X[183] = 1.59219699; LUT_Y[183] = 2.54880536;
    LUT_X[184] = 1.60089752; LUT_Y[184] = 2.51771904;
    LUT_X[185] = 1.60959805; LUT_Y[185] = 2.48249629;
    LUT_X[186] = 1.61829858; LUT_Y[186] = 2.44229796;
    LUT_X[187] = 1.62699911; LUT_Y[187] = 2.39656498;
    LUT_X[188] = 1.63569964; LUT_Y[188] = 2.34537154;
    LUT_X[189] = 1.64440017; LUT_Y[189] = 2.28934691;
    LUT_X[190] = 1.6531007; LUT_Y[190] = 2.22925495;
    LUT_X[191] = 1.66180123; LUT_Y[191] = 2.16575802;
    LUT_X[192] = 1.67050176; LUT_Y[192] = 2.09941283;
    LUT_X[193] = 1.67920229; LUT_Y[193] = 2.03071849;
    LUT_X[194] = 1.68790282; LUT_Y[194] = 1.96014774;
    LUT_X[195] = 1.69660335; LUT_Y[195] = 1.88816058;
    LUT_X[196] = 1.70530388; LUT_Y[196] = 1.81520898;
    LUT_X[197] = 1.71400441; LUT_Y[197] = 1.74173848;
    LUT_X[198] = 1.72270494; LUT_Y[198] = 1.6681888;
    LUT_X[199] = 1.73140547; LUT_Y[199] = 1.5949943;
    LUT_X[200] = 1.740106; LUT_Y[200] = 1.52258398;
    LUT_X[201] = 1.74880653; LUT_Y[201] = 1.45138041;
    LUT_X[202] = 1.75750706; LUT_Y[202] = 1.3817971;
    LUT_X[203] = 1.76620759; LUT_Y[203] = 1.31423354;
    LUT_X[204] = 1.77490812; LUT_Y[204] = 1.24906762;
    LUT_X[205] = 1.78360865; LUT_Y[205] = 1.18664559;
    LUT_X[206] = 1.79230918; LUT_Y[206] = 1.12727002;
    LUT_X[207] = 1.80100971; LUT_Y[207] = 1.07118746;
    LUT_X[208] = 1.80971024; LUT_Y[208] = 1.01857755;
    LUT_X[209] = 1.81841077; LUT_Y[209] = 0.969546165;
    LUT_X[210] = 1.8271113; LUT_Y[210] = 0.924124686;
    LUT_X[211] = 1.83581183; LUT_Y[211] = 0.882275152;
    LUT_X[212] = 1.84451236; LUT_Y[212] = 0.843896644;
    LUT_X[213] = 1.85321289; LUT_Y[213] = 0.808823865;
    LUT_X[214] = 1.86191342; LUT_Y[214] = 0.776817985;
    LUT_X[215] = 1.87061395; LUT_Y[215] = 0.747570688;
    LUT_X[216] = 1.87931448; LUT_Y[216] = 0.720737597;
    LUT_X[217] = 1.88801501; LUT_Y[217] = 0.695983106;
    LUT_X[218] = 1.89671554; LUT_Y[218] = 0.673010068;
    LUT_X[219] = 1.90541607; LUT_Y[219] = 0.651568887;
    LUT_X[220] = 1.9141166; LUT_Y[220] = 0.631454469;
    LUT_X[221] = 1.92281713; LUT_Y[221] = 0.612499034;
    LUT_X[222] = 1.93151766; LUT_Y[222] = 0.594564761;
    LUT_X[223] = 1.94021819; LUT_Y[223] = 0.577537538;
    LUT_X[224] = 1.94891872; LUT_Y[224] = 0.561322011;
    LUT_X[225] = 1.95761925; LUT_Y[225] = 0.545837752;
    LUT_X[226] = 1.96631978; LUT_Y[226] = 0.531016313;
    LUT_X[227] = 1.97502031; LUT_Y[227] = 0.516798951;
    LUT_X[228] = 1.98372084; LUT_Y[228] = 0.50313486;
    LUT_X[229] = 1.99242137; LUT_Y[229] = 0.489979786;
    LUT_X[230] = 2.0011219; LUT_Y[230] = 0.477294931;
    LUT_X[231] = 2.00982243; LUT_Y[231] = 0.465046076;
    LUT_X[232] = 2.01852296; LUT_Y[232] = 0.453202875;
    LUT_X[233] = 2.02722349; LUT_Y[233] = 0.441738284;
    LUT_X[234] = 2.03592402; LUT_Y[234] = 0.430628087;
    LUT_X[235] = 2.04462455; LUT_Y[235] = 0.41985051;
    LUT_X[236] = 2.05332508; LUT_Y[236] = 0.409385898;
    LUT_X[237] = 2.06202561; LUT_Y[237] = 0.399216444;
    LUT_X[238] = 2.07072614; LUT_Y[238] = 0.389325959;
    LUT_X[239] = 2.07942667; LUT_Y[239] = 0.379699682;
    LUT_X[240] = 2.0881272; LUT_Y[240] = 0.370324114;
    LUT_X[241] = 2.09682773; LUT_Y[241] = 0.361186875;
    LUT_X[242] = 2.10552826; LUT_Y[242] = 0.352276583;
    LUT_X[243] = 2.11422879; LUT_Y[243] = 0.343582751;
    LUT_X[244] = 2.12292932; LUT_Y[244] = 0.335095693;
    LUT_X[245] = 2.13162985; LUT_Y[245] = 0.326806443;
    LUT_X[246] = 2.14033038; LUT_Y[246] = 0.318706691;
    LUT_X[247] = 2.14903091; LUT_Y[247] = 0.310788712;
    LUT_X[248] = 2.15773144; LUT_Y[248] = 0.303045322;
    LUT_X[249] = 2.16643197; LUT_Y[249] = 0.295469821;
    LUT_X[250] = 2.1751325; LUT_Y[250] = 0.288055958;
    LUT_X[251] = 2.18383303; LUT_Y[251] = 0.280797885;
    LUT_X[252] = 2.19253356; LUT_Y[252] = 0.273690131;
    LUT_X[253] = 2.20123409; LUT_Y[253] = 0.266727566;
    LUT_X[254] = 2.20993462; LUT_Y[254] = 0.259905377;
    LUT_X[255] = 2.21863515; LUT_Y[255] = 0.253219041;
    LUT_X[256] = 2.22733568; LUT_Y[256] = 0.246664304;
    LUT_X[257] = 2.23603621; LUT_Y[257] = 0.240237164;
    LUT_X[258] = 2.24473674; LUT_Y[258] = 0.233933846;
    LUT_X[259] = 2.25343727; LUT_Y[259] = 0.227750793;
    LUT_X[260] = 2.2621378; LUT_Y[260] = 0.221684647;
    LUT_X[261] = 2.27083833; LUT_Y[261] = 0.215732237;
    LUT_X[262] = 2.27953886; LUT_Y[262] = 0.209890567;
    LUT_X[263] = 2.28823939; LUT_Y[263] = 0.204156807;
    LUT_X[264] = 2.29693992; LUT_Y[264] = 0.198528282;
    LUT_X[265] = 2.30564045; LUT_Y[265] = 0.193002466;
    LUT_X[266] = 2.31434098; LUT_Y[266] = 0.187576978;
    LUT_X[267] = 2.32304151; LUT_Y[267] = 0.182249578;
    LUT_X[268] = 2.33174204; LUT_Y[268] = 0.177018173;
    LUT_X[269] = 2.34044257; LUT_Y[269] = 0.171880829;
    LUT_X[270] = 2.3491431; LUT_Y[270] = 0.166835801;
    LUT_X[271] = 2.35784363; LUT_Y[271] = 0.161881597;
    LUT_X[272] = 2.36654416; LUT_Y[272] = 0.157017097;
    LUT_X[273] = 2.37524469; LUT_Y[273] = 0.152241735;
    LUT_X[274] = 2.38394522; LUT_Y[274] = 0.147555547;
    LUT_X[275] = 2.39264575; LUT_Y[275] = 0.142958441;
    LUT_X[276] = 2.40134628; LUT_Y[276] = 0.138448711;
    LUT_X[277] = 2.41004681; LUT_Y[277] = 0.134023046;
    LUT_X[278] = 2.41874734; LUT_Y[278] = 0.129678114;
    LUT_X[279] = 2.42744787; LUT_Y[279] = 0.125411339;
    LUT_X[280] = 2.4361484; LUT_Y[280] = 0.121220804;
    LUT_X[281] = 2.44484893; LUT_Y[281] = 0.117104992;
    LUT_X[282] = 2.45354946; LUT_Y[282] = 0.113062636;
    LUT_X[283] = 2.46224999; LUT_Y[283] = 0.109092628;
    LUT_X[284] = 2.47095052; LUT_Y[284] = 0.105193976;
    LUT_X[285] = 2.47965105; LUT_Y[285] = 0.101365781;
    LUT_X[286] = 2.48835158; LUT_Y[286] = 0.0976072218;
    LUT_X[287] = 2.49705211; LUT_Y[287] = 0.0939175517;
    LUT_X[288] = 2.50575264; LUT_Y[288] = 0.090296093;
    LUT_X[289] = 2.51445317; LUT_Y[289] = 0.0867422363;
    LUT_X[290] = 2.5231537; LUT_Y[290] = 0.0832554407;
    LUT_X[291] = 2.53185423; LUT_Y[291] = 0.0798352349;
    LUT_X[292] = 2.54055476; LUT_Y[292] = 0.0764812198;
    LUT_X[293] = 2.54925529; LUT_Y[293] = 0.0731930709;
    LUT_X[294] = 2.55795582; LUT_Y[294] = 0.0699705422;
    LUT_X[295] = 2.56665635; LUT_Y[295] = 0.0668134701;
    LUT_X[296] = 2.57535688; LUT_Y[296] = 0.0637217781;
    LUT_X[297] = 2.58405741; LUT_Y[297] = 0.0606954817;
    LUT_X[298] = 2.59275794; LUT_Y[298] = 0.057734694;
    LUT_X[299] = 2.60145847; LUT_Y[299] = 0.0548396316;
    LUT_X[300] = 2.610159; LUT_Y[300] = 0.0520106196;
    LUT_X[301] = 2.61885953; LUT_Y[301] = 0.0492480983;
    LUT_X[302] = 2.62756006; LUT_Y[302] = 0.0465526277;
    LUT_X[303] = 2.63626059; LUT_Y[303] = 0.0439248928;
    LUT_X[304] = 2.64496112; LUT_Y[304] = 0.0413657074;
    LUT_X[305] = 2.65366165; LUT_Y[305] = 0.0388760163;
    LUT_X[306] = 2.66236218; LUT_Y[306] = 0.0364568961;
    LUT_X[307] = 2.67106271; LUT_Y[307] = 0.0341095532;
    LUT_X[308] = 2.67976324; LUT_Y[308] = 0.031835319;
    LUT_X[309] = 2.68846377; LUT_Y[309] = 0.0296356408;
    LUT_X[310] = 2.6971643; LUT_Y[310] = 0.0275120686;
    LUT_X[311] = 2.70586483; LUT_Y[311] = 0.0254662366;
    LUT_X[312] = 2.71456536; LUT_Y[312] = 0.0234998379;
    LUT_X[313] = 2.72326589; LUT_Y[313] = 0.0216145934;
    LUT_X[314] = 2.73196642; LUT_Y[314] = 0.0198122131;
    LUT_X[315] = 2.74066695; LUT_Y[315] = 0.0180943495;
    LUT_X[316] = 2.74936748; LUT_Y[316] = 0.0164625447;
    LUT_X[317] = 2.75806801; LUT_Y[317] = 0.0149181698;
    LUT_X[318] = 2.76676854; LUT_Y[318] = 0.0134623595;
    LUT_X[319] = 2.77546907; LUT_Y[319] = 0.0120959426;
    LUT_X[320] = 2.7841696; LUT_Y[320] = 0.0108193718;
    LUT_X[321] = 2.79287013; LUT_Y[321] = 0.00963265484;
    LUT_X[322] = 2.80157066; LUT_Y[322] = 0.00853529219;
    LUT_X[323] = 2.81027119; LUT_Y[323] = 0.00752622448;
    LUT_X[324] = 2.81897172; LUT_Y[324] = 0.00660379432;
    LUT_X[325] = 2.82767225; LUT_Y[325] = 0.00576572658;
    LUT_X[326] = 2.83637278; LUT_Y[326] = 0.00500913041;
    LUT_X[327] = 2.84507331; LUT_Y[327] = 0.00433052507;
    LUT_X[328] = 2.85377384; LUT_Y[328] = 0.00372589045;
    LUT_X[329] = 2.86247437; LUT_Y[329] = 0.00319074061;
    LUT_X[330] = 2.8711749; LUT_Y[330] = 0.00272021766;
    LUT_X[331] = 2.87987543; LUT_Y[331] = 0.00230920051;
    LUT_X[332] = 2.88857596; LUT_Y[332] = 0.00195242254;
    LUT_X[333] = 2.89727649; LUT_Y[333] = 0.00164459076;
    LUT_X[334] = 2.90597702; LUT_Y[334] = 0.00138049936;
    LUT_X[335] = 2.91467755; LUT_Y[335] = 0.00115513118;
    LUT_X[336] = 2.92337808; LUT_Y[336] = 0.000963741953;
    LUT_X[337] = 2.93207861; LUT_Y[337] = 0.000801924217;
    LUT_X[338] = 2.94077914; LUT_Y[338] = 0.000665649644;
    LUT_X[339] = 2.94947967; LUT_Y[339] = 0.000551290665;
    LUT_X[340] = 2.9581802; LUT_Y[340] = 0.000455623701;
    LUT_X[341] = 2.96688073; LUT_Y[341] = 0.000375817441;
    LUT_X[342] = 2.97558126; LUT_Y[342] = 0.000309410033;
    LUT_X[343] = 2.98428179; LUT_Y[343] = 0.000254279015;
    LUT_X[344] = 2.99298232; LUT_Y[344] = 0.000208607404;
    LUT_X[345] = 3.00168285; LUT_Y[345] = 0.000170848654;
    LUT_X[346] = 3.01038338; LUT_Y[346] = 0.000139692531;
    LUT_X[347] = 3.01908391; LUT_Y[347] = 0.000114033175;
    LUT_X[348] = 3.02778444; LUT_Y[348] = 9.29401216e-05;
    LUT_X[349] = 3.03648497; LUT_Y[349] = 7.56325491e-05;
    LUT_X[350] = 3.0451855; LUT_Y[350] = 6.14567542e-05;
    LUT_X[351] = 3.05388603; LUT_Y[351] = 4.98666641e-05;
    LUT_X[352] = 3.06258656; LUT_Y[352] = 4.04070966e-05;
    LUT_X[353] = 3.07128709; LUT_Y[353] = 3.26994511e-05;
    LUT_X[354] = 3.07998762; LUT_Y[354] = 2.64295151e-05;
    LUT_X[355] = 3.08868815; LUT_Y[355] = 2.13370975e-05;
    LUT_X[356] = 3.09738868; LUT_Y[356] = 1.72072301e-05;
    LUT_X[357] = 3.10608921; LUT_Y[357] = 1.38627129e-05;
    LUT_X[358] = 3.11478974; LUT_Y[358] = 1.11578102e-05;
    LUT_X[359] = 3.12349027; LUT_Y[359] = 8.9729321e-06;
    LUT_X[360] = 3.1321908; LUT_Y[360] = 7.2101571e-06;
    LUT_X[361] = 3.14089133; LUT_Y[361] = 5.78947468e-06;
    LUT_X[362] = 3.14959186; LUT_Y[362] = 4.64564043e-06;
    LUT_X[363] = 3.15829239; LUT_Y[363] = 3.72555217e-06;
    LUT_X[364] = 3.16699292; LUT_Y[364] = 2.98606778e-06;
    LUT_X[365] = 3.17569345; LUT_Y[365] = 2.39219585e-06;
    LUT_X[366] = 3.18439398; LUT_Y[366] = 1.91560004e-06;
    LUT_X[367] = 3.19309451; LUT_Y[367] = 1.5333666e-06;
    LUT_X[368] = 3.20179504; LUT_Y[368] = 1.22699128e-06;
    LUT_X[369] = 3.21049557; LUT_Y[369] = 9.81549126e-07;
    LUT_X[370] = 3.2191961; LUT_Y[370] = 7.85015595e-07;
    LUT_X[371] = 3.22789663; LUT_Y[371] = 6.27712835e-07;
    LUT_X[372] = 3.23659716; LUT_Y[372] = 5.01858957e-07;
    LUT_X[373] = 3.24529769; LUT_Y[373] = 4.01201898e-07;
    LUT_X[374] = 3.25399822; LUT_Y[374] = 3.2072253e-07;
    LUT_X[375] = 3.26269875; LUT_Y[375] = 2.56394317e-07;
    LUT_X[376] = 3.27139928; LUT_Y[376] = 2.04989044e-07;
    LUT_X[377] = 3.28009981; LUT_Y[377] = 1.63919999e-07;
    LUT_X[378] = 3.28880034; LUT_Y[378] = 1.31115557e-07;
    LUT_X[379] = 3.29750087; LUT_Y[379] = 1.0491737e-07;
    LUT_X[380] = 3.3062014; LUT_Y[380] = 8.39984691e-08;
    LUT_X[381] = 3.31490193; LUT_Y[381] = 6.72974383e-08;
    LUT_X[382] = 3.32360246; LUT_Y[382] = 5.39655568e-08;
    LUT_X[383] = 3.33230299; LUT_Y[383] = 4.33243785e-08;
    LUT_X[384] = 3.34100352; LUT_Y[384] = 3.48317159e-08;
    LUT_X[385] = 3.34970405; LUT_Y[385] = 2.80543768e-08;
    LUT_X[386] = 3.35840458; LUT_Y[386] = 2.26463283e-08;
    LUT_X[387] = 3.36710511; LUT_Y[387] = 1.83312121e-08;
    LUT_X[388] = 3.37580564; LUT_Y[388] = 1.48883534e-08;
    LUT_X[389] = 3.38450617; LUT_Y[389] = 1.21415683e-08;
    LUT_X[390] = 3.3932067; LUT_Y[390] = 9.95021255e-09;
    LUT_X[391] = 3.40190723; LUT_Y[391] = 8.202027e-09;
    LUT_X[392] = 3.41060776; LUT_Y[392] = 6.80741741e-09;
    LUT_X[393] = 3.41930829; LUT_Y[393] = 5.69488673e-09;
    LUT_X[394] = 3.42800882; LUT_Y[394] = 4.80738263e-09;
    LUT_X[395] = 3.43670935; LUT_Y[395] = 4.09938519e-09;
    LUT_X[396] = 3.44540988; LUT_Y[396] = 3.53457549e-09;
    LUT_X[397] = 3.45411041; LUT_Y[397] = 3.08397991e-09;
    LUT_X[398] = 3.46281094; LUT_Y[398] = 2.72448467e-09;
    LUT_X[399] = 3.47151147; LUT_Y[399] = 2.43765124e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[399]) ? LUT_X[399] : xin);
      lo = 0;
      hi = 399;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 72;
  localparam int NDEPTH  = 74;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.336073371;
  localparam real K_FALL = 0.7484618896;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.47151147;
  localparam real DOMAIN_EPS = 0.0694302294; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
