`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.442e+11 .. 3.325e+11 rad/s
// rise/fall asymmetry 1.8037 (rise x1.3430, fall x0.7446), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.681e-11 s, as a 0/75 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv2_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 223.94; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 2.239397325e-13;
  localparam real DC_BIAS = 1.722517125;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.44158442e+11;
    WX[1] = 0.1073882316; WP[1] = 1.447599453e+11;
    WX[2] = 0.2147764631; WP[2] = 1.455852421e+11;
    WX[3] = 0.3221646947; WP[3] = 1.466732773e+11;
    WX[4] = 0.4295529263; WP[4] = 1.482076646e+11;
    WX[5] = 0.5369411578; WP[5] = 1.502509253e+11;
    WX[6] = 0.6443293894; WP[6] = 1.527111837e+11;
    WX[7] = 0.7517176209; WP[7] = 1.554751137e+11;
    WX[8] = 0.8591058525; WP[8] = 1.585397824e+11;
    WX[9] = 0.9664940841; WP[9] = 1.619615565e+11;
    WX[10] = 1.073882316; WP[10] = 1.658175235e+11;
    WX[11] = 1.181270547; WP[11] = 1.702631926e+11;
    WX[12] = 1.288658779; WP[12] = 1.755401589e+11;
    WX[13] = 1.39604701; WP[13] = 1.820074505e+11;
    WX[14] = 1.503435242; WP[14] = 1.904319946e+11;
    WX[15] = 1.610823473; WP[15] = 2.041473248e+11;
    WX[16] = 1.718211705; WP[16] = 2.364223903e+11;
    WX[17] = 1.825599937; WP[17] = 3.324926646e+11;
    WX[18] = 1.932988168; WP[18] = 3.16450373e+11;
    WX[19] = 2.0403764; WP[19] = 3.060450972e+11;
    WX[20] = 2.147764631; WP[20] = 2.979488437e+11;
    WX[21] = 2.255152863; WP[21] = 2.911813366e+11;
    WX[22] = 2.362541094; WP[22] = 2.853544176e+11;
    WX[23] = 2.469929326; WP[23] = 2.803008259e+11;
    WX[24] = 2.577317558; WP[24] = 2.758180363e+11;
    WX[25] = 2.684705789; WP[25] = 2.719125427e+11;
    WX[26] = 2.792094021; WP[26] = 2.686421729e+11;
    WX[27] = 2.899482252; WP[27] = 2.660426216e+11;
    WX[28] = 3.006870484; WP[28] = 2.641478683e+11;
    WX[29] = 3.114258715; WP[29] = 2.626084111e+11;
    WX[30] = 3.221646947; WP[30] = 2.613478358e+11;
    WX[31] = 3.329035178; WP[31] = 2.606597043e+11;
    WX[32] = 3.43642341; WP[32] = 2.600241187e+11;
  end

  real LUT_X[0:399];
  real LUT_Y[0:399];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999948;
    LUT_X[1] = 0.00861259; LUT_Y[1] = 3.29999936;
    LUT_X[2] = 0.01722518; LUT_Y[2] = 3.29999921;
    LUT_X[3] = 0.02583777; LUT_Y[3] = 3.29999902;
    LUT_X[4] = 0.03445036; LUT_Y[4] = 3.29999878;
    LUT_X[5] = 0.04306295; LUT_Y[5] = 3.29999849;
    LUT_X[6] = 0.05167554; LUT_Y[6] = 3.29999813;
    LUT_X[7] = 0.06028813; LUT_Y[7] = 3.29999769;
    LUT_X[8] = 0.06890072; LUT_Y[8] = 3.29999714;
    LUT_X[9] = 0.07751331; LUT_Y[9] = 3.29999646;
    LUT_X[10] = 0.0861259; LUT_Y[10] = 3.29999563;
    LUT_X[11] = 0.09473849; LUT_Y[11] = 3.2999946;
    LUT_X[12] = 0.10335108; LUT_Y[12] = 3.29999334;
    LUT_X[13] = 0.11196367; LUT_Y[13] = 3.29999178;
    LUT_X[14] = 0.12057626; LUT_Y[14] = 3.29998986;
    LUT_X[15] = 0.12918885; LUT_Y[15] = 3.29998751;
    LUT_X[16] = 0.13780144; LUT_Y[16] = 3.29998463;
    LUT_X[17] = 0.14641403; LUT_Y[17] = 3.29998109;
    LUT_X[18] = 0.15502662; LUT_Y[18] = 3.29997676;
    LUT_X[19] = 0.16363921; LUT_Y[19] = 3.29997147;
    LUT_X[20] = 0.1722518; LUT_Y[20] = 3.29996501;
    LUT_X[21] = 0.18086439; LUT_Y[21] = 3.29995714;
    LUT_X[22] = 0.18947698; LUT_Y[22] = 3.29994756;
    LUT_X[23] = 0.19808957; LUT_Y[23] = 3.29993592;
    LUT_X[24] = 0.20670216; LUT_Y[24] = 3.29992181;
    LUT_X[25] = 0.21531475; LUT_Y[25] = 3.29990471;
    LUT_X[26] = 0.22392734; LUT_Y[26] = 3.29988405;
    LUT_X[27] = 0.23253993; LUT_Y[27] = 3.29985913;
    LUT_X[28] = 0.24115252; LUT_Y[28] = 3.29982912;
    LUT_X[29] = 0.24976511; LUT_Y[29] = 3.29979305;
    LUT_X[30] = 0.2583777; LUT_Y[30] = 3.2997498;
    LUT_X[31] = 0.26699029; LUT_Y[31] = 3.29969803;
    LUT_X[32] = 0.27560288; LUT_Y[32] = 3.2996362;
    LUT_X[33] = 0.28421547; LUT_Y[33] = 3.29956254;
    LUT_X[34] = 0.29282806; LUT_Y[34] = 3.299475;
    LUT_X[35] = 0.30144065; LUT_Y[35] = 3.29937124;
    LUT_X[36] = 0.31005324; LUT_Y[36] = 3.29924861;
    LUT_X[37] = 0.31866583; LUT_Y[37] = 3.29910416;
    LUT_X[38] = 0.32727842; LUT_Y[38] = 3.29893461;
    LUT_X[39] = 0.33589101; LUT_Y[39] = 3.29873637;
    LUT_X[40] = 0.3445036; LUT_Y[40] = 3.29850559;
    LUT_X[41] = 0.35311619; LUT_Y[41] = 3.29823817;
    LUT_X[42] = 0.36172878; LUT_Y[42] = 3.29792986;
    LUT_X[43] = 0.37034137; LUT_Y[43] = 3.29757634;
    LUT_X[44] = 0.37895396; LUT_Y[44] = 3.29717326;
    LUT_X[45] = 0.38756655; LUT_Y[45] = 3.29671644;
    LUT_X[46] = 0.39617914; LUT_Y[46] = 3.29620191;
    LUT_X[47] = 0.40479173; LUT_Y[47] = 3.29562602;
    LUT_X[48] = 0.41340432; LUT_Y[48] = 3.29498559;
    LUT_X[49] = 0.42201691; LUT_Y[49] = 3.29427793;
    LUT_X[50] = 0.4306295; LUT_Y[50] = 3.29350096;
    LUT_X[51] = 0.43924209; LUT_Y[51] = 3.29265319;
    LUT_X[52] = 0.44785468; LUT_Y[52] = 3.29173378;
    LUT_X[53] = 0.45646727; LUT_Y[53] = 3.29074252;
    LUT_X[54] = 0.46507986; LUT_Y[54] = 3.28967975;
    LUT_X[55] = 0.47369245; LUT_Y[55] = 3.28854639;
    LUT_X[56] = 0.48230504; LUT_Y[56] = 3.2873438;
    LUT_X[57] = 0.49091763; LUT_Y[57] = 3.28607373;
    LUT_X[58] = 0.49953022; LUT_Y[58] = 3.28473825;
    LUT_X[59] = 0.50814281; LUT_Y[59] = 3.28333966;
    LUT_X[60] = 0.5167554; LUT_Y[60] = 3.28188041;
    LUT_X[61] = 0.52536799; LUT_Y[61] = 3.28036304;
    LUT_X[62] = 0.53398058; LUT_Y[62] = 3.27879011;
    LUT_X[63] = 0.54259317; LUT_Y[63] = 3.27716415;
    LUT_X[64] = 0.55120576; LUT_Y[64] = 3.2754876;
    LUT_X[65] = 0.55981835; LUT_Y[65] = 3.27376282;
    LUT_X[66] = 0.56843094; LUT_Y[66] = 3.27199201;
    LUT_X[67] = 0.57704353; LUT_Y[67] = 3.27017723;
    LUT_X[68] = 0.58565612; LUT_Y[68] = 3.26832037;
    LUT_X[69] = 0.59426871; LUT_Y[69] = 3.26642313;
    LUT_X[70] = 0.6028813; LUT_Y[70] = 3.26448707;
    LUT_X[71] = 0.61149389; LUT_Y[71] = 3.26251357;
    LUT_X[72] = 0.62010648; LUT_Y[72] = 3.26050382;
    LUT_X[73] = 0.62871907; LUT_Y[73] = 3.25845889;
    LUT_X[74] = 0.63733166; LUT_Y[74] = 3.25637967;
    LUT_X[75] = 0.64594425; LUT_Y[75] = 3.25426695;
    LUT_X[76] = 0.65455684; LUT_Y[76] = 3.25212135;
    LUT_X[77] = 0.66316943; LUT_Y[77] = 3.24994339;
    LUT_X[78] = 0.67178202; LUT_Y[78] = 3.2477335;
    LUT_X[79] = 0.68039461; LUT_Y[79] = 3.24549198;
    LUT_X[80] = 0.6890072; LUT_Y[80] = 3.24321907;
    LUT_X[81] = 0.69761979; LUT_Y[81] = 3.24091491;
    LUT_X[82] = 0.70623238; LUT_Y[82] = 3.23857957;
    LUT_X[83] = 0.71484497; LUT_Y[83] = 3.23621306;
    LUT_X[84] = 0.72345756; LUT_Y[84] = 3.23381534;
    LUT_X[85] = 0.73207015; LUT_Y[85] = 3.2313863;
    LUT_X[86] = 0.74068274; LUT_Y[86] = 3.22892579;
    LUT_X[87] = 0.74929533; LUT_Y[87] = 3.22643362;
    LUT_X[88] = 0.75790792; LUT_Y[88] = 3.22390955;
    LUT_X[89] = 0.76652051; LUT_Y[89] = 3.22135332;
    LUT_X[90] = 0.7751331; LUT_Y[90] = 3.21876463;
    LUT_X[91] = 0.78374569; LUT_Y[91] = 3.21614315;
    LUT_X[92] = 0.79235828; LUT_Y[92] = 3.21348851;
    LUT_X[93] = 0.80097087; LUT_Y[93] = 3.21080034;
    LUT_X[94] = 0.80958346; LUT_Y[94] = 3.20807821;
    LUT_X[95] = 0.81819605; LUT_Y[95] = 3.2053217;
    LUT_X[96] = 0.82680864; LUT_Y[96] = 3.20253035;
    LUT_X[97] = 0.83542123; LUT_Y[97] = 3.19970367;
    LUT_X[98] = 0.84403382; LUT_Y[98] = 3.19684117;
    LUT_X[99] = 0.85264641; LUT_Y[99] = 3.19394232;
    LUT_X[100] = 0.861259; LUT_Y[100] = 3.19100656;
    LUT_X[101] = 0.86987159; LUT_Y[101] = 3.18803334;
    LUT_X[102] = 0.87848418; LUT_Y[102] = 3.18502206;
    LUT_X[103] = 0.88709677; LUT_Y[103] = 3.1819721;
    LUT_X[104] = 0.89570936; LUT_Y[104] = 3.17888282;
    LUT_X[105] = 0.90432195; LUT_Y[105] = 3.17575357;
    LUT_X[106] = 0.91293454; LUT_Y[106] = 3.17258365;
    LUT_X[107] = 0.92154713; LUT_Y[107] = 3.16937234;
    LUT_X[108] = 0.93015972; LUT_Y[108] = 3.1661189;
    LUT_X[109] = 0.93877231; LUT_Y[109] = 3.16282257;
    LUT_X[110] = 0.9473849; LUT_Y[110] = 3.15948254;
    LUT_X[111] = 0.95599749; LUT_Y[111] = 3.15609798;
    LUT_X[112] = 0.96461008; LUT_Y[112] = 3.15266803;
    LUT_X[113] = 0.97322267; LUT_Y[113] = 3.14919179;
    LUT_X[114] = 0.98183526; LUT_Y[114] = 3.14566833;
    LUT_X[115] = 0.99044785; LUT_Y[115] = 3.14209668;
    LUT_X[116] = 0.99906044; LUT_Y[116] = 3.13847583;
    LUT_X[117] = 1.00767303; LUT_Y[117] = 3.13480474;
    LUT_X[118] = 1.01628562; LUT_Y[118] = 3.1310823;
    LUT_X[119] = 1.02489821; LUT_Y[119] = 3.12730739;
    LUT_X[120] = 1.0335108; LUT_Y[120] = 3.12347882;
    LUT_X[121] = 1.04212339; LUT_Y[121] = 3.11959536;
    LUT_X[122] = 1.05073598; LUT_Y[122] = 3.11565572;
    LUT_X[123] = 1.05934857; LUT_Y[123] = 3.11165857;
    LUT_X[124] = 1.06796116; LUT_Y[124] = 3.10760249;
    LUT_X[125] = 1.07657375; LUT_Y[125] = 3.10348604;
    LUT_X[126] = 1.08518634; LUT_Y[126] = 3.09930769;
    LUT_X[127] = 1.09379893; LUT_Y[127] = 3.09506584;
    LUT_X[128] = 1.10241152; LUT_Y[128] = 3.09075884;
    LUT_X[129] = 1.11102411; LUT_Y[129] = 3.08638493;
    LUT_X[130] = 1.1196367; LUT_Y[130] = 3.0819423;
    LUT_X[131] = 1.12824929; LUT_Y[131] = 3.07742903;
    LUT_X[132] = 1.13686188; LUT_Y[132] = 3.07284314;
    LUT_X[133] = 1.14547447; LUT_Y[133] = 3.06818251;
    LUT_X[134] = 1.15408706; LUT_Y[134] = 3.06344496;
    LUT_X[135] = 1.16269965; LUT_Y[135] = 3.05862818;
    LUT_X[136] = 1.17131224; LUT_Y[136] = 3.05372973;
    LUT_X[137] = 1.17992483; LUT_Y[137] = 3.04874708;
    LUT_X[138] = 1.18853742; LUT_Y[138] = 3.04367754;
    LUT_X[139] = 1.19715001; LUT_Y[139] = 3.03851828;
    LUT_X[140] = 1.2057626; LUT_Y[140] = 3.03326634;
    LUT_X[141] = 1.21437519; LUT_Y[141] = 3.02791856;
    LUT_X[142] = 1.22298778; LUT_Y[142] = 3.02247166;
    LUT_X[143] = 1.23160037; LUT_Y[143] = 3.01692211;
    LUT_X[144] = 1.24021296; LUT_Y[144] = 3.01126622;
    LUT_X[145] = 1.24882555; LUT_Y[145] = 3.00550007;
    LUT_X[146] = 1.25743814; LUT_Y[146] = 2.9996195;
    LUT_X[147] = 1.26605073; LUT_Y[147] = 2.9936201;
    LUT_X[148] = 1.27466332; LUT_Y[148] = 2.98749719;
    LUT_X[149] = 1.28327591; LUT_Y[149] = 2.98124579;
    LUT_X[150] = 1.2918885; LUT_Y[150] = 2.97486057;
    LUT_X[151] = 1.30050109; LUT_Y[151] = 2.96833587;
    LUT_X[152] = 1.30911368; LUT_Y[152] = 2.96166565;
    LUT_X[153] = 1.31772627; LUT_Y[153] = 2.95484341;
    LUT_X[154] = 1.32633886; LUT_Y[154] = 2.94786222;
    LUT_X[155] = 1.33495145; LUT_Y[155] = 2.94071462;
    LUT_X[156] = 1.34356404; LUT_Y[156] = 2.93339258;
    LUT_X[157] = 1.35217663; LUT_Y[157] = 2.92588746;
    LUT_X[158] = 1.36078922; LUT_Y[158] = 2.91818991;
    LUT_X[159] = 1.36940181; LUT_Y[159] = 2.91028982;
    LUT_X[160] = 1.3780144; LUT_Y[160] = 2.90217622;
    LUT_X[161] = 1.38662699; LUT_Y[161] = 2.89383716;
    LUT_X[162] = 1.39523958; LUT_Y[162] = 2.88525963;
    LUT_X[163] = 1.40385217; LUT_Y[163] = 2.87642936;
    LUT_X[164] = 1.41246476; LUT_Y[164] = 2.86733074;
    LUT_X[165] = 1.42107735; LUT_Y[165] = 2.85794653;
    LUT_X[166] = 1.42968994; LUT_Y[166] = 2.84825772;
    LUT_X[167] = 1.43830253; LUT_Y[167] = 2.83824322;
    LUT_X[168] = 1.44691512; LUT_Y[168] = 2.82787951;
    LUT_X[169] = 1.45552771; LUT_Y[169] = 2.8171403;
    LUT_X[170] = 1.4641403; LUT_Y[170] = 2.80599601;
    LUT_X[171] = 1.47275289; LUT_Y[171] = 2.79441323;
    LUT_X[172] = 1.48136548; LUT_Y[172] = 2.78235393;
    LUT_X[173] = 1.48997807; LUT_Y[173] = 2.7697746;
    LUT_X[174] = 1.49859066; LUT_Y[174] = 2.75662507;
    LUT_X[175] = 1.50720325; LUT_Y[175] = 2.74284707;
    LUT_X[176] = 1.51581584; LUT_Y[176] = 2.72837228;
    LUT_X[177] = 1.52442843; LUT_Y[177] = 2.71311983;
    LUT_X[178] = 1.53304102; LUT_Y[178] = 2.69699295;
    LUT_X[179] = 1.54165361; LUT_Y[179] = 2.67987446;
    LUT_X[180] = 1.5502662; LUT_Y[180] = 2.66162047;
    LUT_X[181] = 1.55887879; LUT_Y[181] = 2.64205171;
    LUT_X[182] = 1.56749138; LUT_Y[182] = 2.62094124;
    LUT_X[183] = 1.57610397; LUT_Y[183] = 2.59799709;
    LUT_X[184] = 1.58471656; LUT_Y[184] = 2.57283831;
    LUT_X[185] = 1.59332915; LUT_Y[185] = 2.54496441;
    LUT_X[186] = 1.60194174; LUT_Y[186] = 2.51372656;
    LUT_X[187] = 1.61055433; LUT_Y[187] = 2.47833469;
    LUT_X[188] = 1.61916692; LUT_Y[188] = 2.4379857;
    LUT_X[189] = 1.62777951; LUT_Y[189] = 2.3921885;
    LUT_X[190] = 1.6363921; LUT_Y[190] = 2.34107857;
    LUT_X[191] = 1.64500469; LUT_Y[191] = 2.28529437;
    LUT_X[192] = 1.65361728; LUT_Y[192] = 2.22557389;
    LUT_X[193] = 1.66222987; LUT_Y[193] = 2.1625518;
    LUT_X[194] = 1.67084246; LUT_Y[194] = 2.09676385;
    LUT_X[195] = 1.67945505; LUT_Y[195] = 2.02869251;
    LUT_X[196] = 1.68806764; LUT_Y[196] = 1.95879575;
    LUT_X[197] = 1.69668023; LUT_Y[197] = 1.88751952;
    LUT_X[198] = 1.70529282; LUT_Y[198] = 1.81530214;
    LUT_X[199] = 1.71390541; LUT_Y[199] = 1.74257574;
    LUT_X[200] = 1.722518; LUT_Y[200] = 1.6697669;
    LUT_X[201] = 1.73113059; LUT_Y[201] = 1.59729702;
    LUT_X[202] = 1.73974318; LUT_Y[202] = 1.52558235;
    LUT_X[203] = 1.74835577; LUT_Y[203] = 1.45503307;
    LUT_X[204] = 1.75696836; LUT_Y[204] = 1.38605079;
    LUT_X[205] = 1.76558095; LUT_Y[205] = 1.31902395;
    LUT_X[206] = 1.77419354; LUT_Y[206] = 1.25432083;
    LUT_X[207] = 1.78280613; LUT_Y[207] = 1.19228007;
    LUT_X[208] = 1.79141872; LUT_Y[208] = 1.13319937;
    LUT_X[209] = 1.80003131; LUT_Y[209] = 1.07732371;
    LUT_X[210] = 1.8086439; LUT_Y[210] = 1.0248347;
    LUT_X[211] = 1.81725649; LUT_Y[211] = 0.975843632;
    LUT_X[212] = 1.82586908; LUT_Y[212] = 0.930389959;
    LUT_X[213] = 1.83448167; LUT_Y[213] = 0.888445675;
    LUT_X[214] = 1.84309426; LUT_Y[214] = 0.849921723;
    LUT_X[215] = 1.85170685; LUT_Y[215] = 0.814668193;
    LUT_X[216] = 1.86031944; LUT_Y[216] = 0.78246582;
    LUT_X[217] = 1.86893203; LUT_Y[217] = 0.753025882;
    LUT_X[218] = 1.87754462; LUT_Y[218] = 0.726017404;
    LUT_X[219] = 1.88615721; LUT_Y[219] = 0.701110124;
    LUT_X[220] = 1.8947698; LUT_Y[220] = 0.678006719;
    LUT_X[221] = 1.90338239; LUT_Y[221] = 0.656455002;
    LUT_X[222] = 1.91199498; LUT_Y[222] = 0.636246734;
    LUT_X[223] = 1.92060757; LUT_Y[223] = 0.61721122;
    LUT_X[224] = 1.92922016; LUT_Y[224] = 0.599208171;
    LUT_X[225] = 1.93783275; LUT_Y[225] = 0.582121464;
    LUT_X[226] = 1.94644534; LUT_Y[226] = 0.565854126;
    LUT_X[227] = 1.95505793; LUT_Y[227] = 0.550324428;
    LUT_X[228] = 1.96367052; LUT_Y[228] = 0.535462871;
    LUT_X[229] = 1.97228311; LUT_Y[229] = 0.52120986;
    LUT_X[230] = 1.9808957; LUT_Y[230] = 0.507513895;
    LUT_X[231] = 1.98950829; LUT_Y[231] = 0.494330147;
    LUT_X[232] = 1.99812088; LUT_Y[232] = 0.481619345;
    LUT_X[233] = 2.00673347; LUT_Y[233] = 0.469346871;
    LUT_X[234] = 2.01534606; LUT_Y[234] = 0.457482047;
    LUT_X[235] = 2.02395865; LUT_Y[235] = 0.445997546;
    LUT_X[236] = 2.03257124; LUT_Y[236] = 0.434868912;
    LUT_X[237] = 2.04118383; LUT_Y[237] = 0.424074165;
    LUT_X[238] = 2.04979642; LUT_Y[238] = 0.413593472;
    LUT_X[239] = 2.05840901; LUT_Y[239] = 0.40340887;
    LUT_X[240] = 2.0670216; LUT_Y[240] = 0.393504039;
    LUT_X[241] = 2.07563419; LUT_Y[241] = 0.383864098;
    LUT_X[242] = 2.08424678; LUT_Y[242] = 0.374475446;
    LUT_X[243] = 2.09285937; LUT_Y[243] = 0.365325609;
    LUT_X[244] = 2.10147196; LUT_Y[244] = 0.356403126;
    LUT_X[245] = 2.11008455; LUT_Y[245] = 0.347697437;
    LUT_X[246] = 2.11869714; LUT_Y[246] = 0.339198789;
    LUT_X[247] = 2.12730973; LUT_Y[247] = 0.330898159;
    LUT_X[248] = 2.13592232; LUT_Y[248] = 0.322787183;
    LUT_X[249] = 2.14453491; LUT_Y[249] = 0.314858089;
    LUT_X[250] = 2.1531475; LUT_Y[250] = 0.307103647;
    LUT_X[251] = 2.16176009; LUT_Y[251] = 0.299517118;
    LUT_X[252] = 2.17037268; LUT_Y[252] = 0.292092213;
    LUT_X[253] = 2.17898527; LUT_Y[253] = 0.284823051;
    LUT_X[254] = 2.18759786; LUT_Y[254] = 0.277704128;
    LUT_X[255] = 2.19621045; LUT_Y[255] = 0.270730286;
    LUT_X[256] = 2.20482304; LUT_Y[256] = 0.263896683;
    LUT_X[257] = 2.21343563; LUT_Y[257] = 0.25719877;
    LUT_X[258] = 2.22204822; LUT_Y[258] = 0.25063227;
    LUT_X[259] = 2.23066081; LUT_Y[259] = 0.244193155;
    LUT_X[260] = 2.2392734; LUT_Y[260] = 0.237877631;
    LUT_X[261] = 2.24788599; LUT_Y[261] = 0.231682117;
    LUT_X[262] = 2.25649858; LUT_Y[262] = 0.225603236;
    LUT_X[263] = 2.26511117; LUT_Y[263] = 0.219637797;
    LUT_X[264] = 2.27372376; LUT_Y[264] = 0.213782784;
    LUT_X[265] = 2.28233635; LUT_Y[265] = 0.208035347;
    LUT_X[266] = 2.29094894; LUT_Y[266] = 0.20239279;
    LUT_X[267] = 2.29956153; LUT_Y[267] = 0.196852565;
    LUT_X[268] = 2.30817412; LUT_Y[268] = 0.191412265;
    LUT_X[269] = 2.31678671; LUT_Y[269] = 0.186069622;
    LUT_X[270] = 2.3253993; LUT_Y[270] = 0.180822502;
    LUT_X[271] = 2.33401189; LUT_Y[271] = 0.175668916;
    LUT_X[272] = 2.34262448; LUT_Y[272] = 0.170607033;
    LUT_X[273] = 2.35123707; LUT_Y[273] = 0.165635216;
    LUT_X[274] = 2.35984966; LUT_Y[274] = 0.160752092;
    LUT_X[275] = 2.36846225; LUT_Y[275] = 0.155956684;
    LUT_X[276] = 2.37707484; LUT_Y[276] = 0.151248585;
    LUT_X[277] = 2.38568743; LUT_Y[277] = 0.146627905;
    LUT_X[278] = 2.39430002; LUT_Y[278] = 0.142094347;
    LUT_X[279] = 2.40291261; LUT_Y[279] = 0.137645872;
    LUT_X[280] = 2.4115252; LUT_Y[280] = 0.133279145;
    LUT_X[281] = 2.42013779; LUT_Y[281] = 0.12899104;
    LUT_X[282] = 2.42875038; LUT_Y[282] = 0.124779185;
    LUT_X[283] = 2.43736297; LUT_Y[283] = 0.120641791;
    LUT_X[284] = 2.44597556; LUT_Y[284] = 0.116577433;
    LUT_X[285] = 2.45458815; LUT_Y[285] = 0.112584905;
    LUT_X[286] = 2.46320074; LUT_Y[286] = 0.108663148;
    LUT_X[287] = 2.47181333; LUT_Y[287] = 0.104811211;
    LUT_X[288] = 2.48042592; LUT_Y[288] = 0.10102823;
    LUT_X[289] = 2.48903851; LUT_Y[289] = 0.0973134171;
    LUT_X[290] = 2.4976511; LUT_Y[290] = 0.0936660526;
    LUT_X[291] = 2.50626369; LUT_Y[291] = 0.0900854842;
    LUT_X[292] = 2.51487628; LUT_Y[292] = 0.086571125;
    LUT_X[293] = 2.52348887; LUT_Y[293] = 0.083122454;
    LUT_X[294] = 2.53210146; LUT_Y[294] = 0.079739017;
    LUT_X[295] = 2.54071405; LUT_Y[295] = 0.0764204292;
    LUT_X[296] = 2.54932664; LUT_Y[296] = 0.0731663776;
    LUT_X[297] = 2.55793923; LUT_Y[297] = 0.0699766247;
    LUT_X[298] = 2.56655182; LUT_Y[298] = 0.0668510119;
    LUT_X[299] = 2.57516441; LUT_Y[299] = 0.0637894644;
    LUT_X[300] = 2.583777; LUT_Y[300] = 0.0607919957;
    LUT_X[301] = 2.59238959; LUT_Y[301] = 0.057858713;
    LUT_X[302] = 2.60100218; LUT_Y[302] = 0.0549898223;
    LUT_X[303] = 2.60961477; LUT_Y[303] = 0.052185634;
    LUT_X[304] = 2.61822736; LUT_Y[304] = 0.0494465684;
    LUT_X[305] = 2.62683995; LUT_Y[305] = 0.0467731608;
    LUT_X[306] = 2.63545254; LUT_Y[306] = 0.0441660661;
    LUT_X[307] = 2.64406513; LUT_Y[307] = 0.0416260625;
    LUT_X[308] = 2.65267772; LUT_Y[308] = 0.0391540539;
    LUT_X[309] = 2.66129031; LUT_Y[309] = 0.0367510709;
    LUT_X[310] = 2.6699029; LUT_Y[310] = 0.0344182691;
    LUT_X[311] = 2.67851549; LUT_Y[311] = 0.0321569246;
    LUT_X[312] = 2.68712808; LUT_Y[312] = 0.0299684264;
    LUT_X[313] = 2.69574067; LUT_Y[313] = 0.0278542644;
    LUT_X[314] = 2.70435326; LUT_Y[314] = 0.0258160122;
    LUT_X[315] = 2.71296585; LUT_Y[315] = 0.0238553045;
    LUT_X[316] = 2.72157844; LUT_Y[316] = 0.0219738084;
    LUT_X[317] = 2.73019103; LUT_Y[317] = 0.0201731878;
    LUT_X[318] = 2.73880362; LUT_Y[318] = 0.0184550608;
    LUT_X[319] = 2.74741621; LUT_Y[319] = 0.0168209503;
    LUT_X[320] = 2.7560288; LUT_Y[320] = 0.0152722281;
    LUT_X[321] = 2.76464139; LUT_Y[321] = 0.0138100535;
    LUT_X[322] = 2.77325398; LUT_Y[322] = 0.0124353078;
    LUT_X[323] = 2.78186657; LUT_Y[323] = 0.0111485277;
    LUT_X[324] = 2.79047916; LUT_Y[324] = 0.00994983896;
    LUT_X[325] = 2.79909175; LUT_Y[325] = 0.00883889554;
    LUT_X[326] = 2.80770434; LUT_Y[326] = 0.00781482631;
    LUT_X[327] = 2.81631693; LUT_Y[327] = 0.00687619471;
    LUT_X[328] = 2.82492952; LUT_Y[328] = 0.00602097455;
    LUT_X[329] = 2.83354211; LUT_Y[329] = 0.00524654536;
    LUT_X[330] = 2.8421547; LUT_Y[330] = 0.00454970988;
    LUT_X[331] = 2.85076729; LUT_Y[331] = 0.00392673449;
    LUT_X[332] = 2.85937988; LUT_Y[332] = 0.00337341226;
    LUT_X[333] = 2.86799247; LUT_Y[333] = 0.00288514596;
    LUT_X[334] = 2.87660506; LUT_Y[334] = 0.00245704717;
    LUT_X[335] = 2.88521765; LUT_Y[335] = 0.00208404586;
    LUT_X[336] = 2.89383024; LUT_Y[336] = 0.00176100393;
    LUT_X[337] = 2.90244283; LUT_Y[337] = 0.00148282602;
    LUT_X[338] = 2.91105542; LUT_Y[338] = 0.0012445611;
    LUT_X[339] = 2.91966801; LUT_Y[339] = 0.00104148959;
    LUT_X[340] = 2.9282806; LUT_Y[340] = 0.000869192336;
    LUT_X[341] = 2.93689319; LUT_Y[341] = 0.000723599461;
    LUT_X[342] = 2.94550578; LUT_Y[342] = 0.000601019229;
    LUT_X[343] = 2.95411837; LUT_Y[343] = 0.00049814846;
    LUT_X[344] = 2.96273096; LUT_Y[344] = 0.000412067352;
    LUT_X[345] = 2.97134355; LUT_Y[345] = 0.00034022219;
    LUT_X[346] = 2.97995614; LUT_Y[346] = 0.00028039957;
    LUT_X[347] = 2.98856873; LUT_Y[347] = 0.000230695547;
    LUT_X[348] = 2.99718132; LUT_Y[348] = 0.000189482571;
    LUT_X[349] = 3.00579391; LUT_Y[349] = 0.000155376409;
    LUT_X[350] = 3.0144065; LUT_Y[350] = 0.000127204599;
    LUT_X[351] = 3.02301909; LUT_Y[351] = 0.000103977384;
    LUT_X[352] = 3.03163168; LUT_Y[352] = 8.48615801e-05;
    LUT_X[353] = 3.04024427; LUT_Y[353] = 6.9157519e-05;
    LUT_X[354] = 3.04885686; LUT_Y[354] = 5.62789623e-05;
    LUT_X[355] = 3.05746945; LUT_Y[355] = 4.5735756e-05;
    LUT_X[356] = 3.06608204; LUT_Y[356] = 3.7118946e-05;
    LUT_X[357] = 3.07469463; LUT_Y[357] = 3.00880517e-05;
    LUT_X[358] = 3.08330722; LUT_Y[358] = 2.43602167e-05;
    LUT_X[359] = 3.09191981; LUT_Y[359] = 1.9700974e-05;
    LUT_X[360] = 3.1005324; LUT_Y[360] = 1.59164022e-05;
    LUT_X[361] = 3.10914499; LUT_Y[361] = 1.28464726e-05;
    LUT_X[362] = 3.11775758; LUT_Y[362] = 1.03594183e-05;
    LUT_X[363] = 3.12637017; LUT_Y[363] = 8.34697835e-06;
    LUT_X[364] = 3.13498276; LUT_Y[364] = 6.72039294e-06;
    LUT_X[365] = 3.14359535; LUT_Y[365] = 5.40703776e-06;
    LUT_X[366] = 3.15220794; LUT_Y[366] = 4.34760598e-06;
    LUT_X[367] = 3.16082053; LUT_Y[367] = 3.49375487e-06;
    LUT_X[368] = 3.16943312; LUT_Y[368] = 2.8061467e-06;
    LUT_X[369] = 3.17804571; LUT_Y[369] = 2.25282292e-06;
    LUT_X[370] = 3.1866583; LUT_Y[370] = 1.80785875e-06;
    LUT_X[371] = 3.19527089; LUT_Y[371] = 1.4502532e-06;
    LUT_X[372] = 3.20388348; LUT_Y[372] = 1.16301561e-06;
    LUT_X[373] = 3.21249607; LUT_Y[373] = 9.32415962e-07;
    LUT_X[374] = 3.22110866; LUT_Y[374] = 7.47371076e-07;
    LUT_X[375] = 3.22972125; LUT_Y[375] = 5.98943123e-07;
    LUT_X[376] = 3.23833384; LUT_Y[376] = 4.7993079e-07;
    LUT_X[377] = 3.24694643; LUT_Y[377] = 3.84536612e-07;
    LUT_X[378] = 3.25555902; LUT_Y[378] = 3.08096732e-07;
    LUT_X[379] = 3.26417161; LUT_Y[379] = 2.46861751e-07;
    LUT_X[380] = 3.2727842; LUT_Y[380] = 1.97819238e-07;
    LUT_X[381] = 3.28139679; LUT_Y[381] = 1.58550194e-07;
    LUT_X[382] = 3.29000938; LUT_Y[382] = 1.27113103e-07;
    LUT_X[383] = 3.29862197; LUT_Y[383] = 1.01950374e-07;
    LUT_X[384] = 3.30723456; LUT_Y[384] = 8.18129135e-08;
    LUT_X[385] = 3.31584715; LUT_Y[385] = 6.56993879e-08;
    LUT_X[386] = 3.32445974; LUT_Y[386] = 5.28073348e-08;
    LUT_X[387] = 3.33307233; LUT_Y[387] = 4.2493853e-08;
    LUT_X[388] = 3.34168492; LUT_Y[388] = 3.42440073e-08;
    LUT_X[389] = 3.35029751; LUT_Y[389] = 2.76454544e-08;
    LUT_X[390] = 3.3589101; LUT_Y[390] = 2.2368071e-08;
    LUT_X[391] = 3.36752269; LUT_Y[391] = 1.81476089e-08;
    LUT_X[392] = 3.37613528; LUT_Y[392] = 1.47725849e-08;
    LUT_X[393] = 3.38474787; LUT_Y[393] = 1.20737701e-08;
    LUT_X[394] = 3.39336046; LUT_Y[394] = 9.91576502e-09;
    LUT_X[395] = 3.40197305; LUT_Y[395] = 8.19024976e-09;
    LUT_X[396] = 3.41058564; LUT_Y[396] = 6.81057868e-09;
    LUT_X[397] = 3.41919823; LUT_Y[397] = 5.70744755e-09;
    LUT_X[398] = 3.42781082; LUT_Y[398] = 4.82543022e-09;
    LUT_X[399] = 3.43642341; LUT_Y[399] = 4.12020046e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[399]) ? LUT_X[399] : xin);
      lo = 0;
      hi = 399;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 75;
  localparam int NDEPTH  = 77;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.343033286;
  localparam real K_FALL = 0.7445831835;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.43642341;
  localparam real DOMAIN_EPS = 0.0687284682; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
