`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points. Chosen over the
// node-ODE form because this block's static curve is too steep
// for its inverse to be well-conditioned.
// schedule spanned 1.463e+11 .. 3.274e+11 rad/s
// rise/fall asymmetry 1.7766 (rise x1.3329, fall x0.7503), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.625e-11 s, as a 0/71 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv2_rnm(input real in_val, output real out_val);

  localparam int  NW = 33;
  localparam real TSTEP = 229.142; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 2.291420756e-13;
  localparam real DC_BIAS = 1.744050273;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.462623347e+11;
    WX[1] = 0.109003125; WP[1] = 1.467825485e+11;
    WX[2] = 0.21800625; WP[2] = 1.475244537e+11;
    WX[3] = 0.327009375; WP[3] = 1.485551964e+11;
    WX[4] = 0.4360125; WP[4] = 1.500804588e+11;
    WX[5] = 0.545015625; WP[5] = 1.521799288e+11;
    WX[6] = 0.65401875; WP[6] = 1.547149813e+11;
    WX[7] = 0.763021875; WP[7] = 1.575598977e+11;
    WX[8] = 0.872025; WP[8] = 1.607185671e+11;
    WX[9] = 0.981028125; WP[9] = 1.642532201e+11;
    WX[10] = 1.09003125; WP[10] = 1.682651465e+11;
    WX[11] = 1.199034375; WP[11] = 1.728999537e+11;
    WX[12] = 1.3080375; WP[12] = 1.784450952e+11;
    WX[13] = 1.417040625; WP[13] = 1.852913859e+11;
    WX[14] = 1.52604375; WP[14] = 1.944163479e+11;
    WX[15] = 1.635046875; WP[15] = 2.115460079e+11;
    WX[16] = 1.74405; WP[16] = 2.446451858e+11;
    WX[17] = 1.853053125; WP[17] = 3.27420505e+11;
    WX[18] = 1.96205625; WP[18] = 3.134161571e+11;
    WX[19] = 2.071059375; WP[19] = 3.036010866e+11;
    WX[20] = 2.1800625; WP[20] = 2.958072991e+11;
    WX[21] = 2.289065625; WP[21] = 2.893275287e+11;
    WX[22] = 2.39806875; WP[22] = 2.836297701e+11;
    WX[23] = 2.507071875; WP[23] = 2.787388636e+11;
    WX[24] = 2.616075; WP[24] = 2.743691705e+11;
    WX[25] = 2.725078125; WP[25] = 2.706608763e+11;
    WX[26] = 2.83408125; WP[26] = 2.675463958e+11;
    WX[27] = 2.943084375; WP[27] = 2.652439629e+11;
    WX[28] = 3.0520875; WP[28] = 2.635115807e+11;
    WX[29] = 3.161090625; WP[29] = 2.620135818e+11;
    WX[30] = 3.27009375; WP[30] = 2.610644601e+11;
    WX[31] = 3.379096875; WP[31] = 2.603788461e+11;
    WX[32] = 3.4881; WP[32] = 2.598430279e+11;
  end

  real LUT_X[0:400];
  real LUT_Y[0:400];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999948;
    LUT_X[1] = 0.00872025; LUT_Y[1] = 3.29999936;
    LUT_X[2] = 0.0174405; LUT_Y[2] = 3.2999992;
    LUT_X[3] = 0.02616075; LUT_Y[3] = 3.29999901;
    LUT_X[4] = 0.034881; LUT_Y[4] = 3.29999877;
    LUT_X[5] = 0.04360125; LUT_Y[5] = 3.29999847;
    LUT_X[6] = 0.0523215; LUT_Y[6] = 3.2999981;
    LUT_X[7] = 0.06104175; LUT_Y[7] = 3.29999764;
    LUT_X[8] = 0.069762; LUT_Y[8] = 3.29999708;
    LUT_X[9] = 0.07848225; LUT_Y[9] = 3.29999638;
    LUT_X[10] = 0.0872025; LUT_Y[10] = 3.29999551;
    LUT_X[11] = 0.09592275; LUT_Y[11] = 3.29999444;
    LUT_X[12] = 0.104643; LUT_Y[12] = 3.29999312;
    LUT_X[13] = 0.11336325; LUT_Y[13] = 3.29999149;
    LUT_X[14] = 0.1220835; LUT_Y[14] = 3.29998949;
    LUT_X[15] = 0.13080375; LUT_Y[15] = 3.29998701;
    LUT_X[16] = 0.139524; LUT_Y[16] = 3.29998397;
    LUT_X[17] = 0.14824425; LUT_Y[17] = 3.29998024;
    LUT_X[18] = 0.1569645; LUT_Y[18] = 3.29997566;
    LUT_X[19] = 0.16568475; LUT_Y[19] = 3.29997005;
    LUT_X[20] = 0.174405; LUT_Y[20] = 3.29996319;
    LUT_X[21] = 0.18312525; LUT_Y[21] = 3.2999548;
    LUT_X[22] = 0.1918455; LUT_Y[22] = 3.29994458;
    LUT_X[23] = 0.20056575; LUT_Y[23] = 3.29993214;
    LUT_X[24] = 0.209286; LUT_Y[24] = 3.29991701;
    LUT_X[25] = 0.21800625; LUT_Y[25] = 3.29989867;
    LUT_X[26] = 0.2267265; LUT_Y[26] = 3.29987646;
    LUT_X[27] = 0.23544675; LUT_Y[27] = 3.29984961;
    LUT_X[28] = 0.244167; LUT_Y[28] = 3.29981724;
    LUT_X[29] = 0.25288725; LUT_Y[29] = 3.29977827;
    LUT_X[30] = 0.2616075; LUT_Y[30] = 3.29973146;
    LUT_X[31] = 0.27032775; LUT_Y[31] = 3.29967535;
    LUT_X[32] = 0.279048; LUT_Y[32] = 3.29960827;
    LUT_X[33] = 0.28776825; LUT_Y[33] = 3.29952824;
    LUT_X[34] = 0.2964885; LUT_Y[34] = 3.29943303;
    LUT_X[35] = 0.30520875; LUT_Y[35] = 3.29932008;
    LUT_X[36] = 0.313929; LUT_Y[36] = 3.2991865;
    LUT_X[37] = 0.32264925; LUT_Y[37] = 3.29902907;
    LUT_X[38] = 0.3313695; LUT_Y[38] = 3.29884425;
    LUT_X[39] = 0.34008975; LUT_Y[39] = 3.29862818;
    LUT_X[40] = 0.34881; LUT_Y[40] = 3.29837672;
    LUT_X[41] = 0.35753025; LUT_Y[41] = 3.29808554;
    LUT_X[42] = 0.3662505; LUT_Y[42] = 3.29775017;
    LUT_X[43] = 0.37497075; LUT_Y[43] = 3.29736611;
    LUT_X[44] = 0.383691; LUT_Y[44] = 3.29692892;
    LUT_X[45] = 0.39241125; LUT_Y[45] = 3.29643435;
    LUT_X[46] = 0.4011315; LUT_Y[46] = 3.29587848;
    LUT_X[47] = 0.40985175; LUT_Y[47] = 3.29525776;
    LUT_X[48] = 0.418572; LUT_Y[48] = 3.2945692;
    LUT_X[49] = 0.42729225; LUT_Y[49] = 3.29381036;
    LUT_X[50] = 0.4360125; LUT_Y[50] = 3.29297945;
    LUT_X[51] = 0.44473275; LUT_Y[51] = 3.29207536;
    LUT_X[52] = 0.453453; LUT_Y[52] = 3.29109761;
    LUT_X[53] = 0.46217325; LUT_Y[53] = 3.29004637;
    LUT_X[54] = 0.4708935; LUT_Y[54] = 3.28892239;
    LUT_X[55] = 0.47961375; LUT_Y[55] = 3.28772693;
    LUT_X[56] = 0.488334; LUT_Y[56] = 3.2864617;
    LUT_X[57] = 0.49705425; LUT_Y[57] = 3.28512875;
    LUT_X[58] = 0.5057745; LUT_Y[58] = 3.2837304;
    LUT_X[59] = 0.51449475; LUT_Y[59] = 3.28226917;
    LUT_X[60] = 0.523215; LUT_Y[60] = 3.28074767;
    LUT_X[61] = 0.53193525; LUT_Y[61] = 3.27916855;
    LUT_X[62] = 0.5406555; LUT_Y[62] = 3.27753445;
    LUT_X[63] = 0.54937575; LUT_Y[63] = 3.27584795;
    LUT_X[64] = 0.558096; LUT_Y[64] = 3.27411149;
    LUT_X[65] = 0.56681625; LUT_Y[65] = 3.27232741;
    LUT_X[66] = 0.5755365; LUT_Y[66] = 3.27049787;
    LUT_X[67] = 0.58425675; LUT_Y[67] = 3.26862486;
    LUT_X[68] = 0.592977; LUT_Y[68] = 3.26671019;
    LUT_X[69] = 0.60169725; LUT_Y[69] = 3.26475549;
    LUT_X[70] = 0.6104175; LUT_Y[70] = 3.26276222;
    LUT_X[71] = 0.61913775; LUT_Y[71] = 3.26073165;
    LUT_X[72] = 0.627858; LUT_Y[72] = 3.25866489;
    LUT_X[73] = 0.63657825; LUT_Y[73] = 3.25656291;
    LUT_X[74] = 0.6452985; LUT_Y[74] = 3.2544265;
    LUT_X[75] = 0.65401875; LUT_Y[75] = 3.25225635;
    LUT_X[76] = 0.662739; LUT_Y[76] = 3.250053;
    LUT_X[77] = 0.67145925; LUT_Y[77] = 3.24781689;
    LUT_X[78] = 0.6801795; LUT_Y[78] = 3.24554835;
    LUT_X[79] = 0.68889975; LUT_Y[79] = 3.24324762;
    LUT_X[80] = 0.69762; LUT_Y[80] = 3.24091485;
    LUT_X[81] = 0.70634025; LUT_Y[81] = 3.23855012;
    LUT_X[82] = 0.7150605; LUT_Y[82] = 3.23615344;
    LUT_X[83] = 0.72378075; LUT_Y[83] = 3.23372475;
    LUT_X[84] = 0.732501; LUT_Y[84] = 3.23126396;
    LUT_X[85] = 0.74122125; LUT_Y[85] = 3.22877089;
    LUT_X[86] = 0.7499415; LUT_Y[86] = 3.22624535;
    LUT_X[87] = 0.75866175; LUT_Y[87] = 3.2236871;
    LUT_X[88] = 0.767382; LUT_Y[88] = 3.22109585;
    LUT_X[89] = 0.77610225; LUT_Y[89] = 3.21847129;
    LUT_X[90] = 0.7848225; LUT_Y[90] = 3.21581307;
    LUT_X[91] = 0.79354275; LUT_Y[91] = 3.21312081;
    LUT_X[92] = 0.802263; LUT_Y[92] = 3.21039412;
    LUT_X[93] = 0.81098325; LUT_Y[93] = 3.20763255;
    LUT_X[94] = 0.8197035; LUT_Y[94] = 3.20483566;
    LUT_X[95] = 0.82842375; LUT_Y[95] = 3.20200297;
    LUT_X[96] = 0.837144; LUT_Y[96] = 3.19913397;
    LUT_X[97] = 0.84586425; LUT_Y[97] = 3.19622814;
    LUT_X[98] = 0.8545845; LUT_Y[98] = 3.19328492;
    LUT_X[99] = 0.86330475; LUT_Y[99] = 3.19030375;
    LUT_X[100] = 0.872025; LUT_Y[100] = 3.18728402;
    LUT_X[101] = 0.88074525; LUT_Y[101] = 3.18422512;
    LUT_X[102] = 0.8894655; LUT_Y[102] = 3.1811264;
    LUT_X[103] = 0.89818575; LUT_Y[103] = 3.17798719;
    LUT_X[104] = 0.906906; LUT_Y[104] = 3.17480679;
    LUT_X[105] = 0.91562625; LUT_Y[105] = 3.17158449;
    LUT_X[106] = 0.9243465; LUT_Y[106] = 3.16831952;
    LUT_X[107] = 0.93306675; LUT_Y[107] = 3.16501112;
    LUT_X[108] = 0.941787; LUT_Y[108] = 3.16165846;
    LUT_X[109] = 0.95050725; LUT_Y[109] = 3.15826072;
    LUT_X[110] = 0.9592275; LUT_Y[110] = 3.154817;
    LUT_X[111] = 0.96794775; LUT_Y[111] = 3.15132641;
    LUT_X[112] = 0.976668; LUT_Y[112] = 3.14778801;
    LUT_X[113] = 0.98538825; LUT_Y[113] = 3.1442008;
    LUT_X[114] = 0.9941085; LUT_Y[114] = 3.14056377;
    LUT_X[115] = 1.00282875; LUT_Y[115] = 3.13687584;
    LUT_X[116] = 1.011549; LUT_Y[116] = 3.13313593;
    LUT_X[117] = 1.02026925; LUT_Y[117] = 3.12934286;
    LUT_X[118] = 1.0289895; LUT_Y[118] = 3.12549545;
    LUT_X[119] = 1.03770975; LUT_Y[119] = 3.12159243;
    LUT_X[120] = 1.04643; LUT_Y[120] = 3.1176325;
    LUT_X[121] = 1.05515025; LUT_Y[121] = 3.1136143;
    LUT_X[122] = 1.0638705; LUT_Y[122] = 3.10953641;
    LUT_X[123] = 1.07259075; LUT_Y[123] = 3.10539735;
    LUT_X[124] = 1.081311; LUT_Y[124] = 3.10119555;
    LUT_X[125] = 1.09003125; LUT_Y[125] = 3.09692941;
    LUT_X[126] = 1.0987515; LUT_Y[126] = 3.09259722;
    LUT_X[127] = 1.10747175; LUT_Y[127] = 3.08819722;
    LUT_X[128] = 1.116192; LUT_Y[128] = 3.08372755;
    LUT_X[129] = 1.12491225; LUT_Y[129] = 3.07918625;
    LUT_X[130] = 1.1336325; LUT_Y[130] = 3.07457131;
    LUT_X[131] = 1.14235275; LUT_Y[131] = 3.06988058;
    LUT_X[132] = 1.151073; LUT_Y[132] = 3.06511181;
    LUT_X[133] = 1.15979325; LUT_Y[133] = 3.06026265;
    LUT_X[134] = 1.1685135; LUT_Y[134] = 3.05533064;
    LUT_X[135] = 1.17723375; LUT_Y[135] = 3.05031316;
    LUT_X[136] = 1.185954; LUT_Y[136] = 3.04520748;
    LUT_X[137] = 1.19467425; LUT_Y[137] = 3.04001071;
    LUT_X[138] = 1.2033945; LUT_Y[138] = 3.03471982;
    LUT_X[139] = 1.21211475; LUT_Y[139] = 3.02933159;
    LUT_X[140] = 1.220835; LUT_Y[140] = 3.02384263;
    LUT_X[141] = 1.22955525; LUT_Y[141] = 3.01824937;
    LUT_X[142] = 1.2382755; LUT_Y[142] = 3.01254802;
    LUT_X[143] = 1.24699575; LUT_Y[143] = 3.00673455;
    LUT_X[144] = 1.255716; LUT_Y[144] = 3.00080471;
    LUT_X[145] = 1.26443625; LUT_Y[145] = 2.99475399;
    LUT_X[146] = 1.2731565; LUT_Y[146] = 2.98857756;
    LUT_X[147] = 1.28187675; LUT_Y[147] = 2.98227032;
    LUT_X[148] = 1.290597; LUT_Y[148] = 2.97582681;
    LUT_X[149] = 1.29931725; LUT_Y[149] = 2.96924121;
    LUT_X[150] = 1.3080375; LUT_Y[150] = 2.9625073;
    LUT_X[151] = 1.31675775; LUT_Y[151] = 2.9556184;
    LUT_X[152] = 1.325478; LUT_Y[152] = 2.94856738;
    LUT_X[153] = 1.33419825; LUT_Y[153] = 2.94134654;
    LUT_X[154] = 1.3429185; LUT_Y[154] = 2.93394763;
    LUT_X[155] = 1.35163875; LUT_Y[155] = 2.92636171;
    LUT_X[156] = 1.360359; LUT_Y[156] = 2.91857914;
    LUT_X[157] = 1.36907925; LUT_Y[157] = 2.91058948;
    LUT_X[158] = 1.3777995; LUT_Y[158] = 2.90238136;
    LUT_X[159] = 1.38651975; LUT_Y[159] = 2.89394244;
    LUT_X[160] = 1.39524; LUT_Y[160] = 2.8852592;
    LUT_X[161] = 1.40396025; LUT_Y[161] = 2.87631688;
    LUT_X[162] = 1.4126805; LUT_Y[162] = 2.86709923;
    LUT_X[163] = 1.42140075; LUT_Y[163] = 2.85758835;
    LUT_X[164] = 1.430121; LUT_Y[164] = 2.84776443;
    LUT_X[165] = 1.43884125; LUT_Y[165] = 2.83760546;
    LUT_X[166] = 1.4475615; LUT_Y[166] = 2.82708691;
    LUT_X[167] = 1.45628175; LUT_Y[167] = 2.81618124;
    LUT_X[168] = 1.465002; LUT_Y[168] = 2.80485748;
    LUT_X[169] = 1.47372225; LUT_Y[169] = 2.7930805;
    LUT_X[170] = 1.4824425; LUT_Y[170] = 2.78081028;
    LUT_X[171] = 1.49116275; LUT_Y[171] = 2.7680009;
    LUT_X[172] = 1.499883; LUT_Y[172] = 2.75459929;
    LUT_X[173] = 1.50860325; LUT_Y[173] = 2.74054357;
    LUT_X[174] = 1.5173235; LUT_Y[174] = 2.72576097;
    LUT_X[175] = 1.52604375; LUT_Y[175] = 2.71016505;
    LUT_X[176] = 1.534764; LUT_Y[176] = 2.6936519;
    LUT_X[177] = 1.54348425; LUT_Y[177] = 2.67609504;
    LUT_X[178] = 1.5522045; LUT_Y[178] = 2.65733838;
    LUT_X[179] = 1.56092475; LUT_Y[179] = 2.63718622;
    LUT_X[180] = 1.569645; LUT_Y[180] = 2.61538916;
    LUT_X[181] = 1.57836525; LUT_Y[181] = 2.59162415;
    LUT_X[182] = 1.5870855; LUT_Y[182] = 2.56546707;
    LUT_X[183] = 1.59580575; LUT_Y[183] = 2.53635936;
    LUT_X[184] = 1.604526; LUT_Y[184] = 2.50358239;
    LUT_X[185] = 1.61324625; LUT_Y[185] = 2.46629013;
    LUT_X[186] = 1.6219665; LUT_Y[186] = 2.42370537;
    LUT_X[187] = 1.63068675; LUT_Y[187] = 2.37550577;
    LUT_X[188] = 1.639407; LUT_Y[188] = 2.32204435;
    LUT_X[189] = 1.64812725; LUT_Y[189] = 2.26406156;
    LUT_X[190] = 1.6568475; LUT_Y[190] = 2.20229368;
    LUT_X[191] = 1.66556775; LUT_Y[191] = 2.13735624;
    LUT_X[192] = 1.674288; LUT_Y[192] = 2.0697794;
    LUT_X[193] = 1.68300825; LUT_Y[193] = 2.00005157;
    LUT_X[194] = 1.6917285; LUT_Y[194] = 1.92864212;
    LUT_X[195] = 1.70044875; LUT_Y[195] = 1.85601032;
    LUT_X[196] = 1.709169; LUT_Y[196] = 1.78260827;
    LUT_X[197] = 1.71788925; LUT_Y[197] = 1.70888188;
    LUT_X[198] = 1.7266095; LUT_Y[198] = 1.63527142;
    LUT_X[199] = 1.73532975; LUT_Y[199] = 1.56221185;
    LUT_X[200] = 1.74405; LUT_Y[200] = 1.49013239;
    LUT_X[201] = 1.75277025; LUT_Y[201] = 1.41945481;
    LUT_X[202] = 1.7614905; LUT_Y[202] = 1.35058981;
    LUT_X[203] = 1.77021075; LUT_Y[203] = 1.28393075;
    LUT_X[204] = 1.778931; LUT_Y[204] = 1.21984488;
    LUT_X[205] = 1.78765125; LUT_Y[205] = 1.15866207;
    LUT_X[206] = 1.7963715; LUT_Y[206] = 1.10066234;
    LUT_X[207] = 1.80509175; LUT_Y[207] = 1.04606369;
    LUT_X[208] = 1.813812; LUT_Y[208] = 0.995012746;
    LUT_X[209] = 1.82253225; LUT_Y[209] = 0.947580527;
    LUT_X[210] = 1.8312525; LUT_Y[210] = 0.903764726;
    LUT_X[211] = 1.83997275; LUT_Y[211] = 0.863496505;
    LUT_X[212] = 1.848693; LUT_Y[212] = 0.826644235;
    LUT_X[213] = 1.85741325; LUT_Y[213] = 0.793007007;
    LUT_X[214] = 1.8661335; LUT_Y[214] = 0.762308345;
    LUT_X[215] = 1.87485375; LUT_Y[215] = 0.734214617;
    LUT_X[216] = 1.883574; LUT_Y[216] = 0.708378295;
    LUT_X[217] = 1.89229425; LUT_Y[217] = 0.684478085;
    LUT_X[218] = 1.9010145; LUT_Y[218] = 0.662238159;
    LUT_X[219] = 1.90973475; LUT_Y[219] = 0.641430086;
    LUT_X[220] = 1.918455; LUT_Y[220] = 0.621866942;
    LUT_X[221] = 1.92717525; LUT_Y[221] = 0.603395678;
    LUT_X[222] = 1.9358955; LUT_Y[222] = 0.585890161;
    LUT_X[223] = 1.94461575; LUT_Y[223] = 0.569245528;
    LUT_X[224] = 1.953336; LUT_Y[224] = 0.553373774;
    LUT_X[225] = 1.96205625; LUT_Y[225] = 0.538200354;
    LUT_X[226] = 1.9707765; LUT_Y[226] = 0.523661576;
    LUT_X[227] = 1.97949675; LUT_Y[227] = 0.509702575;
    LUT_X[228] = 1.988217; LUT_Y[228] = 0.49627574;
    LUT_X[229] = 1.99693725; LUT_Y[229] = 0.483339469;
    LUT_X[230] = 2.0056575; LUT_Y[230] = 0.470857184;
    LUT_X[231] = 2.01437775; LUT_Y[231] = 0.458796543;
    LUT_X[232] = 2.023098; LUT_Y[232] = 0.447128792;
    LUT_X[233] = 2.03181825; LUT_Y[233] = 0.435828251;
    LUT_X[234] = 2.0405385; LUT_Y[234] = 0.424871878;
    LUT_X[235] = 2.04925875; LUT_Y[235] = 0.414238918;
    LUT_X[236] = 2.057979; LUT_Y[236] = 0.403910599;
    LUT_X[237] = 2.06669925; LUT_Y[237] = 0.393869891;
    LUT_X[238] = 2.0754195; LUT_Y[238] = 0.384101287;
    LUT_X[239] = 2.08413975; LUT_Y[239] = 0.374590627;
    LUT_X[240] = 2.09286; LUT_Y[240] = 0.365324946;
    LUT_X[241] = 2.10158025; LUT_Y[241] = 0.356292339;
    LUT_X[242] = 2.1103005; LUT_Y[242] = 0.34748185;
    LUT_X[243] = 2.11902075; LUT_Y[243] = 0.338883373;
    LUT_X[244] = 2.127741; LUT_Y[244] = 0.330487562;
    LUT_X[245] = 2.13646125; LUT_Y[245] = 0.322285765;
    LUT_X[246] = 2.1451815; LUT_Y[246] = 0.314269946;
    LUT_X[247] = 2.15390175; LUT_Y[247] = 0.306432639;
    LUT_X[248] = 2.162622; LUT_Y[248] = 0.298766888;
    LUT_X[249] = 2.17134225; LUT_Y[249] = 0.291266205;
    LUT_X[250] = 2.1800625; LUT_Y[250] = 0.283924531;
    LUT_X[251] = 2.18878275; LUT_Y[251] = 0.276736196;
    LUT_X[252] = 2.197503; LUT_Y[252] = 0.26969589;
    LUT_X[253] = 2.20622325; LUT_Y[253] = 0.262798634;
    LUT_X[254] = 2.2149435; LUT_Y[254] = 0.256039751;
    LUT_X[255] = 2.22366375; LUT_Y[255] = 0.249414846;
    LUT_X[256] = 2.232384; LUT_Y[256] = 0.242919784;
    LUT_X[257] = 2.24110425; LUT_Y[257] = 0.236550671;
    LUT_X[258] = 2.2498245; LUT_Y[258] = 0.230303836;
    LUT_X[259] = 2.25854475; LUT_Y[259] = 0.224175815;
    LUT_X[260] = 2.267265; LUT_Y[260] = 0.218163339;
    LUT_X[261] = 2.27598525; LUT_Y[261] = 0.212263322;
    LUT_X[262] = 2.2847055; LUT_Y[262] = 0.206472846;
    LUT_X[263] = 2.29342575; LUT_Y[263] = 0.200789156;
    LUT_X[264] = 2.302146; LUT_Y[264] = 0.195209649;
    LUT_X[265] = 2.31086625; LUT_Y[265] = 0.189731868;
    LUT_X[266] = 2.3195865; LUT_Y[266] = 0.184353502;
    LUT_X[267] = 2.32830675; LUT_Y[267] = 0.179072384;
    LUT_X[268] = 2.337027; LUT_Y[268] = 0.173886499;
    LUT_X[269] = 2.34574725; LUT_Y[269] = 0.168794013;
    LUT_X[270] = 2.3544675; LUT_Y[270] = 0.163793311;
    LUT_X[271] = 2.36318775; LUT_Y[271] = 0.158883102;
    LUT_X[272] = 2.371908; LUT_Y[272] = 0.154062578;
    LUT_X[273] = 2.38062825; LUT_Y[273] = 0.149331567;
    LUT_X[274] = 2.3893485; LUT_Y[274] = 0.144690189;
    LUT_X[275] = 2.39806875; LUT_Y[275] = 0.140137482;
    LUT_X[276] = 2.406789; LUT_Y[276] = 0.135670565;
    LUT_X[277] = 2.41550925; LUT_Y[277] = 0.131285922;
    LUT_X[278] = 2.4242295; LUT_Y[278] = 0.126980665;
    LUT_X[279] = 2.43294975; LUT_Y[279] = 0.122752646;
    LUT_X[280] = 2.44167; LUT_Y[280] = 0.118600215;
    LUT_X[281] = 2.45039025; LUT_Y[281] = 0.114522017;
    LUT_X[282] = 2.4591105; LUT_Y[282] = 0.110516883;
    LUT_X[283] = 2.46783075; LUT_Y[283] = 0.106583778;
    LUT_X[284] = 2.476551; LUT_Y[284] = 0.102721763;
    LUT_X[285] = 2.48527125; LUT_Y[285] = 0.0989299852;
    LUT_X[286] = 2.4939915; LUT_Y[286] = 0.0952076669;
    LUT_X[287] = 2.50271175; LUT_Y[287] = 0.0915541012;
    LUT_X[288] = 2.511432; LUT_Y[288] = 0.0879686504;
    LUT_X[289] = 2.52015225; LUT_Y[289] = 0.0844507459;
    LUT_X[290] = 2.5288725; LUT_Y[290] = 0.0809998888;
    LUT_X[291] = 2.53759275; LUT_Y[291] = 0.0776156518;
    LUT_X[292] = 2.546313; LUT_Y[292] = 0.0742976823;
    LUT_X[293] = 2.55503325; LUT_Y[293] = 0.0710457054;
    LUT_X[294] = 2.5637535; LUT_Y[294] = 0.0678595278;
    LUT_X[295] = 2.57247375; LUT_Y[295] = 0.0647390426;
    LUT_X[296] = 2.581194; LUT_Y[296] = 0.0616842342;
    LUT_X[297] = 2.58991425; LUT_Y[297] = 0.0586951832;
    LUT_X[298] = 2.5986345; LUT_Y[298] = 0.055772073;
    LUT_X[299] = 2.60735475; LUT_Y[299] = 0.0529151946;
    LUT_X[300] = 2.616075; LUT_Y[300] = 0.0501249532;
    LUT_X[301] = 2.62479525; LUT_Y[301] = 0.0474018733;
    LUT_X[302] = 2.6335155; LUT_Y[302] = 0.0447466042;
    LUT_X[303] = 2.64223575; LUT_Y[303] = 0.0421599236;
    LUT_X[304] = 2.650956; LUT_Y[304] = 0.0396427411;
    LUT_X[305] = 2.65967625; LUT_Y[305] = 0.0371960995;
    LUT_X[306] = 2.6683965; LUT_Y[306] = 0.0348211731;
    LUT_X[307] = 2.67711675; LUT_Y[307] = 0.0325192646;
    LUT_X[308] = 2.685837; LUT_Y[308] = 0.0302917965;
    LUT_X[309] = 2.69455725; LUT_Y[309] = 0.0281403;
    LUT_X[310] = 2.7032775; LUT_Y[310] = 0.026066397;
    LUT_X[311] = 2.71199775; LUT_Y[311] = 0.0240717776;
    LUT_X[312] = 2.720718; LUT_Y[312] = 0.0221581698;
    LUT_X[313] = 2.72943825; LUT_Y[313] = 0.020327303;
    LUT_X[314] = 2.7381585; LUT_Y[314] = 0.018580863;
    LUT_X[315] = 2.74687875; LUT_Y[315] = 0.0169204404;
    LUT_X[316] = 2.755599; LUT_Y[316] = 0.0153474718;
    LUT_X[317] = 2.76431925; LUT_Y[317] = 0.0138631742;
    LUT_X[318] = 2.7730395; LUT_Y[318] = 0.0124684764;
    LUT_X[319] = 2.78175975; LUT_Y[319] = 0.0111639474;
    LUT_X[320] = 2.79048; LUT_Y[320] = 0.00994972617;
    LUT_X[321] = 2.79920025; LUT_Y[321] = 0.0088254564;
    LUT_X[322] = 2.8079205; LUT_Y[322] = 0.00779023021;
    LUT_X[323] = 2.81664075; LUT_Y[323] = 0.00684254506;
    LUT_X[324] = 2.825361; LUT_Y[324] = 0.00598027841;
    LUT_X[325] = 2.83408125; LUT_Y[325] = 0.00520068356;
    LUT_X[326] = 2.8428015; LUT_Y[326] = 0.00450040925;
    LUT_X[327] = 2.85152175; LUT_Y[327] = 0.00387554415;
    LUT_X[328] = 2.860242; LUT_Y[328] = 0.0033216854;
    LUT_X[329] = 2.86896225; LUT_Y[329] = 0.00283402858;
    LUT_X[330] = 2.8776825; LUT_Y[330] = 0.00240747445;
    LUT_X[331] = 2.88640275; LUT_Y[331] = 0.00203674624;
    LUT_X[332] = 2.895123; LUT_Y[332] = 0.00171651053;
    LUT_X[333] = 2.90384325; LUT_Y[333] = 0.00144149416;
    LUT_X[334] = 2.9125635; LUT_Y[334] = 0.00120659041;
    LUT_X[335] = 2.92128375; LUT_Y[335] = 0.0010069489;
    LUT_X[336] = 2.930004; LUT_Y[336] = 0.000838045415;
    LUT_X[337] = 2.93872425; LUT_Y[337] = 0.000695730002;
    LUT_X[338] = 2.9474445; LUT_Y[338] = 0.000576253683;
    LUT_X[339] = 2.95616475; LUT_Y[339] = 0.000476275867;
    LUT_X[340] = 2.964885; LUT_Y[340] = 0.000392855707;
    LUT_X[341] = 2.97360525; LUT_Y[341] = 0.00032343129;
    LUT_X[342] = 2.9823255; LUT_Y[342] = 0.000265790594;
    LUT_X[343] = 2.99104575; LUT_Y[343] = 0.000218037812;
    LUT_X[344] = 2.999766; LUT_Y[344] = 0.000178557969;
    LUT_X[345] = 3.00848625; LUT_Y[345] = 0.000145982057;
    LUT_X[346] = 3.0172065; LUT_Y[346] = 0.000119154173;
    LUT_X[347] = 3.02592675; LUT_Y[347] = 9.71015056e-05;
    LUT_X[348] = 3.034647; LUT_Y[348] = 7.90075791e-05;
    LUT_X[349] = 3.04336725; LUT_Y[349] = 6.41887829e-05;
    LUT_X[350] = 3.0520875; LUT_Y[350] = 5.20740305e-05;
    LUT_X[351] = 3.06080775; LUT_Y[351] = 4.21872714e-05;
    LUT_X[352] = 3.069528; LUT_Y[352] = 3.41325342e-05;
    LUT_X[353] = 3.07824825; LUT_Y[353] = 2.75811799e-05;
    LUT_X[354] = 3.0869685; LUT_Y[354] = 2.22610628e-05;
    LUT_X[355] = 3.09568875; LUT_Y[355] = 1.79473323e-05;
    LUT_X[356] = 3.104409; LUT_Y[356] = 1.44546393e-05;
    LUT_X[357] = 3.11312925; LUT_Y[357] = 1.16305464e-05;
    LUT_X[358] = 3.1218495; LUT_Y[358] = 9.34996583e-06;
    LUT_X[359] = 3.13056975; LUT_Y[359] = 7.51047918e-06;
    LUT_X[360] = 3.13929; LUT_Y[360] = 6.02840687e-06;
    LUT_X[361] = 3.14801025; LUT_Y[361] = 4.83551902e-06;
    LUT_X[362] = 3.1567305; LUT_Y[362] = 3.87629042e-06;
    LUT_X[363] = 3.16545075; LUT_Y[363] = 3.10561724e-06;
    LUT_X[364] = 3.174171; LUT_Y[364] = 2.48692358e-06;
    LUT_X[365] = 3.18289125; LUT_Y[365] = 1.99059618e-06;
    LUT_X[366] = 3.1916115; LUT_Y[366] = 1.59269431e-06;
    LUT_X[367] = 3.20033175; LUT_Y[367] = 1.27388947e-06;
    LUT_X[368] = 3.209052; LUT_Y[368] = 1.01859631e-06;
    LUT_X[369] = 3.21777225; LUT_Y[369] = 8.14262106e-07;
    LUT_X[370] = 3.2264925; LUT_Y[370] = 6.50787193e-07;
    LUT_X[371] = 3.23521275; LUT_Y[371] = 5.20053338e-07;
    LUT_X[372] = 3.243933; LUT_Y[372] = 4.15540633e-07;
    LUT_X[373] = 3.25265325; LUT_Y[373] = 3.32016911e-07;
    LUT_X[374] = 3.2613735; LUT_Y[374] = 2.65286385e-07;
    LUT_X[375] = 3.27009375; LUT_Y[375] = 2.11986517e-07;
    LUT_X[376] = 3.278814; LUT_Y[376] = 1.69424094e-07;
    LUT_X[377] = 3.28753425; LUT_Y[377] = 1.35443123e-07;
    LUT_X[378] = 3.2962545; LUT_Y[378] = 1.08318478e-07;
    LUT_X[379] = 3.30497475; LUT_Y[379] = 8.66703727e-08;
    LUT_X[380] = 3.313695; LUT_Y[380] = 6.9395648e-08;
    LUT_X[381] = 3.32241525; LUT_Y[381] = 5.56126097e-08;
    LUT_X[382] = 3.3311355; LUT_Y[382] = 4.4616785e-08;
    LUT_X[383] = 3.33985575; LUT_Y[383] = 3.58454523e-08;
    LUT_X[384] = 3.348576; LUT_Y[384] = 2.88492287e-08;
    LUT_X[385] = 3.35729625; LUT_Y[385] = 2.32693203e-08;
    LUT_X[386] = 3.3660165; LUT_Y[386] = 1.88193176e-08;
    LUT_X[387] = 3.37473675; LUT_Y[387] = 1.52706313e-08;
    LUT_X[388] = 3.383457; LUT_Y[388] = 1.24408478e-08;
    LUT_X[389] = 3.39217725; LUT_Y[389] = 1.01844229e-08;
    LUT_X[390] = 3.4008975; LUT_Y[390] = 8.38524337e-09;
    LUT_X[391] = 3.40961775; LUT_Y[391] = 6.9506853e-09;
    LUT_X[392] = 3.418338; LUT_Y[392] = 5.80687079e-09;
    LUT_X[393] = 3.42705825; LUT_Y[393] = 4.89487859e-09;
    LUT_X[394] = 3.4357785; LUT_Y[394] = 4.16771883e-09;
    LUT_X[395] = 3.44449875; LUT_Y[395] = 3.58792136e-09;
    LUT_X[396] = 3.453219; LUT_Y[396] = 3.12560758e-09;
    LUT_X[397] = 3.46193925; LUT_Y[397] = 2.75695393e-09;
    LUT_X[398] = 3.4706595; LUT_Y[398] = 2.46296601e-09;
    LUT_X[399] = 3.47937975; LUT_Y[399] = 2.22850051e-09;
    LUT_X[400] = 3.4881; LUT_Y[400] = 2.04148428e-09;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[400]) ? LUT_X[400] : xin);
      lo = 0;
      hi = 400;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 71;
  localparam int NDEPTH  = 73;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.332874574;
  localparam real K_FALL = 0.7502581409;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.4881;
  localparam real DOMAIN_EPS = 0.069762; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
