`timescale 1fs/1fs
//======================================================================
// lpfilt -- passive network block, with the subcircuit's own interface.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// .subckt lpfilt dra vout
//
// so the netlist's own card instantiates it unchanged. The characterized
// core lpfilt_rc_rnm is instantiated untouched inside: it is
// what the equivalence check ran against, and it keeps its measured
// behaviour and its `real` ports. Only the boundary changes.
//======================================================================
module lpfilt #(
  parameter real DT    = 1.0e-10,
  parameter real VINIT = 1.8495
) (
  output real   dra_v,
  input  real   dra_i,
  input  real   dra_g,
  output real   vout_v
);
  real v_inject, v_out;

  lpfilt_rc_rnm #(.DT(DT), .VINIT(VINIT)) u_core (
    .i_in     (dra_i),
    .g_in     (dra_g),
    .v_inject (v_inject),
    .v_out    (v_out)
  );

  assign dra_v = v_inject;
  assign vout_v = v_out;
endmodule : lpfilt
