`timescale 1fs/1fs
//====================================================================
// analog_top -- the analog partition's own top level.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// These are the netlist's `x` cards with the syntax changed:
//
//   xcp    pupb pdn dra dd          cpump
//   xlf    dra vout                 lpfilt
//   xvco   aout vout dd             ro_vco
//
// Same instance names, same nets, same port order. There is no
// mapping from a model's private port names onto the circuit's
// nets, and no assumed block ordering, because the models take
// the subcircuits' own interfaces.
//====================================================================
// The PORTS are the boundary the co-simulation declares: the
// nets the deck marks `external` (driven by the digital side)
// and the nets that side reads back. Everything else is
// internal to the partition, exactly as in the netlist.
//====================================================================
// Each analog net is THREE signals, split by how each one
// combines. Currents superpose and so do conductances in
// parallel, so both are `wreal`, where several drivers sum and
// that sum IS Kirchhoff's law; a voltage has exactly one owner,
// so it is a plain `real`. Carrying them in one resolved struct
// instead costs 370x more per update on this simulator, which
// is what made a composed model slower than the transistors.
//
// The conductance is the third because current alone leaves an
// algebraic loop open wherever a driver pushes into a node with
// no capacitance. Each driver states the slope of its own
// characteristic at the voltage it sees, and the block that
// owns the node solves V and i together from the sum.
//====================================================================
module analog_top (
  input  logic  pdn,
  input  logic  pupb,
  output real   aout_v,
  output real   vout_v
);

  real  dd_v, dra_v;   // internal to the partition
  wreal aout_i, dd_i, dra_i, vout_i;   // currents sum across drivers
  wreal aout_g, dd_g, dra_g, vout_g;   // so do parallel conductances

  assign dd_v = 3.3;   // the deck's own source

  cpump u_xcp (
    .pupb(pupb),
    .pdn(pdn),
    .dra_v(dra_v),
    .dra_i(dra_i),
    .dra_g(dra_g),
    .dd_v(dd_v)
  );
  lpfilt u_xlf (
    .dra_v(dra_v),
    .dra_i(dra_i),
    .dra_g(dra_g),
    .vout_v(vout_v)
  );
  ro_vco u_xvco (
    .aout_v(aout_v),
    .cont_v(vout_v),
    .dd_v(dd_v)
  );

endmodule : analog_top
