`timescale 1fs/1fs
//======================================================================
// ro_vco -- oscillator block, with the subcircuit's own interface.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// .subckt ro_vco aout cont dd
//
// so the netlist's own card instantiates it unchanged. The characterized
// core ro_vco_rnm is instantiated untouched inside: it is
// what the equivalence check ran against, and it keeps its measured
// behaviour and its `real` ports. Only the boundary changes.
//======================================================================
module ro_vco #(
  parameter real VDD = 3.3
) (
  output real   aout_v,
  input  real   cont_v,
  input  real   dd_v
);
  logic clk;

  ro_vco_rnm u_core (
    .cont (cont_v),
    .clk  (clk)
  );

  assign aout_v = clk ? VDD : 0.0;
endmodule : ro_vco
