`timescale 1fs/1fs
//======================================================================
// ro_vco -- oscillator block, with the subcircuit's own interface.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// .subckt ro_vco aout cont dd
//
// so the netlist's own card instantiates it unchanged. The characterized
// core ro_vco_rnm is instantiated untouched inside: it is
// what the equivalence check ran against, and it keeps its measured
// behaviour and its `real` ports. Only the boundary changes.
//======================================================================
module ro_vco #(
  parameter real VDD = 3.3
) (
  output real   aout_v,
  input  real   cont_v,
  input  real   dd_v
);
  logic clk;

  ro_vco_rnm u_core (
    .cont (cont_v),
    .vdd  (dd_v),
    .clk  (clk)
  );

  // The swing follows the supply this instance is actually given, not the
  // nominal it was characterized at -- an output that is rail-to-rail at
  // 3.3 V whatever the rail does cannot show a droop to anything
  // downstream. VDD is the fallback for an unconnected or zero supply;
  // the core prints the one-line warning for that case, off this same net.
  assign aout_v = clk ? ((dd_v > 0.0) ? dd_v : VDD) : 0.0;
endmodule : ro_vco
