`timescale 1fs/1fs
//======================================================================
// The ABSTRACT half of the loop MS proxy (UVM-MS clause 4.2.1).
//
// The monitor reads the analog boundary through this and the driver
// writes the reference rate through it, so neither holds a hierarchical
// path into the design. Clause 4.2.1 lists push, pull and "monitor
// continuous signals" as a typical proxy API; that is what these are.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package pll_analog_loop_ms_proxy_pkg;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"

  virtual class pll_analog_loop_ms_proxy extends uvm_ms_proxy;

    function new(string name = "pll_analog_loop_ms_proxy");
      super.new(name);
    endfunction

    // push -- the one thing this environment drives. Everything else
    // about the stimulus is the design's own RTL.
    pure virtual function void push_ref_hz(input real hz);

    // Settle, then measure for a stated span. The window is opened and
    // closed by the same object that owns the counters, so the monitor
    // cannot read a half-finished one.
    pure virtual task run_window(input real settle_s, input real window_s,
                                 input string label);
    pure virtual task wait_window_done();

    // pull -- what the window found.
    pure virtual function real   pull_ref_hz();
    pure virtual function real   pull_rate_hz();
    pure virtual function int    pull_edges();
    pure virtual function real   pull_ctrl_lo();
    pure virtual function real   pull_ctrl_hi();
    pure virtual function real   pull_ctrl_end();
    pure virtual function bit    pull_all_finite();
    pure virtual function string pull_label();

  endclass : pll_analog_loop_ms_proxy

endpackage : pll_analog_loop_ms_proxy_pkg
