`timescale 1fs/1fs
//======================================================================
// pll_analog_loop_ms_pkg -- the stimulus, as data.
//
// One item is one operating request: run the reference at this rate,
// let the loop settle, and measure for this long. The sequence below
// asks for the nominal rate, then a stepped one, then the nominal
// again -- so the run shows the loop LOCKING, FOLLOWING a change, and
// coming back, rather than one settled snapshot that a model frozen at
// its initial condition would also produce.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package pll_analog_loop_ms_pkg;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  import pll_analog_loop_ms_proxy_pkg::*;
  `include "uvm_macros.svh"

  // The specification's numbers, and the divider the RTL implements.
  localparam real REF_HZ     = 10000000;
  localparam int  NDIV       = 40;
  localparam real TOL_FRAC   = 0.02;
  localparam real SETTLE_S   = 2e-05;
  localparam real WINDOW_S   = 5e-06;
  localparam real STEP_FRAC  = 0.005;
  // The control window the specification states, if it states one.
  localparam bit  BAND_STATED = 1'b1;
  localparam real BAND_LO     = 1.75;
  localparam real BAND_HI     = 1.95;

  class pll_analog_loop_ms_item extends uvm_sequence_item;
    rand real   ref_hz;
    rand real   settle_s;
    rand real   window_s;
    string      label = "nominal";

    `uvm_object_utils_begin(pll_analog_loop_ms_item)
      `uvm_field_real(ref_hz,   UVM_ALL_ON)
      `uvm_field_real(settle_s, UVM_ALL_ON)
      `uvm_field_real(window_s, UVM_ALL_ON)
      `uvm_field_string(label,  UVM_ALL_ON)
    `uvm_object_utils_end

    function new(string name = "pll_analog_loop_ms_item");
      super.new(name);
      ref_hz   = REF_HZ;
      settle_s = SETTLE_S;
      window_s = WINDOW_S;
    endfunction
  endclass : pll_analog_loop_ms_item

  class pll_analog_loop_ms_seq extends uvm_sequence #(pll_analog_loop_ms_item);
    `uvm_object_utils(pll_analog_loop_ms_seq)

    function new(string name = "pll_analog_loop_ms_seq");
      super.new(name);
    endfunction

    task body();
      pll_analog_loop_ms_item it;
      // Lock from the initial condition the deck states.
      it = pll_analog_loop_ms_item::type_id::create("nominal");
      start_item(it); it.ref_hz = REF_HZ; it.label = "nominal";
      it.settle_s = SETTLE_S; it.window_s = WINDOW_S; finish_item(it);

      // FOLLOW a change. Small on purpose: this is re-lock, which is in
      // scope, and not acquisition from cold, which is not.
      it = pll_analog_loop_ms_item::type_id::create("stepped");
      start_item(it); it.ref_hz = REF_HZ * (1.0 + STEP_FRAC);
      it.label = "stepped"; it.settle_s = SETTLE_S; it.window_s = WINDOW_S;
      finish_item(it);

      // And come back, so a loop that drifted one way is not read as one
      // that followed.
      it = pll_analog_loop_ms_item::type_id::create("returned");
      start_item(it); it.ref_hz = REF_HZ; it.label = "returned";
      it.settle_s = SETTLE_S; it.window_s = WINDOW_S; finish_item(it);
    endtask
  endclass : pll_analog_loop_ms_seq

  // What the monitor publishes: one window, reduced.
  class pll_analog_loop_ms_result extends uvm_sequence_item;
    real   ref_hz, rate_hz, ctrl_lo, ctrl_hi, ctrl_end;
    int    edges;
    bit    all_finite;
    string label;

    `uvm_object_utils(pll_analog_loop_ms_result)

    function new(string name = "pll_analog_loop_ms_result");
      super.new(name);
    endfunction
  endclass : pll_analog_loop_ms_result

  `include "pll_analog_loop_ms_scoreboard.svh"
  `include "pll_analog_loop_ms_env.svh"
  `include "pll_analog_loop_ms_test.svh"

endpackage : pll_analog_loop_ms_pkg
