#!/usr/bin/env bash
# UVM-MS environment over the WHOLE loop -- AUTO-GENERATED by spice2rnm
# (Veylon Systems).
#
# No co-simulation anywhere in it: the analog half is the generated
# models, the digital half is the design's own RTL, and one xezim
# invocation compiles and simulates UVM, the IEEE 1800-2017 6.6.7
# nettypes and the models together.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
XEZIM=${XEZIM:-$HOME/xezim/target/release/xezim}
UVM=${UVM_SRC:-}
UVM_MS=${UVM_MS_LIB:-$HOME/uvm_ms_demo/ms}
MAX_TIME=${MAX_TIME:-94us}
# Wall-clock guard, seconds. A cap that fires truncates the run BEFORE
# the scoreboard reports, which reads as a silent pass.
WALL_TIMEOUT=${WALL_TIMEOUT:-3600}

if [ ! -x "$XEZIM" ]; then
  echo "ERROR: xezim not found or not executable at '$XEZIM'." >&2
  echo "  Re-run as:  XEZIM=/path/to/xezim $0" >&2
  exit 1
fi
for d in "$UVM/uvm_pkg.sv" "$UVM_MS/uvm_ms_pkg.sv"; do
  [ -f "$d" ] || { echo "ERROR: $d not found (set UVM_SRC / UVM_MS_LIB)." >&2; exit 1; }
done

cd "$ROOT"

# The analog sources by NAME, found on a search path. A generated script
# that hard-codes the directory it was written in cannot be published,
# and this one is meant to be: the same file has to work in the run tree
# and in a curated copy that flattens it.
SEARCH=${SEARCH:-"../analog ../../cpump ../../lpfilt ../../ro_vco . .. ../.. ../../.. ../../../.. ../../analog ../../../analog"}
ANALOG=""
for f in ams_node_pkg.sv cpump_cp_rnm.sv lpfilt_rc_rnm.sv ro_vco_rnm.sv cpump_iface.sv lpfilt_iface.sv ro_vco_iface.sv netlist_top.sv; do
  found=""
  for d in $SEARCH; do [ -f "$d/$f" ] && { found="$d/$f"; break; }; done
  [ -n "$found" ] || { echo "ERROR: $f not found on: $SEARCH" >&2
                       echo "  set SEARCH to the directories holding the models" >&2
                       exit 1; }
  ANALOG="$ANALOG $found"
done

# The customer's RTL, which lives wherever they keep it.
RTL_DIR=${RTL_DIR:-$HOME/s2r_runs/demo4b_pll_deck}
# $RTL_DIR first, then the search path, then rtl/ beside the case root,
# which is where a curated copy puts the customer's files.
RTL=""
for f in pfd.sv divn.sv; do
  found=""
  for d in "$RTL_DIR" $SEARCH ../../../rtl ../../rtl ../rtl ./rtl; do
    [ -f "$d/$f" ] && { found="$d/$f"; break; }
  done
  [ -n "$found" ] || { echo "ERROR: $f not found in '$RTL_DIR', on the" >&2
                       echo "  search path, or in an rtl/ beside it." >&2
                       echo "  re-run as:  RTL_DIR=/path/to/rtl $0" >&2
                       exit 1; }
  RTL="$RTL $found"
done

echo "=== running the UVM-MS loop environment for pll_analog on xezim ==="
timeout "$WALL_TIMEOUT" "$XEZIM" --max-time "$MAX_TIME" -DUVM_NO_DPI \
    -I "$UVM" -I "$UVM_MS" -I "$ROOT" \
    "$UVM/uvm_pkg.sv" \
    "$UVM_MS/uvm_ms_pkg.sv" \
    $ANALOG $RTL \
    pll_analog_loop_ms_proxy_pkg.sv \
    pll_analog_loop_ms_pkg.sv \
    top_pll_analog_loop_ms.sv \
    +UVM_NO_RELNOTES "$@" \
  2>&1 | grep -v 'compile-progress\|degraded to null\|not representable\|dpiexport'
