`timescale 1fs/1fs
//======================================================================
// top_pll_analog_sysms -- the loop, and the concrete half of the MS proxy.
//
// The analog is the characterized models composed the way the deck
// composes them; the digital is the design's own RTL, unchanged. The
// only thing this environment drives is the reference clock.
//
// The proxy implementation lives here because it is the one class that
// must reach the design's signals. Everything above it -- driver,
// monitor, agent, scoreboard, env, test -- talks to the abstract half
// and holds no hierarchical path at all.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module top_pll_analog_sysms;

  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import pll_analog_sysms_proxy_pkg::*;
  import pll_analog_sysms_pkg::*;

  // Where an analog output reads as a one: half the rail the deck
  // declares, which is the level between the two states characterization
  // measured each switched block at.
  localparam real VTH = 1.65;

  //--------------------------------------------------------------------
  // The analog partition, as analog_top declares its boundary.
  //--------------------------------------------------------------------
  logic pdn;
  logic pupb;
  real  aout_v, dra_v, vout_v;
  analog_top u_analog (
    .pdn(pdn),
    .pupb(pupb),
    .dd_v_ext(),
    .aout_v(aout_v),
    .dra_v(dra_v),
    .vout_v(vout_v)
  );

  //--------------------------------------------------------------------
  // The design's own RTL, instantiated with the ports the spec names.
  //--------------------------------------------------------------------
  logic div_clk, dn, ref_clk, up, vco_clk;
  pfd u_pfd (.div_clk(div_clk), .dn(dn), .ref_clk(ref_clk), .up(up));
  divn #(.N(40)) u_div (.clk_in(vco_clk), .clk_out(div_clk));

  // analog -> digital, at the threshold above
  assign vco_clk = (aout_v > VTH);

  // digital -> analog. Each sense DERIVED from the measured tuning slope
  // and the measured per-state currents; see the loop harness header.
  assign pdn    = up;      // active HIGH
  assign pupb   = ~dn;     // active LOW

  //--------------------------------------------------------------------
  // The reference. Its half period is a variable because the sequence
  // steps it -- that is the whole reason this environment has a driver.
  //--------------------------------------------------------------------
  time ref_half = 50000000;
  initial ref_clk = 1'b0;
  always #(ref_half) ref_clk = ~ref_clk;

  //--------------------------------------------------------------------
  // What a window collects. The rate is timed between the FIRST and LAST
  // edge inside it rather than taken from the count: at this reference
  // and this window the count alone is worth about a percent, the same
  // size as the tolerance it would be judged against.
  //--------------------------------------------------------------------
  int unsigned w_edges;
  real         w_t_first, w_t_last;
  bit          w_open = 1'b0;
  real         w_lo = 1.0e308, w_hi = -1.0e308;
  bit          w_finite = 1'b1;

  always @(posedge div_clk) begin
    if (w_open) begin
      if (w_edges == 0) w_t_first = $realtime;
      w_t_last = $realtime;
      w_edges  = w_edges + 1;
    end
  end

  // Every analog net watched on every change it makes, not on a tick: a
  // switched node aliases against an even stride and the pump's own
  // driven node is one.
  always @(aout_v) begin
    if (!(aout_v > -1.0e308 && aout_v < 1.0e308)) w_finite = 1'b0;
  end
  always @(dra_v) begin
    if (!(dra_v > -1.0e308 && dra_v < 1.0e308)) w_finite = 1'b0;
  end
  always @(vout_v) begin
    if (!(vout_v > -1.0e308 && vout_v < 1.0e308)) w_finite = 1'b0;
    else if (w_open) begin
      if (vout_v < w_lo) w_lo = vout_v;
      if (vout_v > w_hi) w_hi = vout_v;
    end
  end

  //--------------------------------------------------------------------
  // The CONCRETE half of the MS proxy (UVM-MS clause 4.2.1).
  //--------------------------------------------------------------------
  event window_done;

  class pll_analog_sysms_proxy_impl extends pll_analog_sysms_proxy;
    real   cur_ref_hz = 10000000;
    string cur_label  = "none";
    real   res_rate, res_lo, res_hi, res_end;
    int    res_edges;
    bit    res_finite;

    function new(string name = "proxy");
      super.new(name);
    endfunction

    function void push_ref_hz(input real hz);
      cur_ref_hz = hz;
      ref_half   = time'(0.5e15 / hz);
    endfunction

    task run_window(input real settle_s, input real window_s,
                    input string label);
      cur_label = label;
      w_finite  = 1'b1;
      #(settle_s * 1.0e15);
      w_lo    = 1.0e308;
      w_hi    = -1.0e308;
      w_edges = 0;
      w_open  = 1'b1;
      #(window_s * 1.0e15);
      w_open  = 1'b0;
      res_edges  = w_edges;
      res_rate   = (w_edges < 2) ? 0.0
                 : (real'(w_edges) - 1.0)
                   / ((w_t_last - w_t_first) * 1.0e-15);
      res_lo     = w_lo;
      res_hi     = w_hi;
      res_end    = vout_v;
      res_finite = w_finite;
      -> window_done;
    endtask

    task wait_window_done();
      @(window_done);
    endtask

    function real   pull_ref_hz();     pull_ref_hz     = cur_ref_hz; endfunction
    function real   pull_rate_hz();    pull_rate_hz    = res_rate;   endfunction
    function int    pull_edges();      pull_edges      = res_edges;  endfunction
    function real   pull_ctrl_lo();    pull_ctrl_lo    = res_lo;     endfunction
    function real   pull_ctrl_hi();    pull_ctrl_hi    = res_hi;     endfunction
    function real   pull_ctrl_end();   pull_ctrl_end   = res_end;    endfunction
    function bit    pull_all_finite(); pull_all_finite = res_finite; endfunction
    function string pull_label();      pull_label      = cur_label;  endfunction
  endclass : pll_analog_sysms_proxy_impl

  pll_analog_sysms_proxy_impl proxy_h;

  initial begin
    proxy_h = new("proxy");
    uvm_config_db #(pll_analog_sysms_proxy)::set(null, "*", "proxy", proxy_h);
    run_test("pll_analog_sysms_test");
  end

endmodule : top_pll_analog_sysms
