`timescale 1fs/1fs
//======================================================================
// pll_analog_sys_jitter -- period jitter of one boundary node, at 1 fs.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// COMPILED AT 1fs WHILE THE REST OF THE ENVIRONMENT IS AT 1ps, and that
// is the whole point of the file. A crossing recorded on a picosecond
// grid cannot be located to better than a picosecond, and the jitter
// figures this is for are tenths of one. Timescale is per module in
// SystemVerilog, so a finer one here costs nothing anywhere else.
//
// EVENT-DRIVEN on the signal, not sampled on a clock. A monitor with its
// own clock measures its own aliasing -- the same mistake the boundary
// log makes at 100 ps, where 199 edges over 1600 ns read as a confident
// 124 MHz.
//======================================================================
module pll_analog_sys_jitter #(
  parameter real VTH  = 1.65,   // the node's own midpoint, measured
  parameter int  SKIP = 8       // cycles discarded while the loop acquires
) (
  input real sig
);

  real prev_v, t_prev, sum_p, sum_p2, min_p, max_p;
  int  n_edge, n_per;
  bit  armed;

  initial begin
    prev_v = 0.0; t_prev = 0.0; sum_p = 0.0; sum_p2 = 0.0;
    min_p = 0.0; max_p = 0.0; n_edge = 0; n_per = 0; armed = 1'b0;
  end

  always @(sig) begin
    real t, p;
    if (prev_v <= VTH && sig > VTH) begin
      t = $realtime * 1.0e-15;
      if (armed) begin
        p = t - t_prev;
        n_edge = n_edge + 1;
        // The acquisition transient is not jitter. A loop that is still
        // pulling in has periods that differ because the frequency is
        // changing, and averaging those in would report the lock ramp.
        if (n_edge > SKIP) begin
          n_per  = n_per + 1;
          sum_p  = sum_p + p;
          sum_p2 = sum_p2 + p * p;
          if (n_per == 1 || p < min_p) min_p = p;
          if (n_per == 1 || p > max_p) max_p = p;
        end
      end
      t_prev = t;
      armed  = 1'b1;
    end
    prev_v = sig;
  end

  function automatic int    periods();     return n_per; endfunction
  function automatic real   mean_period(); return (n_per > 0) ? sum_p / n_per : 0.0; endfunction
  function automatic real   pk_pk();       return (n_per > 1) ? (max_p - min_p) : 0.0; endfunction
  function automatic real   rms_jitter();
    real m, v;
    if (n_per < 2) return 0.0;
    m = sum_p / n_per;
    v = sum_p2 / n_per - m * m;
    return (v > 0.0) ? $sqrt(v) : 0.0;
  endfunction

endmodule
