`timescale 1fs/1fs
// ng_anet port boundary for rc_lpf2_rnm, auto-generated by spice2rnm (Veylon Systems).
//
// The core model is instantiated untouched -- same behaviour,
// same evidence, byte-identical to the file the equivalence
// check ran against. Only the boundary changes discipline.
//
// ng_anet is declared by ng_ams_pkg, which is not generated here --
// it belongs to the model library this wrapper joins. The
// core stays plain `real` and compiles without either.
module rc_lpf2_rnm_ng_anet import ng_ams_pkg::*; (input ng_anet ain, output ng_anet aout);

  // Net -> variable, so the core's `input real` can take it.
  real in_r;
  always @(ain) in_r = ain;

  // Variable -> net on the way back out.
  real out_r;
  assign aout = out_r;

  rc_lpf2_rnm u_rnm (.in_val(in_r), .out_val(out_r));

endmodule : rc_lpf2_rnm_ng_anet
