`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// Fitted transfer function: H(s) = 1 * 1  / ((1+s/2.4023e+07) * (1+s/1.64656e+08))
// zeros (Hz): []
// poles (Hz): [3823382.3097665044, 26205852.219306976]
// fit quality: rms_error_db=1.417e-08  max_error_db=5.81e-08

module rc_lpf2_rnm(input real in_val, output real out_val);

  localparam real WP_0 = 24023019.55;
  localparam real WZ_0 = 0.0;
  localparam bit HAS_ZERO_0 = 0;
  localparam real WP_1 = 164656225.6;
  localparam real WZ_1 = 0.0;
  localparam bit HAS_ZERO_1 = 0;
  localparam real OVERALL_MULT = 3.955539728e+15;
  localparam real TSTEP = 303663.0; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 3.036629791e-10; // same interval, in real seconds, for RK4 math
  localparam real DC_BIAS = 0.9;
  localparam real GAIN_DC = 1.0; // H(0), subtracted off the dynamic
                                            // path so it isn't double-counted
                                            // against static_curve's own DC gain

  function automatic real static_curve(input real xin);
    real xc;
    begin
      xc = (xin < 0.0) ? 0.0 : ((xin > 1.8) ? 1.8 : xin);
      static_curve = -2.198363923e-16 + xc*(1.0);
    end
  endfunction

  real x_0;
  real x_1;

  real k1_0;
  real sec_in1_0;
  real sec_out1_0;
  real k1_1;
  real sec_in1_1;
  real sec_out1_1;
  real k2_0;
  real sec_in2_0;
  real sec_out2_0;
  real k2_1;
  real sec_in2_1;
  real sec_out2_1;
  real k3_0;
  real sec_in3_0;
  real sec_out3_0;
  real k3_1;
  real sec_in3_1;
  real sec_out3_1;
  real k4_0;
  real sec_in4_0;
  real sec_out4_0;
  real k4_1;
  real sec_in4_1;
  real sec_out4_1;
  real final_out;
  real u_dev;
  real static_out;
  real dynamic_out;

  initial begin
    x_0 = 0.0;
    x_1 = 0.0;
  end

  always #(TSTEP) begin : rk4_step
    real dt;
    dt = DT_SECONDS;

    u_dev = in_val - DC_BIAS;

    // k1
        sec_in1_0 = u_dev;
        sec_out1_0 = HAS_ZERO_0 ? ((WZ_0-WP_0)*(x_0) + sec_in1_0) : (x_0);
        k1_0 = -WP_0*(x_0) + sec_in1_0;
        sec_in1_1 = sec_out1_0;
        sec_out1_1 = HAS_ZERO_1 ? ((WZ_1-WP_1)*(x_1) + sec_in1_1) : (x_1);
        k1_1 = -WP_1*(x_1) + sec_in1_1;

    // k2
        sec_in2_0 = u_dev;
        sec_out2_0 = HAS_ZERO_0 ? ((WZ_0-WP_0)*(x_0 + 0.5*dt*k1_0) + sec_in2_0) : (x_0 + 0.5*dt*k1_0);
        k2_0 = -WP_0*(x_0 + 0.5*dt*k1_0) + sec_in2_0;
        sec_in2_1 = sec_out2_0;
        sec_out2_1 = HAS_ZERO_1 ? ((WZ_1-WP_1)*(x_1 + 0.5*dt*k1_1) + sec_in2_1) : (x_1 + 0.5*dt*k1_1);
        k2_1 = -WP_1*(x_1 + 0.5*dt*k1_1) + sec_in2_1;

    // k3
        sec_in3_0 = u_dev;
        sec_out3_0 = HAS_ZERO_0 ? ((WZ_0-WP_0)*(x_0 + 0.5*dt*k2_0) + sec_in3_0) : (x_0 + 0.5*dt*k2_0);
        k3_0 = -WP_0*(x_0 + 0.5*dt*k2_0) + sec_in3_0;
        sec_in3_1 = sec_out3_0;
        sec_out3_1 = HAS_ZERO_1 ? ((WZ_1-WP_1)*(x_1 + 0.5*dt*k2_1) + sec_in3_1) : (x_1 + 0.5*dt*k2_1);
        k3_1 = -WP_1*(x_1 + 0.5*dt*k2_1) + sec_in3_1;

    // k4
        sec_in4_0 = u_dev;
        sec_out4_0 = HAS_ZERO_0 ? ((WZ_0-WP_0)*(x_0 + dt*k3_0) + sec_in4_0) : (x_0 + dt*k3_0);
        k4_0 = -WP_0*(x_0 + dt*k3_0) + sec_in4_0;
        sec_in4_1 = sec_out4_0;
        sec_out4_1 = HAS_ZERO_1 ? ((WZ_1-WP_1)*(x_1 + dt*k3_1) + sec_in4_1) : (x_1 + dt*k3_1);
        k4_1 = -WP_1*(x_1 + dt*k3_1) + sec_in4_1;

    // combine and advance state
    x_0 = x_0 + (dt/6.0)*(k1_0 + 2.0*k2_0 + 2.0*k3_0 + k4_0);
    x_1 = x_1 + (dt/6.0)*(k1_1 + 2.0*k2_1 + 2.0*k3_1 + k4_1);
    dynamic_out = OVERALL_MULT * (sec_out1_1);
    static_out = static_curve(in_val);
    final_out = static_out + (dynamic_out - GAIN_DC*u_dev);
    out_val = final_out;
  end

endmodule
