`timescale 1fs/1fs
//======================================================================
// rc_lpf2_dms -- the mixed-signal wrapper around the generated RNM.
//
// The RNM (rc_lpf2_rnm) keeps the plain `real` ports spice2rnm has
// always emitted: a `real` port is a VARIABLE, so nothing can share it
// and no bridge can attach.  This wrapper is the I/O layer that turns it
// into a net-connected mixed-signal block -- the same relationship
// frequency_adapter_dms has to freq_adapt_core in uvm_ms_demo, where the
// core is untouched and only the boundary changes.
//
// The ports are `interconnect` (IEEE 1800-2017 6.6.8), which is what
// UVM-MS clause 4.2 asks for: the wrapper does not name the analog type,
// it inherits whatever the enclosing testbench wired to it.  Directions
// are explicit -- a directionless interconnect defaults to inout, and
// inout is not supported for real-valued nets.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module rc_lpf2_dms import ng_ams_pkg::*; (
  input  interconnect ain,
  output interconnect aout
);

  // The DELIVERABLE is the boundary module, so that is what
  // the environment instantiates: what is verified is what
  // ships. Its ports are already net-typed, so these
  // interconnect ports connect straight through -- the
  // net/variable conversion happens once, inside it.
  rc_lpf2_rnm_ng_anet u_rnm (.ain(ain), .aout(aout));

endmodule : rc_lpf2_dms
