#!/usr/bin/env bash
# UVM-MS testbench for rc_lpf2_rnm -- AUTO-GENERATED by spice2rnm (Veylon Systems).
#
# Needs an Icarus build with BOTH UVM support and real-number/UDN support
# (interconnect ports, IEEE 1800-2017 6.6.7 nettypes).  Point IVL_PREFIX at it.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
PREFIX=${IVL_PREFIX:-$HOME/iverilog-unified-local}
UVM=${UVM_SRC:-$HOME/iverilog-unified/uvm-core/src}
# The UVM-MS library (Accellera Annex A.1/A.2) is not vendored here.
UVM_MS=${UVM_MS_LIB:-$HOME/uvm_ms_demo/ms}
IV=$PREFIX/bin/iverilog
VV=$PREFIX/bin/vvp

# Say what is missing, rather than letting the first command fail with
# "no such file". The simulator that ran the equivalence check is usually
# NOT the one that can build this: compiling UVM plus 6.6.7 nettypes is a
# much narrower requirement than executing a plain SystemVerilog testbench.
for t in "$IV" "$VV"; do
  if [ ! -x "$t" ]; then
    echo "ERROR: $t not found or not executable." >&2
    echo "  IVL_PREFIX is currently '$PREFIX'." >&2
    echo "  This testbench needs an Icarus build with BOTH UVM support and" >&2
    echo "  real-number/UDN support (interconnect ports, IEEE 1800-2017 6.6.7)." >&2
    echo "  Re-run as:  IVL_PREFIX=/path/to/that/build $0" >&2
    exit 1
  fi
done
for d in "$UVM/uvm_pkg.sv" "$UVM_MS/uvm_ms_pkg.sv"; do
  [ -f "$d" ] || { echo "ERROR: $d not found (set UVM_SRC / UVM_MS_LIB)." >&2; exit 1; }
done

cd "$ROOT"
rm -f rc_lpf2_ms.vvp

echo "=== compiling UVM-MS testbench for rc_lpf2_rnm ==="
$IV -g2012 -DUVM_NO_DPI \
    -I "$UVM" -I "$UVM_MS" -I "$ROOT" \
    -o rc_lpf2_ms.vvp \
    "$UVM/uvm_pkg.sv" \
    "$UVM_MS/uvm_ms_pkg.sv" \
    "${HOUSE_NET_SRC:-../house_lib/ng_ams_pkg.sv}" \
    rc_lpf2_proxy_pkg.sv \
    rc_lpf2_rnm.sv \
    rc_lpf2_dms.sv \
    rc_lpf2_bridge_core.sv \
    rc_lpf2_bridge.sv \
    rc_lpf2_ms_pkg.sv \
    top_rc_lpf2_ms.sv \
  2>&1 | grep -v 'compile-progress\|degraded to null\|not representable\|dpiexport'

[ -f rc_lpf2_ms.vvp ] || { echo "COMPILE FAILED"; exit 1; }

echo "=== running UVM-MS testbench ==="
timeout 600 $VV +UVM_NO_RELNOTES rc_lpf2_ms.vvp "$@"
