`timescale 1fs/1fs
//======================================================================
// top -- UVM-MS testbench for rc_lpf2_rnm.
//
// The MS bridge drives the stimulus net and senses the response net; the
// DMS wrapper carries both into the generated RNM.  Both modules declare
// their DUT-facing ports as `interconnect` and inherit the concrete types
// from the nets below (UVM-MS clause 4.2).
//
// The stimulus net is the user-defined nettype rather than a plain wreal,
// so a second driver added here -- an offset source, noise, another
// bridge -- is combined by the nettype's resolution function rather than
// by the testbench (clause 4.2.3.2).
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module top;

  // UVM + UVM-MS libraries
  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  // Generated packages
  import ng_ams_pkg::*;
  import rc_lpf2_proxy_pkg::*;
  import rc_lpf2_ms_pkg::*;

  // Test library
  `include "rc_lpf2_ms_scoreboard.svh"
  `include "rc_lpf2_ms_tb.svh"
  `include "rc_lpf2_ms_test.svh"

  //--- analog nets ----------------------------------------------------
  ng_anet ain_net;    // resolved UDN: bridge core drives it
  ng_anet aout_net;   // DUT response -- the same UDN as the
                            // stimulus net, not a plain wreal. The
                            // response has a single driver, so the
                            // resolution function is an identity over
                            // it; using the nettype anyway keeps the
                            // generated testbench to IEEE 1800-2017
                            // 6.6.7, which every simulator with UDN
                            // support has. `wreal` is Verilog-AMS, not
                            // 1800, and is not universally available.

  //--- MS bridge and DUT ----------------------------------------------
  rc_lpf2_bridge u_bridge (
    .ain  (ain_net),
    .aout (aout_net)
  );

  rc_lpf2_dms u_dut (
    .ain  (ain_net),
    .aout (aout_net)
  );

  initial begin
    `uvm_ms_info("TOP_MS",
                 "UVM-MS testbench for rc_lpf2_rnm: bridge instantiated, DC goldens from ngspice",
                 UVM_LOW)
    run_test("rc_lpf2_ms_test");
  end

endmodule : top
