`timescale 1fs/1fs
//======================================================================
// inv2_dms -- the mixed-signal wrapper around the generated RNM.
//
// The RNM (inv2_rnm) keeps the plain `real` ports spice2rnm has
// always emitted: a `real` port is a VARIABLE, so nothing can share it
// and no bridge can attach.  This wrapper is the I/O layer that turns it
// into a net-connected mixed-signal block -- the same relationship
// frequency_adapter_dms has to freq_adapt_core in uvm_ms_demo, where the
// core is untouched and only the boundary changes.
//
// The ports are `interconnect` (IEEE 1800-2017 6.6.8), which is what
// UVM-MS clause 4.2 asks for: the wrapper does not name the analog type,
// it inherits whatever the enclosing testbench wired to it.  Directions
// are explicit -- a directionless interconnect defaults to inout, and
// inout is not supported for real-valued nets.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module inv2_dms import inv2_ms_types_pkg::*; (
  input  interconnect ain,
  output interconnect aout
);

  // The core's own ports are net-typed, so these interconnect
  // ports connect straight through. Nothing to convert to a
  // variable and back: the discipline lives in the model, and
  // what the environment drives IS the deliverable.
  inv2_rnm u_rnm (.in_val(ain), .out_val(aout));

endmodule : inv2_dms
