`timescale 1fs/1fs
//======================================================================
// lpfilt_rc_rnm -- passive RC network driven by CURRENT.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// Not a fitted transfer function. For a linear network the state space is
// exact, so the coefficients below come from the netlist's own R and C
// values rather than from a sweep, and carry no fitting error.
//
// The pipeline's dc_ac path models this same network as Vout(Vin) under an
// ideal VOLTAGE drive. That is not how it is used when a charge pump feeds
// it: the drive is a CURRENT, and driving a capacitive network with current
// makes it an integrator -- its transimpedance has a pole at the origin,
// which is where a rational fit is least comfortable and where a state
// space is simply correct.
//
// States are the capacitor node voltages: c1, int1, vout
// Algebraic (no capacitance, hence no memory): dra
//
// A node carrying no capacitance is NOT a state. Its voltage is whatever
// the surrounding resistors make it at that instant, so it is solved
// directly. Treating it as a state with C = 0 is what a single-pole node
// integrator does, and on this network it does not lose accuracy, it
// diverges.
//
// THE INJECTION NODE CLOSES AN ALGEBRAIC LOOP WITH ITS DRIVER. Its voltage
// is set by the current pushed into it and that current is set by its
// voltage, both with no memory between them, so neither can be evaluated
// first. Sampling the driver's current once per step and using it as if it
// were converged puts a delay in that loop; with a driver whose slope times
// the injection resistance exceeds one -- an ordinary transistor into a few
// hundred ohms does -- the delayed loop is unstable and settles on the
// wrong operating point rather than the right one.
//
// So the driver passes its output conductance g_in beside its current, and
// the node is solved in closed form:
//
//     V = (M*Vc + N*i_in + N*g_in*V_prev) / (1 + N*g_in)
//
// which is one Newton step on i = f(V). It is exact for a piecewise-linear
// driver characteristic and stable at any loop gain, because the gain
// appears in the denominator rather than as a multiplier. The current that
// voltage implies, i_solved, is what the states then integrate -- using the
// driver's stale sample there instead would reintroduce the same delay one
// level down.
//
// no DC path to ground: a constant injected current ramps the output without settling. That is what a charge pump into a capacitive filter does, and it is why this is modelled as a state space rather than a DC gain
//======================================================================
module lpfilt_rc_rnm #(
  parameter real DT    = 1e-10,     // integration step, seconds
  parameter real VINIT = 0   // initial state voltage
) (
  input  wreal i_in,      // current INTO dra, amps
  input  wreal g_in,      // that driver's output conductance, siemens
  output wreal v_inject,  // that node's voltage, fed back to the driver
  output wreal v_out      // vout
);

  // capacitor node voltages
  real vc_c1;
  real vc_int1;
  real vc_vout;

  initial begin
    vc_c1 = VINIT;
    vc_int1 = VINIT;
    vc_vout = VINIT;
  end

  // purely resistive nodes
  real vr_dra;
  real d_c1;
  real d_int1;
  real d_vout;

  // the loop solve: the voltage the driver last saw, and the current its
  // characteristic actually carries at the voltage solved for here
  real v_prev, i_solved;

  always #(DT * 1.0e15) begin
    // the injection node and its driver, solved together
    v_prev   = vr_dra;
    vr_dra = (1 * vc_int1 + 300 * (i_in + g_in * v_prev))
                / (1.0 + 300 * g_in);
    i_solved = i_in - g_in * (vr_dra - v_prev);
    // the remaining algebraic nodes: Vr = M*Vc + N*i
    // (none)
    // then the states: dVc/dt = A*Vc + B*i  (forward Euler)
    d_c1 = -500000 * vc_c1 + 500000 * vc_int1;
    d_int1 = 1000000 * vc_c1 + -5000000 * vc_int1 + 4000000 * vc_vout + 200000000 * i_solved;
    d_vout = 40000000 * vc_int1 + -40000000 * vc_vout;
    vc_c1 = vc_c1 + DT * d_c1;
    vc_int1 = vc_int1 + DT * d_int1;
    vc_vout = vc_vout + DT * d_vout;
  end

  assign v_inject = vr_dra;
  assign v_out    = vc_vout;

endmodule : lpfilt_rc_rnm
