`timescale 1fs/1fs
//======================================================================
// ro_vco_ms_pkg -- the measured tuning curve, and the sweep over it.
//
// Every golden here is an ngspice measurement of the real circuit (FFT peak
// of a transient at that control voltage), not a value evaluated from the
// model's own table -- a check against the table the model implements would
// pass unconditionally.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package ro_vco_ms_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  localparam int  NPT       = 15;      // table breakpoints
  localparam int  NHO       = 14;      // held-out midpoints

  // THE BAND THE LOOP ACTUALLY USES, measured by the golden probe against
  // the transistors -- not a range anyone chose. A tuning curve is swept
  // wider than the design drives it, because a table that stopped at the
  // band's edge would clamp there; but a verdict taken over the whole
  // sweep fails a model for disagreeing where the loop never goes.
  //
  // The pipeline takes its verdict inside this band and REPORTS the wider
  // figure. This environment did neither: it applied one flat tolerance
  // everywhere and failed the reference ring at 2.7689 V by 4.986%, a
  // point outside the band, on a model the pipeline's own report calls
  // good. A generated environment that contradicts the report shipped
  // beside it is worse than no environment.
  localparam bit  HAS_BAND  = 1'b1;
  localparam real BAND_LO   = 1.65;
  localparam real BAND_HI   = 2.05;
  localparam real TOL_FRAC  = 0.02; // of period
  localparam int  MEAS_CYC  = 200;

  // Breakpoints: the control voltages the model's table was built from.
  function automatic real bp_volt(input int i);
    case (i)
      0: bp_volt = 4.950000000e-01;
      1: bp_volt = 7.837500000e-01;
      2: bp_volt = 1.072500000e+00;
      3: bp_volt = 1.361250000e+00;
      4: bp_volt = 1.650000000e+00;
      5: bp_volt = 1.750000000e+00;
      6: bp_volt = 1.850000000e+00;
      7: bp_volt = 1.938750000e+00;
      8: bp_volt = 1.950000000e+00;
      9: bp_volt = 2.050000000e+00;
      10: bp_volt = 2.227500000e+00;
      11: bp_volt = 2.516250000e+00;
      12: bp_volt = 2.660625000e+00;
      13: bp_volt = 2.732812500e+00;
      14: bp_volt = 2.805000000e+00;
      default: bp_volt = 0.0;
    endcase
  endfunction
  function automatic real bp_freq(input int i);
    case (i)
      0: bp_freq = 8.044728186e+08;
      1: bp_freq = 7.353222574e+08;
      2: bp_freq = 6.634459647e+08;
      3: bp_freq = 5.803862641e+08;
      4: bp_freq = 4.774032573e+08;
      5: bp_freq = 4.387292022e+08;
      6: bp_freq = 3.998617212e+08;
      7: bp_freq = 3.658689447e+08;
      8: bp_freq = 3.616114645e+08;
      9: bp_freq = 3.241480087e+08;
      10: bp_freq = 2.570119652e+08;
      11: bp_freq = 1.366251648e+08;
      12: bp_freq = 7.416278165e+07;
      13: bp_freq = 4.240882586e+07;
      14: bp_freq = 1.673948453e+07;
      default: bp_freq = 0.0;
    endcase
  endfunction

  // Held-out: measured in ngspice, deliberately NOT given to the model.
  // These are the ones that can actually fail.
  function automatic real ho_volt(input int i);
    case (i)
      0: ho_volt = 6.393750000e-01;
      1: ho_volt = 9.281250000e-01;
      2: ho_volt = 1.216875000e+00;
      3: ho_volt = 1.505625000e+00;
      4: ho_volt = 1.700000000e+00;
      5: ho_volt = 1.794375000e+00;
      6: ho_volt = 1.800000000e+00;
      7: ho_volt = 1.900000000e+00;
      8: ho_volt = 2.000000000e+00;
      9: ho_volt = 2.083125000e+00;
      10: ho_volt = 2.371875000e+00;
      11: ho_volt = 2.588437500e+00;
      12: ho_volt = 2.696718750e+00;
      13: ho_volt = 2.768906250e+00;
      default: ho_volt = 0.0;
    endcase
  endfunction
  function automatic real ho_freq(input int i);
    case (i)
      0: ho_freq = 7.699447053e+08;
      1: ho_freq = 7.001850167e+08;
      2: ho_freq = 6.240349333e+08;
      3: ho_freq = 5.311898106e+08;
      4: ho_freq = 4.581442318e+08;
      5: ho_freq = 4.214532104e+08;
      6: ho_freq = 4.192644847e+08;
      7: ho_freq = 3.806238208e+08;
      8: ho_freq = 3.428134235e+08;
      9: ho_freq = 3.117954549e+08;
      10: ho_freq = 1.989275383e+08;
      11: ho_freq = 1.051005546e+08;
      12: ho_freq = 5.824655798e+07;
      13: ho_freq = 2.809950505e+07;
      default: ho_freq = 0.0;
    endcase
  endfunction

  class ro_vco_vco_item extends uvm_sequence_item;
    real control_v;
    real golden_f;
    bit  held_out;      // scored separately; see the scoreboard
    real measured_f;
    `uvm_object_utils(ro_vco_vco_item)
    function new(string name = "ro_vco_vco_item");
      super.new(name);
    endfunction
  endclass

  // Breakpoints first, then the held-out points. Order is not important to
  // the check -- the model has no memory between control settings -- but a
  // monotonic walk keeps the log readable next to the tuning curve.
  class ro_vco_vco_seq extends uvm_sequence #(ro_vco_vco_item);
    `uvm_object_utils(ro_vco_vco_seq)
    function new(string name = "ro_vco_vco_seq");
      super.new(name);
    endfunction
    virtual task body();
      ro_vco_vco_item it;
      for (int i = 0; i < NPT; i++) begin
        it = ro_vco_vco_item::type_id::create("it");
        start_item(it);
        it.control_v = bp_volt(i);
        it.golden_f  = bp_freq(i);
        it.held_out  = 1'b0;
        finish_item(it);
      end
      for (int i = 0; i < NHO; i++) begin
        it = ro_vco_vco_item::type_id::create("it");
        start_item(it);
        it.control_v = ho_volt(i);
        it.golden_f  = ho_freq(i);
        it.held_out  = 1'b1;
        finish_item(it);
      end
    endtask
  endclass

endpackage : ro_vco_ms_pkg
