//======================================================================
// pi_therm_ms_tb -- env: a driver that also measures, and the scoreboard.
//
// The driver both sets the code and measures the resulting edge, rather
// than calling a monitor task in `top`. The first cut did the latter and
// every code came back unchecked: a class method calling a module-scope
// task is not the same reach as a class reading the enclosing module's
// nets, and the run reported "phase checks=0" -- which without the guard
// in the scoreboard would have read as a pass.
//
// Reading `aout_net` and writing `code_sig` directly is legitimate here
// because this class is included INSIDE top, so those are enclosing-scope
// names, not hierarchical references into somewhere else.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class pi_therm_ms_driver extends uvm_driver #(pi_therm_code_item);
  `uvm_component_utils(pi_therm_ms_driver)
  pi_therm_ms_scoreboard sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Mean phase of the output's falling edges over MEAS_CYC periods.
  // Crossings are interpolated between samples rather than taken at the
  // sample instant: the model updates on its own step, and rounding an
  // edge to that step would report the step size as phase error.
  virtual task measure(input int c);
    real vth, prev_v, prev_t, t_now, tc, acc, ref_ph, ph, cur;
    int  n;
    vth = 0.5 * (1.000000 + 0.000000);
    acc = 0.0; n = 0; ref_ph = -1.0;
    prev_v = aout_net; prev_t = $realtime;
    repeat (MEAS_CYC * 400) begin
      #(5000.000000);
      t_now = $realtime;
      cur   = aout_net;
      if (prev_v >= vth && cur < vth && prev_v != cur) begin
        tc = prev_t + (t_now - prev_t) * ((prev_v - vth) / (prev_v - cur));
        ph = tc / 1.0e15;
        ph = ph - PERIOD_S * $floor(ph / PERIOD_S);
        if (ref_ph < 0.0) ref_ph = ph;
        // Unwrap against the first edge, or an edge sitting either side of
        // the period boundary averages into the middle of the cycle.
        if (ph - ref_ph > PERIOD_S * 0.5)      ph = ph - PERIOD_S;
        else if (ref_ph - ph > PERIOD_S * 0.5) ph = ph + PERIOD_S;
        acc = acc + ph; n = n + 1;
      end
      prev_v = cur; prev_t = t_now;
    end
    if (n > 0) sb.check_code(c, acc / real'(n));
    else `uvm_error("PHASE_MEAS",
                    $sformatf("code %0d produced no falling edges", c))
  endtask

  virtual task run_phase(uvm_phase phase);
    pi_therm_code_item it;
    forever begin
      seq_item_port.get_next_item(it);
      `uvm_info("pi_therm_ms_driver",
                $sformatf("code = %0d", it.code), UVM_MEDIUM)
      code_sig = it.code;
      // Settle first: the delay line still holds the previous code's
      // samples, and measuring through that handover would score the
      // transition rather than the code.
      #(SETTLE_CYC * PERIOD_S * 1.0e15);
      measure(it.code);
      seq_item_port.item_done();
    end
  endtask
endclass

class pi_therm_ms_tb extends uvm_env;
  `uvm_component_utils(pi_therm_ms_tb)
  pi_therm_ms_driver                     driver;
  uvm_sequencer #(pi_therm_code_item)    sqr;
  pi_therm_ms_scoreboard                 sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    driver = pi_therm_ms_driver::type_id::create("driver", this);
    sqr    = uvm_sequencer #(pi_therm_code_item)::type_id::create("sqr", this);
    sb     = pi_therm_ms_scoreboard::type_id::create("sb", this);
  endfunction

  function void connect_phase(uvm_phase phase);
    driver.seq_item_port.connect(sqr.seq_item_export);
    driver.sb = sb;
  endfunction
endclass
