//======================================================================
// pi_therm_ms_tb -- the environment.
//
// Publishes the bridge proxy through uvm_config_db (UVM-MS clause 4.2.1:
// the agent only ever sees the ABSTRACT proxy type, so it is unchanged if
// the core behind it is swapped for a Verilog-AMS one), then wires the
// monitor's analysis port to the scoreboard.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class pi_therm_ms_tb extends uvm_env;

  pi_therm_ms_agent      agent;
  pi_therm_ms_scoreboard sb;

  `uvm_component_utils(pi_therm_ms_tb)

  function new(string name, uvm_component parent = null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // The concrete proxy lives inside the bridge module; hand it to the
    // agent as the abstract type.
    uvm_config_db #(pi_therm_proxy)::set(this, "agent.*",
                                         "bridge_proxy", top.u_bridge.proxy);

    agent = pi_therm_ms_agent::type_id::create("agent", this);
    sb    = pi_therm_ms_scoreboard::type_id::create("sb", this);
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    agent.monitor.item_collected_port.connect(sb.sb_imp);
  endfunction

endclass : pi_therm_ms_tb
