`timescale 1fs/1fs
//======================================================================
// pi_therm_dms -- mixed-signal wrapper around pi_therm_rnm.
//
// Same role as the DC/AC environment's wrapper: the RNM keeps the plain
// `real` ports spice2rnm emits, and this is the I/O layer that turns it
// into a net-connected block. Ports are `interconnect` (IEEE 1800-2017
// 6.6.8) so the wrapper inherits the analog type from whatever the
// testbench wires to it, with explicit directions because a
// directionless interconnect defaults to inout.
//
// The code port is ordinary digital and passes straight through -- it is
// not an analog quantity and does not belong on a nettype.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module pi_therm_dms import pi_therm_ms_types_pkg::*; (
  input  interconnect ain,
  input  int          code,
  output interconnect aout
);

  real in_r = 0.0;
  always @(ain) in_r = ain;

  real out_r;
  assign aout = out_r;

  pi_therm_rnm u_rnm (
    .in_val  (in_r),
    .code         (code),
    .out_val (out_r)
  );

endmodule : pi_therm_dms
