`timescale 1fs/1fs
//======================================================================
// pi_therm_bridge -- the MS Bridge.
//
// Holds the concrete proxy, whose every method reaches the bridge core by
// OOMR (clause 4.2.3) -- setting values and waiting on signals, never
// calling a task that consumes time out there. That is what keeps the
// class-based world and the analog core decoupled while staying inside
// what a simulator will resolve.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module pi_therm_bridge;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  import pi_therm_proxy_pkg::*;

  class pi_therm_bridge_proxy extends pi_therm_proxy;

    function new(string name = "");
      super.new(name);
    endfunction

    virtual function void push_code(input int c);
      core.request(c);
      `uvm_ms_info("BRIDGE_PUSH_CODE", $sformatf("code = %0d", c), UVM_HIGH)
    endfunction

    virtual task wait_measure_done();
      @(core.meas_done);
    endtask

    virtual function int  get_code();    return core.meas_code;  endfunction
    virtual function real get_phase();   return core.meas_phase; endfunction
    virtual function int  get_n_edges(); return core.meas_n;     endfunction

  endclass : pi_therm_bridge_proxy

  pi_therm_bridge_proxy proxy = new("proxy");

  pi_therm_bridge_core core ();

endmodule : pi_therm_bridge
