`timescale 1fs/1fs
//======================================================================
// pi_therm_ms_pkg -- goldens and the code sequence.
//
// The golden table is ngspice measurement: the phase of the output edge
// at each code, taken from a transient run of the real circuit. Nothing
// here is evaluated from the model's own delay table, because a check
// against the table the model was built from would pass unconditionally.
//
// AUTO-GENERATED by spice2rnm.  Edits will be overwritten.
//======================================================================
package pi_therm_ms_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  localparam int  NCODE      = 9;
  localparam real PERIOD_S   = 2.000000000000e-09;
  localparam real TOL_S      = 6.251268968662e-12;   // 0.1 of one LSB
  localparam int  SETTLE_CYC = 6;
  localparam int  MEAS_CYC   = 8;

  // code -> measured phase of the output falling edge, seconds, reduced
  // modulo the period. Measured by ngspice during characterisation.
  function automatic real golden_phase(input int c);
    case (c)
      0: golden_phase = 9.379975611958e-10;
      1: golden_phase = 9.210192522466e-10;
      2: golden_phase = 8.907282824832e-10;
      3: golden_phase = 8.425102937407e-10;
      4: golden_phase = 6.795150066696e-10;
      5: golden_phase = 5.261261670928e-10;
      6: golden_phase = 4.781095603027e-10;
      7: golden_phase = 4.502590425019e-10;
      8: golden_phase = 4.378960437028e-10;
      default: golden_phase = 0.0;
    endcase
  endfunction

  // The delay line refers every code to the EARLIEST edge, so what the
  // model reproduces is relative phase. The scoreboard compares against
  // the golden with the same reference removed.
  localparam real PHASE_BASE = 4.378960437028e-10;

  class pi_therm_code_item extends uvm_sequence_item;
    int  code;
    real measured_phase;
    `uvm_object_utils(pi_therm_code_item)
    function new(string name = "pi_therm_code_item");
      super.new(name);
    endfunction
  endclass

  // Walk every code in order. Order matters for a delay line: its history
  // buffer carries the previous code's samples, so the settle window below
  // is what keeps one code's answer out of the next one's.
  class pi_therm_code_seq extends uvm_sequence #(pi_therm_code_item);
    `uvm_object_utils(pi_therm_code_seq)
    function new(string name = "pi_therm_code_seq");
      super.new(name);
    endfunction
    virtual task body();
      for (int c = 0; c < NCODE; c++) begin
        pi_therm_code_item it = pi_therm_code_item::type_id::create("it");
        start_item(it);
        it.code = c;
        finish_item(it);
      end
    endtask
  endclass

endpackage : pi_therm_ms_pkg
