`timescale 1fs/1fs
//======================================================================
// pi_therm_bridge_core -- the analog side: clock, DUT, and the
// settle-and-measure cycle the proxy asks for.
//
// Port-less on purpose. Nothing outside needs to wire to this block: the
// stimulus is generated here and the response is read here, so exposing
// the nets would invite a testbench to reach past the proxy -- which is
// the coupling the proxy exists to remove.
//
// THE HANDSHAKE IS SIGNALS, NOT NAMED EVENTS, and the timing runs here
// rather than in a task the proxy calls. A named event triggered through
// an out-of-module reference from class code is not resolved by every
// simulator: one here reported both events as undriven and the run hung
// at time zero. @(posedge) on a bit is the same handshake through a
// construct the DC/AC bridge already relies on.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module pi_therm_bridge_core;

  import pi_therm_ms_types_pkg::*;

  pi_therm_wire ain_net;
  pi_therm_wire aout_net;

  real clk_r = 1.000000;
  assign ain_net = clk_r;
  int  code_sig = 0;

  // Toggled, not levelled: a level would have to be cleared by whoever
  // set it, and that is a second handshake to get wrong.
  bit  meas_req   = 1'b0;
  bit  meas_done  = 1'b0;
  real meas_phase = 0.0;
  int  meas_n     = 0;
  int  meas_code  = 0;

  real vth, prev_v, prev_t, t_now, tc, acc, ref_ph, ph_i, cur;
  int  n_i;

  // Half-period square wave. The DUT is a delay line, so an ideal square
  // is enough to place an edge; the finite-edge subtleties that matter to
  // the CIRCUIT were already handled when its phases were measured.
  initial begin
    forever begin
      #(1000000.000000) clk_r = 0.000000;
      #(1000000.000000) clk_r = 1.000000;
    end
  end

  pi_therm_dms u_dut (
    .ain  (ain_net),
    .code (code_sig),
    .aout (aout_net)
  );

  // Apply a code and ask for a measurement. A function, so the proxy
  // never blocks inside an out-of-module call.
  function automatic void request(input int c);
    code_sig = c;
    meas_req = ~meas_req;
  endfunction

  // Settle, then measure. Crossings are interpolated between samples
  // rather than taken at the sample instant: the model updates on its own
  // step, and rounding an edge to that step would report the step size as
  // phase error.
  always @(meas_req) begin
    meas_code = code_sig;
    // The delay line still holds the previous code's samples; measuring
    // through that handover would score the transition, not the code.
    #(6 * 2.0 * 1000000.000000);
    vth = 0.5 * (1.000000 + 0.000000);
    acc = 0.0; n_i = 0; ref_ph = -1.0;
    prev_v = aout_net; prev_t = $realtime;
    repeat (8 * 400) begin
      #(5000.000000);
      t_now = $realtime;
      cur   = aout_net;
      if (prev_v >= vth && cur < vth && prev_v != cur) begin
        tc   = prev_t + (t_now - prev_t) * ((prev_v - vth) / (prev_v - cur));
        ph_i = tc / 1.0e15;
        ph_i = ph_i - 2.000000000000e-09 * $floor(ph_i / 2.000000000000e-09);
        if (ref_ph < 0.0) ref_ph = ph_i;
        // Unwrap against the first edge, or an edge sitting either side of
        // the period boundary averages into the middle of the cycle.
        if (ph_i - ref_ph > 2.000000000000e-09 * 0.5)      ph_i = ph_i - 2.000000000000e-09;
        else if (ref_ph - ph_i > 2.000000000000e-09 * 0.5) ph_i = ph_i + 2.000000000000e-09;
        acc = acc + ph_i; n_i = n_i + 1;
      end
      prev_v = cur; prev_t = t_now;
    end
    meas_phase = (n_i > 0) ? (acc / real'(n_i)) : 0.0;
    meas_n     = n_i;
    meas_done  = ~meas_done;
  end

endmodule : pi_therm_bridge_core
