`timescale 1fs/1fs
//======================================================================
// pi_therm_proxy_pkg -- the ABSTRACT half of the MS Proxy (clause 4.2.1).
//
// uvm_ms_proxy (Annex A.1) extended with the API between the UVM-MS agent
// and the MS Bridge. The CONCRETE implementation lives inside the bridge
// and is handed to the agent through uvm_config_db as this abstract type.
//
// THE API IS A CODE, NOT A LEVEL. For this block the analog input does
// not vary -- it is a free-running clock -- and what varies is a digital
// code. A push(real) API would make the agent pretend otherwise.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package pi_therm_proxy_pkg;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"

  virtual class pi_therm_proxy extends uvm_ms_proxy;

    function new(string name = "pi_therm_proxy");
      super.new(name);
    endfunction

    // 6.2.4 push -- apply a code and ask for a measurement. Returns at
    // once; the core does the settling and the measuring.
    pure virtual function void push_code(input int c);

    // 6.2.5 push-sync -- block until that measurement has finished.
    pure virtual task wait_measure_done();

    // 6.2.6 pull -- what the core measured.
    pure virtual function int  get_code();
    pure virtual function real get_phase();
    pure virtual function int  get_n_edges();

  endclass : pi_therm_proxy

endpackage : pi_therm_proxy_pkg
