//======================================================================
// pi_therm_ms_test -- run the code sweep, then report.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class pi_therm_ms_test extends uvm_test;
  `uvm_component_utils(pi_therm_ms_test)
  pi_therm_ms_tb tb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    tb = pi_therm_ms_tb::type_id::create("tb", this);
  endfunction

  virtual task run_phase(uvm_phase phase);
    pi_therm_code_seq seq;
    phase.raise_objection(this);
    seq = pi_therm_code_seq::type_id::create("seq");
    seq.start(tb.sqr);
    tb.sb.report_phase();
    phase.drop_objection(this);
  endtask
endclass
