#!/usr/bin/env bash
# UVM-MS PHASE testbench for pi_therm_rnm -- AUTO-GENERATED by spice2rnm (Veylon Systems).
#
# Needs an Icarus build with BOTH UVM support and real-number/UDN support
# (interconnect ports, IEEE 1800-2017 6.6.7 nettypes). Point IVL_PREFIX at it.
#
# Fewer files than the DC/AC environment: there is no MS bridge here,
# because the stimulus is a free-running clock generated in top rather than
# an analog level pushed from the driver. See uvm_ms_phase_codegen.py.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
PREFIX=${IVL_PREFIX:-$HOME/iverilog-unified-local}
UVM=${UVM_SRC:-$HOME/iverilog-unified/uvm-core/src}
UVM_MS=${UVM_MS_LIB:-$HOME/uvm_ms_demo/ms}
IV=$PREFIX/bin/iverilog
VV=$PREFIX/bin/vvp

for t in "$IV" "$VV"; do
  if [ ! -x "$t" ]; then
    echo "ERROR: $t not found or not executable." >&2
    echo "  IVL_PREFIX is currently '$PREFIX'." >&2
    echo "  This testbench needs an Icarus build with BOTH UVM support and" >&2
    echo "  real-number/UDN support (interconnect ports, IEEE 1800-2017 6.6.7)." >&2
    echo "  Re-run as:  IVL_PREFIX=/path/to/that/build $0" >&2
    exit 1
  fi
done
for d in "$UVM/uvm_pkg.sv" "$UVM_MS/uvm_ms_pkg.sv"; do
  [ -f "$d" ] || { echo "ERROR: $d not found (set UVM_SRC / UVM_MS_LIB)." >&2; exit 1; }
done

cd "$ROOT"
rm -f pi_therm_ms.vvp

echo "=== compiling UVM-MS phase testbench for pi_therm_rnm ==="
"$IV" -g2012 -DUVM_NO_DPI \
    -I "$UVM" -I "$UVM_MS" -I "$ROOT" \
    -o pi_therm_ms.vvp \
    "$UVM/uvm_pkg.sv" \
    "$UVM_MS/uvm_ms_pkg.sv" \
    pi_therm_ms_types_pkg.sv \
    pi_therm_rnm.sv \
    pi_therm_dms.sv \
    pi_therm_ms_pkg.sv \
    top_pi_therm_ms.sv || { echo "COMPILE FAILED" >&2; exit 1; }

echo "=== running UVM-MS phase testbench ==="
"$VV" +UVM_NO_RELNOTES pi_therm_ms.vvp "$@"
