`timescale 1fs/1fs
//======================================================================
// top -- UVM-MS testbench for pi_therm_rnm.
//
// The clock and the DUT live in the bridge core, not here: the UVM layer
// reaches them through the MS Proxy, which is what lets the agent stay
// the same whichever core sits behind it.
//
// THE STIMULUS IS A CODE, not a level. The analog input is a
// free-running clock and does not vary, so the proxy API pushes codes.
// A level-pushing API would make the agent pretend otherwise.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module top;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  import pi_therm_ms_types_pkg::*;
  import pi_therm_proxy_pkg::*;
  import pi_therm_ms_pkg::*;

  pi_therm_bridge u_bridge ();

  `include "pi_therm_ms_scoreboard.svh"
  `include "pi_therm_ms_tb.svh"
  `include "pi_therm_ms_test.svh"

  initial begin
    `uvm_ms_info("TOP_MS",
                 "UVM-MS phase testbench for pi_therm_rnm: goldens are ngspice edge measurements",
                 UVM_LOW)
    run_test("pi_therm_ms_test");
  end

endmodule : top
