`timescale 1fs/1fs
//======================================================================
// top -- UVM-MS testbench for pi_therm_rnm.
//
// The stimulus is a free-running clock on the nettype net rather than a
// level pushed through an MS bridge, because for this block the analog
// input is not what varies: the CODE is. Driving a clock through a
// level-pushing bridge would add a layer without adding a check. The
// nettype, the `interconnect` ports and the uvm_ms library are all as
// they are in the DC/AC environment.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module top;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  import pi_therm_ms_types_pkg::*;
  import pi_therm_ms_pkg::*;

  //--- analog nets ----------------------------------------------------
  pi_therm_wire ain_net;
  pi_therm_wire aout_net;

  //--- the clock, and the code under test -----------------------------
  real clk_r = 1.000000;
  assign ain_net = clk_r;
  int  code_sig = 0;

  // Half-period square wave. The DUT is a delay line, so an ideal square
  // is enough to place an edge; the finite-edge subtleties that matter to
  // the CIRCUIT were already handled when its phases were measured.
  initial begin
    forever begin
      #(1000000.000000) clk_r = 0.000000;
      #(1000000.000000) clk_r = 1.000000;
    end
  end

  pi_therm_dms u_dut (
    .ain  (ain_net),
    .code (code_sig),
    .aout (aout_net)
  );

  //--- test ------------------------------------------------------------
  `include "pi_therm_ms_scoreboard.svh"
  `include "pi_therm_ms_tb.svh"
  `include "pi_therm_ms_test.svh"

  initial begin
    `uvm_ms_info("TOP_MS",
                 "UVM-MS phase testbench for pi_therm_rnm: goldens are ngspice edge measurements",
                 UVM_LOW)
    run_test("pi_therm_ms_test");
  end

endmodule : top
