`timescale 1ns/1ps
//======================================================================
// Northgate Semiconductor -- mixed-signal net package.
//
// NOT generated by spice2rnm. This is a small stand-in for a customer's
// EXISTING real-number-model library: the conventions a team already has
// before any model is generated for them.
//
// Everything analog in this library travels on ng_anet. Multiple drivers
// on one net sum, which is what a current-summing node needs.
//======================================================================
package ng_ams_pkg;

  function automatic real ng_sum(input real drivers[]);
    real total = 0.0;
    foreach (drivers[i]) total += drivers[i];
    return total;
  endfunction

  nettype real ng_anet with ng_sum;

  // House convention: analog quantities are volts unless a signal name
  // says otherwise, and every model states its own supply.
  localparam real NG_VDD_NOM = 1.8;

endpackage : ng_ams_pkg
