`timescale 1fs/1fs
// SystemVerilog Real Number Model, auto-generated by spice2rnm (Veylon Systems).
// SCHEDULED-LAG form: dy/dt = wp(in)*(static_curve(in) - y),
// with wp measured at 33 operating points.
//
// Chosen over the node-ODE form because:
//   this block INVERTS. The node ODE relaxes as -g'(V)/TAU with g the
//   inverse of the static curve, so a curve that descends gives an
//   equation reinforcing a departure instead of opposing it -- and an
//   inverting stage has no such node anyway: its input drives a gate,
//   not a series resistance
// schedule spanned 1.388e+11 .. 3.487e+11 rad/s
// rise/fall asymmetry 1.8813 (rise x1.3716, fall x0.7291), from
// the two full-swing traversals of the step schedule
// rise/fall SKEW 1.838e-11 s, as a 0/88 step output delay --
// the measured difference between the two traversals' own
// 50% crossings. Without it this model is symmetric about
// its own threshold and returns exactly 50.000% duty.

module inv2_rnm(input wreal in_val, output wreal out_val);

  // A net cannot be assigned procedurally, so the body computes into
  // this variable and one continuous assignment drives the port --
  // the net/variable step the separate boundary file used to perform.
  real out_val__d;
  assign out_val = out_val__d;

  localparam int  NW = 33;
  localparam real TSTEP = 209.088; // femtoseconds, for #(...) only
  localparam real DT_SECONDS = 2.090875984e-13;
  localparam real DC_BIAS = 1.65;

  real WX [0:NW-1];   // input value
  real WP [0:NW-1];   // measured pole there, rad/s
  initial begin
    WX[0] = 0.0; WP[0] = 1.387775024e+11;
    WX[1] = 0.103125; WP[1] = 1.395612298e+11;
    WX[2] = 0.20625; WP[2] = 1.405534379e+11;
    WX[3] = 0.309375; WP[3] = 1.417232659e+11;
    WX[4] = 0.4125; WP[4] = 1.431939364e+11;
    WX[5] = 0.515625; WP[5] = 1.450707926e+11;
    WX[6] = 0.61875; WP[6] = 1.473299337e+11;
    WX[7] = 0.721875; WP[7] = 1.498756171e+11;
    WX[8] = 0.825; WP[8] = 1.526918932e+11;
    WX[9] = 0.928125; WP[9] = 1.558214115e+11;
    WX[10] = 1.03125; WP[10] = 1.593177638e+11;
    WX[11] = 1.134375; WP[11] = 1.632980324e+11;
    WX[12] = 1.2375; WP[12] = 1.67932784e+11;
    WX[13] = 1.340625; WP[13] = 1.734959221e+11;
    WX[14] = 1.44375; WP[14] = 1.804423949e+11;
    WX[15] = 1.546875; WP[15] = 1.899239314e+11;
    WX[16] = 1.65; WP[16] = 2.097886426e+11;
    WX[17] = 1.753125; WP[17] = 3.48692081e+11;
    WX[18] = 1.85625; WP[18] = 3.270917003e+11;
    WX[19] = 1.959375; WP[19] = 3.138669057e+11;
    WX[20] = 2.0625; WP[20] = 3.045141458e+11;
    WX[21] = 2.165625; WP[21] = 2.969839689e+11;
    WX[22] = 2.26875; WP[22] = 2.90609109e+11;
    WX[23] = 2.371875; WP[23] = 2.851523685e+11;
    WX[24] = 2.475; WP[24] = 2.802624771e+11;
    WX[25] = 2.578125; WP[25] = 2.760277205e+11;
    WX[26] = 2.68125; WP[26] = 2.722335318e+11;
    WX[27] = 2.784375; WP[27] = 2.690246499e+11;
    WX[28] = 2.8875; WP[28] = 2.665394514e+11;
    WX[29] = 2.990625; WP[29] = 2.646523577e+11;
    WX[30] = 3.09375; WP[30] = 2.631166092e+11;
    WX[31] = 3.196875; WP[31] = 2.618443072e+11;
    WX[32] = 3.3; WP[32] = 2.610828529e+11;
  end

  real LUT_X[0:400];
  real LUT_Y[0:400];
  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit lut_loaded;
  function automatic void load_lut();
    LUT_X[0] = 0.0; LUT_Y[0] = 3.29999948;
    LUT_X[1] = 0.00825; LUT_Y[1] = 3.29999936;
    LUT_X[2] = 0.0165; LUT_Y[2] = 3.29999922;
    LUT_X[3] = 0.02475; LUT_Y[3] = 3.29999904;
    LUT_X[4] = 0.033; LUT_Y[4] = 3.29999882;
    LUT_X[5] = 0.04125; LUT_Y[5] = 3.29999856;
    LUT_X[6] = 0.0495; LUT_Y[6] = 3.29999823;
    LUT_X[7] = 0.05775; LUT_Y[7] = 3.29999783;
    LUT_X[8] = 0.066; LUT_Y[8] = 3.29999734;
    LUT_X[9] = 0.07425; LUT_Y[9] = 3.29999674;
    LUT_X[10] = 0.0825; LUT_Y[10] = 3.299996;
    LUT_X[11] = 0.09075; LUT_Y[11] = 3.29999511;
    LUT_X[12] = 0.099; LUT_Y[12] = 3.29999401;
    LUT_X[13] = 0.10725; LUT_Y[13] = 3.29999267;
    LUT_X[14] = 0.1155; LUT_Y[14] = 3.29999104;
    LUT_X[15] = 0.12375; LUT_Y[15] = 3.29998905;
    LUT_X[16] = 0.132; LUT_Y[16] = 3.29998663;
    LUT_X[17] = 0.14025; LUT_Y[17] = 3.29998369;
    LUT_X[18] = 0.1485; LUT_Y[18] = 3.29998012;
    LUT_X[19] = 0.15675; LUT_Y[19] = 3.29997578;
    LUT_X[20] = 0.165; LUT_Y[20] = 3.29997053;
    LUT_X[21] = 0.17325; LUT_Y[21] = 3.29996418;
    LUT_X[22] = 0.1815; LUT_Y[22] = 3.29995649;
    LUT_X[23] = 0.18975; LUT_Y[23] = 3.29994722;
    LUT_X[24] = 0.198; LUT_Y[24] = 3.29993605;
    LUT_X[25] = 0.20625; LUT_Y[25] = 3.29992262;
    LUT_X[26] = 0.2145; LUT_Y[26] = 3.29990647;
    LUT_X[27] = 0.22275; LUT_Y[27] = 3.29988711;
    LUT_X[28] = 0.231; LUT_Y[28] = 3.29986393;
    LUT_X[29] = 0.23925; LUT_Y[29] = 3.29983623;
    LUT_X[30] = 0.2475; LUT_Y[30] = 3.29980319;
    LUT_X[31] = 0.25575; LUT_Y[31] = 3.29976383;
    LUT_X[32] = 0.264; LUT_Y[32] = 3.29971706;
    LUT_X[33] = 0.27225; LUT_Y[33] = 3.29966157;
    LUT_X[34] = 0.2805; LUT_Y[34] = 3.29959589;
    LUT_X[35] = 0.28875; LUT_Y[35] = 3.29951832;
    LUT_X[36] = 0.297; LUT_Y[36] = 3.29942692;
    LUT_X[37] = 0.30525; LUT_Y[37] = 3.29931949;
    LUT_X[38] = 0.3135; LUT_Y[38] = 3.2991936;
    LUT_X[39] = 0.32175; LUT_Y[39] = 3.29904651;
    LUT_X[40] = 0.33; LUT_Y[40] = 3.29887525;
    LUT_X[41] = 0.33825; LUT_Y[41] = 3.29867657;
    LUT_X[42] = 0.3465; LUT_Y[42] = 3.29844702;
    LUT_X[43] = 0.35475; LUT_Y[43] = 3.29818296;
    LUT_X[44] = 0.363; LUT_Y[44] = 3.29788063;
    LUT_X[45] = 0.37125; LUT_Y[45] = 3.29753622;
    LUT_X[46] = 0.3795; LUT_Y[46] = 3.29714594;
    LUT_X[47] = 0.38775; LUT_Y[47] = 3.2967061;
    LUT_X[48] = 0.396; LUT_Y[48] = 3.29621322;
    LUT_X[49] = 0.40425; LUT_Y[49] = 3.29566412;
    LUT_X[50] = 0.4125; LUT_Y[50] = 3.29505595;
    LUT_X[51] = 0.42075; LUT_Y[51] = 3.29438633;
    LUT_X[52] = 0.429; LUT_Y[52] = 3.29365336;
    LUT_X[53] = 0.43725; LUT_Y[53] = 3.29285563;
    LUT_X[54] = 0.4455; LUT_Y[54] = 3.29199229;
    LUT_X[55] = 0.45375; LUT_Y[55] = 3.29106301;
    LUT_X[56] = 0.462; LUT_Y[56] = 3.29006796;
    LUT_X[57] = 0.47025; LUT_Y[57] = 3.28900779;
    LUT_X[58] = 0.4785; LUT_Y[58] = 3.28788354;
    LUT_X[59] = 0.48675; LUT_Y[59] = 3.28669662;
    LUT_X[60] = 0.495; LUT_Y[60] = 3.28544873;
    LUT_X[61] = 0.50325; LUT_Y[61] = 3.2841418;
    LUT_X[62] = 0.5115; LUT_Y[62] = 3.28277792;
    LUT_X[63] = 0.51975; LUT_Y[63] = 3.28135928;
    LUT_X[64] = 0.528; LUT_Y[64] = 3.27988813;
    LUT_X[65] = 0.53625; LUT_Y[65] = 3.27836671;
    LUT_X[66] = 0.5445; LUT_Y[66] = 3.27679723;
    LUT_X[67] = 0.55275; LUT_Y[67] = 3.27518183;
    LUT_X[68] = 0.561; LUT_Y[68] = 3.27352254;
    LUT_X[69] = 0.56925; LUT_Y[69] = 3.27182129;
    LUT_X[70] = 0.5775; LUT_Y[70] = 3.27007986;
    LUT_X[71] = 0.58575; LUT_Y[71] = 3.2682999;
    LUT_X[72] = 0.594; LUT_Y[72] = 3.26648292;
    LUT_X[73] = 0.60225; LUT_Y[73] = 3.26463027;
    LUT_X[74] = 0.6105; LUT_Y[74] = 3.26274318;
    LUT_X[75] = 0.61875; LUT_Y[75] = 3.26082271;
    LUT_X[76] = 0.627; LUT_Y[76] = 3.25886982;
    LUT_X[77] = 0.63525; LUT_Y[77] = 3.25688532;
    LUT_X[78] = 0.6435; LUT_Y[78] = 3.25486991;
    LUT_X[79] = 0.65175; LUT_Y[79] = 3.25282417;
    LUT_X[80] = 0.66; LUT_Y[80] = 3.25074861;
    LUT_X[81] = 0.66825; LUT_Y[81] = 3.24864362;
    LUT_X[82] = 0.6765; LUT_Y[82] = 3.2465095;
    LUT_X[83] = 0.68475; LUT_Y[83] = 3.24434648;
    LUT_X[84] = 0.693; LUT_Y[84] = 3.24215474;
    LUT_X[85] = 0.70125; LUT_Y[85] = 3.23993436;
    LUT_X[86] = 0.7095; LUT_Y[86] = 3.23768538;
    LUT_X[87] = 0.71775; LUT_Y[87] = 3.2354078;
    LUT_X[88] = 0.726; LUT_Y[88] = 3.23310155;
    LUT_X[89] = 0.73425; LUT_Y[89] = 3.23076652;
    LUT_X[90] = 0.7425; LUT_Y[90] = 3.22840258;
    LUT_X[91] = 0.75075; LUT_Y[91] = 3.22600955;
    LUT_X[92] = 0.759; LUT_Y[92] = 3.22358721;
    LUT_X[93] = 0.76725; LUT_Y[93] = 3.22113532;
    LUT_X[94] = 0.7755; LUT_Y[94] = 3.21865363;
    LUT_X[95] = 0.78375; LUT_Y[95] = 3.21614183;
    LUT_X[96] = 0.792; LUT_Y[96] = 3.21359961;
    LUT_X[97] = 0.80025; LUT_Y[97] = 3.21102663;
    LUT_X[98] = 0.8085; LUT_Y[98] = 3.20842254;
    LUT_X[99] = 0.81675; LUT_Y[99] = 3.20578694;
    LUT_X[100] = 0.825; LUT_Y[100] = 3.20311945;
    LUT_X[101] = 0.83325; LUT_Y[101] = 3.20041964;
    LUT_X[102] = 0.8415; LUT_Y[102] = 3.19768707;
    LUT_X[103] = 0.84975; LUT_Y[103] = 3.19492129;
    LUT_X[104] = 0.858; LUT_Y[104] = 3.19212183;
    LUT_X[105] = 0.86625; LUT_Y[105] = 3.18928818;
    LUT_X[106] = 0.8745; LUT_Y[106] = 3.18641985;
    LUT_X[107] = 0.88275; LUT_Y[107] = 3.18351629;
    LUT_X[108] = 0.891; LUT_Y[108] = 3.18057695;
    LUT_X[109] = 0.89925; LUT_Y[109] = 3.17760126;
    LUT_X[110] = 0.9075; LUT_Y[110] = 3.17458864;
    LUT_X[111] = 0.91575; LUT_Y[111] = 3.17153846;
    LUT_X[112] = 0.924; LUT_Y[112] = 3.16845008;
    LUT_X[113] = 0.93225; LUT_Y[113] = 3.16532285;
    LUT_X[114] = 0.9405; LUT_Y[114] = 3.16215609;
    LUT_X[115] = 0.94875; LUT_Y[115] = 3.15894908;
    LUT_X[116] = 0.957; LUT_Y[116] = 3.15570108;
    LUT_X[117] = 0.96525; LUT_Y[117] = 3.15241135;
    LUT_X[118] = 0.9735; LUT_Y[118] = 3.14907908;
    LUT_X[119] = 0.98175; LUT_Y[119] = 3.14570345;
    LUT_X[120] = 0.99; LUT_Y[120] = 3.14228361;
    LUT_X[121] = 0.99825; LUT_Y[121] = 3.13881868;
    LUT_X[122] = 1.0065; LUT_Y[122] = 3.13530773;
    LUT_X[123] = 1.01475; LUT_Y[123] = 3.13174982;
    LUT_X[124] = 1.023; LUT_Y[124] = 3.12814395;
    LUT_X[125] = 1.03125; LUT_Y[125] = 3.12448908;
    LUT_X[126] = 1.0395; LUT_Y[126] = 3.12078415;
    LUT_X[127] = 1.04775; LUT_Y[127] = 3.11702804;
    LUT_X[128] = 1.056; LUT_Y[128] = 3.11321958;
    LUT_X[129] = 1.06425; LUT_Y[129] = 3.10935757;
    LUT_X[130] = 1.0725; LUT_Y[130] = 3.10544074;
    LUT_X[131] = 1.08075; LUT_Y[131] = 3.10146778;
    LUT_X[132] = 1.089; LUT_Y[132] = 3.09743733;
    LUT_X[133] = 1.09725; LUT_Y[133] = 3.09334794;
    LUT_X[134] = 1.1055; LUT_Y[134] = 3.08919814;
    LUT_X[135] = 1.11375; LUT_Y[135] = 3.08498636;
    LUT_X[136] = 1.122; LUT_Y[136] = 3.08071097;
    LUT_X[137] = 1.13025; LUT_Y[137] = 3.07637028;
    LUT_X[138] = 1.1385; LUT_Y[138] = 3.07196251;
    LUT_X[139] = 1.14675; LUT_Y[139] = 3.06748579;
    LUT_X[140] = 1.155; LUT_Y[140] = 3.06293818;
    LUT_X[141] = 1.16325; LUT_Y[141] = 3.05831763;
    LUT_X[142] = 1.1715; LUT_Y[142] = 3.05362201;
    LUT_X[143] = 1.17975; LUT_Y[143] = 3.04884908;
    LUT_X[144] = 1.188; LUT_Y[144] = 3.04399647;
    LUT_X[145] = 1.19625; LUT_Y[145] = 3.0390617;
    LUT_X[146] = 1.2045; LUT_Y[146] = 3.03404218;
    LUT_X[147] = 1.21275; LUT_Y[147] = 3.02893517;
    LUT_X[148] = 1.221; LUT_Y[148] = 3.02373778;
    LUT_X[149] = 1.22925; LUT_Y[149] = 3.01844696;
    LUT_X[150] = 1.2375; LUT_Y[150] = 3.01305952;
    LUT_X[151] = 1.24575; LUT_Y[151] = 3.00757207;
    LUT_X[152] = 1.254; LUT_Y[152] = 3.00198101;
    LUT_X[153] = 1.26225; LUT_Y[153] = 2.99628257;
    LUT_X[154] = 1.2705; LUT_Y[154] = 2.99047273;
    LUT_X[155] = 1.27875; LUT_Y[155] = 2.98454723;
    LUT_X[156] = 1.287; LUT_Y[156] = 2.97850156;
    LUT_X[157] = 1.29525; LUT_Y[157] = 2.97233089;
    LUT_X[158] = 1.3035; LUT_Y[158] = 2.96603013;
    LUT_X[159] = 1.31175; LUT_Y[159] = 2.95959381;
    LUT_X[160] = 1.32; LUT_Y[160] = 2.95301611;
    LUT_X[161] = 1.32825; LUT_Y[161] = 2.9462908;
    LUT_X[162] = 1.3365; LUT_Y[162] = 2.93941121;
    LUT_X[163] = 1.34475; LUT_Y[163] = 2.93237019;
    LUT_X[164] = 1.353; LUT_Y[164] = 2.92516004;
    LUT_X[165] = 1.36125; LUT_Y[165] = 2.91777247;
    LUT_X[166] = 1.3695; LUT_Y[166] = 2.91019854;
    LUT_X[167] = 1.37775; LUT_Y[167] = 2.90242859;
    LUT_X[168] = 1.386; LUT_Y[168] = 2.89445212;
    LUT_X[169] = 1.39425; LUT_Y[169] = 2.88625774;
    LUT_X[170] = 1.4025; LUT_Y[170] = 2.87783304;
    LUT_X[171] = 1.41075; LUT_Y[171] = 2.86916445;
    LUT_X[172] = 1.419; LUT_Y[172] = 2.86023711;
    LUT_X[173] = 1.42725; LUT_Y[173] = 2.85103465;
    LUT_X[174] = 1.4355; LUT_Y[174] = 2.84153905;
    LUT_X[175] = 1.44375; LUT_Y[175] = 2.83173033;
    LUT_X[176] = 1.452; LUT_Y[176] = 2.82158627;
    LUT_X[177] = 1.46025; LUT_Y[177] = 2.81108206;
    LUT_X[178] = 1.4685; LUT_Y[178] = 2.80018985;
    LUT_X[179] = 1.47675; LUT_Y[179] = 2.78887823;
    LUT_X[180] = 1.485; LUT_Y[180] = 2.77711156;
    LUT_X[181] = 1.49325; LUT_Y[181] = 2.76484917;
    LUT_X[182] = 1.5015; LUT_Y[182] = 2.75204428;
    LUT_X[183] = 1.50975; LUT_Y[183] = 2.73864273;
    LUT_X[184] = 1.518; LUT_Y[184] = 2.72458129;
    LUT_X[185] = 1.52625; LUT_Y[185] = 2.7097854;
    LUT_X[186] = 1.5345; LUT_Y[186] = 2.69416628;
    LUT_X[187] = 1.54275; LUT_Y[187] = 2.67761698;
    LUT_X[188] = 1.551; LUT_Y[188] = 2.66000706;
    LUT_X[189] = 1.55925; LUT_Y[189] = 2.64117517;
    LUT_X[190] = 1.5675; LUT_Y[190] = 2.62091884;
    LUT_X[191] = 1.57575; LUT_Y[191] = 2.59898017;
    LUT_X[192] = 1.584; LUT_Y[192] = 2.57502638;
    LUT_X[193] = 1.59225; LUT_Y[193] = 2.54862516;
    LUT_X[194] = 1.6005; LUT_Y[194] = 2.51922049;
    LUT_X[195] = 1.60875; LUT_Y[195] = 2.48613193;
    LUT_X[196] = 1.617; LUT_Y[196] = 2.44863656;
    LUT_X[197] = 1.62525; LUT_Y[197] = 2.40620496;
    LUT_X[198] = 1.6335; LUT_Y[198] = 2.35879665;
    LUT_X[199] = 1.64175; LUT_Y[199] = 2.30687414;
    LUT_X[200] = 1.65; LUT_Y[200] = 2.25109129;
    LUT_X[201] = 1.65825; LUT_Y[201] = 2.19204815;
    LUT_X[202] = 1.6665; LUT_Y[202] = 2.13024859;
    LUT_X[203] = 1.67475; LUT_Y[203] = 2.06613477;
    LUT_X[204] = 1.683; LUT_Y[204] = 2.0001183;
    LUT_X[205] = 1.69125; LUT_Y[205] = 1.93259632;
    LUT_X[206] = 1.6995; LUT_Y[206] = 1.86395792;
    LUT_X[207] = 1.70775; LUT_Y[207] = 1.79458639;
    LUT_X[208] = 1.716; LUT_Y[208] = 1.72486;
    LUT_X[209] = 1.72425; LUT_Y[209] = 1.65515245;
    LUT_X[210] = 1.7325; LUT_Y[210] = 1.58583315;
    LUT_X[211] = 1.74075; LUT_Y[211] = 1.51726712;
    LUT_X[212] = 1.749; LUT_Y[212] = 1.44981403;
    LUT_X[213] = 1.75725; LUT_Y[213] = 1.38382602;
    LUT_X[214] = 1.7655; LUT_Y[214] = 1.31964381;
    LUT_X[215] = 1.77375; LUT_Y[215] = 1.25759093;
    LUT_X[216] = 1.782; LUT_Y[216] = 1.19796606;
    LUT_X[217] = 1.79025; LUT_Y[217] = 1.14103396;
    LUT_X[218] = 1.7985; LUT_Y[218] = 1.08701584;
    LUT_X[219] = 1.80675; LUT_Y[219] = 1.03608066;
    LUT_X[220] = 1.815; LUT_Y[220] = 0.988338794;
    LUT_X[221] = 1.82325; LUT_Y[221] = 0.943839919;
    LUT_X[222] = 1.8315; LUT_Y[222] = 0.902575503;
    LUT_X[223] = 1.83975; LUT_Y[223] = 0.864484219;
    LUT_X[224] = 1.848; LUT_Y[224] = 0.829454576;
    LUT_X[225] = 1.85625; LUT_Y[225] = 0.797319816;
    LUT_X[226] = 1.8645; LUT_Y[226] = 0.767852201;
    LUT_X[227] = 1.87275; LUT_Y[227] = 0.740774372;
    LUT_X[228] = 1.881; LUT_Y[228] = 0.715790831;
    LUT_X[229] = 1.88925; LUT_Y[229] = 0.692620974;
    LUT_X[230] = 1.8975; LUT_Y[230] = 0.671018091;
    LUT_X[231] = 1.90575; LUT_Y[231] = 0.650774083;
    LUT_X[232] = 1.914; LUT_Y[232] = 0.631716401;
    LUT_X[233] = 1.92225; LUT_Y[233] = 0.613702424;
    LUT_X[234] = 1.9305; LUT_Y[234] = 0.59661381;
    LUT_X[235] = 1.93875; LUT_Y[235] = 0.580351669;
    LUT_X[236] = 1.947; LUT_Y[236] = 0.564832677;
    LUT_X[237] = 1.95525; LUT_Y[237] = 0.549986034;
    LUT_X[238] = 1.9635; LUT_Y[238] = 0.535751092;
    LUT_X[239] = 1.97175; LUT_Y[239] = 0.522075493;
    LUT_X[240] = 1.98; LUT_Y[240] = 0.50891372;
    LUT_X[241] = 1.98825; LUT_Y[241] = 0.496225934;
    LUT_X[242] = 1.9965; LUT_Y[242] = 0.483977061;
    LUT_X[243] = 2.00475; LUT_Y[243] = 0.472136047;
    LUT_X[244] = 2.013; LUT_Y[244] = 0.460675252;
    LUT_X[245] = 2.02125; LUT_Y[245] = 0.449569965;
    LUT_X[246] = 2.0295; LUT_Y[246] = 0.438797993;
    LUT_X[247] = 2.03775; LUT_Y[247] = 0.428339324;
    LUT_X[248] = 2.046; LUT_Y[248] = 0.418175847;
    LUT_X[249] = 2.05425; LUT_Y[249] = 0.408291112;
    LUT_X[250] = 2.0625; LUT_Y[250] = 0.398670134;
    LUT_X[251] = 2.07075; LUT_Y[251] = 0.389299217;
    LUT_X[252] = 2.079; LUT_Y[252] = 0.380165809;
    LUT_X[253] = 2.08725; LUT_Y[253] = 0.371258381;
    LUT_X[254] = 2.0955; LUT_Y[254] = 0.36256631;
    LUT_X[255] = 2.10375; LUT_Y[255] = 0.354079793;
    LUT_X[256] = 2.112; LUT_Y[256] = 0.345789759;
    LUT_X[257] = 2.12025; LUT_Y[257] = 0.337687799;
    LUT_X[258] = 2.1285; LUT_Y[258] = 0.329766105;
    LUT_X[259] = 2.13675; LUT_Y[259] = 0.322017411;
    LUT_X[260] = 2.145; LUT_Y[260] = 0.314434945;
    LUT_X[261] = 2.15325; LUT_Y[261] = 0.307012387;
    LUT_X[262] = 2.1615; LUT_Y[262] = 0.299743828;
    LUT_X[263] = 2.16975; LUT_Y[263] = 0.292623736;
    LUT_X[264] = 2.178; LUT_Y[264] = 0.285646926;
    LUT_X[265] = 2.18625; LUT_Y[265] = 0.27880853;
    LUT_X[266] = 2.1945; LUT_Y[266] = 0.272103975;
    LUT_X[267] = 2.20275; LUT_Y[267] = 0.265528958;
    LUT_X[268] = 2.211; LUT_Y[268] = 0.259079426;
    LUT_X[269] = 2.21925; LUT_Y[269] = 0.252751559;
    LUT_X[270] = 2.2275; LUT_Y[270] = 0.246541752;
    LUT_X[271] = 2.23575; LUT_Y[271] = 0.240446601;
    LUT_X[272] = 2.244; LUT_Y[272] = 0.234462889;
    LUT_X[273] = 2.25225; LUT_Y[273] = 0.22858757;
    LUT_X[274] = 2.2605; LUT_Y[274] = 0.222817765;
    LUT_X[275] = 2.26875; LUT_Y[275] = 0.217150745;
    LUT_X[276] = 2.277; LUT_Y[276] = 0.211583925;
    LUT_X[277] = 2.28525; LUT_Y[277] = 0.206114855;
    LUT_X[278] = 2.2935; LUT_Y[278] = 0.200741214;
    LUT_X[279] = 2.30175; LUT_Y[279] = 0.195460801;
    LUT_X[280] = 2.31; LUT_Y[280] = 0.190271536;
    LUT_X[281] = 2.31825; LUT_Y[281] = 0.185171451;
    LUT_X[282] = 2.3265; LUT_Y[282] = 0.180158695;
    LUT_X[283] = 2.33475; LUT_Y[283] = 0.175231539;
    LUT_X[284] = 2.343; LUT_Y[284] = 0.17038839;
    LUT_X[285] = 2.35125; LUT_Y[285] = 0.16562782;
    LUT_X[286] = 2.3595; LUT_Y[286] = 0.160948628;
    LUT_X[287] = 2.36775; LUT_Y[287] = 0.156349946;
    LUT_X[288] = 2.376; LUT_Y[288] = 0.151831381;
    LUT_X[289] = 2.38425; LUT_Y[289] = 0.147393009;
    LUT_X[290] = 2.3925; LUT_Y[290] = 0.143034724;
    LUT_X[291] = 2.40075; LUT_Y[291] = 0.138755056;
    LUT_X[292] = 2.409; LUT_Y[292] = 0.134551192;
    LUT_X[293] = 2.41725; LUT_Y[293] = 0.130420237;
    LUT_X[294] = 2.4255; LUT_Y[294] = 0.126359899;
    LUT_X[295] = 2.43375; LUT_Y[295] = 0.122368454;
    LUT_X[296] = 2.442; LUT_Y[296] = 0.118444541;
    LUT_X[297] = 2.45025; LUT_Y[297] = 0.114587027;
    LUT_X[298] = 2.4585; LUT_Y[298] = 0.110794925;
    LUT_X[299] = 2.46675; LUT_Y[299] = 0.107067353;
    LUT_X[300] = 2.475; LUT_Y[300] = 0.10340351;
    LUT_X[301] = 2.48325; LUT_Y[301] = 0.0998026633;
    LUT_X[302] = 2.4915; LUT_Y[302] = 0.0962641417;
    LUT_X[303] = 2.49975; LUT_Y[303] = 0.0927873314;
    LUT_X[304] = 2.508; LUT_Y[304] = 0.0893716742;
    LUT_X[305] = 2.51625; LUT_Y[305] = 0.0860166671;
    LUT_X[306] = 2.5245; LUT_Y[306] = 0.0827218625;
    LUT_X[307] = 2.53275; LUT_Y[307] = 0.0794868696;
    LUT_X[308] = 2.541; LUT_Y[308] = 0.0763113562;
    LUT_X[309] = 2.54925; LUT_Y[309] = 0.0731950506;
    LUT_X[310] = 2.5575; LUT_Y[310] = 0.0701377448;
    LUT_X[311] = 2.56575; LUT_Y[311] = 0.0671392973;
    LUT_X[312] = 2.574; LUT_Y[312] = 0.0641996368;
    LUT_X[313] = 2.58225; LUT_Y[313] = 0.0613187661;
    LUT_X[314] = 2.5905; LUT_Y[314] = 0.0584967662;
    LUT_X[315] = 2.59875; LUT_Y[315] = 0.0557338004;
    LUT_X[316] = 2.607; LUT_Y[316] = 0.053030119;
    LUT_X[317] = 2.61525; LUT_Y[317] = 0.0503860637;
    LUT_X[318] = 2.6235; LUT_Y[318] = 0.0478020717;
    LUT_X[319] = 2.63175; LUT_Y[319] = 0.0452786794;
    LUT_X[320] = 2.64; LUT_Y[320] = 0.0428165263;
    LUT_X[321] = 2.64825; LUT_Y[321] = 0.0404163568;
    LUT_X[322] = 2.6565; LUT_Y[322] = 0.0380790219;
    LUT_X[323] = 2.66475; LUT_Y[323] = 0.0358054788;
    LUT_X[324] = 2.673; LUT_Y[324] = 0.0335967886;
    LUT_X[325] = 2.68125; LUT_Y[325] = 0.0314541119;
    LUT_X[326] = 2.6895; LUT_Y[326] = 0.029378701;
    LUT_X[327] = 2.69775; LUT_Y[327] = 0.0273718892;
    LUT_X[328] = 2.706; LUT_Y[328] = 0.0254350756;
    LUT_X[329] = 2.71425; LUT_Y[329] = 0.0235697056;
    LUT_X[330] = 2.7225; LUT_Y[330] = 0.0217772468;
    LUT_X[331] = 2.73075; LUT_Y[331] = 0.020059159;
    LUT_X[332] = 2.739; LUT_Y[332] = 0.0184168595;
    LUT_X[333] = 2.74725; LUT_Y[333] = 0.0168516828;
    LUT_X[334] = 2.7555; LUT_Y[334] = 0.0153648346;
    LUT_X[335] = 2.76375; LUT_Y[335] = 0.0139573432;
    LUT_X[336] = 2.772; LUT_Y[336] = 0.0126300063;
    LUT_X[337] = 2.78025; LUT_Y[337] = 0.011383337;
    LUT_X[338] = 2.7885; LUT_Y[338] = 0.0102175106;
    LUT_X[339] = 2.79675; LUT_Y[339] = 0.00913231414;
    LUT_X[340] = 2.805; LUT_Y[340] = 0.00812710188;
    LUT_X[341] = 2.81325; LUT_Y[341] = 0.00720075998;
    LUT_X[342] = 2.8215; LUT_Y[342] = 0.00635168264;
    LUT_X[343] = 2.82975; LUT_Y[343] = 0.0055777628;
    LUT_X[344] = 2.838; LUT_Y[344] = 0.00487639936;
    LUT_X[345] = 2.84625; LUT_Y[345] = 0.00424452199;
    LUT_X[346] = 2.8545; LUT_Y[346] = 0.00367863374;
    LUT_X[347] = 2.86275; LUT_Y[347] = 0.00317487021;
    LUT_X[348] = 2.871; LUT_Y[348] = 0.00272907303;
    LUT_X[349] = 2.87925; LUT_Y[349] = 0.0023368739;
    LUT_X[350] = 2.8875; LUT_Y[350] = 0.00199378487;
    LUT_X[351] = 2.89575; LUT_Y[351] = 0.00169528993;
    LUT_X[352] = 2.904; LUT_Y[352] = 0.00143693277;
    LUT_X[353] = 2.91225; LUT_Y[353] = 0.00121439633;
    LUT_X[354] = 2.9205; LUT_Y[354] = 0.00102357034;
    LUT_X[355] = 2.92875; LUT_Y[355] = 0.000860604437;
    LUT_X[356] = 2.937; LUT_Y[356] = 0.000721945619;
    LUT_X[357] = 2.94525; LUT_Y[357] = 0.000604360335;
    LUT_X[358] = 2.9535; LUT_Y[358] = 0.000504942377;
    LUT_X[359] = 2.96175; LUT_Y[359] = 0.000421108752;
    LUT_X[360] = 2.97; LUT_Y[360] = 0.000350586108;
    LUT_X[361] = 2.97825; LUT_Y[361] = 0.000291390413;
    LUT_X[362] = 2.9865; LUT_Y[362] = 0.000241802443;
    LUT_X[363] = 2.99475; LUT_Y[363] = 0.00020034125;
    LUT_X[364] = 3.003; LUT_Y[364] = 0.000165737342;
    LUT_X[365] = 3.01125; LUT_Y[365] = 0.00013690681;
    LUT_X[366] = 3.0195; LUT_Y[366] = 0.000112927218;
    LUT_X[367] = 3.02775; LUT_Y[367] = 9.30156846e-05;
    LUT_X[368] = 3.036; LUT_Y[368] = 7.65093253e-05;
    LUT_X[369] = 3.04425; LUT_Y[369] = 6.28480476e-05;
    LUT_X[370] = 3.0525; LUT_Y[370] = 5.15595482e-05;
    LUT_X[371] = 3.06075; LUT_Y[371] = 4.22463235e-05;
    LUT_X[372] = 3.069; LUT_Y[372] = 3.45744716e-05;
    LUT_X[373] = 3.07725; LUT_Y[373] = 2.82640677e-05;
    LUT_X[374] = 3.0855; LUT_Y[374] = 2.30809087e-05;
    LUT_X[375] = 3.09375; LUT_Y[375] = 1.88294437e-05;
    LUT_X[376] = 3.102; LUT_Y[376] = 1.53467302e-05;
    LUT_X[377] = 3.11025; LUT_Y[377] = 1.24972749e-05;
    LUT_X[378] = 3.1185; LUT_Y[378] = 1.0168638e-05;
    LUT_X[379] = 3.12675; LUT_Y[379] = 8.26769613e-06;
    LUT_X[380] = 3.135; LUT_Y[380] = 6.71747294e-06;
    LUT_X[381] = 3.14325; LUT_Y[381] = 5.45445723e-06;
    LUT_X[382] = 3.1515; LUT_Y[382] = 4.42634056e-06;
    LUT_X[383] = 3.15975; LUT_Y[383] = 3.59011371e-06;
    LUT_X[384] = 3.168; LUT_Y[384] = 2.9104696e-06;
    LUT_X[385] = 3.17625; LUT_Y[385] = 2.35846708e-06;
    LUT_X[386] = 3.1845; LUT_Y[386] = 1.91041609e-06;
    LUT_X[387] = 3.19275; LUT_Y[387] = 1.54694992e-06;
    LUT_X[388] = 3.201; LUT_Y[388] = 1.2522551e-06;
    LUT_X[389] = 3.20925; LUT_Y[389] = 1.01343375e-06;
    LUT_X[390] = 3.2175; LUT_Y[390] = 8.19976609e-07;
    LUT_X[391] = 3.22575; LUT_Y[391] = 6.633287e-07;
    LUT_X[392] = 3.234; LUT_Y[392] = 5.36531801e-07;
    LUT_X[393] = 3.24225; LUT_Y[393] = 4.33930823e-07;
    LUT_X[394] = 3.2505; LUT_Y[394] = 3.50933016e-07;
    LUT_X[395] = 3.25875; LUT_Y[395] = 2.83810804e-07;
    LUT_X[396] = 3.267; LUT_Y[396] = 2.29540577e-07;
    LUT_X[397] = 3.27525; LUT_Y[397] = 1.85671047e-07;
    LUT_X[398] = 3.2835; LUT_Y[398] = 1.50215877e-07;
    LUT_X[399] = 3.29175; LUT_Y[399] = 1.21566186e-07;
    LUT_X[400] = 3.3; LUT_Y[400] = 9.84193439e-08;
    lut_loaded = 1'b1;
  endfunction
  function automatic real static_curve(input real xin);
    integer lo, hi, mid;
    real xc;
    begin
      if (!lut_loaded) load_lut();
      xc = (xin < LUT_X[0]) ? LUT_X[0] : ((xin > LUT_X[400]) ? LUT_X[400] : xin);
      lo = 0;
      hi = 400;
      while (hi - lo > 1) begin
        mid = (lo + hi) / 2;
        if (xc < LUT_X[mid]) hi = mid; else lo = mid;
      end
      static_curve = (LUT_X[hi] == LUT_X[lo])
                   ? LUT_Y[lo]
                   : LUT_Y[lo] + (LUT_Y[hi]-LUT_Y[lo]) * (xc-LUT_X[lo]) / (LUT_X[hi]-LUT_X[lo]);
    end
  endfunction

  // Rate at this input, linearly interpolated between measured
  // points and CLAMPED outside them -- extrapolating a rate is
  // how a schedule produces a negative or absurd pole.
  function automatic real wp_of(input real xin);
    int i;
    real t;
    begin
      if (xin <= WX[0]) wp_of = WP[0];
      else if (xin >= WX[NW-1]) wp_of = WP[NW-1];
      else begin
        wp_of = WP[NW-1];
        for (i = 0; i < NW-1; i++) begin
          if (xin >= WX[i] && xin <= WX[i+1]) begin
            t = (WX[i+1] == WX[i]) ? 0.0 : (xin - WX[i]) / (WX[i+1] - WX[i]);
            wp_of = WP[i] + t * (WP[i+1] - WP[i]);
          end
        end
      end
    end
  endfunction

  // Direction-dependent output delay, in integration steps.
  // Only the DIFFERENCE between the directions changes duty,
  // so the faster one carries zero. The block's COMMON
  // propagation delay is not modelled: it moves both edges
  // together and leaves every duty unchanged.
  localparam int ND_RISE = 0;
  localparam int ND_FALL = 88;
  localparam int NDEPTH  = 90;
  real dbuf [0:NDEPTH-1];
  int  dhead, dtap;
  bit  dir_up;
  real yprev;

  // Measured rise/fall asymmetry. wp is indexed by the input
  // alone, which gives the same rate whichever way the output
  // is going -- and a model that is symmetric about its own
  // threshold returns exactly 50.000% duty for a 50% input,
  // whatever the circuit does. These come from the schedule's
  // two full-swing traversals and multiply to 1.
  localparam real K_RISE = 1.371606837;
  localparam real K_FALL = 0.7290718979;

  real y, tgt, w;
  bit  primed;
  initial begin
    y = static_curve(DC_BIAS);
    primed = 1'b0;
    for (int i = 0; i < NDEPTH; i++) dbuf[i] = y;
    dhead = 0; dir_up = 1'b0; yprev = y;
  end

  always #(TSTEP) begin : lag_step
    real dt, k1, k2, k3, k4;
    dt = DT_SECONDS;
    // Open at the DC solution for the stimulus's OWN first
    // value, which is what SPICE's t=0 operating point solves.
    if (!primed) begin
      y = static_curve(in_val);
      primed = 1'b1;
    end
    // The target and the rate are both functions of the INPUT,
    // so they are constant across the four RK4 stages; only y
    // advances. That keeps the step explicit and cheap.
    tgt = static_curve(in_val);
    // Direction is decided once per step, from the sign of
    // the error, and held across the four RK4 stages -- the
    // same treatment tgt and w already get.
    w   = wp_of(in_val) * ((tgt > y) ? K_RISE : K_FALL);
    k1  = w * (tgt - y);
    k2  = w * (tgt - (y + 0.5*dt*k1));
    k3  = w * (tgt - (y + 0.5*dt*k2));
    k4  = w * (tgt - (y + dt*k3));
    y   = y + (dt/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4);
    // Direction is LATCHED: it changes only when the output
    // actually moves, so the tap is stable through a
    // transition, and the flat regions -- where every history
    // sample is equal anyway -- cannot flip it.
    if (y > yprev + 1.0e-9)      dir_up = 1'b1;
    else if (y < yprev - 1.0e-9) dir_up = 1'b0;
    yprev = y;
    dbuf[dhead] = y;
    dtap = dhead - (dir_up ? ND_RISE : ND_FALL);
    while (dtap < 0) dtap = dtap + NDEPTH;
    while (dtap >= NDEPTH) dtap = dtap - NDEPTH;
    out_val__d = dbuf[dtap];
    dhead = (dhead + 1) % NDEPTH;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.0;
  localparam real DOMAIN_HI  = 3.3;
  localparam real DOMAIN_EPS = 0.066; // 2% of the span, see model_assertions.py
  bit domain_reported = 1'b0;

  always @(in_val) begin : domain_check
    a_input_domain: assert (in_val >= DOMAIN_LO - DOMAIN_EPS && in_val <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. static_curve clamps there, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               in_val, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit nan_reported = 1'b0;

  always @(out_val) begin : output_health
    // NaN is the one value that is not equal to itself.
    a_output_finite: assert (out_val == out_val)
    else if (!nan_reported) begin
      nan_reported = 1'b1;
      $error("%m: output is NaN -- the integration diverged. Reported once.");
    end
  end
`endif

endmodule
