`timescale 1fs/1fs
//======================================================================
// inv1_ms_pkg -- the mixed-signal agent for inv1_rnm.
//
// Item / driver / monitor / agent / sequencer / sequences.  The golden
// table lives here too, so the sequence item and the scoreboard read the
// same numbers.
//
// THE GOLDEN TABLE IS NGSPICE DATA, not the fitted transfer function.
// Checking the model against the fit would be checking it against the
// equations it implements -- it would pass unconditionally and mean
// nothing.  GOLD_X/GOLD_Y are 41 operating points measured from
// the circuit during characterization.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package inv1_ms_pkg;

  import uvm_pkg::*;
  import inv1_proxy_pkg::*;
  `include "uvm_macros.svh"

  //--------------------------------------------------------------------
  // Golden operating points, measured by ngspice during characterization.
  //
  // Emitted as case-statement functions rather than unpacked real array
  // parameters: this compiler accepts a CONSTANT index into a real array
  // parameter but rejects a variable one ("Variable index into array
  // parameter requires integral elements"), and every use here is
  // variable-indexed.
  //--------------------------------------------------------------------
  localparam int GOLD_N = 41;

  function automatic real gold_x(input int idx);
    case (idx)
      0: gold_x = 0.0;
      1: gold_x = 0.0882121;
      2: gold_x = 0.1764242;
      3: gold_x = 0.2646363;
      4: gold_x = 0.3528484;
      5: gold_x = 0.4410605;
      6: gold_x = 0.5292726;
      7: gold_x = 0.6174847;
      8: gold_x = 0.7056968;
      9: gold_x = 0.7939089;
      10: gold_x = 0.882121;
      11: gold_x = 0.9703331;
      12: gold_x = 1.0585452;
      13: gold_x = 1.1467573;
      14: gold_x = 1.2349694;
      15: gold_x = 1.3231815;
      16: gold_x = 1.4113936;
      17: gold_x = 1.4996057;
      18: gold_x = 1.5878178;
      19: gold_x = 1.6760299;
      20: gold_x = 1.764242;
      21: gold_x = 1.8524541;
      22: gold_x = 1.9406662;
      23: gold_x = 2.0288783;
      24: gold_x = 2.1170904;
      25: gold_x = 2.2053025;
      26: gold_x = 2.2935146;
      27: gold_x = 2.3817267;
      28: gold_x = 2.4699388;
      29: gold_x = 2.5581509;
      30: gold_x = 2.646363;
      31: gold_x = 2.7345751;
      32: gold_x = 2.8227872;
      33: gold_x = 2.9109993;
      34: gold_x = 2.9992114;
      35: gold_x = 3.0874235;
      36: gold_x = 3.1756356;
      37: gold_x = 3.2638477;
      38: gold_x = 3.3520598;
      39: gold_x = 3.4402719;
      40: gold_x = 3.528484;
      default: gold_x = 0.0;
    endcase
  endfunction

  function automatic real gold_y(input int idx);
    case (idx)
      0: gold_y = 3.29999946;
      1: gold_y = 3.29999522;
      2: gold_y = 3.29996003;
      3: gold_y = 3.2997052;
      4: gold_y = 3.29822067;
      5: gold_y = 3.29251499;
      6: gold_y = 3.28020342;
      7: gold_y = 3.26264109;
      8: gold_y = 3.24154586;
      9: gold_y = 3.21738184;
      10: gold_y = 3.18994002;
      11: gold_y = 3.15871881;
      12: gold_y = 3.12296474;
      13: gold_y = 3.0815589;
      14: gold_y = 3.03277492;
      15: gold_y = 2.97378648;
      16: gold_y = 2.89951382;
      17: gold_y = 2.79923943;
      18: gold_y = 2.64153082;
      19: gold_y = 2.24779647;
      20: gold_y = 1.53179617;
      21: gold_y = 0.926452331;
      22: gold_y = 0.631945279;
      23: gold_y = 0.475113398;
      24: gold_y = 0.365812826;
      25: gold_y = 0.281699677;
      26: gold_y = 0.213938477;
      27: gold_y = 0.158154126;
      28: gold_y = 0.112090639;
      29: gold_y = 0.0739914873;
      30: gold_y = 0.0432228827;
      31: gold_y = 0.020254617;
      32: gold_y = 0.00649032014;
      33: gold_y = 0.00129007213;
      34: gold_y = 0.00018661299;
      35: gold_y = 2.26650368e-05;
      36: gold_y = 2.46650068e-06;
      37: gold_y = 2.58915017e-07;
      38: gold_y = 3.02486423e-08;
      39: gold_y = 6.99158748e-09;
      40: gold_y = 4.6236457e-09;
      default: gold_y = 0.0;
    endcase
  endfunction

  // Absolute tolerance on the response, in volts.  Derived at generation
  // time from the DC fit residual and the measured output span, so it
  // tracks how well the model actually fit rather than being a guess.
  localparam real TOL_ABS = 0.00659999891;

  //--------------------------------------------------------------------
  // Golden AC points, also measured by ngspice (the .ac analysis), not
  // evaluated from the fitted transfer function.
  //
  // AC_N == 0 means no AC check was generated -- either the
  // characterization had no usable AC data, or the model has no poles
  // and so has no frequency response to check.
  //
  // The excitation is SMALL-SIGNAL about the DC bias (AC_AMPL below).
  // It has to be: the RNM is a static nonlinear curve plus a linear
  // dynamic path, and ngspice's .ac golden is the linearization at the
  // bias point. A large-signal swing would traverse the static curve and
  // legitimately disagree.
  //--------------------------------------------------------------------
  localparam int  AC_N     = 0;
  localparam real AC_AMPL  = 0.00659999891;
  localparam real AC_BIAS  = 1.76424278;
  localparam real TOL_DB   = 0.914251048;
  localparam real TOL_DEG  = 8;

  function automatic real ac_freq(input int idx);
    case (idx)
      default: ac_freq = 0.0;
    endcase
  endfunction

  function automatic real ac_mag_db(input int idx);
    case (idx)
      default: ac_mag_db = 0.0;
    endcase
  endfunction

  function automatic real ac_phase_deg(input int idx);
    case (idx)
      default: ac_phase_deg = 0.0;
    endcase
  endfunction

  //--------------------------------------------------------------------
  // Golden DUTY points, measured by ngspice transient runs.
  //
  // What the block DOES to duty: drive a clock of a known input duty and
  // record the duty that comes out. For a clock-path block this is the
  // function, and neither the DC sweep nor the AC linearization
  // describes it.
  //
  // DUTY_VTH is per point and is ngspice's own output midpoint for that
  // run, frozen here. The model is sliced at a number it cannot move.
  //
  // DUTY_N == 0 means no duty golden was generated: either the block is
  // not clock-like, or no point produced complete cycles.
  //--------------------------------------------------------------------
  localparam int  DUTY_N       = 0;
  localparam real DUTY_VLO     = 0;
  localparam real DUTY_VHI     = 0;
  localparam real TOL_DUTY_PP  = 0.5;

  function automatic real duty_freq(input int idx);
    case (idx)
      default: duty_freq = 0.0;
    endcase
  endfunction

  function automatic real duty_in(input int idx);
    case (idx)
      default: duty_in = 0.0;
    endcase
  endfunction

  function automatic real duty_gold(input int idx);
    case (idx)
      default: duty_gold = 0.0;
    endcase
  endfunction

  function automatic real duty_vth(input int idx);
    case (idx)
      default: duty_vth = 0.0;
    endcase
  endfunction

  //--------------------------------------------------------------------
  // CLASS: inv1_ms_transaction
  //
  // One analog operating point.  The stimulus is an INDEX into the golden
  // table rather than a `rand real` level: IEEE 1800-2017 18.4 restricts
  // rand to integral types (real rand is an 1800-2023 addition), and
  // indexing also guarantees every randomized stimulus has a golden to
  // check against.
  //--------------------------------------------------------------------
  typedef enum { OP_DC, OP_AC, OP_DUTY } op_kind_e;

  class inv1_ms_transaction extends uvm_sequence_item;

    rand op_kind_e    kind;
    rand int unsigned gold_idx;   // index into the DC table when kind == OP_DC
    rand int unsigned ac_idx;     // index into the AC table when kind == OP_AC
    rand int unsigned duty_idx;   // index into the duty table, kind == OP_DUTY

    real level;       // DC stimulus driven, volts
    real response;    // DC response, volts        (filled by the monitor)
    real freq;        // AC or clock frequency, Hz
    real mag_db;      // AC gain magnitude, dB     (filled by the monitor)
    real phase_deg;   // AC phase, degrees         (filled by the monitor)
    real in_duty;     // duty driven into the block, fraction
    real out_duty;    // duty measured out         (filled by the monitor)
    real vth;         // threshold this point is sliced at, volts

    `uvm_object_utils_begin(inv1_ms_transaction)
      `uvm_field_enum(op_kind_e, kind, UVM_DEFAULT)
      `uvm_field_int (gold_idx,  UVM_DEFAULT)
      `uvm_field_int (ac_idx,    UVM_DEFAULT)
      `uvm_field_int (duty_idx,  UVM_DEFAULT)
      `uvm_field_real(level,     UVM_DEFAULT)
      `uvm_field_real(response,  UVM_DEFAULT)
      `uvm_field_real(freq,      UVM_DEFAULT)
      `uvm_field_real(mag_db,    UVM_DEFAULT)
      `uvm_field_real(phase_deg, UVM_DEFAULT)
      `uvm_field_real(in_duty,   UVM_DEFAULT)
      `uvm_field_real(out_duty,  UVM_DEFAULT)
      `uvm_field_real(vth,       UVM_DEFAULT)
    `uvm_object_utils_end

    constraint gold_idx_c { gold_idx inside {[0:GOLD_N-1]}; }
    constraint ac_idx_c   { AC_N > 0 -> ac_idx inside {[0:AC_N-1]};
                            AC_N == 0 -> ac_idx == 0; }
    constraint duty_idx_c { DUTY_N > 0 -> duty_idx inside {[0:DUTY_N-1]};
                            DUTY_N == 0 -> duty_idx == 0; }
    // Never randomize into a mode that has no golden behind it: a check
    // with nothing to compare against is a pass that means nothing.
    constraint kind_c     { AC_N == 0   -> kind != OP_AC;
                            DUTY_N == 0 -> kind != OP_DUTY; }

    function new(string name = "inv1_ms_transaction");
      super.new(name);
    endfunction

    // Must be virtual: a non-virtual post_randomize leaves a
    // factory-overridden item's own fields at zero.
    virtual function void post_randomize();
      level = gold_x(gold_idx);
      if (kind == OP_DUTY && DUTY_N > 0) begin
        freq    = duty_freq(duty_idx);
        in_duty = duty_in(duty_idx);
        vth     = duty_vth(duty_idx);
      end else begin
        freq = (AC_N > 0) ? ac_freq(ac_idx) : 0.0;
      end
    endfunction

    virtual function string convert2string();
      if (kind == OP_DUTY)
        return $sformatf("DUTY idx = %0d, freq = %0.6g Hz, in = %0.2f%%, out = %0.2f%%",
                         duty_idx, freq, 100.0 * in_duty, 100.0 * out_duty);
      if (kind == OP_AC)
        return $sformatf("AC  idx = %0d, freq = %0.6g Hz, mag = %0.4f dB, phase = %0.2f deg",
                         ac_idx, freq, mag_db, phase_deg);
      return $sformatf("DC  idx = %0d, level = %0.6f V, response = %0.6f V",
                       gold_idx, level, response);
    endfunction

  endclass : inv1_ms_transaction

  //--------------------------------------------------------------------
  // CLASS: inv1_ms_driver
  //
  // Pushes the level through the proxy (6.2.4) and then holds the item
  // until the core reports a settled sample (6.2.5 push-sync), rather
  // than guessing a delay.
  //--------------------------------------------------------------------
  class inv1_ms_driver extends uvm_driver #(inv1_ms_transaction);

    protected inv1_proxy bridge_proxy;
    int num_sent = 0;

    `uvm_component_utils(inv1_ms_driver)

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    virtual function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      if (!uvm_config_db #(inv1_proxy)::get(this, "", "bridge_proxy", bridge_proxy))
        `uvm_fatal(get_type_name(), "bridge proxy not configured")
    endfunction

    virtual task run_phase(uvm_phase phase);
      forever begin
        seq_item_port.get_next_item(req);
        drive_transaction(req);
        seq_item_port.item_done();
      end
    endtask

    virtual task drive_transaction(inv1_ms_transaction txn);
      num_sent++;
      `uvm_info(get_type_name(),
                $sformatf("pushing %s", txn.convert2string()), UVM_MEDIUM)
      if (txn.kind == OP_DUTY)
        bridge_proxy.push_duty(.freq(txn.freq), .in_duty(txn.in_duty),
                               .v_lo(DUTY_VLO), .v_hi(DUTY_VHI),
                               .vth(txn.vth));
      else if (txn.kind == OP_AC)
        bridge_proxy.push_ac(.freq(txn.freq), .ampl(AC_AMPL), .bias(AC_BIAS));
      else
        bridge_proxy.push(.level(txn.level), .enable(1'b1));
      bridge_proxy.wait_sampling_done();
    endtask

  endclass : inv1_ms_driver

  //--------------------------------------------------------------------
  // CLASS: inv1_ms_monitor
  //
  // 6.2.2 continuous monitoring: waits on the core's handshake and pulls
  // both what was driven and what was measured (6.2.6), so the scoreboard
  // never has to trust the driver's copy of the stimulus.
  //--------------------------------------------------------------------
  class inv1_ms_monitor extends uvm_monitor;

    protected inv1_proxy bridge_proxy;
    uvm_analysis_port #(inv1_ms_transaction) item_collected_port;
    int num_col = 0;

    `uvm_component_utils(inv1_ms_monitor)

    function new(string name, uvm_component parent);
      super.new(name, parent);
      item_collected_port = new("item_collected_port", this);
    endfunction

    virtual function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      if (!uvm_config_db #(inv1_proxy)::get(this, "", "bridge_proxy", bridge_proxy))
        `uvm_fatal(get_type_name(), "bridge proxy not configured")
    endfunction

    virtual task run_phase(uvm_phase phase);
      inv1_ms_transaction txn;
      forever begin
        bridge_proxy.wait_sampling_done();

        txn = inv1_ms_transaction::type_id::create("txn", this);
        void'(begin_tr(txn, "analog operating point"));

        if (bridge_proxy.get_is_duty()) begin
          txn.kind     = OP_DUTY;
          txn.freq     = bridge_proxy.get_stimulus();
          txn.in_duty  = bridge_proxy.get_in_duty();
          txn.out_duty = bridge_proxy.get_duty();
        end else if (bridge_proxy.get_is_ac()) begin
          txn.kind      = OP_AC;
          txn.freq      = bridge_proxy.get_stimulus();
          txn.mag_db    = bridge_proxy.get_mag_db();
          txn.phase_deg = bridge_proxy.get_phase_deg();
        end else begin
          txn.kind     = OP_DC;
          txn.level    = bridge_proxy.get_stimulus();
          txn.response = bridge_proxy.get_response();
        end

        num_col++;
        `uvm_info(get_type_name(),
                  $sformatf("collected %s", txn.convert2string()), UVM_HIGH)
        item_collected_port.write(txn);
        end_tr(txn);
      end
    endtask

  endclass : inv1_ms_monitor

  //--------------------------------------------------------------------
  // CLASS: inv1_ms_agent
  //--------------------------------------------------------------------
  class inv1_ms_agent extends uvm_agent;

    inv1_ms_driver  driver;
    inv1_ms_monitor monitor;
    uvm_sequencer #(inv1_ms_transaction) sequencer;

    `uvm_component_utils(inv1_ms_agent)

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    virtual function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      monitor = inv1_ms_monitor::type_id::create("monitor", this);
      if (get_is_active() == UVM_ACTIVE) begin
        driver    = inv1_ms_driver::type_id::create("driver", this);
        sequencer = uvm_sequencer #(inv1_ms_transaction)::type_id::create("sequencer", this);
      end
    endfunction

    virtual function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      if (get_is_active() == UVM_ACTIVE)
        driver.seq_item_port.connect(sequencer.seq_item_export);
    endfunction

  endclass : inv1_ms_agent

  //--------------------------------------------------------------------
  // SEQUENCE: sweep every characterized operating point, in order.
  // Directed rather than random so one run covers the whole golden table.
  //--------------------------------------------------------------------
  class inv1_ms_sweep_seq extends uvm_sequence #(inv1_ms_transaction);

    `uvm_object_utils(inv1_ms_sweep_seq)

    function new(string name = "inv1_ms_sweep_seq");
      super.new(name);
    endfunction

    virtual task body();
      inv1_ms_transaction txn;
      for (int i = 0; i < GOLD_N; i++) begin
        txn = inv1_ms_transaction::type_id::create("txn");
        start_item(txn);
        txn.kind     = OP_DC;
        txn.gold_idx = i;
        txn.level    = gold_x(i);
        finish_item(txn);
      end
      for (int i = 0; i < AC_N; i++) begin
        txn = inv1_ms_transaction::type_id::create("txn");
        start_item(txn);
        txn.kind   = OP_AC;
        txn.ac_idx = i;
        txn.freq   = ac_freq(i);
        finish_item(txn);
      end
      for (int i = 0; i < DUTY_N; i++) begin
        txn = inv1_ms_transaction::type_id::create("txn");
        start_item(txn);
        txn.kind     = OP_DUTY;
        txn.duty_idx = i;
        txn.freq     = duty_freq(i);
        txn.in_duty  = duty_in(i);
        txn.vth      = duty_vth(i);
        finish_item(txn);
      end
    endtask

  endclass : inv1_ms_sweep_seq

  //--------------------------------------------------------------------
  // SEQUENCE: randomized operating points.  Same golden table, visited in
  // a random order with repeats -- exercises the push path the way an
  // integrating testbench would rather than as a tidy monotonic ramp.
  //--------------------------------------------------------------------
  class inv1_ms_random_seq extends uvm_sequence #(inv1_ms_transaction);

    rand int unsigned n_items;
    constraint n_items_c { n_items inside {[8:24]}; }

    `uvm_object_utils(inv1_ms_random_seq)

    function new(string name = "inv1_ms_random_seq");
      super.new(name);
    endfunction

    virtual task body();
      inv1_ms_transaction txn;
      if (n_items == 0) n_items = 16;
      repeat (n_items) begin
        txn = inv1_ms_transaction::type_id::create("txn");
        start_item(txn);
        if (!txn.randomize())
          `uvm_error("SEQ", "randomization of the operating point failed")
        finish_item(txn);
      end
    endtask

  endclass : inv1_ms_random_seq

endpackage : inv1_ms_pkg
