`timescale 1fs/1fs
//======================================================================
// rc_lpf2_bridge_core -- the DMS bridge core (UVM-MS clause 6.2).
//
// The bridge core is what actually touches the DUT pins and converts
// between the class-based testbench's notion of a stimulus (a level) and
// the analog value on the net.  Everything the proxy touches is a plain
// module-scope variable or function reached by OOMR from the bridge --
// clause 4.2.3 requires that, so the same proxy still works if this
// module is swapped for a Verilog-AMS core.
//
// This core drives AND senses, because the block it wraps is a single
// input / single output transfer characteristic: one push settles the
// input and samples the output, which is one operating point of the DC
// sweep the model was characterized against.
//
// SETTLE_FS comes from the slowest fitted pole (12 tau), so the sample is
// taken after the model has settled rather than after a guessed delay.
//
// AUTO-GENERATED by spice2rnm.  Edits will be overwritten.
//======================================================================
module rc_lpf2_bridge_core import rc_lpf2_ms_types_pkg::*; #(
  parameter real SETTLE_FS = 499520886,
  // Adaptive DC settling: step by a quarter of the nominal settle time
  // and stop once the response goes quiet. The cap bounds a DUT that
  // never settles; the epsilon is a fraction of the checking tolerance,
  // so "quiet" means "quiet enough for the check that follows".
  parameter real SETTLE_STEP_FS  = 124880221,
  parameter int  SETTLE_MAX_STEPS = 160,
  parameter real SETTLE_EPS      = 0.00018,
  // Samples per cycle used to synthesise the AC excitation and to
  // correlate the response.  64 keeps the staircase error on the drive
  // below ~0.1% and the phase quantisation at 360/64/2 = 2.8 degrees.
  parameter int  AC_SAMPLES_PER_CYCLE = 64,
  // Whole cycles discarded before correlating, and then correlated over.
  // Discarding lets the sinusoidal steady state establish; correlating
  // over WHOLE cycles is what makes the DC/bias term integrate away.
  parameter int  AC_SETTLE_CYCLES = 6,
  parameter int  AC_MEAS_CYCLES   = 8,
  // Duty measurement. The clock is synthesised here with the same
  // trapezoid equivalence.generate_clock uses for the ngspice golden --
  // finite edges, because a block whose job is to move an edge can only
  // do it across an edge that takes time. Leading cycles are discarded
  // for the same reason the golden discards them: the first cycle starts
  // from the initial condition, not from the steady state.
  parameter int  DUTY_SAMPLES_PER_PERIOD = 256,
  parameter int  DUTY_SETTLE_CYCLES      = 2,
  parameter int  DUTY_MEAS_CYCLES        = 4,
  parameter real DUTY_EDGE_FRAC          = 0.1,
  // Output samples per DRIVE step, for crossing detection only.
  //
  // The drive grid and the sense grid are not the same problem. The drive
  // has to match the PWL waveform ngspice was given, and 256 points per
  // period does that. The sense grid has to resolve the model's own edge,
  // and it does not: a scheduled-lag comparator slams in ~15 ps while the
  // drive step at 29.5 MHz is 132 ps, so the edge lands between two
  // samples and the interpolated crossing is decided by their VALUES
  // rather than by where the edge actually was. Measured: adding a 91.7 ps
  // delay to the model moved the reported duty by 0.001 pp at 14.8 MHz --
  // the shifted edge simply stayed inside the same sample interval. A
  // 1000 ps delay was reported faithfully, which is how the quantisation
  // gave itself away.
  //
  // Sub-sampling costs almost nothing. The model advances on its own
  // `always #(TSTEP)` at 1.755 ps whatever this is set to, so the extra
  // work is bridge wake-ups, not model steps.
  parameter int  DUTY_SENSE_SUB          = 16
) (
  output rc_lpf2_wire ain,    // stimulus toward the DUT
  input  rc_lpf2_wire aout    // response from the DUT (see top: UDN, not wreal)
);

  localparam real TWO_PI = 6.28318530717958647692;

  //--------------------------------------------------------------------
  // Pushed in by the proxy (D->A)
  //--------------------------------------------------------------------
  real level_in = 0.9;
  bit  enable   = 1'b0;
  int  push_seq = 0;

  // AC request
  bit  ac_mode    = 1'b0;
  real ac_freq_in = 0.0;
  real ac_ampl_in = 0.0;
  real ac_bias_in = 0.9;

  // Duty request
  bit  duty_mode    = 1'b0;
  real duty_freq_in = 0.0;
  real duty_in_duty = 0.5;
  real duty_lo_in   = 0.0;
  real duty_hi_in   = 0.0;
  real duty_vth_in  = 0.0;

  //--------------------------------------------------------------------
  // Published to the proxy (A->D)
  //--------------------------------------------------------------------
  real stim_out      = 0.0;
  real resp_out      = 0.0;
  real mag_db_out    = 0.0;
  real phase_deg_out = 0.0;
  real duty_out      = -1.0;   // negative == no complete cycle was seen
  bit  sampling_done = 1'b0;
  int  report_tick   = 0;

  //--------------------------------------------------------------------
  // Proxy API entry point.  A function, not a variable poke, so the
  // signature survives a move to Verilog-AMS (which has no void
  // functions, hence the integer return).  See UVM-MS 6.1.5.
  //
  // push_seq is bumped on every call so that pushing the SAME level twice
  // still triggers a fresh settle-and-sample; keying the drive process
  // off level_in alone would silently drop the repeat.
  //--------------------------------------------------------------------
  function automatic int set_drive(input real level, input bit en);
    ac_mode   = 1'b0;
    duty_mode = 1'b0;
    level_in = level;
    enable   = en;
    push_seq = push_seq + 1;
    set_drive = 1;
  endfunction

  function automatic int set_ac_drive(input real freq, input real ampl,
                                      input real bias);
    ac_mode    = 1'b1;
    duty_mode  = 1'b0;
    ac_freq_in = freq;
    ac_ampl_in = ampl;
    ac_bias_in = bias;
    enable     = 1'b1;
    push_seq   = push_seq + 1;
    set_ac_drive = 1;
  endfunction

  function automatic int set_duty_drive(input real freq, input real in_duty,
                                        input real v_lo, input real v_hi,
                                        input real vth);
    duty_mode    = 1'b1;
    ac_mode      = 1'b0;
    duty_freq_in = freq;
    duty_in_duty = in_duty;
    duty_lo_in   = v_lo;
    duty_hi_in   = v_hi;
    duty_vth_in  = vth;
    enable       = 1'b1;
    push_seq     = push_seq + 1;
    set_duty_drive = 1;
  endfunction

  //--------------------------------------------------------------------
  // The analog drive itself.
  //--------------------------------------------------------------------
  real drive_v = 0.9;
  assign ain = drive_v;

  // Pulse the handshake without stealing time from the process that
  // incremented report_tick.
  always @(report_tick) begin
    sampling_done = 1'b1;
    #1 sampling_done = 1'b0;
  end

  //--------------------------------------------------------------------
  // Small-signal AC point.
  //
  // Excite with a sinusoid and recover the response amplitude and phase
  // by correlating against one cycle of sin and cos -- a single-bin DFT
  // at the excitation frequency.  Peak-picking would have been shorter
  // but is biased by the sample grid and by any harmonic content; the
  // correlation rejects both, and rejects the DC/bias term outright
  // because it runs over a whole number of cycles.
  //
  // With drive d[n] = bias + A*sin(t[n]) and response
  // v[n] = bias' + B*sin(t[n]+phi), summed over whole cycles:
  //     sum v[n]*sin(t[n]) = (N/2)*B*cos(phi)
  //     sum v[n]*cos(t[n]) = (N/2)*B*sin(phi)
  // so B = 2*hypot(.)/N and phi = atan2(cos-sum, sin-sum).
  //--------------------------------------------------------------------
  task automatic measure_ac();
    real period_fs, dt_fs, theta, v;
    real acc_i, acc_q, amp_out;
    int  n, total;

    if (ac_freq_in <= 0.0 || ac_ampl_in <= 0.0) begin
      mag_db_out    = 0.0;
      phase_deg_out = 0.0;
      return;
    end

    period_fs = 1.0e15 / ac_freq_in;
    dt_fs     = period_fs / real'(AC_SAMPLES_PER_CYCLE);

    // Step to the operating point and let the model's own time constant
    // settle before any sinusoid is applied.
    drive_v = ac_bias_in;
    #(SETTLE_FS);

    // Discard the transient: drive whole cycles without correlating.
    total = AC_SAMPLES_PER_CYCLE * AC_SETTLE_CYCLES;
    for (n = 0; n < total; n++) begin
      theta   = TWO_PI * real'(n) / real'(AC_SAMPLES_PER_CYCLE);
      drive_v = ac_bias_in + ac_ampl_in * $sin(theta);
      #(dt_fs);
    end

    // Correlate over whole cycles.
    acc_i = 0.0;
    acc_q = 0.0;
    total = AC_SAMPLES_PER_CYCLE * AC_MEAS_CYCLES;
    for (n = 0; n < total; n++) begin
      theta   = TWO_PI * real'(n) / real'(AC_SAMPLES_PER_CYCLE);
      drive_v = ac_bias_in + ac_ampl_in * $sin(theta);
      #(dt_fs);
      v     = aout;
      acc_q = acc_q + v * $sin(theta);
      acc_i = acc_i + v * $cos(theta);
    end

    amp_out = 2.0 * $sqrt(acc_i * acc_i + acc_q * acc_q) / real'(total);

    if (amp_out <= 0.0) begin
      mag_db_out = -300.0;   // floor rather than -inf from $log10(0)
    end else begin
      mag_db_out = 20.0 * $log10(amp_out / ac_ampl_in);
    end
    phase_deg_out = $atan2(acc_i, acc_q) * 360.0 / TWO_PI;
  endtask

  //--------------------------------------------------------------------
  // Duty point.
  //
  // Drive a trapezoidal clock and measure the duty of the RESPONSE about
  // a threshold that was pushed in with the golden.
  //
  // Crossings are linearly interpolated between samples rather than taken
  // at the sample that straddles them. The RNM advances on a fixed
  // integration step and the drive is a staircase on top of that, so raw
  // crossings quantise to the coarser of the two grids; interpolating
  // across a monotonic edge resolves well below either. The golden was
  // measured from the ngspice trace with the same interpolation, and the
  // two numbers are only comparable because both use it.
  //
  // Duty is high-time over period for each complete rise -> fall -> rise,
  // averaged. Pairing on rises rather than counting samples above the
  // threshold is what makes it independent of the sample grid.
  //--------------------------------------------------------------------
  task automatic measure_duty();
    real period_fs, dt_fs, dt_sub, t_edge, t_hi_end, ph, span;
    real v, v_prev, t_now, t_prev, t_cross, frac;
    real last_rise, pend_fall, sum_duty;
    int  n, m, total, n_settle, n_duty;
    bit  have_rise, have_fall;

    duty_out = -1.0;
    if (duty_freq_in <= 0.0 || duty_in_duty <= 0.0 || duty_in_duty >= 1.0)
      return;

    period_fs = 1.0e15 / duty_freq_in;
    dt_fs     = period_fs / real'(DUTY_SAMPLES_PER_PERIOD);
    dt_sub    = dt_fs / real'(DUTY_SENSE_SUB);
    span      = duty_hi_in - duty_lo_in;

    // Same edge rule as generate_clock: both edges plus a sliver of flat
    // time have to fit inside the period, or the trapezoid degenerates.
    t_edge = DUTY_EDGE_FRAC * period_fs;
    if (duty_in_duty < (1.0 - duty_in_duty))
      t_hi_end = duty_in_duty * period_fs;
    else
      t_hi_end = (1.0 - duty_in_duty) * period_fs;
    if (2.0 * t_edge >= t_hi_end)
      t_edge = 0.4 * t_hi_end;
    t_hi_end = duty_in_duty * period_fs;

    // Start from the low rail so the first edge is a real one.
    drive_v = duty_lo_in;
    #(SETTLE_FS);

    last_rise = 0.0;
    pend_fall = 0.0;
    sum_duty  = 0.0;
    n_duty    = 0;
    have_rise = 1'b0;
    have_fall = 1'b0;

    n_settle = DUTY_SAMPLES_PER_PERIOD * DUTY_SETTLE_CYCLES;
    total    = DUTY_SAMPLES_PER_PERIOD
               * (DUTY_SETTLE_CYCLES + DUTY_MEAS_CYCLES);

    v_prev = aout;
    t_prev = $realtime;

    for (n = 0; n < total; n++) begin
      ph = real'(n % DUTY_SAMPLES_PER_PERIOD) * dt_fs;
      if (ph < t_edge)
        drive_v = duty_lo_in + span * (ph / t_edge);
      else if (ph < t_hi_end)
        drive_v = duty_hi_in;
      else if (ph < t_hi_end + t_edge)
        drive_v = duty_hi_in - span * ((ph - t_hi_end) / t_edge);
      else
        drive_v = duty_lo_in;

      // Hold the drive and sense across it, so a near-vertical model edge
      // is located to the SENSE grid rather than to the drive grid.
      for (m = 0; m < DUTY_SENSE_SUB; m++) begin
        #(dt_sub);
        v     = aout;
        t_now = $realtime;

        // Only start counting edges once the settle window has passed, so
        // the turn-on transient cannot contribute a cycle.
        if (n >= n_settle) begin
          if (((v_prev < duty_vth_in) != (v < duty_vth_in)) && (v != v_prev)) begin
            frac    = (duty_vth_in - v_prev) / (v - v_prev);
            t_cross = t_prev + (t_now - t_prev) * frac;
            if (v > v_prev) begin
              // A rise closes the previous cycle, if that cycle had a fall.
              if (have_rise && have_fall && (t_cross > last_rise)) begin
                sum_duty = sum_duty + (pend_fall - last_rise)
                                      / (t_cross - last_rise);
                n_duty   = n_duty + 1;
              end
              last_rise = t_cross;
              have_rise = 1'b1;
              have_fall = 1'b0;
            end else begin
              // First fall after the current rise is the one that counts.
              if (have_rise && !have_fall) begin
                pend_fall = t_cross;
                have_fall = 1'b1;
              end
            end
          end
        end

        v_prev = v;
        t_prev = t_now;
      end
    end

    if (n_duty > 0)
      duty_out = sum_duty / real'(n_duty);
    else
      $display("WARNING: %m: no complete cycle at %0.6g Hz -- the response never crossed %0.6f V twice in the same direction",
               duty_freq_in, duty_vth_in);
  endtask

  // Wait for the response to stop moving, rather than for a fixed time.
  //
  // A fixed SETTLE_FS is only right if the DUT's slowest time constant
  // is the one the fit reported. It often is not: on a composed
  // current-DAC model the node time constant is 226 ps at the bias but
  // stretches to 1 ns where the devices turn off, because the device
  // conductance that dominates it disappears. Twelve of the FITTED tau
  // is under three of the real one there, leaving 6% of the step
  // un-settled -- 0.10 V against a 0.07 V tolerance, and a failure that
  // says nothing about the model.
  //
  // Stepping until the change per interval falls below a fraction of the
  // checking tolerance adapts to whatever the operating point actually
  // does, and the cap keeps a non-settling DUT from hanging the run.
  task automatic settle_response();
    real prev, delta;
    int  n, quiet;
    prev  = aout;
    quiet = 0;
    for (n = 0; n < SETTLE_MAX_STEPS; n++) begin
      #(SETTLE_STEP_FS);
      delta = aout - prev;
      if (delta < 0.0) delta = -delta;
      prev = aout;
      // Two consecutive quiet intervals, so a slow monotonic drift
      // through a single quiet sample does not read as settled.
      if (delta < SETTLE_EPS) begin
        quiet = quiet + 1;
        if (quiet >= 2) return;
      end else begin
        quiet = 0;
      end
    end
    // $display, not `uvm_ms_warning: those macros are `included in the
    // BRIDGE, and this core is compiled as its own module without them.
    // Reaching here means the DUT never went quiet, which is worth
    // saying out loud even without the UVM reporting hierarchy.
    $display("WARNING: %m: response still moving by %0.6g V per %0.6g fs after %0d steps; sampling anyway",
             delta, SETTLE_STEP_FS, SETTLE_MAX_STEPS);
  endtask

  // 6.2.4 push -> settle -> 6.2.2 sample -> 6.2.5 report.
  always @(push_seq) begin
    if (enable) begin
      if (duty_mode) begin
        measure_duty();
        stim_out = duty_freq_in;
        resp_out = aout;
      end else if (ac_mode) begin
        measure_ac();
        stim_out = ac_freq_in;
        resp_out = aout;
      end else begin
        drive_v = level_in;
        settle_response();
        stim_out = drive_v;
        resp_out = aout;
      end
      report_tick = report_tick + 1;
    end
  end

endmodule : rc_lpf2_bridge_core
