//======================================================================
// rc_lpf2_ms_test -- sweep every characterized operating point, then a
// randomized burst over the same table.
//
// AUTO-GENERATED by spice2rnm.  Edits will be overwritten.
//======================================================================
class rc_lpf2_ms_test extends uvm_test;

  rc_lpf2_ms_tb tb;

  `uvm_component_utils(rc_lpf2_ms_test)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    tb = rc_lpf2_ms_tb::type_id::create("tb", this);
  endfunction

  virtual task run_phase(uvm_phase phase);
    rc_lpf2_ms_sweep_seq  sweep;
    rc_lpf2_ms_random_seq rand_seq;

    phase.raise_objection(this, "rc_lpf2 operating-point sweep");

    sweep = rc_lpf2_ms_sweep_seq::type_id::create("sweep");
    sweep.start(tb.agent.sequencer);

    rand_seq = rc_lpf2_ms_random_seq::type_id::create("rand_seq");
    if (!rand_seq.randomize())
      `uvm_error(get_type_name(), "randomization of the random sequence failed")
    rand_seq.start(tb.agent.sequencer);

    // Let the last push settle and be collected before the run ends.
    #(1.99808354e+09);

    phase.drop_objection(this, "rc_lpf2 operating-point sweep");
  endtask

endclass : rc_lpf2_ms_test
