`timescale 1fs/1fs
// wreal boundary for rc_lpf2_rnm, auto-generated by spice2rnm (Veylon Systems).
//
// For flows standardised on wreal nets. The core model is
// instantiated untouched -- same behaviour, same evidence --
// and only the boundary changes discipline, exactly as the
// DMS wrapper does for the user-defined-nettype environment.
//
// wreal is Verilog-AMS vocabulary, not IEEE 1800: this file
// compiles where the simulator provides the extension, and is
// deliberately a separate file so the default output carries
// no dependence on it.
module rc_lpf2_rnm_wreal(input wreal ain, output wreal aout);

  // Net -> variable, so the core's `input real` can take it.
  real in_r;
  always @(ain) in_r = ain;

  // Variable -> net on the way back out.
  real out_r;
  assign aout = out_r;

  rc_lpf2_rnm u_rnm (.in_val(in_r), .out_val(out_r));

endmodule : rc_lpf2_rnm_wreal
