//======================================================================
// ro_vco_ms_test -- walk the tuning curve, then report.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class ro_vco_ms_test extends uvm_test;
  `uvm_component_utils(ro_vco_ms_test)
  ro_vco_ms_tb tb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    tb = ro_vco_ms_tb::type_id::create("tb", this);
  endfunction

  virtual task run_phase(uvm_phase phase);
    ro_vco_vco_seq seq;
    phase.raise_objection(this);
    seq = ro_vco_vco_seq::type_id::create("seq");
    seq.start(tb.sqr);
    tb.sb.report_vco();
    phase.drop_objection(this);
  endtask
endclass
