`timescale 1fs/1fs
//======================================================================
// ro_vco_rnm -- real-number model of a voltage-controlled oscillator.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//
// This block's function is a FREQUENCY, so there is no H(s) here and no
// fixed integration timestep. The output edge is scheduled from the control
// voltage in effect at the time:
//
//     always begin #(half_period(cont)) clk = ~clk; end
//
// which costs one event per half cycle instead of one per timestep, and
// keeps phase continuous across a control change: the edge already
// scheduled is not retimed, exactly as a real oscillator behaves.
//
// Tuning curve: 16 points measured from SPICE over 0.49..2.80 V
// (16.7..804.5 MHz). Each point is the period counted over whole
// cycles of a transient whose timestep is a fixed fraction of that point's
// own period, re-run at half that step to show the number stopped moving.
// Held-out error on the 14 midpoints between them: 4.986% of period (1774.5 ps), worst at 2.7689 V.
// In the MEASURED OPERATING BAND 1.7972..1.9034 V, taken from a golden
// co-simulation run before this model existed: 0.002% (0.1 ps) over 4
// held-out point(s), worst at 1.8901 V.
// Measurement convergence: halving the timestep moved the
// worst point by 0.015%. The held-out score above is
// interpolation error ONLY -- it compares points measured one
// way against a table built the same way, so it is blind to
// anything the measurement gets wrong at every point alike.
// This figure is that part.
//
// The table is CLAMPED at both ends. Inside a loop the control voltage
// leaves this range during acquisition; saturating is the honest answer
// there, where a fitted polynomial would extrapolate to a frequency the
// circuit cannot produce.
//======================================================================
module ro_vco_rnm (
  input  real  cont,
  output logic clk
);

  localparam int N = 16;
  real VC [0:N-1];
  real FO [0:N-1];

  // Loaded by the function that reads it, on first use -- NOT by an
  // initial block. IEEE 1800 leaves the order of initial and always
  // procedures at time zero undefined, and a reader that runs first would
  // see an all-zero table.
  bit tab_loaded;
  function automatic void load_tab();
      VC[0] = 0.495000; FO[0] = 8.044728186e+08;
      VC[1] = 0.783750; FO[1] = 7.353222574e+08;
      VC[2] = 1.072500; FO[2] = 6.634459647e+08;
      VC[3] = 1.361250; FO[3] = 5.803862641e+08;
      VC[4] = 1.650000; FO[4] = 4.774032573e+08;
      VC[5] = 1.797191; FO[5] = 4.203573328e+08;
      VC[6] = 1.823740; FO[6] = 4.100376667e+08;
      VC[7] = 1.850288; FO[7] = 3.997504459e+08;
      VC[8] = 1.876836; FO[8] = 3.895104865e+08;
      VC[9] = 1.903384; FO[9] = 3.793295313e+08;
      VC[10] = 1.938750; FO[10] = 3.658689447e+08;
      VC[11] = 2.227500; FO[11] = 2.570119652e+08;
      VC[12] = 2.516250; FO[12] = 1.366251648e+08;
      VC[13] = 2.660625; FO[13] = 7.416278165e+07;
      VC[14] = 2.732812; FO[14] = 4.240882586e+07;
      VC[15] = 2.805000; FO[15] = 1.673948453e+07;
    tab_loaded = 1'b1;
  endfunction

  function automatic real freq_of(input real v);
    int  k;
    real t;
    if (!tab_loaded) load_tab();
    if (v <= VC[0])   return FO[0];
    if (v >= VC[N-1]) return FO[N-1];
    for (k = 0; k < N-1; k++) begin
      if (v >= VC[k] && v <= VC[k+1]) begin
        t = (v - VC[k]) / (VC[k+1] - VC[k]);
        return FO[k] + t * (FO[k+1] - FO[k]);
      end
    end
    return FO[N-1];
  endfunction

  // Half period in the module's time unit (1 fs).
  function automatic real half_period_fs(input real v);
    real f;
    f = freq_of(v);
    // A zero delay here would spin the scheduler forever rather than model
    // a stopped oscillator, so floor it at the slowest tabulated rate.
    if (f <= 0.0) return 1.0e15 / (2.0 * 1.673948453e+07);
    return 1.0e15 / (2.0 * f);
  endfunction

  initial clk = 1'b0;

  always begin
    #(half_period_fs(cont));
    clk = ~clk;
  end


`ifndef SPICE2RNM_NO_ASSERT
  //--------------------------------------------------------------------
  // Validity domain, from the measurements that built this model.
  //
  // These state where the evidence applies. Outside it the model does
  // not extrapolate -- it CLAMPS, and keeps returning a plausible
  // number -- so being told once is the difference between a wrong
  // answer you can see and one you cannot.
  //
  // Compile out with +define+SPICE2RNM_NO_ASSERT.
  //--------------------------------------------------------------------
  localparam real DOMAIN_LO  = 0.495;
  localparam real DOMAIN_HI  = 2.805;
  localparam real DOMAIN_EPS = 0.0; // exact -- no stimulus here overshoots, so no margin is earned
  bit domain_reported = 1'b0;

  always @(cont) begin : domain_check
    a_input_domain: assert (cont >= DOMAIN_LO - DOMAIN_EPS && cont <= DOMAIN_HI + DOMAIN_EPS)
    else if (!domain_reported) begin
      domain_reported = 1'b1;
      $warning("%m: input %0.6g V is outside the characterized range %0.6g..%0.6g V. the table clamps at its measured end points, so this model keeps running and returns the endpoint value -- it is not extrapolating, and it is no longer evidence. Reported once.",
               cont, DOMAIN_LO, DOMAIN_HI);
    end
  end

  bit in_nan_reported = 1'b0;

  always @(cont) begin : input_health
    // NaN is the one value that is not equal to itself.
    a_input_finite: assert (cont == cont)
    else if (!in_nan_reported) begin
      in_nan_reported = 1'b1;
      $error("%m: control input is NaN -- whatever drives this model diverged. Reported once.");
    end
  end
`endif

endmodule : ro_vco_rnm
