//======================================================================
// ro_vco_ms driver, monitor, agent, env.
//
// Rebuilt on the pattern the loop environment uses. What changed is not
// what is measured but WHO holds the reach: the timing lives in the
// concrete proxy in `top`, because it has to see the signals, and
// nothing above it does. The driver asks for a point; the monitor waits
// for one and publishes what it found; the scoreboard subscribes.
//
// The previous shape had the driver measure and call the scoreboard
// directly. It worked, and it left no analysis port to attach a second
// observer to, and it duplicated the edge-timing the loop environment
// also carries.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class ro_vco_ms_driver extends uvm_driver #(ro_vco_vco_item);
  `uvm_component_utils(ro_vco_ms_driver)

  ro_vco_ms_proxy proxy;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db #(ro_vco_ms_proxy)::get(this, "", "proxy", proxy))
      `uvm_fatal("NOPROXY", "no MS proxy was handed to the driver")
  endfunction

  virtual task run_phase(uvm_phase phase);
    ro_vco_vco_item req;
    forever begin
      seq_item_port.get_next_item(req);
      proxy.run_point(req.control_v, req.golden_f, req.held_out);
      seq_item_port.item_done();
    end
  endtask
endclass : ro_vco_ms_driver


class ro_vco_ms_monitor extends uvm_monitor;
  `uvm_component_utils(ro_vco_ms_monitor)

  uvm_analysis_port #(ro_vco_vco_result) ap;
  ro_vco_ms_proxy proxy;

  function new(string name, uvm_component parent);
    super.new(name, parent);
    ap = new("ap", this);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db #(ro_vco_ms_proxy)::get(this, "", "proxy", proxy))
      `uvm_fatal("NOPROXY", "no MS proxy was handed to the monitor")
  endfunction

  virtual task run_phase(uvm_phase phase);
    ro_vco_vco_result r;
    forever begin
      proxy.wait_point_done();
      r = ro_vco_vco_result::type_id::create("r");
      r.control_v  = proxy.pull_control();
      r.golden_f   = proxy.pull_golden();
      r.measured_f = proxy.pull_freq();
      r.held_out   = proxy.pull_held_out();
      `uvm_info(get_type_name(),
                $sformatf("%s %0.4f V -> %0.6g Hz (golden %0.6g Hz)",
                          r.held_out ? "held-out" : "breakpoint",
                          r.control_v, r.measured_f, r.golden_f), UVM_MEDIUM)
      ap.write(r);
    end
  endtask
endclass : ro_vco_ms_monitor


class ro_vco_ms_agent extends uvm_agent;
  `uvm_component_utils(ro_vco_ms_agent)

  ro_vco_ms_driver                  driver;
  ro_vco_ms_monitor                 monitor;
  uvm_sequencer #(ro_vco_vco_item)  sqr;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    monitor = ro_vco_ms_monitor::type_id::create("monitor", this);
    if (get_is_active() == UVM_ACTIVE) begin
      driver = ro_vco_ms_driver::type_id::create("driver", this);
      sqr    = uvm_sequencer #(ro_vco_vco_item)::type_id::create("sqr", this);
    end
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (get_is_active() == UVM_ACTIVE)
      driver.seq_item_port.connect(sqr.seq_item_export);
  endfunction
endclass : ro_vco_ms_agent


class ro_vco_ms_tb extends uvm_env;
  `uvm_component_utils(ro_vco_ms_tb)

  ro_vco_ms_agent      agent;
  ro_vco_ms_scoreboard sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    agent = ro_vco_ms_agent::type_id::create("agent", this);
    sb    = ro_vco_ms_scoreboard::type_id::create("sb", this);
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    agent.monitor.ap.connect(sb.sb_imp);
  endfunction
endclass : ro_vco_ms_tb
