`timescale 1fs/1fs
//======================================================================
// The ABSTRACT half of the VCO MS proxy (UVM-MS clause 4.2.1).
//
// The driver asks for a point, the concrete half in `top` sets the
// control and times the oscillation, and the monitor reads back what it
// found. Neither holds a hierarchical path into the design, which is
// the coupling this exists to remove -- the timing has to sit where it
// can see the signals, but nothing else does.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package ro_vco_ms_proxy_pkg;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"

  virtual class ro_vco_ms_proxy extends uvm_ms_proxy;

    function new(string name = "ro_vco_ms_proxy");
      super.new(name);
    endfunction

    // push: hold the control here and time the output. The golden and
    // the point's kind ride along so the monitor can publish a complete
    // transaction without the driver writing to the scoreboard.
    pure virtual task run_point(input real v, input real golden,
                                input bit held_out);
    // monitor continuous signals: wait until a point has been timed.
    pure virtual task wait_point_done();
    // pull: what that point found.
    pure virtual function real pull_control();
    pure virtual function real pull_freq();
    pure virtual function real pull_golden();
    pure virtual function bit  pull_held_out();

  endclass : ro_vco_ms_proxy

endpackage : ro_vco_ms_proxy_pkg
