//======================================================================
// ro_vco_ms_tb -- a driver that also measures, plus the scoreboard.
//
// The driver measures rather than delegating to a task in `top`, following
// the phase environment: a class method calling a module-scope task is not
// the same reach as a class reading its enclosing module's signals, and
// getting that wrong produces a run with zero checks that looks clean.
// Writing `cont_r` and reading `clk_sig` is legitimate here because this
// class is `include`d INSIDE top, so both are enclosing-scope names.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class ro_vco_ms_driver extends uvm_driver #(ro_vco_vco_item);
  `uvm_component_utils(ro_vco_ms_driver)
  ro_vco_ms_scoreboard sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Rate over MEAS_CYC whole cycles, in Hz.
  //
  // Two edges are discarded after the control voltage changes. The model
  // schedules an edge and then waits out that delay, so the edge already in
  // flight was scheduled under the PREVIOUS voltage; counting it would
  // blend two settings and read as error that is not there.
  virtual task measure(input real v, output real f_hz);
    real t0, t1;
    int  n;
    cont_r = v;
    @(posedge clk_sig);
    @(posedge clk_sig);
    t0 = $realtime;
    n  = 0;
    while (n < MEAS_CYC) begin
      @(posedge clk_sig);
      n++;
    end
    t1 = $realtime;
    // $realtime is in the module's time unit (1 fs).
    f_hz = (t1 > t0) ? (real'(MEAS_CYC) * 1.0e15 / (t1 - t0)) : 0.0;
  endtask

  virtual task run_phase(uvm_phase phase);
    ro_vco_vco_item req;
    real f;
    forever begin
      seq_item_port.get_next_item(req);
      measure(req.control_v, f);
      req.measured_f = f;
      `uvm_info(get_type_name(),
                $sformatf("%s %0.4f V -> %0.6g Hz (golden %0.6g Hz)",
                          req.held_out ? "held-out" : "breakpoint",
                          req.control_v, f, req.golden_f), UVM_MEDIUM)
      sb.check_point(req.control_v, req.golden_f, f, req.held_out);
      seq_item_port.item_done();
    end
  endtask
endclass


class ro_vco_ms_tb extends uvm_env;
  `uvm_component_utils(ro_vco_ms_tb)

  ro_vco_ms_driver drv;
  ro_vco_ms_scoreboard sb;
  uvm_sequencer #(ro_vco_vco_item) sqr;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    sb  = ro_vco_ms_scoreboard::type_id::create("sb", this);
    drv = ro_vco_ms_driver::type_id::create("drv", this);
    sqr = uvm_sequencer #(ro_vco_vco_item)::type_id::create("sqr", this);
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    drv.seq_item_port.connect(sqr.seq_item_export);
    drv.sb = sb;
  endfunction
endclass
