`timescale 1fs/1fs
//======================================================================
// ro_vco_dms -- mixed-signal wrapper around ro_vco_rnm.
//
// The control input arrives on the environment's nettype net (IEEE
// 1800-2017 6.6.7) through an `interconnect` port (6.6.8), exactly as in
// the DC/AC environment. The OUTPUT is deliberately plain `logic`: this
// block's product is a clock edge, and putting it on an analog net would
// invite a voltage comparison that says nothing about the thing being
// checked.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module ro_vco_dms import ro_vco_ms_types_pkg::*; (
  input  interconnect cont,
  output logic        clk
);

  real cont_r;
  assign cont_r = cont;

  ro_vco_rnm u_rnm (
    .cont (cont_r),
    .clk  (clk)
  );

endmodule : ro_vco_dms
