#!/usr/bin/env bash
# UVM-MS VCO testbench for ro_vco_rnm -- AUTO-GENERATED by spice2rnm (Veylon Systems).
#
# Runs entirely on xezim: one invocation compiles and simulates UVM, the
# IEEE 1800-2017 6.6.7 user-defined nettypes and interconnect (6.6.8) ports.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
XEZIM=${XEZIM:-$HOME/xezim/target/release/xezim}
UVM=${UVM_SRC:-$HOME/iverilog-unified/uvm-core/src}
UVM_MS=${UVM_MS_LIB:-$HOME/uvm_ms_demo/ms}
MAX_TIME=${MAX_TIME:-50ms}
# Wall-clock guard, seconds. A cap that fires truncates the run BEFORE the
# scoreboard reports, which reads as a silent pass.
WALL_TIMEOUT=${WALL_TIMEOUT:-3600}

if [ ! -x "$XEZIM" ]; then
  echo "ERROR: xezim not found or not executable at '$XEZIM'." >&2
  echo "  Re-run as:  XEZIM=/path/to/xezim $0" >&2
  exit 1
fi
for d in "$UVM/uvm_pkg.sv" "$UVM_MS/uvm_ms_pkg.sv"; do
  [ -f "$d" ] || { echo "ERROR: $d not found (set UVM_SRC / UVM_MS_LIB)." >&2; exit 1; }
done

cd "$ROOT"

echo "=== running UVM-MS VCO testbench for ro_vco_rnm on xezim ==="
timeout "$WALL_TIMEOUT" "$XEZIM" --max-time "$MAX_TIME" -DUVM_NO_DPI \
    -I "$UVM" -I "$UVM_MS" -I "$ROOT" \
    "$UVM/uvm_pkg.sv" \
    "$UVM_MS/uvm_ms_pkg.sv" \
    ro_vco_ms_types_pkg.sv \
    ro_vco_rnm.sv \
    ro_vco_dms.sv \
    ro_vco_ms_pkg.sv \
    top_ro_vco_ms.sv \
    +UVM_NO_RELNOTES "$@" \
  2>&1 | grep -v 'compile-progress\|degraded to null\|not representable\|dpiexport'
