`timescale 1fs/1fs
//======================================================================
// top -- UVM-MS testbench for ro_vco_rnm.
//
// The control voltage rides the environment's nettype net into the DMS
// wrapper's `interconnect` port, so the analog boundary is the same one the
// DC/AC and phase environments use. There is no stimulus generator in top:
// for this block the input is a level the driver sets, and the thing that
// varies over time is the output the model produces from it.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module top;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  import ro_vco_ms_types_pkg::*;
  import ro_vco_ms_pkg::*;

  //--- the control net, and the clock under test ----------------------
  ro_vco_wire cont_net;
  real  cont_r = 0.495000;
  assign cont_net = cont_r;
  logic clk_sig;

  ro_vco_dms u_dut (
    .cont (cont_net),
    .clk  (clk_sig)
  );

  //--- test ------------------------------------------------------------
  `include "ro_vco_ms_scoreboard.svh"
  `include "ro_vco_ms_tb.svh"
  `include "ro_vco_ms_test.svh"

  initial begin
    `uvm_ms_info("TOP_MS",
                 "UVM-MS VCO testbench for ro_vco_rnm: goldens are ngspice frequency measurements",
                 UVM_LOW)
    run_test("ro_vco_ms_test");
  end

endmodule : top
