`timescale 1fs/1fs
//======================================================================
// dcc_proxy_pkg -- the ABSTRACT half of the MS Proxy (clause 4.2.1).
//
// uvm_ms_proxy (Annex A.1) is extended with the prototypes that form the
// API between the UVM-MS agent and the MS Bridge.  The CONCRETE
// implementation lives inside the bridge (dcc_bridge.sv) and is
// handed to the agent through uvm_config_db as this abstract type, so the
// agent is unchanged whether the core behind it is DMS, Verilog-AMS, or
// anything else.
//
// AUTO-GENERATED by spice2rnm.  Edits will be overwritten.
//======================================================================
package dcc_proxy_pkg;

  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"

  virtual class dcc_proxy extends uvm_ms_proxy;

    // Mirrored from the bridge core by an always block in the bridge, per
    // UVM-MS 6.1.5.  Readable status only; the blocking task below is
    // what a driver or monitor should synchronise on.
    int eot;

    function new(string name = "dcc_proxy");
      super.new(name);
    endfunction

    // 6.2.4 push -- hand a DC stimulus level to the core, return at once.
    pure virtual function void push(input real level, input bit enable);

    // 6.2.4 push -- request a small-signal AC point: excite at freq with
    // amplitude ampl about bias, and measure the steady-state response.
    // Kept separate from push() rather than overloaded with a mode flag,
    // so the API says what it does at the call site.
    pure virtual function void push_ac(input real freq,
                                       input real ampl,
                                       input real bias);

    // 6.2.4 push -- request a DUTY point: drive a trapezoidal clock of
    // `in_duty` at `freq` swinging v_lo..v_hi, and measure the duty of the
    // response about `vth`. The threshold is pushed in rather than found
    // by the core, because it is ngspice's own output midpoint for this
    // golden -- a core that recomputed a midpoint from the model's trace
    // would let a model with a collapsed swing pick a flattering slice.
    pure virtual function void push_duty(input real freq,
                                         input real in_duty,
                                         input real v_lo,
                                         input real v_hi,
                                         input real vth);

    // 6.2.6 pull -- read back what was driven and what was measured.
    pure virtual function real get_stimulus();
    pure virtual function real get_response();

    // 6.2.6 pull -- the AC result of the last push_ac.
    pure virtual function real get_mag_db();
    pure virtual function real get_phase_deg();

    // 6.2.6 pull -- the duty the core measured on the last push_duty,
    // as a fraction (0..1), or a negative value if no complete cycle was
    // seen. Negative is deliberate: it cannot be confused with a real
    // duty, so a model that produced no edges reads as unmeasured rather
    // than as 0% duty, which would look like a legitimate answer.
    pure virtual function real get_duty();

    // 6.2.6 pull -- the input duty the core was asked for. The scoreboard
    // needs it to pick the golden: this table is keyed by (frequency,
    // input duty), and several points normally share a frequency. Pulled
    // from the CORE rather than taken from the driver's item, for the
    // reason get_is_ac gives -- a monitor that trusted the driver's copy
    // of the stimulus would stop being an independent observer.
    pure virtual function real get_in_duty();

    // Which kind of point the core last completed.  The monitor needs
    // this to interpret the pulled values, and asking the CORE keeps the
    // monitor independent of the driver -- a monitor that inferred the
    // mode from what the driver last sent would stop being an
    // independent observer.
    pure virtual function bit get_is_ac();
    pure virtual function bit get_is_duty();

    // 6.2.5 push-sync -- block until the core has a settled sample.
    pure virtual task wait_sampling_done();

  endclass : dcc_proxy

endpackage : dcc_proxy_pkg
