//======================================================================
// dcc_ms_test -- sweep every characterized operating point, then a
// randomized burst over the same table.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class dcc_ms_test extends uvm_test;

  dcc_ms_tb tb;

  `uvm_component_utils(dcc_ms_test)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    tb = dcc_ms_tb::type_id::create("tb", this);
  endfunction

  virtual task run_phase(uvm_phase phase);
    dcc_ms_sweep_seq  sweep;
    dcc_ms_random_seq rand_seq;

    phase.raise_objection(this, "dcc operating-point sweep");

    sweep = dcc_ms_sweep_seq::type_id::create("sweep");
    sweep.start(tb.agent.sequencer);

    rand_seq = dcc_ms_random_seq::type_id::create("rand_seq");
    if (!rand_seq.randomize())
      `uvm_error(get_type_name(), "randomization of the random sequence failed")
    rand_seq.start(tb.agent.sequencer);

    // Let the last push settle and be collected before the run ends.
    #(129289683);

    phase.drop_objection(this, "dcc operating-point sweep");
  endtask

endclass : dcc_ms_test
