`timescale 1fs/1fs
//======================================================================
// dcc_bridge -- the MS BRIDGE (UVM-MS clause 4.2, Annex B.2).
//
// A SystemVerilog module containing:
//   * the concrete MS Proxy   (extends dcc_proxy)
//   * the bridge core instance (dcc_bridge_core, the DMS flavour)
//
// The DUT-facing ports are `interconnect`, as clause 4.2 requires: the
// bridge is generic and should not have to name the analog type the DUT
// chose.  The types are inherited from the actual at instantiation --
// including the nettype's resolution function, so extra drivers on the
// stimulus net still combine (clause 4.2.3.2).
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module dcc_bridge import dcc_ms_types_pkg::*; (
  output interconnect ain,     // stimulus toward the DUT
  input  interconnect aout     // response from the DUT
);

  // UVM + MS extras
  import uvm_pkg::*;
  import uvm_ms_pkg::*;
  `include "uvm_macros.svh"
  `include "uvm_ms_includes.svh"

  import dcc_proxy_pkg::*;

  //--------------------------------------------------------------------
  // The concrete proxy.  Every method reaches the bridge core by OOMR,
  // which is what keeps the class-based world and the core decoupled --
  // UVM-MS clause 4.2.3.
  //--------------------------------------------------------------------
  class dcc_bridge_proxy extends dcc_proxy;

    function new(string name = "");
      super.new(name);
    endfunction

    // 6.2.4 push
    virtual function void push(input real level, input bit enable);
      void'(core.set_drive(level, enable));
      `uvm_ms_info("BRIDGE_PUSH",
                   $sformatf("level = %0.6f V  enable = %0b", level, enable),
                   UVM_HIGH)
    endfunction

    // 6.2.4 push -- small-signal AC point
    virtual function void push_ac(input real freq, input real ampl,
                                  input real bias);
      void'(core.set_ac_drive(freq, ampl, bias));
      `uvm_ms_info("BRIDGE_PUSH_AC",
                   $sformatf("freq = %0.6g Hz  ampl = %0.6g V  bias = %0.6f V",
                             freq, ampl, bias),
                   UVM_HIGH)
    endfunction

    // 6.2.4 push -- duty point
    virtual function void push_duty(input real freq, input real in_duty,
                                    input real v_lo, input real v_hi,
                                    input real vth);
      void'(core.set_duty_drive(freq, in_duty, v_lo, v_hi, vth));
      `uvm_ms_info("BRIDGE_PUSH_DUTY",
                   $sformatf("freq = %0.6g Hz  in_duty = %0.2f%%  swing = %0.4f..%0.4f V  vth = %0.6f V",
                             freq, 100.0 * in_duty, v_lo, v_hi, vth),
                   UVM_HIGH)
    endfunction

    // 6.2.6 pull -- in DMS the core's variables may be read directly
    virtual function real get_stimulus(); return core.stim_out; endfunction
    virtual function real get_response(); return core.resp_out; endfunction
    virtual function real get_mag_db();   return core.mag_db_out; endfunction
    virtual function real get_phase_deg(); return core.phase_deg_out; endfunction
    virtual function real get_duty();      return core.duty_out; endfunction
    virtual function real get_in_duty();   return core.duty_in_duty; endfunction
    virtual function bit  get_is_ac();     return core.ac_mode; endfunction
    virtual function bit  get_is_duty();   return core.duty_mode; endfunction

    // 6.2.5 push-sync handshake
    virtual task wait_sampling_done();
      @(posedge core.sampling_done);
    endtask

  endclass : dcc_bridge_proxy

  dcc_bridge_proxy proxy = new("proxy");

  //--------------------------------------------------------------------
  // Bridge core instantiation
  //--------------------------------------------------------------------
  dcc_bridge_core core (
    .ain  (ain),
    .aout (aout)
  );

  //--------------------------------------------------------------------
  // Copy core changes into the proxy (UVM-MS 6.1.5).  The @() is at the
  // end so proxy.eot is assigned when the process starts.
  //--------------------------------------------------------------------
  always begin
    proxy.eot = core.sampling_done;
    @(core.sampling_done);
  end

endmodule : dcc_bridge
