`timescale 1fs/1fs
//======================================================================
// dcc_ms_types_pkg -- the real-number-modelling net type.
//
// A user-defined nettype (UDN) whose resolution function sums every
// driver's contribution.  UVM-MS clause 4.2.3.2 / Figure 5 ("Multiple
// analog drivers on a single net") is why this is a nettype rather than
// a plain wreal: the bridge core drives the stimulus, and anything added
// to the same net later -- an offset source, a noise source, a second
// bridge -- combines here, in the net type, not in the testbench.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
package dcc_ms_types_pkg;

  function automatic real sum_res(input real drivers[]);
    real total = 0.0;
    foreach (drivers[i]) total += drivers[i];
    return total;
  endfunction

  nettype real dcc_wire with sum_res;

endpackage : dcc_ms_types_pkg
