`timescale 1fs/1fs
// wreal port boundary for dcc_rnm, auto-generated by spice2rnm (Veylon Systems).
//
// The core model is instantiated untouched -- same behaviour,
// same evidence, byte-identical to the file the equivalence
// check ran against. Only the boundary changes discipline.
//
// wreal is Verilog-AMS vocabulary, not IEEE 1800: this file
// compiles where the simulator provides the extension, and
// is a separate file so the core carries no dependence on it.
module dcc_rnm_wreal(input wreal ain, output wreal aout);

  // Net -> variable, so the core's `input real` can take it.
  real in_r;
  always @(ain) in_r = ain;

  // Variable -> net on the way back out.
  real out_r;
  assign aout = out_r;

  dcc_rnm u_rnm (.in_val(in_r), .out_val(out_r));

endmodule : dcc_rnm_wreal
