//======================================================================
// dcc_ms_scoreboard
//
// Compares the model's settled response against the ngspice-measured DC
// transfer characteristic.
//
// The comparison is deliberately NOT against the fitted transfer function
// the RNM implements -- that would be the model checked against its own
// equations, which passes unconditionally.  GOLD_Y is what the circuit
// did in ngspice.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
class dcc_ms_scoreboard extends uvm_scoreboard;

  uvm_analysis_imp #(dcc_ms_transaction, dcc_ms_scoreboard) sb_imp;

  int  checks    = 0;
  int  failures  = 0;
  real worst_err = 0.0;
  real worst_at  = 0.0;

  int  duty_checks   = 0;
  int  duty_failures = 0;
  real worst_duty_pp = 0.0;
  real worst_duty_at = 0.0;

  int  ac_checks    = 0;
  int  ac_failures  = 0;
  real worst_db     = 0.0;
  real worst_db_at  = 0.0;
  real worst_deg    = 0.0;
  real worst_deg_at = 0.0;

  `uvm_component_utils(dcc_ms_scoreboard)

  function new(string name, uvm_component parent);
    super.new(name, parent);
    sb_imp = new("sb_imp", this);
  endfunction

  // The driven level comes back through the monitor as a real, so match
  // it to the nearest characterized point rather than relying on exact
  // equality of two reals that have been round-tripped through the core.
  function automatic int nearest_gold(input real x);
    int  best = 0;
    real best_d = 1.0e30;
    real d;
    for (int i = 0; i < GOLD_N; i++) begin
      d = x - gold_x(i);
      if (d < 0.0) d = -d;
      if (d < best_d) begin
        best_d = d;
        best   = i;
      end
    end
    return best;
  endfunction

  // Same idea for the AC table: the frequency comes back through the
  // core as a real, so match to the nearest characterized frequency.
  function automatic int nearest_ac(input real f);
    int  best = 0;
    real best_d = 1.0e30;
    real d;
    for (int i = 0; i < AC_N; i++) begin
      d = f - ac_freq(i);
      if (d < 0.0) d = -d;
      if (d < best_d) begin
        best_d = d;
        best   = i;
      end
    end
    return best;
  endfunction

  function automatic real wrap180(input real deg);
    real d = deg;
    while (d >  180.0) d = d - 360.0;
    while (d < -180.0) d = d + 360.0;
    return d;
  endfunction

  // Same nearest-match idea as the DC and AC tables, over the pair the
  // duty golden is keyed by. Matching on frequency alone would collide
  // whenever two points share a rate and differ only in input duty,
  // which is the normal shape of this table.
  function automatic int nearest_duty(input real f, input real d);
    int  best = 0;
    real best_d = 1.0e30;
    real df, dd, score;
    for (int i = 0; i < DUTY_N; i++) begin
      df = (duty_freq(i) != 0.0) ? (f - duty_freq(i)) / duty_freq(i) : f;
      dd = d - duty_in(i);
      score = df * df + dd * dd;
      if (score < best_d) begin
        best_d = score;
        best   = i;
      end
    end
    return best;
  endfunction

  virtual function void write(dcc_ms_transaction txn);
    int  idx;
    real expected, err;
    real exp_db, err_db, exp_deg, err_deg;
    real exp_duty, err_pp;

    if (txn.kind == OP_DUTY) begin
      idx      = nearest_duty(txn.freq, txn.in_duty);
      exp_duty = duty_gold(idx);

      duty_checks++;

      // The table is keyed by (frequency, input duty). If the input duty
      // did not survive the round trip through the core, every point
      // matches whichever row has the lowest one and the check silently
      // compares the model against the wrong golden -- which looks like a
      // failing model rather than a broken testbench. It happened; this
      // is what catches it next time.
      if (txn.in_duty <= 0.0 || txn.in_duty >= 1.0) begin
        duty_failures++;
        `uvm_error("DUTY_CHECK",
                   $sformatf("FAIL f = %0.6g Hz: the driven input duty came back as %0.4f, which is not a duty -- the golden cannot be identified and any comparison here would be against the wrong row",
                             txn.freq, txn.in_duty))
        return;
      end

      // A negative duty is the core saying it saw no complete cycle --
      // never a measurement. Scoring it as a number would turn a model
      // that produced no edges at all into a large but finite error,
      // which is a failure that reads like a tolerance problem.
      if (txn.out_duty < 0.0) begin
        duty_failures++;
        `uvm_error("DUTY_CHECK",
                   $sformatf("FAIL f = %0.6g Hz, in %0.2f%%: the model produced NO complete cycle -- no duty to compare against ngspice %0.2f%%",
                             txn.freq, 100.0 * txn.in_duty, 100.0 * exp_duty))
        return;
      end

      err_pp = (txn.out_duty - exp_duty) * 100.0;
      if (err_pp < 0.0) err_pp = -err_pp;

      if (err_pp > worst_duty_pp) begin
        worst_duty_pp = err_pp;
        worst_duty_at = txn.freq;
      end

      if (err_pp > TOL_DUTY_PP) begin
        duty_failures++;
        `uvm_error("DUTY_CHECK",
                   $sformatf("FAIL f = %0.6g Hz, in %0.2f%%: ngspice %0.3f%%, model %0.3f%%, err %0.3f pp > tol %0.3f pp",
                             txn.freq, 100.0 * txn.in_duty, 100.0 * exp_duty,
                             100.0 * txn.out_duty, err_pp, TOL_DUTY_PP))
      end else begin
        `uvm_info("DUTY_CHECK",
                  $sformatf("PASS f = %0.6g Hz, in %0.2f%%: ngspice %0.3f%%, model %0.3f%%, err %0.3f pp",
                            txn.freq, 100.0 * txn.in_duty, 100.0 * exp_duty,
                            100.0 * txn.out_duty, err_pp), UVM_HIGH)
      end
      return;
    end

    if (txn.kind == OP_AC) begin
      idx    = nearest_ac(txn.freq);
      exp_db = ac_mag_db(idx);
      err_db = txn.mag_db - exp_db;
      if (err_db < 0.0) err_db = -err_db;

      ac_checks++;
      if (err_db > worst_db) begin
        worst_db    = err_db;
        worst_db_at = txn.freq;
      end

      if (err_db > TOL_DB) begin
        ac_failures++;
        `uvm_error("AC_CHECK",
                   $sformatf("FAIL f = %0.6g Hz: ngspice %0.4f dB, model %0.4f dB, err %0.4f dB > tol %0.4f dB",
                             txn.freq, exp_db, txn.mag_db, err_db, TOL_DB))
      end else begin
        `uvm_info("AC_CHECK",
                  $sformatf("PASS f = %0.6g Hz: ngspice %0.4f dB, model %0.4f dB, err %0.4f dB",
                            txn.freq, exp_db, txn.mag_db, err_db), UVM_HIGH)
      end

      // Phase is checked more loosely than magnitude, and deliberately:
      // the excitation is a 64-step staircase, so the recovered phase
      // carries a half-sample bias of ~2.8 degrees that has nothing to do
      // with the model. It is still worth checking -- a misplaced pole
      // moves phase long before it moves magnitude much.
      exp_deg = ac_phase_deg(idx);
      err_deg = wrap180(txn.phase_deg - exp_deg);
      if (err_deg < 0.0) err_deg = -err_deg;
      if (err_deg > worst_deg) begin
        worst_deg    = err_deg;
        worst_deg_at = txn.freq;
      end
      if (err_deg > TOL_DEG) begin
        ac_failures++;
        `uvm_error("AC_PHASE",
                   $sformatf("FAIL f = %0.6g Hz: ngspice %0.2f deg, model %0.2f deg, err %0.2f deg > tol %0.2f deg",
                             txn.freq, exp_deg, txn.phase_deg, err_deg, TOL_DEG))
      end
      return;
    end

    idx      = nearest_gold(txn.level);
    expected = gold_y(idx);
    err      = txn.response - expected;
    if (err < 0.0) err = -err;

    checks++;
    if (err > worst_err) begin
      worst_err = err;
      worst_at  = txn.level;
    end

    if (err > TOL_ABS) begin
      failures++;
      `uvm_error("DC_CHECK",
                 $sformatf("FAIL in = %0.6f V: ngspice %0.6f V, model %0.6f V, err %0.6f V > tol %0.6f V",
                           txn.level, expected, txn.response, err, TOL_ABS))
    end else begin
      `uvm_info("DC_CHECK",
                $sformatf("PASS in = %0.6f V: ngspice %0.6f V, model %0.6f V, err %0.6f V",
                          txn.level, expected, txn.response, err), UVM_HIGH)
    end
  endfunction

  virtual function void report_phase(uvm_phase phase);
    `uvm_info("SB_SUMMARY",
              $sformatf("dc checks=%0d failed=%0d | worst err %0.6f V at in = %0.6f V (tol %0.6f V)",
                        checks, failures, worst_err, worst_at, TOL_ABS), UVM_LOW)
    if (AC_N > 0)
      `uvm_info("SB_SUMMARY",
                $sformatf("ac checks=%0d failed=%0d | worst %0.4f dB at %0.6g Hz (tol %0.4f dB); worst %0.2f deg at %0.6g Hz (tol %0.2f deg)",
                          ac_checks, ac_failures, worst_db, worst_db_at, TOL_DB,
                          worst_deg, worst_deg_at, TOL_DEG), UVM_LOW)
    else
      `uvm_info("SB_SUMMARY",
                "ac checks=0 (no AC golden was generated for this model)", UVM_LOW)

    if (DUTY_N > 0)
      `uvm_info("SB_SUMMARY",
                $sformatf("duty checks=%0d failed=%0d | worst %0.3f pp at %0.6g Hz (tol %0.3f pp)",
                          duty_checks, duty_failures, worst_duty_pp,
                          worst_duty_at, TOL_DUTY_PP), UVM_LOW)

    if (checks == 0)
      `uvm_error("SB_SUMMARY",
                 "no operating points were checked -- the monitor never delivered a transaction")
    if (DUTY_N > 0 && duty_checks == 0)
      `uvm_error("SB_SUMMARY",
                 "a duty golden was generated but no duty point was ever checked")
    if (AC_N > 0 && ac_checks == 0)
      `uvm_error("SB_SUMMARY",
                 "an AC golden was generated but no AC point was ever checked")
  endfunction

endclass : dcc_ms_scoreboard
