`timescale 1fs/1fs
//======================================================================
// dcc_dms -- the mixed-signal wrapper around the generated RNM.
//
// The RNM (dcc_rnm) keeps the plain `real` ports spice2rnm has
// always emitted: a `real` port is a VARIABLE, so nothing can share it
// and no bridge can attach.  This wrapper is the I/O layer that turns it
// into a net-connected mixed-signal block -- the same relationship
// frequency_adapter_dms has to freq_adapt_core in uvm_ms_demo, where the
// core is untouched and only the boundary changes.
//
// The ports are `interconnect` (IEEE 1800-2017 6.6.8), which is what
// UVM-MS clause 4.2 asks for: the wrapper does not name the analog type,
// it inherits whatever the enclosing testbench wired to it.  Directions
// are explicit -- a directionless interconnect defaults to inout, and
// inout is not supported for real-valued nets.
//
// AUTO-GENERATED by spice2rnm (Veylon Systems).  Edits will be overwritten.
//======================================================================
module dcc_dms import dcc_ms_types_pkg::*; (
  input  interconnect ain,
  output interconnect aout
);

  // Net -> variable, so the RNM's `input real` port can take it.
  real in_r = 0.9;
  always @(ain) in_r = ain;

  // Variable -> net on the way back out.
  real out_r;
  assign aout = out_r;

  dcc_rnm u_rnm (
    .in_val (in_r),
    .out_val (out_r)
  );

endmodule : dcc_dms
