#!/usr/bin/env bash
# UVM-MS testbench for dcc_rnm -- AUTO-GENERATED by spice2rnm (Veylon Systems).
#
# Runs entirely on xezim: one invocation compiles and simulates UVM, the
# IEEE 1800-2017 6.6.7 user-defined nettypes and interconnect (6.6.8) ports,
# and the UVM-MS proxy's out-of-module references into the analog bridge
# core. No separate elaborate step.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
XEZIM=${XEZIM:-$HOME/xezim/target/release/xezim}
UVM=${UVM_SRC:-$HOME/iverilog-unified/uvm-core/src}
# The UVM-MS library (Accellera Annex A.1/A.2) is not vendored here.
UVM_MS=${UVM_MS_LIB:-$HOME/uvm_ms_demo/ms}
# A simulation-time ceiling, not a run length -- the run still ends at
# $finish. Generous because a low-frequency AC point advances tens of us of
# sim time per measurement, past xezim's 100us default guard.
MAX_TIME=${MAX_TIME:-50ms}

# Say what is missing rather than letting the first command fail with "no
# such file". xezim is the one simulator here that compiles UVM *and* 6.6.7
# nettypes *and* resolves the proxy OOMR pattern (clause 4.2.3) in one shot.
if [ ! -x "$XEZIM" ]; then
  echo "ERROR: xezim not found or not executable at '$XEZIM'." >&2
  echo "  Re-run as:  XEZIM=/path/to/xezim $0" >&2
  exit 1
fi
for d in "$UVM/uvm_pkg.sv" "$UVM_MS/uvm_ms_pkg.sv"; do
  [ -f "$d" ] || { echo "ERROR: $d not found (set UVM_SRC / UVM_MS_LIB)." >&2; exit 1; }
done

cd "$ROOT"

echo "=== running UVM-MS testbench for dcc_rnm on xezim ==="
timeout 600 "$XEZIM" --max-time "$MAX_TIME" -DUVM_NO_DPI \
    -I "$UVM" -I "$UVM_MS" -I "$ROOT" \
    "$UVM/uvm_pkg.sv" \
    "$UVM_MS/uvm_ms_pkg.sv" \
    dcc_ms_types_pkg.sv \
    dcc_proxy_pkg.sv \
    dcc_rnm.sv \
    dcc_dms.sv \
    dcc_bridge_core.sv \
    dcc_bridge.sv \
    dcc_ms_pkg.sv \
    top_dcc_ms.sv \
    +UVM_NO_RELNOTES "$@" \
  2>&1 | grep -v 'compile-progress\|degraded to null\|not representable\|dpiexport'
